KhronosGroup/WebGL

extensions/proposals/WEBGL_multiview/extension.xml

The native extension spec recommends an error in case the number of
views doesn't match between the framebuffer and the shader. This
should be required behavior in the WebGL version of the extension.
When the number of views specified in the active program is one,
it needs to be specified what happens with gl_ViewID_OVR. The simplest
option is to specify that it always evaluates to zero in this case.
Another alternative would be to forbid statically using gl_ViewID_OVR
in this case, but this could only be validated at link time.

Address unspecified behavior in the WEBGL_multiview spec

---

sdk/tests/js/webgl-test-utils.js

These types are webgl2 types for texture/renderbuffer. 
When I use wtu.fillTexture to fill data to texture, I found that the original code of wtu.getBytesPerComponent will report type not supported, which is not correct. 
PTAL, @zhenyao and @kenrussell . Thanks a lot!

add more types into wtu.getBytesPerComponent

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/depth-stencil-feedback-loop.html

piman pointed out that there should be feedback loop detection for depth/stencil buffer, see https://codereview.chromium.org/2461973002/diff/40001/gpu/command_buffer/service/gles2_cmd_decoder.cc. 
Add test case to expose this feature.
Also see the comments at #2160. 
PTAL. @zhenyao

Depth stencil feedback loop

---

sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-video.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-video.js

Attempt to address flakiness reported in http://crbug.com/671209.
Verified this change in both Chrome and Firefox.

Use wtu.startPlayingAndWaitForVideo in image-bitmap-from-video tests.

---

sdk/tests/conformance/glsl/00_test_list.txt
sdk/tests/conformance/glsl/preprocessor/00_test_list.txt
sdk/tests/conformance/glsl/preprocessor/macro-expansion-tricky.html

The test is crashing in the latest Firefox and the stable branch of
Chrome. It's passing in Edge and in Chrome Canary, which is using the
latest version of ANGLE shader translator.

Add a tricky recursive macro expansion test

---

sdk/tests/conformance2/textures/misc/tex-srgb-mipmap.html

With the log, it's efficient to debug chrome build bots failures.

Print failure message to log for debugging

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/float-parsing.html

The tests are only for WebGL 2.0 and not 1.0, since ESSL 3.00.6 added
more explicit rules for parsing floats.

Add tests for WebGL 2 float parsing corner cases

---

specs/1.0.0/index.html
specs/1.0.1/index.html
specs/1.0.2/index.html
specs/1.0.3/index.html
specs/latest/1.0/index.html

Fix this link for the current 1.0 spec and all existing stable versions (no change in functionality).

Update a broken link to the canvas element

---

sdk/tests/conformance2/glsl3/float-parsing.html

This targets an ANGLE issue where infinity literals are not written
to the shader output as infinity, but rather as max finite float.

Add tests checking for non-constant infinity

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/read-draw-when-missing-image.html

I am investigating the framebuffer completeness issue, found that a corresponding feature is not covered when we read from or draw to a color buffer which has no image. 
In GLES 2.0/3.0 spec, it is not specified what happen in this situation. In WebGL 1.0, it explicitly says that it generates INVALID_OPERATION if reading from a color buffer without image, see https://www.khronos.org/registry/webgl/specs/latest/1.0/#6.26. 
The corresponding APIs are readPixels, copyTexImage2D, copyTexSubImage2D, copyTexSubImage3D. 
When drawing to a color buffer without image, I propose to not generate any error, and do nothing. And the Chromium current implementation does follow this. 
The corresponding APIs are clear, clearBuffer*, drawElements, drawArrays. 
Another related API is blitFramebuffer, I …

Add test cases to test the functionality when reading from or drawing to a color buffer without image attached

---

conformance-suites/2.0.0/conformance2/rendering/framebuffer-completeness-unaffected.html
conformance-suites/2.0.0/conformance2/textures/canvas/00_test_list.txt
conformance-suites/2.0.0/conformance2/textures/webgl_canvas/00_test_list.txt
conformance-suites/2.0.0/deqp/framework/common/tcuSkipList.js
conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-2d-with-canvas-sub-rectangle.js

Disable WebGL 2.0.0 snapshot tests failing due to Mac AMD/Intel drivers

---

conformance-suites/2.0.0/conformance2/reading/read-pixels-from-fbo-test.html
sdk/tests/conformance2/reading/read-pixels-from-fbo-test.html

They are exposed by https://codereview.chromium.org/2577293002/
Verified on Mac/Linux that the tolerance increase is necessary.

Increase the error tolerance in certain readPixels test cases

---

sdk/tests/deqp/framework/common/tcuSkipList.js

Since the MacOSX driver bug is fixed in 10.12.2 release

Remove R11_G11_B10 entries from skip list

---

sdk/tests/conformance2/textures/misc/00_test_list.txt
sdk/tests/conformance2/textures/misc/angle-stuck-depth-textures.html

ANGLE would not release a particular resource cache after recreating
an internal reference to the depth texture, causing rendering to
get stuck with one version of the texture. The test covers that bug.
See http://anglebug.com/1664 for more info.
PTAL @kenrussell @zhenyao

Add test to cover ANGLE sticking depth textures.

---

extensions/proposals/WEBGL_multiview/extension.xml

Corrects some small omissions. The spec for declaring num_views is
written similarly to how declaring local_size in compute shaders is
specified.

Tweaks to WEBGL_multiview spec text

---

sdk/tests/conformance/extensions/ext-sRGB.html
sdk/tests/conformance2/textures/misc/tex-srgb-mipmap.html
sdk/tests/js/webgl-test-utils.js

This patch checks if SRGB_EXT format works for generateMipmap.
Also move some common functions to webgl-test-utils.js.
@zhenyao, @kenrussell, @qkmiao and @Richard-Yunchao, PTAL.

Add srgb extension format checking for generateMipmap.

---

conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-blob.js
conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-canvas.js
conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-image-bitmap.js
conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-image-data.js
conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-image.js
conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-video.js
conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-blob.js
conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-canvas.js
conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-image-bitmap.js
conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-image-data.js
conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-image.js
conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-video.js
conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-with-image-bitmap-utils.js
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-blob.js
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-canvas.js
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-image-bitmap.js
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-image-data.js
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-image.js
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-video.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-blob.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-canvas.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-image-bitmap.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-image-data.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-image.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-video.js
sdk/tests/js/tests/tex-image-and-sub-image-with-image-bitmap-utils.js

After these changes, Firefox passes these tests.
Firefox does not yet implement support for the options dict in the createImageBitmap function.
The tests seem to want this to be optional, but the test fails to complete instead of failing softly.

Fix bitmaps

---

conformance-suites/2.0.0/js/webgl-test-utils.js
sdk/tests/js/webgl-test-utils.js

This avoids spurious warnings like:
"XML Parsing Error: syntax error
Location: file:///c:/dev/webgl-repo/conformance-suites/2.0.0/resources/uniformBlockShader.vert
Line Number 1, Column 1:"

Override mimetype for wtu.readFile to text/plain.

---

sdk/tests/js/webgl-test-utils.js

Buffer is already a TypedArray type. We don't need to take care of bytes
per component when calculating its size.

Fix wrong size of buffer when filling texture

---

specs/latest/2.0/index.html
specs/latest/2.0/webgl2.idl

This is to address https://github.com/KhronosGroup/WebGL/issues/2233, the spec part.
@kenrussell @kainino0x @jdashg PTAL

Add imageSize to compressedTex{Sub}Image{2|3}D.

---

conformance-suites/2.0.0/conformance2/rendering/blitframebuffer-size-overflow.html

Apply the small pull request at https://github.com/KhronosGroup/WebGL/pull/2222 to WebGL 2.0.0. 
Sorry, I should fix it in that pr.  @zhenyao, PTAL. Thanks!

Fix a typo and deinit resources in WebGL 2.0.0 test

---

sdk/tests/conformance2/renderbuffers/framebuffer-test.html

This failed on NVIDIA Linux with ANGLE and Intel Mac OSX. Chrome bug is filed: https://bugs.chromium.org/p/chromium/issues/detail?id=678526.

Add fbo complete test for fbo attaching base level of a texture

---

conformance-suites/2.0.0/conformance2/attribs/gl-vertexattribipointer.html
sdk/tests/conformance2/attribs/gl-vertexattribipointer.html

@kenrussell, @zhenyao and @jdashg , PTAL. 
Apply https://github.com/KhronosGroup/WebGL/pull/2228 to VertexAttribIPointer too.

VertexAttribIPointer with no array buffer is bound and offset is zero

---

sdk/tests/conformance/textures/misc/texture-upload-size.html
sdk/tests/conformance2/textures/misc/tex-image-with-bad-args-from-dom-elements.html
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-video.js

Updated file name according https://github.com/KhronosGroup/WebGL/pull/2240. 
PTAL @kenrussell @zhenyao @jdashg

Fix vp9 webm video resource name

---

conformance-suites/2.0.0/conformance/textures/misc/texture-upload-size.html
conformance-suites/2.0.0/conformance2/textures/misc/tex-image-with-bad-args-from-dom-elements.html
conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-3d-with-video.js

This is a port of #2247 to the 2.0.0 snapshot, which was broken with #2240 .

Fix vp9 webm resource name in 2.0.0 snapshot.

---

conformance-suites/2.0.0/conformance2/rendering/attrib-type-match.html
sdk/tests/conformance2/rendering/attrib-type-match.html

Sorry, I made a mistake for this test. PTAL. @zhenyao  and @kenrussell . 
vertexAttribIPointer have no parameter of normalized... 
I am surprised that the test can pass in Chromium. Per my understanding of IDL file and JS binding grammar, if the function have 5 parameters, and we fill it with 6 and call the function, then it can not be found in WebGLRenderingContext( or WebGL2RenderingContext) during function overloading.

Fix bugs in attrib-type-match.html

---

specs/latest/1.0/index.html

The typed array specification originally developed by Khronos has been
subsumed into the ECMAScript specification, and is no longer being
maintained.

Updated WebGL 1.0 to point to ECMAScript spec for typed arrays.

---

specs/2.0.0/index.html
specs/latest/2.0/index.html

Clarified use of clearBufferfi by incorporating some text from the ES
3.0 manual page.

Fix texImage3D and clearBuffer spec bugs found by Kathleen Mattson.

---

specs/2.0.0/index.html
specs/latest/2.0/index.html

The arguments were made non-nullable in WebGL 1.0. Updating this
detail documentation was overlooked.

Fixed nullability of getUniform's arguments in WebGL 2.0.

---

sdk/tests/conformance/offscreencanvas/context-creation-worker.html
sdk/tests/conformance/offscreencanvas/context-creation.html
sdk/tests/conformance/offscreencanvas/context-lost-restored-worker.html
sdk/tests/conformance/offscreencanvas/context-lost-restored.html
sdk/tests/conformance/offscreencanvas/context-lost-worker.html
sdk/tests/conformance/offscreencanvas/context-lost.html
sdk/tests/conformance/offscreencanvas/methods-worker.html
sdk/tests/conformance/offscreencanvas/methods.html
sdk/tests/conformance2/offscreencanvas/context-creation-worker.html
sdk/tests/conformance2/offscreencanvas/context-creation.html
sdk/tests/conformance2/offscreencanvas/methods-2-worker.html
sdk/tests/conformance2/offscreencanvas/methods-2.html
sdk/tests/js/js-test-pre.js

finishTest() doesn't break the execution of left part of a test. We
should explicitly stop doing following test after finishTest().
This fixes some issues introduced in
https://github.com/KhronosGroup/WebGL/pull/2159.

Skip OffscreenCanvas test if it's not supported

---

conformance-suites/2.0.0/conformance2/textures/misc/tex-mipmap-levels.html
conformance-suites/2.0.0/deqp/framework/common/tcuSkipList.js
sdk/tests/conformance2/textures/misc/00_test_list.txt
sdk/tests/conformance2/textures/misc/tex-3d-mipmap-levels-intel-bug.html
sdk/tests/conformance2/textures/misc/tex-mipmap-levels.html

Make WebGL 2.0.0 100% pass with Chrome on Linux Intel HD530 with Mesa
driver 13.0.3.

Move failed tests on Intel Mesa to 2.0.1

---

conformance-suites/2.0.0/deqp/framework/common/tcuSkipList.js

Due to NVidia Quadro 600 driver bug.

Disable multisample.fbo_max_samples.* in 2.0.0

---

sdk/tests/conformance2/context/00_test_list.txt
sdk/tests/conformance2/context/context-resize-changes-buffer-binding-bug.html

The bug is, when resizing a canvas, chrome incorrectly set PIXEL_UNPACK_BUFFER
binding to 0 without recovering it.

Add a conformance test that caught a chrome crash.

---

sdk/tests/conformance/more/functions/readPixelsBadArgs.html
sdk/tests/conformance/more/functions/texImage2DHTML.html
sdk/tests/conformance/more/functions/texSubImage2DHTML.html
sdk/tests/conformance/textures/misc/origin-clean-conformance.html

Will test these live on the khronos.org site and then backport the
changes to the earlier conformance snapshots.
Partially addresses #2273.

Updated links to cross-origin resources to point to get.webgl.org.

---

conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-video.js
conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-video.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-video.js

Fixed 3D image-bitmap-from-video tests and backported following two prs:
1. Fix timeout when video type is unsupported (#2275).
2. Use wtu.startPlayingAndWaitForVideo in image-bitmap-from-video tests.
(#2184).

Fix timeout in 3D image-bitmap-from-video tests and backport 2D fixup to 2.0.0 snapshot

---

sdk/tests/js/tests/tex-image-and-sub-image-with-image-bitmap-utils.js

This makes the new added video type tests pass.
I saw these tests failed on chromium bots in roll: https://codereview.chromium.org/2664653002/. But I cannot reproduce them locally. Failed message is something like: "at (8, 8) expected: 255,0,0 was 253,1,0".

Add tolerance for pixels checking in image_bitmap_from_video tests

---

conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-with-image-bitmap-utils.js

Backport "Add tolerance for pixels checking in image_bitmap_from_video
tests (#2281)" to 2.0.0 snapshot.

Fix tolerance issue in WebGL 2.0.0 snapshot

---

conformance-suites/2.0.0/conformance/extensions/webgl-compressed-texture-atc.html
sdk/tests/conformance/extensions/webgl-compressed-texture-atc.html

This is fallout from #2053, in which I forgot to update the ATC tests.
This wasn't noticed because it runs only on limited configurations (as ATC is an AMD extension). I found it while debugging test failures on Google Pixel (Qualcomm Adreno 530), which supports it.
This corrects a failure on this device on both Chrome and Firefox.

Update more extension tests to account for removal of ETC2/EAC

---

sdk/tests/conformance2/renderbuffers/framebuffer-test.html
sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/framebuffer-texture-level1.html

This test is new in 2.0.1 and is failing on at least Chrome OpenGL
Windows using an NVIDIA GPU. It's easier to keep track of the failure
if the test is in a separate test file, rather than in a catch-all
framebuffer test file with lots of unrelated tests.
Also fix wrong order of shouldBe parameters in the test to get a
better error message.

Split attaching texture level 1 to framebuffer to a different test

---

sdk/tests/conformance/offscreencanvas/00_test_list.txt
sdk/tests/conformance/offscreencanvas/context-attribute-preserve-drawing-buffer.html
sdk/tests/conformance/offscreencanvas/offscreencanvas-resize.html
sdk/tests/js/tests/canvas-tests-utils.js

@kenrussell 
The two new tests that are adding here are adapted from existing Chromium layout tests:
1. offscreencanvas-resize.html
https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/canvas/OffscreenCanvas-resize.html
The resizing behavior is specified in WHATWG spec https://html.spec.whatwg.org/multipage/scripting.html#the-offscreencanvas-interface,
2. context-attribute-preserve-drawing-buffer.html
https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/canvas/OffscreenCanvas-webgl-preserveDrawingBuffer.html

Update more conformance tests to OffscreenCanvas

---

sdk/tests/conformance/glsl/bugs/multiplication-assignment.html
sdk/tests/conformance/glsl/bugs/struct-constructor-highp-bug.html
sdk/tests/conformance/glsl/bugs/unary-minus-operator-float-bug.html
sdk/tests/js/glsl-conformance-test.js

Use the GLSL test runner instead of having custom procedural code in
the tests. This makes the test code cleaner and the tests easier to
debug, since the GLSL runner prints out the shader source.

Make some GLSL tests use the GLSL test framework

---

sdk/tests/conformance/extensions/webgl-draw-buffers-feedback-loop.html

Fix negative case of conformance/extensions/webgl-draw-buffers-feedback-loop.html
This fixes a test failure when WEBGL_draw_buffers is unavailable.
@Richard-Yunchao @zhenyao PTAL

Fix negative case of webgl-draw-buffers-feedback-loop.html

---

conformance-suites/1.0.3/conformance/extensions/webgl-compressed-texture-size-limit.html
conformance-suites/2.0.0/conformance/extensions/webgl-compressed-texture-size-limit.html
sdk/tests/extra/webgl-compressed-texture-size-limit-stress.html
sdk/tests/js/tests/webgl-compressed-texture-size-limit.js

ArrayBuffer allocations larger than 1 GB are not reliable on 32-bit
browsers. To make the compressed texture size conformance test
reliable, the max allocation size it uses needs to be limited down to
1 GB from the theoretical limit it was previously using.
To restore as much of the lost coverage as possible, cover max texture
size with 2D textures that are large only in one dimension and small
in the other dimension.
A separate stress test that uses ArrayBuffers up to the theoretical 4
GB limit is also added. This is valuable to have since it can reveal
bugs in 64-bit browsers that the lighter conformance test does not
reveal anymore. It also uses larger cube map textures in its positive
tests, raising the size limit from 2K x 2K to 8K x 8K.

Make compressed texture max size test reliable

---

extensions/WEBGL_lose_context/extension.xml
specs/latest/1.0/index.html
specs/latest/1.0/webgl.idl

Document that WEBGL_lose_context extension should destroy graphics
resources.

Rename preferLowPowerToHighPerformance to powerPreference.

---

specs/latest/1.0/index.html

A slight tweak to the wording that indicates what
would cause such an event to fire. The motivation
behind this is that it was possible to read the
specification and conclude that a lost + restored
must be fired if a GPU switch occurs.

Improve the description of WebGLContextEvent

---

specs/latest/1.0/index.html

Change "loss/restoration of state" to "loss/restoration of the context".

---

conformance-suites/2.0.0/deqp/functional/gles3/es3fMultisampleTests.js
sdk/tests/deqp/functional/gles3/es3fMultisampleTests.js

This fixes these tests on Chrome and Firefox on the Google Pixel.

fix deqp testing 8-sample FBOs on hardware which doesn't support it

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/gradient-in-discontinuous-loop.html

The HLSL compiler doesn't handle gradient in discontinuous control flow
nicely, and ANGLE was missing handling for new GLSL ES 300 gradient
builtins in its workaround. This is a regression test.
See http://anglebug.com/1915

Add a GLSL3 test for a HLSL compiler freeze.

---

conformance-suites/2.0.0/conformance/extensions/00_test_list.txt

It is unclear whether this is a driver bug on Android/Qualcomm,
or if the test itself was wrong (didn't allow all possible errors).
I think the NO_ERRORs are a driver bug, and the others might not be.
This fixes this failure on both Chrome and Firefox (in exactly the same way) on Google Pixel.

Remove ATC tests from 2.0.0 tests

---

sdk/tests/conformance2/glsl3/compare-structs-containing-arrays.html

These tests are clearly intended to be render tests (i.e. have their output be checked to be green). This passes at least on some machines (e.g. Linux NVIDIA).

fix "runTests" to "runRenderTests" in compare-structs-containing-arrays

---

conformance-suites/2.0.0/deqp/framework/common/tcuSkipList.js

These tests are failing in Chrome on Google Pixel (7.1.1).
We've investigated this, and we're pretty confident that it's a driver bug, even though these tests pass in ES3 dEQP and in Firefox - it seems to be due to some unknown interaction with Chrome's architecture.
http://crbug.com/695742

2.0.0: disable multisample.fbo_{4,max}_samples.constancy_*

---

conformance-suites/2.0.0/deqp/functional/gles3/es3fNegativeTextureApiTests.js
sdk/tests/deqp/functional/gles3/es3fNegativeTextureApiTests.js

This was required to get the test to pass on Android (Pixel).

negativetextureapi: reduce allocations to prevent OOM

---

conformance-suites/2.0.0/webgl-conformance-tests.html
sdk/tests/webgl-conformance-tests.html

Works around 100k clipboard limit on Android, which makes capturing conformance results very difficult.
Also much more convenient than copy-pasting.

Add "download text summary" button

---

sdk/tests/conformance/renderbuffers/feedback-loop.html

This test, it uses glBindAttribLocation, but the string name is wrong, so it can't bind the correct vertex attribute, and in the shader it also doesn't use layout syntax, so the index will be undefined, the index is based on OpenGL automatic assigned . The Chrome with AMD can work is because just luck that the position and uv is the same as enableattribute index, but Firefox with AMD is position and uv reverse order.

fix typo at renderbuffers-feedback-loop.html

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/vector-dynamic-indexing-swizzled-lvalue.html

This exposes a bug that was recently fixed in ANGLE as well as bugs in
various OpenGL drivers.

Add a test for dynamically indexing a swizzled l-value vector

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/uniform-struct-with-non-square-matrix.html

This exposes a bug in ANGLE's D3D backend.

Add a test for a uniform struct with a non-square matrix

---

sdk/tests/conformance/glsl/bugs/compare-loop-index-to-uniform.html
sdk/tests/conformance/glsl/bugs/constant-precision-qualifier.html
sdk/tests/conformance/glsl/bugs/floored-division-accuracy.html
sdk/tests/conformance/glsl/bugs/logic-inside-block-without-braces.html
sdk/tests/conformance/glsl/bugs/modulo-arithmetic-accuracy.html
sdk/tests/conformance2/glsl3/array-assign-constructor.html
sdk/tests/conformance2/glsl3/short-circuiting-in-loop-condition.html
sdk/tests/js/glsl-conformance-test.js

This unifies test output and reduces duplication of trivial code
without losing coverage.

Use GLSL test framework for tests that need to set uniforms

---

conformance-suites/2.0.0/conformance2/misc/uninitialized-test-2.html
conformance-suites/2.0.0/deqp/functional/gles3/es3fNegativeTextureApiTests.js
sdk/tests/conformance2/misc/uninitialized-test-2.html
sdk/tests/deqp/functional/gles3/es3fNegativeTextureApiTests.js

This doesn't change test semantics.
This coalesces a few more allocations in negativetextureapi.html (see
also #2318) and many allocations in uninitialized-test-2.html.

Further reduce unnecessary JS allocations

---

conformance-suites/2.0.0/deqp/functional/gles3/es3fSyncTests.js
sdk/tests/deqp/functional/gles3/es3fSyncTests.js

In WebGL, a finish() or flush() may not have any effect. This means
TIMEOUT_EXPIRED is still possible in this test case, even though it
doesn't call clientWaitSync until a frame after the fenceSync() and
finish() operations.
This was seen on Pixel (Android/Qualcomm).

fence_sync.client_wait_sync_finish: Allow TIMEOUT_EXPIRED

---

extensions/proposals/WEBGL_multiview/extension.xml

Rendering to a stereo default framebuffer should be replaced with
something else defined in another extension spec - either a new type
of framebuffer abstraction that also knows the HMD it is targeting, or
by rendering to the default framebuffer side-by-side.

Remove proposed core spec changes from WEBGL_multiview extension

---

conformance-suites/2.0.0/webgl-conformance-tests.html
sdk/tests/webgl-conformance-tests.html

Accidental reload makes it easy to lose results in the middle of a conformance run. In Chrome, it's particularly easy if you don't disable "pull-to-refresh" in about:flags. This causes the browser to prompt when reloading.

Prompt user before reloading webgl-conformance-tests.html

---

conformance-suites/2.0.0/deqp/functional/gles3/es3fNegativeTextureApiTests.js
sdk/tests/deqp/functional/gles3/es3fNegativeTextureApiTests.js

Even after reducing the memory usage a few times, these allocations are too huge (>256MB on Android/NVIDIA). We decided to just remove them; (max+1,max+1) doesn't add significant coverage over (max+1,1) and (1,max+1), and these tests are just too unreliable on low-memory or 32-bit devices.

negativetextureapi.html: remove tests which cause huge allocations

---

specs/latest/1.0/index.html

PTAL, @zhenyao and @kenrussell .
See the discussion at #2340.

WebGL 1.0 spec update: no shader binaries in WebGL

---

conformance-suites/2.0.0/webgl-conformance-tests.html
sdk/tests/webgl-conformance-tests.html

Amendment to #2319
Removes a few tabs and newlines from the beginning and end of the downloaded txt file.

Trim whitespace from conformance txt download

---

sdk/tests/conformance/glsl/bugs/00_test_list.txt
sdk/tests/conformance/glsl/bugs/varying-arrays-should-not-be-reversed.html

I've created a GLSL bug conformance test that checks an ugly bug I ran into in Chrome for Android on my Adreno 300-series devices (Nexus 7 2013, Moto G3).
Firefox successfully passes the test on the same devices. Unfortunately I don't currently have access to any Android devices with other GPUs so I cannot check to see if it passes in Chrome on those.

add 'varying arrays should not be reversed' to GLSL bug conformance tests

---

sdk/tests/conformance/textures/misc/00_test_list.txt
sdk/tests/conformance/textures/misc/copy-tex-image-crash.html

Regression test for https://crbug.com/707445 (crash in Apple Intel driver, OS regression in 10.12.4).

Draw into source of copyTexSubImage2D shouldn't crash

---

sdk/tests/conformance/reading/00_test_list.txt
sdk/tests/conformance/reading/fbo-remains-unchanged-after-read-pixels.html

It seems that every readPixels call will trigger CMAA operation in
Chromium if CMAA is enabled. If there are not drawing operations
between two readPixels calls, fbo content should not be changed.

Add case for default fbo content would not changed between two readPxels calls.

---

specs/latest/1.0/index.html
specs/latest/2.0/index.html

The use of the term "normative references" here has implications that
were unintended and undesired for the WebGL specifications. Since the
distinction is not critical for this specification, remove it.

Remove "normative references" sub-section.

---

sdk/tests/conformance/glsl/misc/00_test_list.txt
sdk/tests/conformance/glsl/misc/uninitialized-local-global-variables.html
specs/latest/1.0/index.html

This test is currently failed by Chrome and Firefox (it needs to be implemented in the ANGLE shader translator, http://anglebug.com/1966
According to @kenrussell,
> the WebGL WG resolved to make this spec and conformance test change a while ago.

Spec & test that local and global variables are initialized

---

sdk/tests/conformance2/textures/misc/00_test_list.txt
sdk/tests/conformance2/textures/misc/copy-texture-cube-map-AMD-bug.html

This is a regression test for crbug.com/712117.

Copy into integer cube map texture should work

---

sdk/tests/conformance/textures/misc/00_test_list.txt
sdk/tests/conformance/textures/misc/origin-clean-conformance-offscreencanvas.html
sdk/tests/conformance2/textures/misc/00_test_list.txt
sdk/tests/conformance2/textures/misc/origin-clean-conformance-offscreencanvas.html

@kenrussell  Adding two security tests:
1. sdk/tests/conformance/textures/misc/origin-clean-conformance-offscreencanvas.html tests whether texImage2D and texSubImage2D functions in OffscreenCanvas Webgl context correctly throw security exception when cross-origin image sources are updated
2. sdk/tests/conformance2/textures/misc/origin-clean-conformance-offscreencanvas.html tests whether texImage2D, texImage3D, texSubImage2D, texSubImage3D in OffscreenCanvas Webgl2 context correctly throw security exceptions.
Note that although these two tests look similar to sdk/tests/conformance/textures/misc/origin-clean-conformance.html (for HTMLCanvasElement), they have many differences: (1) toDataURL is not present
in OffscreenCanvas so not tested (2) the functions in webgl2 are completely different …

Security tests for OffscreenCanvas texImage functions

---

sdk/tests/conformance2/misc/object-deletion-behaviour-2.html

Makes it easier to run it from its URL rather than through the harness.

Fetch WebGL 2.0 context by default in object-deletion-behaviour-2 test.

---

sdk/tests/conformance/offscreencanvas/00_test_list.txt
sdk/tests/conformance/offscreencanvas/offscreencanvas-transfer-image-bitmap.html
sdk/tests/conformance2/offscreencanvas/00_test_list.txt
sdk/tests/conformance2/offscreencanvas/offscreencanvas-transfer-image-bitmap.html
sdk/tests/js/tests/offscreencanvas-transfer-image-bitmap.js

These two tests are based on an existing Chromium Layout test for OffscreenCanvas webgl (https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/canvas/webgl/offscreenCanvas-transferToImageBitmap-texImage2D.html). One tests for webgl 1 and the other tests for webgl 2. They share the same functions provided in sdk/tests/js/tests/offscreencanvas-transfer-image-bitmap.js.
@zhenyao for review.

Test OffscreenCanvas's transferToImageBitmap function for both webgl and webgl2

---

sdk/tests/conformance2/textures/misc/00_test_list.txt
sdk/tests/conformance2/textures/misc/tex-base-level-bug.html

This is a regression test for Chromium Issue 705865.
First, Set texture base level > 0, then set texture level 0
result in pixel comparison error of its base level.
The test case fails on mac and windows.

Add tex-base-level-bug.html to detect driver bug of texImage2D.

---

sdk/tests/conformance2/samplers/00_test_list.txt
sdk/tests/conformance2/samplers/multi-context-sampler-test.html

Regression test for http://crbug.com/713127 .

Verify that samplers' state doesn't leak across contexts.

---

sdk/tests/conformance2/textures/misc/tex-srgb-mipmap.html

When we call generateMipmaps for srgb texture, we need to emulate under the
hood for desktop GL prior to GL 4.4. The tests in this pull request are used
to expose errors during the emulation in Chromium:
1.During the emulation of generateMipmap for srgb texture, we tried to
generate all mipmaps of the original texture. But if the texture is immutable
, we can't generate mipmaps exceed the original range. See the bug at
https://crbug.com/712096.
2.In addition, during the emulation, there are some errors if the width and
height are not equal.

Add test for srgb emulation of generateMipmap

---

sdk/tests/conformance2/textures/misc/tex-image-with-bad-args-from-dom-elements.html
sdk/tests/conformance2/textures/misc/tex-image-with-different-data-source.html

Splitting part of the https://github.com/KhronosGroup/WebGL/pull/2375 to
allow landing https://crrev.com/2821363003/ before landing the
https://github.com/KhronosGroup/WebGL/pull/2375.
This is related to #2274: GL_RGB10_A2 and texImageSource variants of tex*Image*

Prepare tests for landing texImageSource & GL_RGB10_A2 support.

---

sdk/tests/conformance2/buffers/uniform-buffers-second-compile.html
sdk/tests/conformance2/transform_feedback/transform_feedback.html
sdk/tests/js/webgl-test-utils.js

This extra test recompiles the transform feedback shader program while
preventing getShaderParameter from forcing a bypass of Chromium's shader
cache.
Passes in Firefox, fails in Chrome. Passes in Chrome with a patch.

transform_feedback: test multiple compiles of the same shaders

---

conformance-suites/1.0.1/conformance/context/constants.html
conformance-suites/1.0.2/conformance/context/constants.html
conformance-suites/1.0.3/conformance/context/constants-and-properties.html
conformance-suites/2.0.0/conformance2/context/constants-and-properties-2.html
sdk/tests/conformance/context/constants-and-properties.html
sdk/tests/conformance2/context/constants-and-properties-2.html
specs/latest/1.0/index.html
specs/latest/1.0/webgl.idl

This enum is not used at all in WebGL 1.0 and 2.0.
This is pointed out in https://github.com/KhronosGroup/WebGL/issues/2370

Remove STENCIL_INDEX from WebGL 1.0 spec

---

sdk/tests/conformance/extensions/webgl-depth-texture.html

According to the extension spec, INVALID_OPERATION is generated if
1) level > 0 or
2) target != TEXTURE_2D
When we test with CUBEMAP targets, we used level == 1, so target != TEXTURE_2D
isn't really tested (and therefore, Chrome behaved incorrectly).
ALso, we do test level > 0 with target == TEXTURE_2D and make sure
INVALID_OPERATION is generated in this case.  So it's clear to me when we test
with CUBEMAP targets with level == 1, the intention is to test with level == 0.

Fix a test coverage issue in webgl-depth-texture.html

---

conformance-suites/1.0.3/conformance/resources/webgl-test-utils.js
conformance-suites/1.0.3/webgl-conformance-tests.html
conformance-suites/2.0.0/conformance2/context/context-attributes-depth-stencil-antialias-obeyed.html
conformance-suites/2.0.0/js/webgl-test-utils.js
conformance-suites/2.0.0/webgl-conformance-tests.html
sdk/tests/conformance2/context/00_test_list.txt
sdk/tests/conformance2/context/context-attributes-depth-stencil-antialias-obeyed.html
sdk/tests/conformance2/context/no-experimental-webgl2.html
sdk/tests/js/webgl-test-utils.js
sdk/tests/webgl-conformance-tests.html

This removes all references to "experimental-webgl2" and adds a test to ensure implementations do not respond to "experimental-webgl2"
Usage of "experimental-webgl2" and mentions of it spread like a virus. Supporting it makes code overly complicated. Let's stop letting this propagate.

Remove experimental webgl2

---

sdk/tests/conformance2/textures/misc/tex-srgb-mipmap.html

Follow up immutable tex srgb emulation issue of generateMipmap.
When max level of a srgb texture is set, check if the max level
mipmap is generated or not.

Add test to tex-srgb-mipmap.html

---

sdk/tests/conformance/glsl/misc/00_test_list.txt
sdk/tests/conformance/glsl/misc/sampler-operand.html

According to ESSL spec, sampler operands can only be used in array
indexing, structure field selection, and parentheses expresions.
This validates this rule.

Add sampler operands validation tests (#2391)

---

specs/latest/1.0/index.html
specs/latest/1.0/webgl.idl
specs/latest/2.0/index.html
specs/latest/2.0/webgl2.idl

This annotates all ArrayBuffer or ArrayBufferView types with [AllowShared], per the proto-specification at https://tc39.github.io/ecmascript_sharedmem/dom_shmem.html#webgl, extended to also modify the Web GL 2.0 entrypoints. This allows the backing data to be a SharedArrayBuffer, instead of only non-shared ArrayBuffers, per https://github.com/heycam/webidl/pull/353.
This also makes some related editorial changes, removing the redundant BufferDataSource typedef in favor of the defined-in-Web IDL BufferSource type, and consolidating two overloads of bufferData (one accepting ArrayBuffer? and the other accepting ArrayBufferView) into a single overload accepting BufferSource?.
---
This is my first time contributing to the Web GL spec, so help appreciated with any policies, procedures, or …

Support SharedArrayBuffers

---

sdk/tests/conformance/glsl/misc/uninitialized-local-global-variables.html

Added tests with two declarators in the same declaration. These cases
need to be taken into account when transforming the shader source to
initialize unininitialized variables.
Also change shader precision to mediump. Supporting highp float in
fragment shaders is not mandatory in WebGL 1.0.

Expand testing uninitialized variables

---

sdk/tests/conformance2/rendering/framebuffer-texture-level1.html

The issue is raised in crbug.com/722684

Test fbo attached to a non-level-0 texture image completeness behavior.

---

sdk/tests/conformance/extensions/ext-disjoint-timer-query.html

Issue raised by Tarek Sherif on public_webgl list.

EXT_disjoint_timer_query must not be advertised on WebGL 2.0 contexts.

---

sdk/tests/conformance/glsl/misc/uninitialized-local-global-variables.html
sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/uninitialized-local-global-variables.html

Add tests for nameless structs. They don't have constructors, so
initializing them may need special handling.
Also add a WebGL 2.0 test for uninitialized variable declarations in
loop conditions. In WebGL 1.0, this case isn't possible due to ESSL
1.00 Appendix A limitations for loops.

Add tests for uninitialized variable corner cases

---

sdk/tests/conformance2/renderbuffers/multisampled-renderbuffer-initialization.html

This is a regression test for Chrome on Adreno 4xx/5xx:
http://crbug.com/696126

Add test for resizing multisampled renderbuffers

---

sdk/tests/conformance2/renderbuffers/multisampled-renderbuffer-initialization.html

Followup to #2407.
This clear is needed to expose this Qualcomm bug via Firefox as well.

Add `clear` call to test for resizing multisampled renderbuffers

---

specs/latest/2.0/index.html

This could be argued either way -- e.g. "WebGL 1" and "WebGL 2" --
but it should at least be consistent.

Standardize on "WebGL 1.0" and "2.0" naming convention.

---

extensions/WEBGL_compressed_texture_s3tc_srgb/extension.xml

Done after Mozilla voiced support.

Moved WEBGL_compressed_texture_s3tc_srgb to community approved.

---

sdk/tests/deqp/functional/gles3/es3fMultisampleTests.js

Previously the test wasn't able to handle sample counts >= 64. This
was because it's counting unique colors, and it was detecting colors
with <= 3 difference in one channel as the same. But if you have 65
different gray levels between 0 and 255, at least two of them will be
set apart by only 3.
This made the test fail on Quadro drivers that supported 64 samples.
Now the test automatically lowers the tolerance if it is required by
having a high sample count.
After this fix the test at least has a chance of handling high sample
counts correctly, though it still needs to be verified if this fix is
sufficient on its own.

Fix dEQP multisample test tolerance for sample counts >= 64

---

sdk/tests/conformance2/renderbuffers/multisampled-renderbuffer-initialization.html

These test changing renderbuffers from non-multisampled to multisampled
and vice versa. This caught an extra bug in my workaround in Chrome.
The test function is refactored a little bit to be more flexible.
I spent quite a bit of time trying to add a test for depth renderbuffers, but I wasn't able to get it working. blitFramebuffer on the depth bit from a depth-only FBO to a depth+color FBO doesn't seem to do anything, though I don't know why.

Add more cases to multisampled-renderbuffer-initialization

---

sdk/tests/conformance/rendering/00_test_list.txt
sdk/tests/conformance/rendering/framebuffer-texture-clear.html

This test is ported from crbug.com/710443's sample.mm provided
by bsalomon.
If we bind a texture to a frame buffer's color attachment, clear
it using the composition of 0 and 1. The render color is not
correct when sampling that texture to another frame buffer.
It seems that the clear command didn't work in some situations
and the result is random.
This bug can be reproduced in below situations:
case1 : Set TexParameteriv(GL_TEXTURE_2D, GL_TEXTURE_SWIZZLE_RGBA*)
when bind sampler.
case2 : Set TexParameteriv(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER*)
when bind sampler and don't use it before bind sampler.
This patch will use case2 to reproduce Mac bug since WebGL don't
support swizzle.
Change the alpha component of clear color can also workaround this bug.

Expose Intel 6000/6100 clear to 0/1 bug

---

sdk/tests/conformance2/renderbuffers/00_test_list.txt
sdk/tests/conformance2/renderbuffers/multisampled-depth-renderbuffer-initialization.html

Tests for the Qualcomm driver bug in
http://crbug.com/696126
as well as a Mac/Intel bug that I haven't reported yet.

Add tests for uninitialized multisampled depth renderbuffers

---

sdk/tests/conformance/rendering/00_test_list.txt
sdk/tests/conformance/rendering/clear-after-copyTexImage2D.html

This patch exposes an Intel D3D driver bug on clear.
The bug can be reproduced by following steps:
1. Create a WebGL context with antialias
2. Create a texture and call copyTexImage2D on it
3. Clear the default framebuffer by a color that isn't pure 0/1
The final render color isn't consistent with the clear color on
Intel D3D drivers.

Expose a clear to non 0/1 bug on Intel D3D drivers

---

sdk/tests/conformance/textures/misc/cube-map-uploads-out-of-order.html
sdk/tests/conformance2/rendering/blitframebuffer-filter-outofbounds.html
sdk/tests/conformance2/rendering/blitframebuffer-filter-srgb.html
sdk/tests/conformance2/rendering/blitframebuffer-multisampled-readbuffer.html
sdk/tests/conformance2/rendering/blitframebuffer-outside-readbuffer.html
sdk/tests/conformance2/rendering/blitframebuffer-resolve-to-back-buffer.html
sdk/tests/conformance2/rendering/blitframebuffer-scissor-enabled.html
sdk/tests/conformance2/rendering/blitframebuffer-srgb-and-linear-drawbuffers.html
sdk/tests/conformance2/rendering/blitframebuffer-stencil-only.html
sdk/tests/conformance2/rendering/clear-srgb-color-buffer.html
sdk/tests/conformance2/rendering/read-draw-when-missing-image.html
sdk/tests/conformance2/textures/misc/angle-stuck-depth-textures.html
sdk/tests/conformance2/textures/misc/copy-texture-image-luma-format.html
sdk/tests/conformance2/textures/misc/texel-fetch-undefined.html

It was being included in several WebGL 2 conformance tests that were
not using it.

Remove extra includes of glsl-conformance-test.js

---

sdk/tests/conformance/attribs/00_test_list.txt
sdk/tests/conformance/attribs/gl-bindAttribLocation-nonexistent-attribute.html
sdk/tests/conformance2/attribs/gl-vertexattribipointer-offsets.html

The attribute locations are specified in the shader text in
gl-vertexattribipointer-offsets.html. Clean up the non-existent
attribute name "vPosition".
Add a new targeted test to cover bindAttribLocation behavior when the
attribute name doesn't exist in the shader. This didn't seem to be
intentionally covered in existing tests.

Fix bogus vertex attribute name in offset test

---

conformance-suites/2.0.0/conformance2/rendering/instanced-arrays.html
sdk/tests/conformance2/rendering/instanced-arrays.html

if non of vertex attribs have zero a divisor.
The original limit was introduced in WebGL1 extension due to D3D9 limit.
Such limit does not exist in D3D11, therefore should not be applied to WebGL2.

Remove WebGL2 constraint that requires draw*Instanced() calls to fail

---

conformance-suites/2.0.0/deqp/functional/gles3/es3fNegativeVertexArrayApiTests.js
sdk/tests/deqp/functional/gles3/es3fNegativeVertexArrayApiTests.js

requires at least one vertex attribs to have zero divisor.
This is addressing https://github.com/KhronosGroup/WebGL/issues/2419

Another test case being affected by instanced draws where we no longer

---

extensions/EXT_color_buffer_float/extension.xml
sdk/tests/conformance2/extensions/ext-color-buffer-float.html

RGB16F and RGB32F are both valid internal texture formats and
should not produce an error when this extension is enabled. The
extension should not be limiting the enums that can be passed
to CopyTexImage.

Fix ext-color-buffer-float.html to pass valid RGB16F/32F texture formats

---

sdk/tests/conformance/renderbuffers/framebuffer-object-attachment.html

Calling framebufferRenderbuffer on a created renderbuffer before calling bindRenderbuffer on the render buffer must flag an invalid operation and the attachment should fail.
From the spec:
[OpenGL ES 2.0.25] Section 4.4.3 page 112
[OpenGL ES 3.0.2] Section 4.4.2 page 201
'renderbuffer' must be either zero or the name of an existing renderbuffer object of
type 'renderbuffertarget', otherwise an INVALID_OPERATION error is generated.

Test calling framebufferRenderbuffer before bindRenderbuffer

---

sdk/tests/conformance/glsl/misc/global-variable-init.html
specs/latest/1.0/index.html

It should be made clear that referring to built-in globals like
gl_FragCoord is not allowed, but on the other hand referring to
built-in constants like gl_MaxVertexUniformVectors is.
This matches the existing behavior in ANGLE.

Clarify what is allowed in global initializers

---

sdk/tests/conformance/extensions/webgl-draw-buffers-feedback-loop.html

gl.COLOR_ATTACHMENT[1-9] is undefined on WebGL1. However, when
the WEBGL_draw_buffers extension is enabled on WebGL1 one can use
ext.COLOR_ATTACHMENT[N]_WEBGL in its place. This test checks
for the extension but erroneously uses gl.COLOR_ATTACHMENT1
instead of ext.COLOR_ATTACHMENT1_WEBGL after it finding it.

Replace gl.COLOR_ATTACHMENT1 with ext.COLOR_ATTACHMENT1_WEBGL

---

sdk/tests/conformance/glsl/bugs/angle-ambiguous-function-call.html

Cover a missing workaround in ANGLE: The shader translation needs to
work around HLSL compiler treating structs with different names but
identical fields as ambiguous.

Add a test case for ambiguous struct parameters HLSL bug

---

sdk/tests/conformance/textures/misc/gl-teximage.html

Reverts KhronosGroup/WebGL#2440.
Please see my comment on the other pull request for why this change was problematic.

Revert "Test drawing with textures from non-ready video uploads."

---

sdk/tests/conformance2/uniforms/00_test_list.txt
sdk/tests/conformance2/uniforms/uniform-blocks-with-arrays.html

This exposes a bug in ANGLE's DirectX/HLSL backend. Works on ANGLE's
GL backend.

Add test for uniform blocks containing arrays of structs

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/multisampling-fragment-evaluation.html

The test checks that the fragment shader is evaluated only once per
framebuffer pixel when drawing into a multisampled framebuffer. This
is specified in GLES 3.0.5 section 3.6.3.

Add a test exposing non-conformant multisampling

---

sdk/tests/conformance/rendering/00_test_list.txt
sdk/tests/conformance/rendering/texture-switch-performance.html
sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/texture-switch-performance.html

A test for the Mac/AMD texture-switching performance problem reported in: https://bugs.chromium.org/p/chromium/issues/detail?id=735483
I've tested on a Mac with an Intel Iris, iPad Air 2, Nexus 10, Pixel Phone, and they all pass as they should. An affected Mac with a Radeon R9 M290 fails as it should.

Texture switch performance

---

sdk/tests/conformance/extensions/00_test_list.txt
sdk/tests/conformance/extensions/webgl-draw-buffers-broadcast-return.html
sdk/tests/conformance/extensions/webgl-draw-buffers.html
sdk/tests/js/tests/webgl-draw-buffers-utils.js

The test verifies that the value written to gl_FragColor is
broadcasted correctly regardless of any return statements in main().
This exposes a bug in ANGLE.
The patch includes refactoring of webgl-draw-buffers.html: Common
functionality with the new test is moved to a new utility file, and
simpleVertexShader from WebGLTestUtils is now used.

Add a test for broadcasting gl_FragColor when main() returns

---

sdk/tests/conformance/extensions/webgl-draw-buffers-broadcast-return.html
sdk/tests/conformance2/rendering/draw-buffers.html
sdk/tests/js/tests/webgl-draw-buffers-utils.js

Add new multiple render target subtests that do a discard in the
fragment shader. The new subtests are added to both WebGL 1.0
EXT_draw_buffers tests and WebGL 2.0 core tests.
The new subtests are not expected to expose existing bugs.
The patch includes refactoring the WebGL 2.0 draw buffers test so that
it shares utility code with the EXT_draw_buffers test.

Add a multiple render targets test for discarding fragment

---

sdk/tests/conformance/rendering/texture-switch-performance.html
sdk/tests/conformance2/rendering/texture-switch-performance.html

This test assumed it will achieve a steady-state 30 FPS frame rate,
which is optimistic for automated test machines which build and run
debug versions of the browser. Reduce the expectation to 10 FPS.

Relax texture switch performance test from #2448 .

---

sdk/tests/conformance/rendering/texture-switch-performance.html
sdk/tests/conformance2/rendering/texture-switch-performance.html

@kenrussell  Set up both the WebGL and WebGL 2 texture switch performance tests to first run for 2 seconds without switching textures to get a baseline frame count, then run again for 2 seconds while switching textures to get a test frame count to compare it to. 
I currently have it set up to fail if the test frame count drops below 80% of the baseline. This is well above what the affected AMD/Mac machine I have to test on can achieve (40-45%). The lowest I've seen from a passing machine is 88% on my Nexus 10, but there's still room to tweak the threshold if you need to.
The test run time and threshold are stored in RUNTIME and THRESHOLD variables near the start of the test so they're easy to tweak. The tests didn't become that much more complicated, so I didn't bother to refactor, but …

Texture switch test compares to baseline

---

specs/2.0.0/index.html

Promoters on June 30, 2017.
Synced with snapshotted version.

Moved WebGL 2.0.0 to final state per ratification vote by Khronos

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/blitframebuffer-r11f-g11f-b10f.html
sdk/tests/js/webgl-test-utils.js

This exposes a bug in Chrome, http://crbug.com/751206, affecting blits
between user framebuffers on macOS when the default back buffer is RGB
and non-antialiased.

Test blits of R11F_G11F_B10F color framebuffers.

---

specs/latest/1.0/index.html

Adds a non-normative note about the performance problems with updating sampler uniforms on some systems (see https://bugs.chromium.org/p/chromium/issues/detail?id=735483).

Non-normative note about poor performance of sampler uniform updates.

---

extensions/proposals/WEBGL_multiview/extension.xml

From prototyping we have learned that most of the expected perfomance
gains from the extension can be realized without the shader
restrictions on NVIDIA OpenGL drivers, and particularly in the context
of the web the shader restrictions might only buy marginal additional
performance. As such it makes sense to leave the restrictions out to
make the API simpler and easier to program.

Roll back shader restrictions in WEBGL_multiview spec

---

sdk/tests/conformance2/buffers/uniform-buffers.html
specs/latest/2.0/index.html

Uniform buffer draw tests can check that the uniform buffer is in the
std140 layout, since the WebGL spec mandates std140 layout. This makes
the tests simpler and enables sharing some common functionality
between subtests as well.
This refactoring is done to make way for a few more uniform buffer
tests that are needed for bugs that recently got fixed in ANGLE
related to structs in uniform blocks.
The test was also expecting that the value of
UNIFORM_BUFFER_OFFSET_ALIGNMENT was divisible by 4, but that was
somewhat non-obvious. The test for it is also clearer now. This
requirement didn't seem to be enshrined in the spec previously, but it
is reasonable and the test has been there for a while so put it in the
spec now.

Clean up uniform buffer tests

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/array-initialize-with-same-name-array.html

It's possible to initialize variables with a variable with the same
name from an outer scope. This is broken in ANGLE's HLSL backend for
arrays, so add a separate test for the array case.

Test initializing an array with another one that has the same name

---

sdk/tests/conformance2/buffers/uniform-buffers.html

These tests pass on ANGLE's GL backend but failed on the DX backend
until very recent fixes.

Add uniform buffer subtests exposing ANGLE bugs

---

sdk/tests/conformance2/rendering/element-index-uint.html

This can make Chrome/ANGLE disable index range retrieving in validation.
See https://bugs.chromium.org/p/angleproject/issues/detail?id=1393

Out-of-range vertex may not generate INVALID_OPERATION

---

sdk/tests/conformance/offscreencanvas/offscreencanvas-resize.html

This fix covers two spec compliance issues: 1) When an OffscreenCanvas
is resized, its size must propagate to the placeholder canvas's
width and height attributes; 2) Setting the width and height attributes
on a placeholder canvas throws an exception.
Related spec change: https://github.com/whatwg/html/pull/2951

Fix offscreencanvas-resize test to comply with spec

---

sdk/tests/js/tests/tex-image-and-sub-image-2d-with-webgl-canvas.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-webgl-canvas.js

The new tests cover cases when the source image for a texture upload
is a visible WebGL canvas.  When the canvas is visible (in the DOM)
it gets presented to screen, which alters internal state, which can be a
source of buggy behavior.
Related chrome bug: crbug.com/759180

New tests for texImage* with visible webgl canvas

---

specs/latest/1.0/index.html

Different versions of OpenGL and OpenGL ES on top of which WebGL 1.0
is implemented follow different rules. Since this does not affect the
majority of applications, document it as a difference in behavior.
This may be strengthened later.

Add diff spec for signed normalized vertex attributes in WebGL 1.0.

---

sdk/tests/conformance/glsl/bugs/sampler-array-struct-function-arg.html

The sampler-array-struct-function-arg test did not signal completion
and so could time out in the test harness.

Add a missing include of js-test-post

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/input-with-interpotaion-as-lvalue.html

This patch adds tests to expose a compiler bug in ANGLE. The compiler
should always report a compile error when handling an input with
interpolation qualifier as l-value in shaders.

Add test for using an input with interpolation qualifier as l-value

---

sdk/tests/conformance2/attribs/00_test_list.txt
sdk/tests/conformance2/attribs/gl-vertex-attrib-normalized-int.html

The test verifies that a WebGL 2 implementation converts singed integer
vertex attributes using zero-presering rule as it's required to the
GLES 3 spec.
See also https://github.com/KhronosGroup/WebGL/pull/2486.
/cc @kenrussell @zhenyao

Test for signed int attribs conversion

---

sdk/tests/deqp/framework/common/tcuFloat.js
sdk/tests/deqp/framework/delibs/debase/deMath.js
sdk/tests/deqp/functional/gles3/es3fShaderPrecisionTests.js

There turned out to be many bugs (mostly relating to JS numbers) in code that affected this test.
I think I've fixed all of them. But it's entirely possible that other tests will now hit the new assertions I added. So this is in a branch inside KhronosGroup/WebGL so I can dry-run a roll to this branch in Chrome before merging to master.

Fixes for dEQP shader.precision.float.mediump_add_fragment

---

sdk/tests/conformance/extensions/oes-texture-float.html
sdk/tests/conformance/extensions/oes-texture-half-float.html

Also fixes some indent levels.

Require color_buffer exts if float textures are implicitly renderable.

---

extensions/proposals/WEBGL_video_texture/extension.xml

Rename the extension so that it specifically covers the case of binding
video textures to WebGL textures.

Rename OES_EGL_image_external to WEBGL_video_texture

---

sdk/tests/conformance/glsl/bugs/00_test_list.txt
sdk/tests/conformance/glsl/bugs/conditional-texture-fetch.html

This is a reduced test case for a bug reported by Figma. It produces an HLSL compiler error on ANGLE's Direct3D 9 backend, but doesn't (yet) produce incorrect rendering results.

Add test case for texture fetches inside conditionals.

---

sdk/tests/conformance/glsl/bugs/sampler-array-struct-function-arg.html

This test is not intended to be specific to WebGL 2.0.
Fixes issue #2514.

Remove incorrect context version from sampler array test

---

sdk/tests/conformance/textures/misc/00_test_list.txt
sdk/tests/conformance/textures/misc/texture-with-flip-y-and-premultiply-alpha.html

It's about uploading textures from typed array with invalid type/format
while FLIP_Y or PREMULTIPLY_ALPHA is set to true.

Add a regression test for Chrome bug crbug.com/765469

---

tools/.gitignore
tools/README.md
tools/conformance.py

This script is to run any version of Khronos WebGL conformance test on
various OSes (like Android, ChromeOS, Linux, MacOS and Windows) with
various browsers (like Chrome, Edge, FireFox, Safari, etc.). Results
will be compared with expectations and a final report will be generated.

Add conformance test script

---

extensions/proposals/WEBGL_texture_source_iframe/extension.xml

I've done a bit of rewording regarding promises to be a bit closer to TAG's guide, i.e.:
- added `<void>` to signify that no additional data's passed with promise;
- replaces "returns promise" with "promise will be fulfilled" as it's a bit more accurate.
/cc @zhenyao

WEBGL_texture_source_iframe: some rewording about promises

---

sdk/tests/conformance/glsl/bugs/00_test_list.txt
sdk/tests/conformance/glsl/bugs/vector-scalar-arithmetic-inside-loop-complex.html

Add more variations of shaders that reproduce the same bug. This adds
better coverage for a workaround under development for ANGLE.
Some more complex variations are put to a separate test file - the
workaround in ANGLE will not be sophisticated enough to handle them,
but they should be fixed by a future driver update.

Add more tests for vector/scalar arithmetic inside a loop

---

sdk/tests/conformance/canvas/00_test_list.txt
sdk/tests/conformance/canvas/render-after-resize-test.html

This test passes on Firefox on my 2014 MBP macOS 10.13 but fails on Chrome 62-64

Adds a test for rendering directly after resizing the canvas

---

extensions/proposals/WEBGL_multiview/extension.xml

The multiview spec is now written against the latest revision of the
native OVR_multiview spec. The native OVR_multiview spec has been
tightened to specify more error conditions, so some of the addendums
in the WebGL spec are not necessary anymore.
Formatting and examples are also improved.
This doesn't introduce any major functional changes.

Clarify WEBGL_multiview spec

---

sdk/tests/conformance/canvas/render-after-resize-test.html

Exposes the issue more simply. Follow-on to #2546.
Still passes in Firefox, fails in Chrome and Safari, on macOS 10.13 on
MacBook Pro with NVIDIA GPU.

Simplify render-after-resize-test. Draw single unit quad.

---

conformance-suites/1.0.1/conformance/more/functions/texSubImage2DBadArgs.html
conformance-suites/1.0.2/conformance/more/functions/texSubImage2DBadArgs.html
conformance-suites/1.0.3/conformance/more/functions/texSubImage2DBadArgs.html
conformance-suites/2.0.0/conformance/more/functions/texSubImage2DBadArgs.html
sdk/tests/conformance/more/functions/texSubImage2DBadArgs.html

INVALID_OPERATION should also be an acceptable result because texSubImage2d could be called with format and type that differ from format and type that was set previously by texImage2D.

Accept INVALID_OPERATION for texSubImage2D when format/type differs

---

sdk/tests/conformance/rendering/00_test_list.txt
sdk/tests/conformance/rendering/rendering-stencil-large-viewport.html

On Intel windows platforms, rendering large viewport and stencil buffer
enabled will lead to memory leak on d3d11 driver.
Test for help reproduce bug http://crbug.com/782317

Reproduce Intel driver bug on windows when rendering large viewport

---

conformance-suites/1.0.0/resources/webgl-test-harness.js
conformance-suites/1.0.1/resources/webgl-test-harness.js
conformance-suites/1.0.2/resources/webgl-test-harness.js
conformance-suites/1.0.3/resources/webgl-test-harness.js
conformance-suites/2.0.0/js/webgl-test-harness.js
sdk/tests/js/webgl-test-harness.js

The wrapped logging function it uses only takes one argument.
Concatenate the message to the success state string rather
than passing it as an unused second argument.

Make test harness result reporter log success message to console

---

sdk/tests/deqp/framework/common/tcuFuzzyImageCompare.js

This is a typo compared with the native dEQP source code.

Fix a bug in tcuFuzzyImageCompare.bilinearSample

---

sdk/tests/conformance/glsl/bugs/00_test_list.txt
sdk/tests/conformance/glsl/bugs/in-parameter-passed-as-inout-argument-and-global.html

Some recent versions of NVIDIA GL drivers have an issue with a
function in parameter being passed as an inout argument while there is
a global variable with the same name.
The issue will be fixed in a future NVIDIA driver update.
http://crbug.com/792210

Add a test for weird name conflict on NVIDIA GL driver

---

sdk/tests/conformance/glsl/bugs/00_test_list.txt
sdk/tests/conformance/glsl/bugs/assign-to-swizzled-twice-in-function.html

This reproduces a crash at least in Chromium running on recent NVIDIA
OpenGL drivers.
Chrome bug report that this test case is based on is here:
http://crbug.com/798117

Add a test for assigning twice to a swizzled vec inside a function

---

specs/latest/1.0/index.html
specs/latest/1.0/webgl.idl
specs/latest/2.0/index.html
specs/latest/2.0/webgl2.idl

WebIDL recently introduced dedicated syntax for mixins [1]. This
replaces the existing [NoInterfaceObject] and "implements" syntax with
"interface mixin" and "includes" in the appropriate places.
This fixes #2538, fixes #2539 issues.
[1] https://github.com/heycam/webidl/commit/45e8173d40ddff8dcf81697326e094bcf8b92920

Use Web IDL's new-ish interface mixins concept

---

sdk/tests/conformance2/uniforms/00_test_list.txt
sdk/tests/conformance2/uniforms/dependent-buffer-change.html
sdk/tests/conformance2/uniforms/simple-buffer-change.html

Regression tests for: https://bugs.chromium.org/p/chromium/issues/detail?id=792966
Ported the two ANGLE UBO dirty bit regression tests, SimpleBufferChange and DependentBufferChange, from https://github.com/google/angle/blob/master/src/tests/gl_tests/UniformBufferTest.cpp
I haven't been able to test that this actually catches the bug, since Chrome and Firefox are both updated for me, so this should be verified by someone. (Is there an easy way to get older versions of Chrome to test things like this?)

Regression tests for ANGLE UBO dirty bit bug

---

specs/latest/2.0/index.html
specs/latest/2.0/webgl2.idl

Introduced `interface mixin` syntax in #2566 but it's incorrect.
A `interface mixin` SHOULD NOT includes another mixin.
This fixes #2574.

Fix misuse of mixin syntax

---

sdk/tests/conformance2/textures/misc/00_test_list.txt
sdk/tests/conformance2/textures/misc/copy-texture-image-same-texture.html

are from the same texture.
This is a regression test for crbug.com/797235

Add a test case for CopyTexImage2D behavior when source/target images

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/forward-declaration.html

Fails on Pixel C with Chrome because of flattening of precision
qualifiers into variables' types, and because of a bug in the GLSL
compiler on this device.
Thanks to Robert Muth of art.muth.org for reporting.

Add GLSL 3.00 test for forward declarations of functions.

---

specs/2.0.0/index.html
specs/latest/2.0/index.html

These 2 GLenums have been added into WebGL 1.0 spec: https://www.khronos.org/registry/webgl/specs/latest/1.0/. So it is not necessary to add them again in WebGL 2.0 spec. You know, WebGL 2.0 spec only show the new added GLenums.

Remove unnecessary GLenums about coverage

---

tools/conformance.py

It seems this WebDriver based harness also uses the Chrome-specific
Telemetry API when running on ChromeOS.
Fixes http://crbug.com/803843 . Thanks to nednguyen@ for the patch.

Update new test harness's use of Telemetry API.

---

sdk/tests/conformance/textures/misc/texture-size.html

Variances of 2 have now been seen on MacBook Pros with AMD GPUs:
https://ci.chromium.org/buildbot/chromium.gpu/Mac%20Retina%20Release%20%28AMD%29/22175
Fixes http://crbug.com/804887 .

Increase tolerance to 3.

---

conformance-suites/1.0.3/conformance/textures/texture-size-limit.html
conformance-suites/2.0.0/conformance/textures/misc/texture-size-limit.html
sdk/tests/conformance/textures/misc/texture-size-limit.html

Different formats have different effective max texture sizes/max mip levels.

Probe for max texture level for each format separately.

---

sdk/tests/conformance/glsl/bugs/00_test_list.txt
sdk/tests/conformance/glsl/bugs/if-return-and-elseif.html

An if statement containing a return together with an else if produces
wrong output on Chrome and Firefox on Windows.
This is a minimal test case for this bug: http://anglebug.com/2325

Add a test for a HLSL bug with if, return and else if

---

sdk/tests/conformance/extensions/angle-instanced-arrays.html

The newest version of the ANGLE_instanced_arrays test runs different
subtests with different shaders, which may have overlapping attrib
locations. Make sure that the different subtests don't interfere with
each other by resetting vertex attrib divisors after each subtest.
Previously the test could pass if attrib locations were automatically
assigned in a certain way, but changes to attribute location
assignment in the WebGL implementation could make it fail when it
should have passed.
This change does not need to be backported to earlier conformance suite
versions nor the WebGL 2 test for instancing, as they only use one
shader and always bind vertex attrib locations explicitly, so the
locations can only be set one way.

Reset vertex attrib divisors between instancing tests

---

conformance-suites/2.0.0/conformance2/textures/misc/copy-texture-image-luma-format.html
sdk/tests/conformance2/textures/misc/copy-texture-image-luma-format.html

The test is not querying attribute locations, so use the test
utilities to bind the attributes to locations 0 and 1. This ensures
that the test runs consistently.
This change is backported also to conformance suite version 2.0.0.

Assign attribute locations explicitly in luma texture copy test

---

sdk/tests/conformance2/sync/sync-webgl-specific.html
specs/latest/2.0/index.html

Follow the same semantics for sync objects as were previously used for
queries. Add a test for the new behavior.

Define that sync objects do not become signaled until control returns to the event loop.

---

sdk/tests/conformance2/context/00_test_list.txt
sdk/tests/conformance2/context/context-sharing-texture2darray-texture3d-data-bug.html

This test verifies that 2 different contexts both using 2d array texture
or 3d texture does not share/leak the texture data among them due to context
save/restore bug.

Multiple WebGL2 Context sharing texture2darray/texture3d data bug test.

---

sdk/tests/conformance2/context/context-sharing-texture2darray-texture3d-data-bug.html

This test was passing when using python SimpleHTTPServer even if the include
paths were incorrect. This is because python smartly searched for these include
files in other folders. The test failed when command line was used to run test
by bots or when running test directly on chrome without using the simplehttpserver.

Include file path fix for a test.

---

sdk/tests/conformance2/transform_feedback/00_test_list.txt
sdk/tests/conformance2/transform_feedback/simultaneous_binding.html
sdk/tests/conformance2/transform_feedback/states-and-errors.html
sdk/tests/conformance2/transform_feedback/switching-objects.html

Adds a new test switching-objects.html which tests various consequences of switching transform feedback objects. This includes a test for the new behavior where TRANSFORM_FEEDBACK_BUFFER is not modified when switching transform feedback objects. The OpenGL/ES working group just approved the spec change for this new behavior.
Also adds testing of drawElements cases in simultaneous_binding.html, in addition to existing drawArrays cases.

Expanded transform feedback tests

---

sdk/tests/conformance2/transform_feedback/00_test_list.txt
sdk/tests/conformance2/transform_feedback/too-small-buffers.html

The ES spec says that drawing should always fail with GL_INVALID_OPERATION when the bound transform feedback buffers are too small to hold the result. Chrome and Firefox both fail some of these tests (on Linux Nvidia at least).

Test transform feedback into too small buffers.

---

sdk/tests/js/tests/out-of-bounds-test.js

In particular, don't try to draw $LARGE numbers of triangles. An RBAB
implementation will not reject these 'invalid' draws, and will try to draw
all the triangles, which, for N=0x7fffffff trips the TDR and incurs context
loss.

Support robust_buffer_access_behavior implementations.

---

sdk/tests/conformance/glsl/bugs/constant-precision-qualifier.html

finishTest() is called right after test() returns, ending the test prematurely before all the test cases complete. This is because test() has a call to GLSLConformanceTester.runRenderTests(), which runs the tests asynchronously. runRenderTests() also already calls finishTest() after the last test completes.

constant-precision-qualifier.html is finishing early due to an extra finishTest()

---

sdk/tests/js/glsl-conformance-test.js

GLSLConformanceTester.runTests() uses setTimeout(.., 1) in between tests, making the tests asynchronous. runOneTest(), the function called in the setTimeout callback, doesn't do intensive work that takes a long time, and it does a checkCanvas at the end of the function that would reset the harness timeout timer. Changing this to a synchronous for loop instead.
This PR is a followup from #2608

Remove setTimeout() from GLSLConformanceTester.runTests()

---

specs/latest/1.0/index.html

WebGL has long enforced behavior that goes against GLSL ES 3.00.6
section 12.47. WebGL requires that uniform and attribute names don't
collide, whereas GLSL ES specifies that there's no collision in this
case. The WebGL test that enforces this is:
conformance\glsl\misc\shaders-with-name-conflicts.html
The test refers to discussion in OpenGL ES working group, but it seems
that the results of the discussion were not put into writing outside
of the test case.
Explicitly specify the WebGL behavior to clear confusion around this.

Explicitly specify uniform and attribute name collisions

---

sdk/tests/conformance2/glsl3/short-circuiting-in-loop-condition.html

The test in for loop expression can't expose an Intel driver bug. We
add another test in for loop condition to conver it.

Add a test case in for loop condition

---

sdk/tests/webgl-conformance-tests.html

Skipped tests also show as gray instead of red.

Report skipped tests as both skipped and failed rather than just failed.

---

sdk/tests/conformance/misc/webgl-specific-stencil-settings.html
sdk/tests/js/webgl-test-utils.js

and add a safeguard against future glEnumToString usage mistakes
(follow-up to #2583)

Fix usage of glEnumToString in webgl-specific-stencil-settings

---

sdk/tests/conformance2/attribs/00_test_list.txt
sdk/tests/conformance2/attribs/gl-bindAttribLocation-aliasing-inactive.html
sdk/tests/js/tests/gl-bindattriblocation-aliasing.js
sdk/tests/js/webgl-test-utils.js
specs/latest/2.0/index.html

GLSL ES 3.00.6 already has strict rules when it comes to attribute
aliasing, so WebGL 2.0 can simply refer to those rather than spell out
its own.
A new test is added to fully cover the attribute aliasing rules of
GLSL ES 3.00.6. It shares some code with the older attribute aliasing
test for WebGL 1.0.

Clarify WebGL 2 spec for attribute aliasing

---

sdk/tests/js/webgl-test-utils.js

* the program now sets `gl_Position` and `gl_FragColor` to `vec4(0.0)`
* drawArrays now draws one triangle instead of 0
(but that triangle is of zero size)
This is necessary to make sure the draw call doesn't early out before it
does validation.
(follow-up to #2583)

Change dummySetProgramAndDrawNothing to draw >0 elements

---

sdk/tests/conformance/context/context-lost-restored.html

When calling restoreContext() multiple times after context is lost, each function call will cause a context restored event queued. All queued context restored events should be merged before a context restored event is fired. 
Calling restoreContext() multiple times should not cause error or crash. Added a test to test the behavior.

Test queueing multiple context restored event after context is lost

---

sdk/tests/conformance2/rendering/clearbuffer-and-draw.html
sdk/tests/js/webgl-test-utils.js

With the preserveDrawingBuffer:false context creation option, Chromium
was incorrectly tracking the effects of clearBuffer on the default
back buffer.
Modified various quad setup functions in webgl-test-utils to allow the
quad to be more easily scaled.
Regression test for http://crbug.com/828262 .

Test combinations of clearBuffer*(), clear() and draws.

---

sdk/tests/conformance2/sync/sync-webgl-specific.html

Like the conformance2/query/occlusion-query test, use a fixed number
of iterations, as on slow automated test machines, a fixed duration
based on Date.now() leads to test flakiness.
Improve the synchronization with the GL server by using readPixels
instead of flush or finish.

Use fixed number of iterations in sync-webgl-specific.

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/texture-offset-non-constant-offset.html

The existing texture offset tests did not seem to cover this invalid
usage of the texture offset functions yet.

Add a test for using non-constant texture offset

---

sdk/tests/conformance2/glsl3/switch-case.html

This was not being validated correctly by ANGLE until recently, though
this would not cause issues if the native drivers were working
correctly.

Add a test for having a case statement inside a block

---

sdk/tests/js/webgl-test-utils.js

loadShader thinks shaderSource generated an error, but really it's an error from a previous call. We can either assert before calling shaderSource that there's no current GL error, OR we can just treat shaderSource as infallible, which it really should be here.

wtu.loadShader's gl.shaderSource should be treated as infallible.

---

extensions/WEBGL_shared_resources/extension.xml

Checked with https://www.w3.org/2009/07/webidl-check (plugging in some
needed definitions above this extension's IDL).
Fixes #2596.

Fix IDL of WEBGL_shared_resources draft extension.

---

sdk/tests/conformance/misc/webgl-specific-stencil-settings.html
sdk/tests/js/webgl-test-utils.js

Add new tests testing
- various transitions from valid to invalid states (in order to test invalidation of the cached validation in Chrome)
- drawing to the default framebuffer
Also modifies dummySetProgramAndDrawNothing to keep one WebGLProgram _per WebGL context_.
https://crbug.com/806557

Add more stencil validation tests

---

sdk/tests/conformance2/transform_feedback/simultaneous_binding.html

... and unbound VAOs.
This makes the simultaneous_binding test a little more complete.

Test transform feedback buffers bound to disabled vertex attribs

---

sdk/tests/conformance2/rendering/blitframebuffer-size-overflow.html
specs/latest/2.0/index.html

BlitFramebuffer bugs that trigger when using large rectangle
dimensions seem to be widespread on all desktop OpenGL drivers. They
have been seen on at least:
AMD Windows OpenGL
Intel Windows OpenGL
Intel Linux OpenGL
NVIDIA OpenGL (all platforms)
In addition there are some issues with handling large dimensions in
existing blitFramebuffer workarounds inside ANGLE.
In some cases these issues can be worked around by clipping the
blitFramebuffer rectangles so that their width and height fit a signed
32-bit integer. However, this approach doesn't work in case
blitFramebuffer is used to scale the framebuffer and the greatest
common divisor of the source and destination dimensions is 1.
Since these issues likely don't have any impact on real-world
applications, it's reasonable to limit the …

Limit blitFramebuffer source and destination rectangle size

---

sdk/tests/conformance/glsl/misc/00_test_list.txt
sdk/tests/conformance/glsl/misc/fragcolor-fragdata-invariant.html

Declaring a variable invariant doesn't access it, so it should not
really count as using the variable. Earlier versions of ANGLE would
treat declaring both gl_FragColor and gl_FragData invariant an error,
but recent versions have been fixed to allow this usage.

Add a test for declaring both gl_FragColor and gl_FragData invariant

---

sdk/tests/conformance2/textures/misc/tex-storage-2d.html
sdk/tests/conformance2/textures/misc/tex-storage-and-subimage-3d.html

Regression test from Firefox where e.g. level=9, width=512, height=1
fails.
https://bugzilla.mozilla.org/show_bug.cgi?id=1461293

Test texStorage[2,3]D with non-square sizes.

---

sdk/tests/conformance2/textures/misc/tex-storage-2d.html
sdk/tests/conformance2/textures/misc/tex-storage-and-subimage-3d.html

Reverts KhronosGroup/WebGL#2647
There was a bug in the handling of cube map textures.

Revert "Test texStorage[2,3]D with non-square sizes."

---

sdk/tests/conformance2/rendering/blitframebuffer-size-overflow.html

The range of an integer is [-0x7fffffff - 1, 0x7fffffff].
We restrict the width/height to the max value that can be
store in an integer in latest WebGL 2 spec. If we
reverse the data order for blitting, an invalid value like
0x7fffffff + 1 would become a valid value for an integer:
-0x7fffffff - 1. But it is invalid for blitting.
The new added tests cover this corner case to make it clear.

Add tests for blitting to cover width/height overflow.

---

conformance-suites/1.0.2/resources/js-test-pre.js
conformance-suites/1.0.3/resources/js-test-pre.js
conformance-suites/2.0.0/js/js-test-pre.js
sdk/tests/js/js-test-pre.js

LayoutTests have supported window.requestAnimationFrame for a while. I am removing this WebKit-specific code so that window.requestAnimationFrame calls will not fail on WebKit's test framework.

WebKit (now) supports requestAnimationFrame

---

sdk/tests/conformance/textures/misc/texture-size-limit.html
sdk/tests/js/tests/iterable-test.js
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-canvas.js
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-webgl-canvas.js
sdk/tests/js/tests/webgl-compressed-texture-size-limit.js
sdk/tests/js/webgl-test-utils.js
sdk/tests/test-guidelines.md

Texture upload tests in particular take a long time because they run a max of
60 tests per second, because they rely on waitForComposite to yield execution.
waitForComposite should only be used when necessary. Use dispatchTask if we
want to yield to the event loop.
Before:
all/conformance/textures/canvas (Passed: 3880/3880 in 48.68 seconds)
conformance/textures/canvas/tex-2d-rgb-rgb-unsigned_byte.html (Passed: 1122/1122 in 14113.0 ms)
After:
all/conformance/textures/canvas (Passed: 3880/3880 in 8.90 seconds)
conformance/textures/canvas/tex-2d-rgb-rgb-unsigned_byte.html (Passed: 1122/1122 in 2097.0 ms)

Add wtu.dispatchTask for use instead of waitForComposite.

---

sdk/tests/conformance2/transform_feedback/simultaneous_binding.html

The transform feedback generic binding point is not part of the transform feedback object and is not used for transform feedback. Only the indexed binding points are used. A buffer that is bound to the generic binding point should be usable for either transform feedback or non-transform-feedback purposes.
I realized this was a problem in [crbug.com/853978](http://crbug.com/853978). The previous behavior was confusing because unbinding the transform feedback object was not enough to enable drawing from a transform feedback buffer if it was still bound to the generic binding point.

Transform feedback generic binding point should not block buffer usage

---

sdk/tests/conformance2/transform_feedback/00_test_list.txt
sdk/tests/conformance2/transform_feedback/same-buffer-two-binding-points.html
specs/latest/2.0/index.html

This case used to be underspecified, so behavior varies between
platforms. Particularly on D3D having two stream outputs written to
the same buffer is disallowed, and on OpenGL ES there's some undefined
behavior. Prohibit having the same buffer bound to two transform
feedback outputs when calling BeginTransformFeeback to avoid
non-portable behaviors from now on.
Currently the test doesn't yet generate the expected error on any of
the platforms tested. On Chromium or Firefox running on ANGLE's D3D
backend, the buffer is not touched by transform feedback.
On Chromium's GL backend, only one of the outputs is written to the
buffer by transform feedback.
The behavior is the same on recent HW/drivers from both NVIDIA and
Intel.

Specify binding one buffer to two transform feedback outputs

---

sdk/tests/conformance/textures/misc/tex-video-using-tex-unit-non-zero.html
sdk/tests/js/webgl-test-utils.js

Use WebGLTestUtils.comparePixels, and include failing video type in
error messages.
Intended to diagnose intermittent failures of this test in
http://crbug.com/830901 .

Improve logging for tex-video-using-tex-unit-non-zero.html .

---

conformance-suites/1.0.3/conformance/ogles/GL/struct/nestedstructcomb_various_frag.frag
conformance-suites/1.0.3/conformance/ogles/GL/struct/nestedstructcomb_various_vert.vert
conformance-suites/2.0.0/conformance/ogles/GL/struct/nestedstructcomb_various_frag.frag
conformance-suites/2.0.0/conformance/ogles/GL/struct/nestedstructcomb_various_vert.vert
sdk/tests/conformance/ogles/GL/struct/nestedstructcomb_various_frag.frag
sdk/tests/conformance/ogles/GL/struct/nestedstructcomb_various_vert.vert

Affects the ogles/struct/struct_049_to_56.html tests.  The ERROR_EPSILON
value of 0.1 was too strict for FP16 implementation of medium precision.
This change relaxes the epsilon to 0.125.
Fixes #2675

Fix the ERROR_EPSILON for GL struct tests

---

specs/latest/1.0/index.html
specs/latest/1.0/webgl.idl
specs/latest/2.0/index.html
specs/latest/2.0/webgl2.idl

This extended attribute has been required by Web IDL since
heycam/webidl#423 . In order for WebGL to be accessible by web workers
using OffscreenCanvas, the attribute being added to all WebGL
interfaces is:
[Exposed=(Window,Worker)]
Fixes #2571 .

Add [Exposed] Web IDL attribute to all WebGL interfaces.

---

sdk/tests/conformance2/extensions/00_test_list.txt
sdk/tests/conformance2/extensions/webgl_multiview.html
sdk/tests/conformance2/extensions/webgl_multiview_draw_buffers.html
sdk/tests/conformance2/extensions/webgl_multiview_flat_varying.html
sdk/tests/conformance2/extensions/webgl_multiview_instanced_draw.html
sdk/tests/js/tests/webgl_multiview_util.js

This adds tests for different features that interact with
WEBGL_multiview:
1. Multiple draw buffers.
2. Using a flat varying in a multiview shader (this covers a bug that
was recently worked around in ANGLE).
3. Instanced draw calls. Multiview can be implemented by leveraging
instancing together with some other GL / D3D11 features, so it's
important to test this.
All of these tests pass when run against Chrome Canary with WebGL
draft extensions enabled.

Add more WEBGL_multiview tests

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/framebuffer-completeness-draw-framebuffer.html

The test checks that the draw framebuffer can still be rendered to
even if the read framebuffer is incomplete.
The new test exposes a bug in Chrome 67. It seems to be specific to
ANGLE's D3D11 backend. Bug link: http://anglebug.com/2737
The latest stable version of Firefox is not affected by the bug.

Add a test for draw framebuffer completeness

---

sdk/tests/js/webgl-test-utils.js

Chrome's media team points out that their own internal tests only
watch for video.currentTime > 0, and those tests are reliable. Use the
same structure in WebGLTestUtils. This change should work across all
web browsers.
Addresses feedback given in http://crbug.com/834933 . Attempting to
eliminate test flakiness observed in http://crbug.com/830901 .

Simplify WebGLTestUtils.startPlayingAndWaitForVideo.

---

sdk/tests/conformance2/extensions/00_test_list.txt
sdk/tests/conformance2/extensions/webgl_multiview_non_multiview_shaders.html
sdk/tests/conformance2/extensions/webgl_multiview_single_view_operations.html

This adds two test files. One concentrates on drawing to multiview
framebuffers with shaders that don't contain a GL_OVR_multiview
extension directive. The other one does different operations on
multiview framebuffers containing just a single view.
All of the added tests pass with the latest version of ANGLE, however
latest Chromium still needs to integrate the latest ANGLE changes with
fixes to multiview read functionality.

Add WEBGL_multiview tests for single view operations

---

sdk/tests/conformance2/extensions/webgl_multiview.html
sdk/tests/js/webgl-test-utils.js

The added tests make sure that none of the WEBGL_multiview
functionality is enabled if the extension is disabled.

Test WEBGL_multiview when the extension is disabled

---

specs/latest/1.0/webgl.idl

Follow-on to #2685. Forgot to regenerate the IDL after backing off
from my first change.
Related to #2683.

Regenerate WebGL 1.0 IDL.

---

other/get.webgl.org/troubleshooting/DoNotCopyOrLinkThisFileElseYouWillNotGetAutoUpdatedHelpForYourUsers.js

Make it point to the top-level help for Chrome. The previous URL has
been redirected to a "tips and tricks" page which is not very useful.
Thanks to webmaster James Riordon for raising the issue.

Update Chrome troubleshooting URL.

---

specs/latest/2.0/index.html

I'm intending to use a derivative of this text in an MDN update as well.

Document non-blocking getBufferSubData

---

extensions/rejected/WEBGL_get_buffer_sub_data_async/extension.xml

This was causing the extension registry to fail to rebuild
successfully.

Fix href of rejected WEBGL_get_buffer_sub_data_async extension.

---

specs/latest/1.0/index.html
specs/latest/2.0/index.html

OffscreenCanvas is documented in the WHATWG's current specifications,
and browsers are beginning to ship support for fetching WebGL contexts
against them, as well as use them as texture sources. Document this
properly in the WebGL specification.
In Chromium, this work was tracked under issue http://crbug.com/563816
and many dependent bugs.

Add references to OffscreenCanvas.

---

sdk/tests/conformance/buffers/buffer-data-array-buffer-delete.html
sdk/tests/conformance/canvas/canvas-test.html
sdk/tests/conformance/canvas/draw-static-webgl-to-multiple-canvas-test.html
sdk/tests/conformance/canvas/draw-webgl-to-canvas-test.html
sdk/tests/conformance/canvas/framebuffer-bindings-affected-by-to-data-url.html
sdk/tests/conformance/canvas/rapid-resizing.html
sdk/tests/conformance/canvas/to-data-url-test.html
sdk/tests/conformance/context/context-attribute-preserve-drawing-buffer.html
sdk/tests/conformance/context/premultiplyalpha-test.html
sdk/tests/conformance/renderbuffers/framebuffer-state-restoration.html
sdk/tests/conformance/rendering/multisample-corruption.html
sdk/tests/conformance/rendering/preservedrawingbuffer-leak.html
sdk/tests/conformance/textures/misc/tex-video-using-tex-unit-non-zero.html
sdk/tests/conformance/textures/misc/texture-upload-size.html
sdk/tests/conformance2/rendering/canvas-resizing-with-pbo-bound.html
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-webgl-canvas.js

Those tests error out when run in Servo because of missing support for a bunch of features, such as preserving the drawing buffer or loading SVG images. Instead, make the tests fail, and finish the tests
so that the next ones are started.

Make some tests succeed to fail more gracefully

---

specs/latest/1.0/index.html
specs/latest/2.0/index.html

This behavior is already tested by gl-vertex-attrib.html.
Fixes #2700.

Better specify errors for vertexAttrib*v entry points.

---

sdk/tests/conformance/rendering/framebuffer-switch.html
sdk/tests/conformance/rendering/framebuffer-texture-switch.html

Servo doesn't implement the named getter yet and thus those tests fail for
reasons unrelated to our WebGL support.

Avoid using window's named getter on a couple of tests

---

sdk/demos/common/webgl-utils.js
sdk/demos/intel/ComputeBoids.html

This example is ported from
https://github.com/google/nxt-standalone/blob/master/examples/ComputeBoids.cpp.
Try this example using latest chrome canary with below commands:
Chrome.exe --use-cmd-decoder=passthrough --enable-webgl2-compute-context
--use-angle=gl  --use-gl=angle
Currently, it still can't get correct result on d3d backend since SSBO
for d3d is still under development in ANGLE.

Add ComputeBoids example

---

extensions/proposals/WEBGL_blend_equation_advanced_coherent/extension.xml

Proposal to expose KHR_blend_equation_advanced_coherent to WebGL. Forked from the previous proposal for KHR_blend_equation_advanced according to #2704.

Propose WEBGL_blend_equation_advanced_coherent

---

sdk/tests/conformance/extensions/00_test_list.txt
sdk/tests/conformance/extensions/webgl-compressed-texture-astc.html
sdk/tests/conformance/extensions/webgl-compressed-texture-etc.html
sdk/tests/conformance/extensions/webgl-compressed-texture-etc1.html
sdk/tests/conformance/extensions/webgl-compressed-texture-s3tc-srgb.html
sdk/tests/conformance/extensions/webgl-compressed-texture-s3tc.html
sdk/tests/conformance/textures/misc/00_test_list.txt
sdk/tests/conformance/textures/misc/compressed-tex-image.html
sdk/tests/js/tests/compressed-texture-utils.js
sdk/tests/js/webgl-test-utils.js

This refactors code to share some common utilities for testing compressed textures, improves negative test coverage and adds some tests for WEBGL_compressed_texture_etc1.

Improve compressed texture tests

---

extensions/WEBGL_compressed_texture_bptc/extension.xml
sdk/tests/conformance/extensions/00_test_list.txt
sdk/tests/conformance/extensions/webgl-compressed-texture-bptc.html

The test is not very thorough yet, as it's not testing for correct
decoding of the compressed data. However, more complete tests will be
easier to develop once there is a prototype implementation available.
The extension is moved to draft so that prototyping can proceed.

Add a test for WEBGL_compressed_texture_bptc

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/instanced-rendering-large-divisor.html

This test covers a recently fixed ANGLE bug http://anglebug.com/2832
that was present on the D3D11 backend.

Add a test for instanced rendering with large divisors

---

sdk/tests/conformance/rendering/00_test_list.txt
sdk/tests/conformance/rendering/canvas-alpha-bug.html

This patch intends to add a conformance test to expose an alpha
blending issue on Chromium on Intel macOS drivers. The test is
based on the case provided in https://crbug.com/886970.

Add test to expose an alpha blending issue on Intel macOS drivers

---

extensions/EXT_texture_compression_bptc/extension.xml
extensions/EXT_texture_compression_rgtc/extension.xml
sdk/tests/conformance/extensions/00_test_list.txt
sdk/tests/conformance/extensions/ext-texture-compression-bptc.html
sdk/tests/conformance/extensions/ext-texture-compression-rgtc.html

Also retarget BPTC from the ARB_ ext to the EXT_ one, since EXT_ is the
ES version.
CC @Oletus, how does this sound?

Rename BPTC and RGTC extensions to EXT_.

---

specs/latest/1.0/index.html

Clarify that all depth resources are cleared to 1.0 by default.

---

sdk/tests/conformance/textures/misc/compressed-tex-image.html

Since this can happen before we check all our enums, this subtest
should accept either error.

*TexSubImage on an undefined texture image is INVALID_OPERATION.

---

conformance-suites/2.0.0/conformance2/textures/misc/copy-texture-image.html
sdk/tests/conformance2/textures/misc/copy-texture-image.html

* Sized formats can still drop components. (e.g. RGBA->RGB)
* Both RGBA8 and RGBA8_SNORM count as fixed-point.
* Depth formats may generate INVALID_OP in addition to INVALID_ENUM.

Changes to conformance2/textures/misc/copy-texture-image.html

---

specs/latest/2.0/index.html

Per the post-merge comments in https://github.com/KhronosGroup/WebGL/pull/2726 -- forgot to update the "latest" copy.

Clarify texStorage*D initialization for compressed formats

---

sdk/tests/conformance/rendering/00_test_list.txt
sdk/tests/conformance/rendering/draw-webgl-to-canvas-2d-repeatedly.html

Each draw should show only the most recently rendered content from the
WebGL canvas. This was not the case when rendering via SwiftShader.
Regression test for http://crbug.com/894021 .

Test repeated rendering of WebGL canvas to 2D canvas.

---

sdk/tests/conformance2/rendering/framebuffer-texture-changing-base-level.html

Also check that each level in turn is actually cleared to green.
Overall failure is still present in all browsers.

Cleanup in framebuffer-texture-changing-base-level.

---

sdk/tests/conformance/textures/misc/canvas-teximage-after-multiple-drawimages.html

The JavaScript execution was racing with document parsing, causing the
test to fail intermittently. Follow-on to #2706.
Chromium bug: http://crbug.com/905682 .

Run canvas-teximage-after-multiple-drawimages test in onload handler.

---

sdk/tests/conformance/rendering/00_test_list.txt
sdk/tests/conformance/rendering/color-mask-preserved-during-implicit-clears.html

Catches a bug that manifested on Chrome on macOS, but could have
affected any other platform. This new test already passes on Firefox.
Regression test for http://crbug.com/911918 .

Color mask must be preserved during implicit clears.

---

sdk/tests/conformance2/extensions/webgl_multiview_transform_feedback.html

This updates the CTS to be in line with the recent extension wording
change. It allows multiview rendering when Transform Feedback is bound
and paused.
See http://anglebug.com/3012
@kenrussell @jdashg @kainino0x  PTAL
Note anglebug.com links are temporarily broken but should be fixed at some point. Full issue here:
https://bugs.chromium.org/p/angleproject/issues/detail?id=3012
Also was having trouble testing this with Canary. It seems to ignore when ANGLE exposes the multiview extension. Not sure how to test this locally.

Update multiview transform feedback validation.

---

sdk/tests/conformance2/uniforms/incompatible-texture-type-for-sampler.html

Add checks for shadow samplers and add consideration of normalization for integer textures. The rules are:
Float samplers accept only float textures and normalized integer textures (signed or unsigned).
Signed samplers accept only signed integer textures (normalized or unnormalized).
Unsigned samplers accept only unsigned integer textures (normalized or unnormalized).
Shadow samplers accept only depth textures, and only if their TEXTURE_COMPARE_MODE state is set.
As a special extra restriction, depth textures cannot be sampled by non-shadow samplers if their TEXTURE_COMPARE_MODE state is set. Non-depth textures are not affected by this restriction.

Test shadow samplers and TEXTURE_COMPARE_MODE

---

sdk/tests/conformance2/textures/misc/00_test_list.txt
sdk/tests/conformance2/textures/misc/generate-mipmap-with-large-base-level.html

On MacOSX, if we set a large TEXTURE_BASE_LEVEL on an immutable texture, then
call GenerateMipmap() on it will trigger a driver crash.

Add a regression test for crbug.com/913301

---

sdk/tests/conformance/rendering/color-mask-preserved-during-implicit-clears.html

Test against all variants of antialias and premultipliedAlpha.
Follow-on to #2751. Addresses additional scenarios from
http://crbug.com/913033 .

Add more variants of implicit-clear test.

---

sdk/tests/deqp/functional/gles3/es3fShaderTextureFunctionTests.js

This test uses shadow samplers, so it is required to set TEXTURE_COMPARE_MODE to avoid INVALID_OPERATION. We can set it unconditionally because it is ignored for non-depth textures.

COMPARE_MODE is required to use shadow samplers

---

sdk/tests/conformance/context/deleted-object-behavior.html
sdk/tests/conformance2/transform_feedback/transform_feedback.html

Framebuffers and programs are the primary container objects in the
WebGL 1.0 specification. Test deleting attachments of both bound and
unbound framebuffers. Deleting programs and shaders is well tested
elsewhere.
Strengthen the WebGL 2.0-specific transform feedback test to cover
deleting output buffers, as well as active transform feedback objects.
Vertex Array Objects (VAOs), the last container type, are already well
tested by conformance/extensions/oes-vertex-array-object.html and
conformance2/vertex_arrays/vertex-array-object.html .
Regression test for http://crbug.com/739604 .

Add deleted object test; strengthen transform feedback test.

---

specs/latest/1.0/index.html
specs/latest/2.0/index.html

This was previously done in #2228 but a couple of places were missed.
The specified behavior is already tested by the conformance suite.

Allow vertexAttribPointer to reset binding points' state.

---

sdk/tests/conformance/extensions/oes-texture-float.html

Add framebuffer tests to oes-texture-float, copied test format from oes-texture-half-float.
The oes-texture-half-float pr: https://github.com/KhronosGroup/WebGL/pull/1622.

Add framebuffer tests to oes-texture-float

---

sdk/tests/conformance/extensions/oes-texture-half-float.html

Replaces getTypeName and getFormatName with glEnumToString util function.

Use glEnumToString helper for format and type names

---

sdk/tests/webgl-conformance-tests.html

Try it live here:
http://kai.graphics/WebGL/sdk/tests/webgl-conformance-tests.html
It's not that polished, but I think it's an improvement on mobile devices. The swoopy iframe might not be the most popular, but it could be made mobile only. (EDIT: made it more usable, so it's probably okay for desktop now)
I had some more ideas for making the test runner more friendly to use, but they're harder.
Emulated display on a small screen (Chrome DevTools' iPhone 5 setting):

Runner: semi-optimize layout for smaller screens

---

sdk/tests/deqp/framework/common/tcuSkipList.js

It is skipped in native dEQP. See:
https://android.googlesource.com/platform/external/deqp/+/40ff528%5E%21/
https://bugs.chromium.org/p/angleproject/issues/detail?id=3094

Skip texture_functions.texturelodoffset.sampler3d_float_vertex

---

conformance-suites/1.0.3/conformance/misc/webgl-specific.html

The 1.0.3 version of webgl-specific.html should request stencil:true, and enable(STENCIL_TEST).

Stencil mismatch is only an error if there are active stencil bits.

---

sdk/tests/conformance/textures/misc/texture-active-bind.html
sdk/tests/js/js-test-pre.js

Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1503813

Test for A8-on-R8 swizzle being applied to the wrong tex unit.

---

sdk/tests/conformance/reading/read-pixels-test.html
specs/latest/1.0/index.html

This would allow, for example, BGRA readPixels, even though BGRA would
normally be an INVALID_ENUM for webgl.

Allow arbitrary enums for readPixels via IMPLEMENTATION_COLOR_READ_*.

---

conformance-suites/2.0.0/deqp/framework/common/tcuSkipList.js
sdk/tests/deqp/framework/common/tcuSkipList.js

(These suppressions were already in 2.0.0, this just adds them to
top-of-tree 2.0 as well.)
crbug.com/695679
crbug.com/906745

Skip deqp derivate.dfdy highp tests on 2.0 ToT

---

sdk/tests/js/tests/tex-image-and-sub-image-2d-with-canvas-sub-rectangle.js
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-canvas.js
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-data.js
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-webgl-canvas.js
sdk/tests/js/tests/tex-image-and-sub-image-with-image-bitmap-utils.js

Seems to no longer be necessary to skip these cases/checks!
Tested on 10.13.6 (Chrome, Firefox) and 10.12.6 (Chrome).
crbug.com/665197

Remove skipCorner logic from texImage *_integer-unsigned_byte tests

---

sdk/tests/deqp/functional/gles3/00_test_list.txt

The builtinprecision tests are not correct. Errors were introduced when porting the tests from C++ to JavaScript. Tests that fail here pass in the C++ version of dEQP ported to WASM. This change disables the tests until they can be fixed.

Disable incorrect builtinprecision tests

---

conformance-suites/2.0.0/deqp/functional/gles3/es3fNegativeVertexArrayApiTests.js
sdk/tests/deqp/functional/gles3/es3fNegativeVertexArrayApiTests.js

If validating args, only the arg being validated should have an invalid
value. Thus, don't call drawElements(mode=-1, count=1) with a zero-byte
buffer, or you can get either error.

drawElements with a zero-byte buffer should call with count=0.

---

serve_localhost.py

This invokes a modified basic http.server that adds anti-caching
headers. Otherwise, browsers cache test files, making testing and
debugging less reliable.

Add serve_localhost.py for more robust local test runs.

---

specs/latest/1.0/index.html
specs/latest/2.0/index.html

This PR describes how DOM images are converted on texture uploads. It seems that implementations already follow this.
Partially resolves issue #2789.

Specify DOM image conversion

---

sdk/tests/conformance2/extensions/ext-float-blend.html
sdk/tests/js/tests/ext-float-blend.js

Added more ext-float-blend tests, similar to those new tests added to angle.
- testExtFloatBlendMRT
- testExtFloatBlendNonFloat32Type
Follow up work for this one: https://github.com/khronosgroup/webgl/pull/2779

add more ext-float-blend tests

---

sdk/tests/conformance/textures/misc/texture-active-bind.html

Fixes this test on Chrome due to #2818.

Fix A8-on-R8 swizzle test on Chrome

---

conformance-suites/2.0.0/deqp/temp_externs/html5.js
sdk/tests/deqp/temp_externs/html5.js

Remove temp_externs/html5.js's references to 'mozHidden' and 'mozVisibilityState'

---

sdk/tests/conformance2/uniforms/incompatible-texture-type-for-sampler.html

A sampler object can override a texture object's TEXTURE_COMPARE_MODE state. Chrome was not correctly accounting for this when validating texture/sampler compatibility.
Firefox nightly also currently fails a couple of cases in this test.

Test that sampler objects override texture state

---

sdk/tests/conformance2/buffers/get-buffer-sub-data-validity.html

This adds a minimal regression test for crbug.com/941930, where several things were being incorrectly managed in the nonblocking readback path in Chrome's passthrough command decoder.
It also `async`ifies this test to make it more readable.
I recommend reviewing the two commits separately - the first should make no functional changes.

 get-buffer-sub-data-validity.html: asyncify + regression test for crbug.com/941930

---

extensions/EXT_float_blend/extension.xml
sdk/tests/conformance/extensions/oes-texture-float.html
sdk/tests/conformance2/extensions/ext-float-blend.html
sdk/tests/js/tests/ext-float-blend.js

Update tests to require implicit activation accordingly.

Implicitly enable EXT_float_blend and promote it to Community Approved.

---

extensions/EXT_float_blend/extension.xml

Prevented building of the extension registry. Follow-up to #2830.

Fix XML for EXT_float_blend extension.

---

extensions/OVR_multiview2/extension.xml
sdk/tests/conformance2/extensions/ovr_multiview2.html
sdk/tests/conformance2/extensions/ovr_multiview2_depth.html
sdk/tests/conformance2/extensions/ovr_multiview2_draw_buffers.html
sdk/tests/conformance2/extensions/ovr_multiview2_flat_varying.html
sdk/tests/conformance2/extensions/ovr_multiview2_instanced_draw.html
sdk/tests/conformance2/extensions/ovr_multiview2_non_multiview_shaders.html
sdk/tests/conformance2/extensions/ovr_multiview2_single_view_operations.html
sdk/tests/conformance2/extensions/ovr_multiview2_timer_query.html
sdk/tests/conformance2/extensions/ovr_multiview2_transform_feedback.html
sdk/tests/js/tests/ovr_multiview2_util.js

Removed all references to opaque frame buffer. Removed support of WebGL, only WebGL2 2DTextureArrays are supported.
Function rename: framebufferTextureMultiviewWEBGL -> framebufferTextureMultiviewOVR
extension directive rename: GL_OVR_multiview -> GL_OVR_multiview2
Renamed all test files from webgl_multiview... to ovr_multiview2...

Renaming WEBGL_multiview to OVR_multiview2 spec and test changes

---

sdk/tests/conformance2/rendering/fs-color-type-mismatch-color-buffer-type.html

https://github.com/KhronosGroup/WebGL/pull/2780
Active draw buffers should have its corresponding outputs from fragment shader.

update test to sync up with spec update #2780

---

specs/latest/1.0/index.html
specs/latest/1.0/webgl.idl

Developers of stylus-based drawing applications (e.g. Google Keep)
have found this hint to be critical in order to be competitive with
native applications. It has been prototyped in Chromium and yields
significant latency improvements there.
This is the WebGL analogue of https://github.com/whatwg/html/pull/4360
and partially addresses https://github.com/whatwg/html/issues/4087 .
Principally authored by @yellowdoge, Miguel Casas-Sanchez <mcasas@chromium.org>

Add "desynchronized" flag to WebGLContextAttributes.

---

sdk/tests/conformance/extensions/webgl-compressed-texture-s3tc.html

As requested by @kenrussell in #2745 (so this should close it?).
Repeating the original issue here for clarity -- I discovered an overly restrictive checks in Firefox for compressed texture uploads from a PBO, where it allowed an image to be uploaded from a PBO with a non-zero initial offset, but always required the remaining size in the PBO to be equal to image size. This breaks for example in case a PBO contains more images and one wants to upload just one of them. The same works correctly under Chromium-based browsers.
This PR adds two tests:
- first, where the PBO size = image size, uploading the whole buffer contents to a texture (to test the common case, since there was no PBO+compression test before I think -- passes in both Chrome and Firefox)
- second, where the PBO size = 3 …

Test compressed texture upload from (a subrange of) a PBO

---

sdk/tests/conformance2/rendering/vertex-id.html

https://buganizer.corp.google.com/issues/129495560#comment3
As stated here, default precision for `int` is `mediump` which is often implemented as 16 bits on mobile parts. This would leads to the failure of this test on pixel 2 and 3 (Qualcomm)

User highp for VertexID in vertex-id.html test

---

LICENSE.txt
sdk/tests/conformance/attribs/gl-bindAttribLocation-aliasing.html

Copyright blocks can now be abbreviated to:
```
Copyright (c) [year] The Khronos Group Inc.
Use of this source code is governed by an MIT-style license that can be
found in the LICENSE.txt file.
```

Add LICENSE.txt.

---

extensions/proposals/EXT_texture_norm16/extension.xml

As suggested by @jdashg, that even with incomplete support on mobile,
this is still probably nice to expose.
@lexaknyazev succinctly summarized the rationale
in https://github.com/KhronosGroup/WebGL/issues/2810#issuecomment-466387837
1. Integer formats do not support filtering.
2. Floating point formats with comparable memory consumption provide less precision.
float16 can represent only about 15K distinct values in 0.0 .. 1.0 range.
float11 and float10 - fewer than 1K and 500 respectively.
3. DOM image sources (e.g. PNG) with 16 bits per channel could be copied to GPU
without intermediate floating point processing
Fixes #2180

Expose extension for EXT_texture_norm16.

---

sdk/tests/conformance/offscreencanvas/context-attribute-preserve-drawing-buffer.html
sdk/tests/conformance/offscreencanvas/offscreencanvas-resize.html
sdk/tests/js/tests/canvas-tests-utils.js

The commit() method of OffscreenCanvas contexts was controversial and has not been shipped by any browser. Rewrite the OffscreenCanvas tests to not require it.
For background, see:
https://github.com/w3ctag/design-reviews/issues/288
https://groups.google.com/a/chromium.org/d/topic/blink-dev/hRZ_P2o-aEk/discussion

Remove OffscreenCanvas commit() requirement

---

sdk/tests/conformance2/rendering/depth-stencil-feedback-loop.html

A feedback loop is formed regardless of the status of depth or stencil mask, and if depth or stencil test is turned on or not.
Related discussion could be found: https://bugs.chromium.org/p/chromium/issues/detail?id=763695
> I'm not sure whether it's feasible to require that if depth writes are disabled, that it's legal to sample a depth texture that's also attached to the FBO. The OpenGL ES 3.0.5 spec section 4.4.3.1 "Rendering Feedback Loops" and section 3.8.10.3 "Rendering Feedback Loops" don't say anything about depth textures and disabling depth writes, so I suspect that at least some OpenGL ES drivers will give undefined results in this scenario. This informs making this pattern illegal in WebGL, requiring copying the texture if it's desired to both have it bound as a sampled …

update depth stencil feedbackloop test behavior

---

sdk/tests/conformance/rendering/rendering-sampling-feedback-loop.html

This test also works for old driver not supporting `#extension GL_EXT_draw_buffers : require` for shaders. (d3d9 and some old android devices)

Fix rendering-sampling-feedback-loop test for old drivers

---

sdk/tests/conformance2/rendering/depth-stencil-feedback-loop.html

To form a feedback loop, texture needs to be complete. As stated in OpenGL ES 3.0.5 Section 3.8.13 (P161)
> Using the preceding definitions, a texture is complete unless any of the following conditions hold true:
...
• The effective internal format specified for the texture arrays is a sized
internal depth or depth and stencil format (see table 3.14), the value of
TEXTURE_COMPARE_MODE is NONE, and either the magnification filter is
not NEAREST or the minification filter is neither NEAREST nor NEAREST_-
MIPMAP_NEAREST.
Added some `gl.texParameteri` to make depth and depth_stencil texture "texture-complete"

Fix depth and stencil texture completeness in depth-stencil-feedback-loop.html

---

specs/latest/2.0-compute/index.bs

Program Pipeline is not a core feature for compute shader, it is
not very important. Furthermore, program pipeline is not very
useful. We didn't find that some demos or applications rely on it
and state that it is a must-to-have feature. In addition, we didn't
see a simple way to implement this feature on Direct3D 11. So we tend
to remove this feature from WebGL 2.0 compute.

Remove Program Pipeline from WebGL 2.0 compute

---

sdk/tests/conformance/offscreencanvas/context-attribute-preserve-drawing-buffer.html

There's no way to guarantee the compositor finished preparing the frame.
So we are gonna change the test to the following behavior: 
Do a for loop for `await nextFrame()` and keep doing readpixels and checking within the loop until we reach some time limit (say 0.5s). For testing `preserveDrawingBuffer: false` we could early terminate if the pixel data matches. And when testing `preserveDrawingBuffer: true` we could assert failure once the pixel doesn't match the expected ones.

Fix context-attribute-preserve-drawing-buffer.html

---

sdk/tests/conformance2/textures/misc/tex-mipmap-levels.html

Disambiguates failures in automated testing logs.

tex-mipmap-levels.html: more descriptive print messages

---

sdk/tests/conformance2/rendering/vertex-id.html

This test seem to fail on windows with angle back-end without explicitly declaring `gl_PointSize`

Add `gl_PointSize = 1.0;` in vertex-id.html to make consistent result on win + angle

---

specs/latest/2.0-compute/index.bs

Current <Copyright> section has two "specification": https://www.khronos.org/registry/webgl/specs/latest/2.0-compute/. It's incorrect. This small change fix the tiny bug. 
PTAL. @kenrussell

Fix a typo in Copyright for WebGL 2 compute

---

sdk/tests/conformance/extensions/webgl-depth-texture.html

This helps guarantee that WebGL1-on-ES3 works properly, since there was a question about the filterability of depth components in ES3.

In WEBGL_depth_texture test, check filtering results.

---

sdk/tests/conformance/attribs/gl-vertex-attrib-unconsumed-out-of-bounds.html
sdk/tests/conformance/extensions/webgl-draw-buffers.html
sdk/tests/conformance2/buffers/get-buffer-sub-data-validity.html
sdk/tests/deqp/modules/shared/glsShaderExecUtil.js

Based on the discussion here: https://github.com/KhronosGroup/WebGL/pull/2780, and finalization here: https://github.com/KhronosGroup/WebGL/issues/2845
Fix a test case to avoid `gl.INVALID_OPERATION` error generated;
FYI: By doing a quick search for `void main() {}`, there's another appearance in https://github.com/KhronosGroup/WebGL/blob/master/sdk/tests/conformance2/context/incorrect-context-object-behaviour.html
However it doesn't cause any error since there's no gl.draw(Arrays*/Elements*) call. Leave it unmodified.

Empty glsl fragment shader fixes

---

other/get.webgl.org/webgl2/index.html

Some browsers pass less than 20% of the WebGL2 conformance tests
yet turning on support would make it appear WebGL2 is supported
leading to improper reporting all around the net.
Here's a minor test to try to weed out such implementations
from reporting support.

Handle Bad Implementations

---

extensions/OVR_multiview2/extension.xml

I just did a small change on the example shader replacing both view matrices with an array of matrices as I have found most implementations I have seen so far on js engines tend to implement it as in the original example with custom uniforms for each matrix.
Maybe it's quite obvious but even if currently most of the use case for multiview are WebVR with 2 views, eventually we could increase that number as new devices appears, and we won't need to adapt the code to support new uniforms `u_viewMatrix2`, `u_viewMatrix3`,... just increase the number of views, simplifying the engine a bit.
```glsl
uniform mat4 u_viewMatrix0;
uniform mat4 u_viewMatrix1;
void main() {
if (gl_ViewID_OVR == 0u) {
gl_Position = u_viewMatrix0 * inPos;
} else {
gl_Position = u_viewMatrix1 * inPos;
}
}
```
```glsl …
```

Modify OVR_multiview2 example to use array of matrices

---

sdk/tests/webgl-conformance-tests.html

- also tweaked the position of the test list to reduce
the gap between it and the header

WebKit-specific rule to stop the slide-over button from looking horrible on iOS

---

sdk/tests/conformance/programs/00_test_list.txt
sdk/tests/conformance/programs/program-handling.html
sdk/tests/conformance/programs/program-test.html

Mostly a port from @greggman 's program handling test https://github.com/KhronosGroup/WebGL/issues/2842
There is a section doing similar tests in `program-test.html`. But since it only detects gl errors without actually drawing something, it couldn't really expose problems. I removed that one test case from there. The new `program-handling.html` tests covers better for the topic of program handling for various linking situation.

Port greggman new program handling test

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/matrix-row-major.html
sdk/tests/js/glsl-conformance-test.js

Requires adding some simple support for uniform blocks.
Currently breaks on some Apple platforms.
Fixes issue #2882.

Add conformance test for row_major matrices

---

extensions/WEBGL_draw_buffers/extension.xml
sdk/tests/conformance/extensions/webgl-draw-buffers.html
sdk/tests/conformance2/rendering/draw-buffers.html
specs/latest/2.0/index.html

Add tests and update spec and extensions description texts.
Discussion: https://github.com/KhronosGroup/WebGL/issues/2880

Validating draw buffers now also considers color mask settings

---

conformance-suites/1.0.3/conformance/glsl/misc/shaders-with-invariance.html
conformance-suites/2.0.0/conformance/glsl/misc/shaders-with-invariance.html
sdk/tests/conformance/glsl/misc/shaders-with-invariance.html

The ESSL 1.0 specification states that the global invariance pragma
applies only to output variables. During the most recent work on this
test in #1924, the assumption was that this pragma applied essentially
to all variables, because ESSL 1.0 also mandates that the invariant
qualifier must match between vertex shader outputs and fragment shader
inputs.
ANGLE's shader translator is relaxing the validation in this area in
order to both support a Vulkan backend and pass the ES 2.0
drawElements test suite. The best understanding of the intent of the
ES 2.0 and ESSL 1.0 specifications has been applied in coming to this
decision.
The associated WebGL conformance test in shaders-with-invariance.html,
which asserts a link failure with a variant output variable in the
vertex shader and an …

Change invariance rule for #pragma STDGL invariant(all).

---

sdk/tests/py/lint/lint.py
sdk/tests/py/lint/lint.whitelist

Two files in the repository deliberately contain non-UTF-8 Unicode
characters. Explicitly whitelist them so if other files later accidentally
add such characters, they're discovered.
Related to #2885.

Whitelist files containing Unicode characters.

---

sdk/tests/conformance/reading/read-pixels-test.html
sdk/tests/conformance/textures/misc/texture-formats-test.html
specs/latest/1.0/index.html
specs/latest/2.0/index.html

Where Uint8Array is allowed per spec, also allow Uint8ClampedArray.
This makes interaction with ImageData easier.
Firefox already allows Uint8ClampedArray in texImage2D where
Uint8Array is allowed, so this is a difference in behavior between
implementations that's now being clarified.
Reported in http://crbug.com/961658 .

Allow Uint8ClampedArray in readPixels and tex{Sub}Image.

---

extensions/KHR_parallel_shader_compile/extension.xml

This extension significantly improves startup time and smoothness of
WebGL applications loading many shader programs.

Promote KHR_parallel_shader_compile to community approved.

---

extensions/rejected/WEBGL_security_sensitive_resources/extension.xml

Olli Etuaho, formerly of NVIDIA, demonstrated that it's possible to
infer textures' contents despite defenses such as these. No current
champion of this spec. Per discussion in WebGL WG, reject it.

Reject WEBGL_security_sensitive_resources.

---

sdk/tests/conformance/renderbuffers/depth-renderbuffer-initialization.html
sdk/tests/conformance2/renderbuffers/multisampled-depth-renderbuffer-initialization.html

This patch fixes a typo in the depth renderbuffer initialization
tests that the depth renderbuffer should be initialized to 1.0
according to WebGL SPEC (WebGL 1.0, Chapter 4.1) instead of 0.

Fix typo in depth renderbuffer initialization tests

---

sdk/tests/conformance/glsl/misc/re-compile-re-link.html

Missing parameter in gl.getShaderInfoLog

Fix missing parameter to shader log display in re-compile-relink glsl/misc tests

---

sdk/tests/conformance/extensions/ext-float-blend.html
sdk/tests/conformance2/extensions/ext-float-blend.html
sdk/tests/js/tests/ext-float-blend.js

Some test results:
* :heavy_check_mark: Linux Chrome 75 (OpenGL Backend)
* :heavy_check_mark: Linux Firefox Nightly
* :heavy_check_mark: Win Chromium local build with ext-float-blend enabled for D3D9 (Angle, validating cmd decoder, D3D9 Backend)
* :heavy_check_mark: Win Chrome 75 (Angle, validating cmd decoder, D3D11, OpenGL Backend)
Failing ones: RGBA float32 fbo color attachment is said to be unsupported, but it should be supported if WEBGL_color_buffer_float is available https://www.khronos.org/registry/webgl/extensions/WEBGL_color_buffer_float/ (RGB float32 is optional)
* :heavy_multiplication_x: Win Chrome 75 (Angle, passthrough cmd decoder, D3D11, OpenGL Backend)
* :heavy_multiplication_x: Win Firefox Nightly

Ext float blend test for WebGL 1

---

sdk/tests/conformance/extensions/oes-standard-derivatives.html

Regression test for https://crbug.com/971660 .
See comment for details.

Add a test for #extension after non-preprocessor code in ESSL 1.00

---

sdk/tests/conformance/offscreencanvas/context-attribute-preserve-drawing-buffer.html

Display the canvases that are being tested in the web page, in case
their eventual display is affecting the browser's composition paths.
Increase the timeout for the preserveDrawingBuffer:false test to 2000
ms in order to see whether that eliminates flakiness seen on automated
testing machines.
Related to http://crbug.com/979843 .

Increase logging in OffscreenCanvas preserveDrawingBuffer test.

---

sdk/tests/conformance/glsl/misc/shaders-with-invariance.html

Previous change "Change invariance rule for #pragma STDGL invariant(all)."
incorrectly updated fragmentShaderGlobalInvariant test to expect to pass.
That test uses "#pragma STDGL invariant(all)" in the FS which only affects
outputs and therefore does NOT cause the input varying to match the VS output
invariant varying, thus causing a link fail.
Therefore restoring this test to correctly expect the link to fail. The
change to expect it to pass was made during an intermediate ANGLE fix that
can be referenced for more info:
https://chromium-review.googlesource.com/c/angle/angle/+/1558678
New bug relevant to this current fix is:
https://bugs.chromium.org/p/chromium/issues/detail?id=980675

Fix invariance rule for FS #pragma STDGL invariant(all)

---

conformance-suites/1.0.1/conformance/resources/webgl-test-utils.js
conformance-suites/1.0.2/conformance/resources/webgl-test-utils.js
conformance-suites/1.0.3/conformance/resources/webgl-test-utils.js
conformance-suites/2.0.0/js/webgl-test-utils.js
sdk/tests/js/webgl-test-utils.js

Browsers often refuse to auto-play videos without user interaction,
unless the videos are muted.

Mute videos before playing.

---

sdk/tests/js/webgl-test-utils.js

This is an attempt to see whether this eliminates flakiness in
video-related WebGL tests, per suggestion from Chrome's media team in
https://crbug.com/979444#c20 .

Set preload='auto' flag on videos uploaded to WebGL textures.

---

sdk/tests/conformance/glsl/misc/large-loop-compile.html

This test assumes the HLSL compiler will finish within 5000 ms for a
long loop which it apparently has to unroll. On some slower Windows
bots this timeout is occasionally being hit, so increase the timeout
50%, to 7500 ms.
Related to http://crbug.com/691951.

Increase timeout on long-loop-compile.html.

---

other/test-runner/config.json

The name "blocklist" is more inclusive than "blacklist" while
still conveying the intention clearly.
See https://developers.google.com/style/word-list#blacklist
In order to rename Chrome's --ignore-gpu-blacklist command line
parameter we must first add the new --ignore-gpu-blocklist
everywhere it is used. Once this is done, Chrome can rename its
command line parameter and then we can remove the old references.
This PR adds the --ignore-gpu-blocklist command line parameter.

Add blocklist Chrome command line parameter

---

sdk/tests/conformance2/extensions/00_test_list.txt
sdk/tests/conformance2/extensions/ext-texture-filter-anisotropic.html
sdk/tests/js/tests/ext-texture-filter-anisotropic.js

Refactors and reuses the previous WebGL 1.0 test, and adds tests for
setting and getting this parameter against sampler objects, which is
supposed to work per Issue 1 in the OpenGL extension specification:
https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_filter_anisotropic.txt
Both Chrome's and Firefox's WebGL 2.0 implementations currently fail
the positive sampler-related portions of this test.
Addresses #2006.

Add WebGL 2.0 EXT_texture_filter_anisotropic test.

---

sdk/tests/conformance2/sync/sync-webgl-specific.html

There was a wrong check on the `gl.getSyncParameter` return value, which results that the test always pass.

Fix typo in WebGL2 sync test

---

extensions/WEBGL_draw_instanced_base_vertex_base_instance/extension.xml
extensions/WEBGL_multi_draw_instanced_base_vertex_base_instance/extension.xml

Promote WEBGL_draw_instanced_base_vertex_base_instance and WEBGL_multi_draw_instanced_base_vertex_base_instance to draft.
Together change the parameter order of multiDraw* version calls to fit that of WEBGL_multi_draw_instanced.

Promote BaseVertex BaseInstance related extensions to draft

---

sdk/tests/conformance/glsl/misc/non-ascii-comments.vert.html

As noted in
https://bugs.chromium.org/p/chromium/issues/detail?id=940865, comments
were not stripped by WebGL in some cases. Added a test to prevent this
from happening again.

Add test cases to non-ascii-comments test

---

sdk/tests/conformance2/vertex_arrays/vertex-array-object-and-disabled-attributes.html

conformance2/vertex_arrays/
vertex-array-object-and-disabled-attributes.html was assuming that the
"position" attribute location would match between two separately
compiled and linked programs. This must be enforced via
bindAttribLocation.
Associated with ANGLE test bug: http://crbug.com/angleproject/4049
Fixes #2949 .

Fix vertex-array-object-and-disabled-attributes test.

---

extensions/proposals/WEBGL_video_texture/extension.xml

Instead of using texture2D with a textureVideoWEBGL argument.
Related to bug and pull request up for discussion:
http://crbug.com/776222
https://chromium-review.googlesource.com/1866274

Update WEBGL_video_texture extension to define textureVideoWEBGL.

---

sdk/tests/conformance/extensions/00_test_list.txt

Tests added in `00_test_list.txt` should be `oes-fbo-render-mipmap.html`.
Thanks @kenrussell for pointing this out.

Fix incorrect test html name in test list

---

extensions/WEBGL_draw_instanced_base_vertex_base_instance/extension.xml
extensions/WEBGL_multi_draw_instanced_base_vertex_base_instance/extension.xml

Didn't assign an extension number when promoted to draft.
Thanks for Ken for pointing this out.

Fix BaseVertexBaseInstance extensions number

---

extensions/proposals/WEBGL_video_texture/extension.xml

The previously chosen constants collided with other OpenGL constants.

Allocate enums for WEBGL_video_texture extension out of WebGL's block.

---

extensions/OES_fbo_render_mipmap/extension.xml

Trivial fix for the sample code in `OES_fbo_render_mimap/extension.xml`
As discussed here: https://github.com/KhronosGroup/WebGL/pull/2952#discussion_r339275137
Status of each framebuffer is only guaranteed to be framebuffer-complete after the texture it attaches to is in a good state.
Also for a 128x128 ( = 2^7) texture it should have 8 mipmap levels to be mipmap complete. (1 (level=7), 2, 4, 8, 16, 32, 64, 128(level = 0) )

Fix sample code in OES_fbo_render_mimap/extension.xml

---

conformance-suites/1.0.0/conformance/context-attributes-alpha-depth-stencil-antialias.html
conformance-suites/1.0.1/conformance/context/context-attributes-alpha-depth-stencil-antialias.html
conformance-suites/1.0.2/conformance/context/context-attributes-alpha-depth-stencil-antialias.html
conformance-suites/1.0.3/conformance/context/context-attributes-alpha-depth-stencil-antialias.html
conformance-suites/2.0.0/conformance/context/context-attributes-alpha-depth-stencil-antialias.html
sdk/tests/conformance/context/context-attributes-alpha-depth-stencil-antialias.html

Previously modified canvas size to 3\*3 for CMAA
algorithm, but CMAA had been removed from chromium,
revert canvas size to 2\*2.

Revert antialias cases

---

sdk/tests/conformance/extensions/webgl-compressed-texture-astc.html
sdk/tests/js/webgl-test-utils.js

When sampling invalid LDR ASTC textures which are not sRGB, hardware is allowed to return either the normal error color (magenta) or all NaNs. This modifies the ASTC test to accept an all NaN result in this case.
This fixes the test on some Qualcomm Android devices including Pixel phones.

Accept all NaNs when sampling invalid LDR ASTC non-sRGB

---

sdk/tests/extra/workload-simulator.html

This adds a bunch of options to the workload simulator. We can now test OffscreenCanvas (main thread only) and specify arbitrary context creation parameters including powerPreference.
Try it here: https://jdarpinian.github.io/WebGL/sdk/tests/extra/workload-simulator.html

Workload simulator: OffscreenCanvas and context creation params

---

sdk/tests/extra/workload-simulator.html

Added a button to create/remove a high power context on demand to test GPU switching.
Also: Fix sliders in Safari. Allow disabling WebGL 2. Organize UI into collapsible sections. Display renderer info.
Demo: https://jdarpinian.github.io/WebGL/sdk/tests/extra/workload-simulator.html

Workload simulator: Test GPU switching

---

sdk/tests/conformance2/extensions/00_test_list.txt
sdk/tests/conformance2/extensions/ext-texture-norm16.html
sdk/tests/js/webgl-test-utils.js

Add test for EXT_texture_norm16 extension.
Refactor checkCanvasRect a bit to expose `opt_readBackFormat` to assign formats other than `gl.RGBA`

Test for EXT_texture_norm16 extension

---

sdk/tests/conformance2/textures/misc/tex-3d-size-limit.html

Large image requests can trigger an out-of-memory error (#1925). In #2579, we try to probe the max non-OOM level for 2D and cube map textures. This is applied to 3D textures now.

Probe for max non-OOM 3D texture size

---

sdk/tests/resources/js-test-style.css

Some, especially TV-set, browsers render black or transparent by default.
Setting background explicitly to white will help many people.
An example of a non-white background requirement -- Section 5.3.3.1 of HbbTV 2.0.1 spec:
https://www.hbbtv.org/wp-content/uploads/2015/07/HbbTV-SPEC20-00023-002-HbbTV_2.0.1_specification_for_publication_clean.pdf

Explicitly set the background color to white

---

conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-2d-with-video.js
conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-3d-with-video.js
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-video.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-video.js

Bump tolerance limit for tex-image...video.js 5=>6.

---

sdk/tests/conformance2/extensions/ext-texture-norm16.html

Part of the fix after figuring out the root cause for the failure hasn't landed.
https://github.com/KhronosGroup/WebGL/pull/2972/files

Fix alpha channel set to 1 in ext-texture-norm16 test

---

sdk/tests/js/tests/gl-object-get-calls.js
sdk/tests/js/webgl-test-utils.js

* Caches the value->enum unmappings, instead of linearly searching.
* Combine same-valued enum names: 0 -> NONE/ZERO/POINTS/NO_ERROR.
* glErrorShouldBeImpl still maps 0 -> NO_ERROR though.

glEnumToString allow glOrExt arg.

---

sdk/tests/conformance2/samplers/samplers.html

Now glEnumToString might return multiple enums sharing one values #2980.
Quick fix for a test where https://github.com/KhronosGroup/WebGL/blob/master/sdk/tests/conformance2/samplers/samplers.html#L177
```
eval("gl['POINTS/ZERO/NO_ERROR/NONE']");
```
will return undefined leading to a test failure..
This is a quick fix but might not be optimal.

Fix samplers.html: enumToString might return multiple enums separated by slash

---

sdk/tests/conformance2/extensions/ext-texture-norm16.html
sdk/tests/js/webgl-test-utils.js

By default the fragment shader uses `lowp` for `sampler2D`. It is not enough for RGBA16 UNSIGNED_SHORT normalized value which has 16 bit for each channel. Use an override shader with `precision highp float; uniform highp sampler2D tex;` declared instead.
This should probably be generalized, since this is effectively needed for all tests with >8 bits per channel, including all float/half-float tests.
Previous discussion could be found in #2999

Use high precision float and sampler2D for ext-texture-norm16.html

---

sdk/tests/conformance2/extensions/ext-texture-norm16.html
sdk/tests/js/webgl-test-utils.js

In OpenGL ES Shading language spec 100 section 7.2
```
mediump vec4 gl_FragCoord;
bool gl_FrontFacing;
mediump vec4 gl_FragColor;
mediump vec4 gl_FragData[gl_MaxDrawBuffers];
mediump vec2 gl_PointCoord;
```
These declarations show the output precision would be mediump which is at least 2<sup>-10</sup> for floating point precision and is unchangeable. Thus it is not sufficient for render ability required by EXT_texture_norm16 for 16 bit normalized unsigned short.
This might also affect how we design this extension. If we want it to be exposed to WebGL 1 in the future, we might need a separate version of it lacking the rendering ability. I think we could discuss this part of the topic in WebGL WG meeting.
Previous discussion in #3000

Use ESSL300 Texture Quad shader for ext_texture_norm16

---

sdk/tests/conformance2/extensions/ext-texture-norm16.html

As Jeff points out in #3001 
> EXT_texture_norm16 doesn't guarantee that fragment output below highp isn't truncated. 
...
It's important to test that ESSL100 shaders sample from this correctly, and ideally that RTT works within the restrictions of mediump.
We use 100 shader program to test texture sampling, use both 300 and 100 shader program to test RTT, with a tolerance set for the 100 one.
Once this test is ported to `conformance/` we could check the current gl context version and decide if we still test with 300 shader program.

Retain ESSL100 usage in ext-texture-norm16

---

sdk/tests/conformance/offscreencanvas/00_test_list.txt
sdk/tests/conformance/offscreencanvas/offscreencanvas-timer-query.html
sdk/tests/conformance2/offscreencanvas/00_test_list.txt
sdk/tests/conformance2/offscreencanvas/offscreencanvas-query.html
sdk/tests/conformance2/offscreencanvas/offscreencanvas-sync.html
sdk/tests/conformance2/offscreencanvas/offscreencanvas-timer-query.html

Test the following scenarios with OffscreenCanvas on workers:
- Query objects with WebGL 2.0 contexts
- Sync objects with WebGL 2.0 contexts
- Timer queries with WebGL 1.0 and 2.0 contexts
Regression test for http://crbug.com/1010877 .

Add tests for query, sync and timer queries on workers.

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/matrix-row-major-dynamic-indexing.html

This is failing on OSX Chrome. A bug will also be filed with Chrome.
I'm seeing this issue on a personal project. In my environment, with `layout(row_major)` the test fails, `layout(column_major)` test succeeds.
Edit: ANGLE bug filed at https://bugs.chromium.org/p/angleproject/issues/detail?id=4242

Add conformance test for dynamic indexing of row_major matrix arrays

---

sdk/tests/conformance/context/context-lost.html

Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1608311

Test resizing a lost WebGL context.

---

sdk/tests/conformance/context/00_test_list.txt
sdk/tests/conformance/context/zero-sized-canvas.html
specs/latest/1.0/index.html

0x0 canvas yields 1x1 WebGL context.

Spec zero-sized canvas behavior and test.

---

sdk/tests/conformance2/textures/misc/tex-storage-compressed-formats.html

In Chrome (80-82), sampling from freshly-allocated compressed 2D texture array results in `INVALID_ENUM` error on `drawArrays` call.
https://crbug.com/1051217

Check sampling from allocated compressed texture array

---

sdk/tests/conformance/extensions/ext-texture-compression-bptc.html
sdk/tests/conformance/extensions/ext-texture-compression-rgtc.html
sdk/tests/js/tests/compressed-texture-utils.js

CTS used to miss the validation test for bptc and rgtc (There are some compressedTexSubImage* tests for pvrtc, s3tc and astc). Now latest Firefox and Chromium on Linux Nvidia are tested passing these newly added tests.

Add compressedTexSubImage validation test for bptc and rgtc

---

sdk/tests/conformance/glsl/preprocessor/comments.html

It's nicer to have a one-stop-shop for validating tests for this
behavior.

Duplicate and centralize glsl-comment testcases into this file.

---

conformance-suites/1.0.3/conformance/more/functions/texImage2DHTML.html
conformance-suites/1.0.3/conformance/more/functions/texSubImage2DHTML.html
conformance-suites/2.0.0/conformance/more/functions/texImage2DHTML.html
conformance-suites/2.0.0/conformance/more/functions/texSubImage2DHTML.html
sdk/tests/conformance/more/functions/texImage2DHTML.html
sdk/tests/conformance/more/functions/texSubImage2DHTML.html
sdk/tests/js/webgl-test-utils.js

`HTMLImageElement.complete` no longer changes except on microtask boundaries.
Backported minimal fixes to 1.0.3 and 2.0.0.
More invasive fix to make things nicer moving forward for top-of-tree.

Remove now-broken `while (!img.complete) {}`.

---

extensions/EXT_draw_buffers_indexed/extension.xml

Fixes #2938.
There is also an identical `OES_draw_buffers_indexed` extension. Should we expose it instead?

Add WebGL-specific limitations to EXT_draw_buffers_indexed

---

sdk/tests/conformance2/renderbuffers/multisampled-depth-renderbuffer-initialization.html
specs/latest/2.0/index.html

Firefox allows DEPTH_STENCIL with samples >= 0.
Chrome allows samples==0, but INVALID_ENUM for samples >= 1.

 Make renderbufferStorageMultisample with DEPTH_STENCIL and samples>0 generate INVALID_OPERATION.

---

sdk/tests/conformance/textures/misc/00_test_list.txt
sdk/tests/conformance/textures/misc/compressed-tex-image.html
sdk/tests/conformance2/textures/misc/00_test_list.txt
sdk/tests/conformance2/textures/misc/compressed-tex-image.html
sdk/tests/js/tests/compressed-tex-image.js

Refactor compressed-tex-image into WebGL 1.0 and 2.0 tests.

---

sdk/tests/conformance/misc/uninitialized-test.html

These tests uncover bugs in some WebGL implementations that will be
filed separately.

Upstream some copyTexSubImage2D test cases from WebKit.

---

sdk/tests/conformance/extensions/oes-texture-float-linear.html
sdk/tests/conformance/extensions/oes-texture-half-float-linear.html
sdk/tests/js/tests/oes-texture-float-and-half-float-linear.js

Doing instanceof makes it hard for webgl-1on2 testing, since the rendering context there is webgl1 behavior, but instanceof WebGL2RenderingContext.

Do is-webgl2 checks by duck-typing, not instanceof.

---

sdk/tests/conformance/context/context-attribute-preserve-drawing-buffer.html
sdk/tests/webgl-conformance-tests.html

Previously, at smaller window sizes, the preserveDrawingBuffer:false
test canvas was off the visible region of the page, and thus not cleared
since it was not Painted.
The fix:
* Increase the min-width of the test-runner test iframe.
* Decrease the size of canvases in context-attribute-preserve-drawing-buffer.html.

Fix flakiness of context-attribute-preserve-drawing-buffer.html.

---

sdk/tests/conformance/context/00_test_list.txt

deleted-object-behavior was added to the conformance test but never added to any test_list.txt files.
Add deleted-object-behavior.html to 00_test_list.txt as part this change.

Add deleted-object-behavior.html to 00_test_list.txt

---

sdk/tests/js/tests/tex-image-and-sub-image-2d-with-webgl-canvas.js

Remove explicit use of Promises in the inner loop, and change to use
async/await, to provide better control of the execution order of the
test cases.
Verified in Chrome, Firefox and Safari on macOS. ToT of all browsers
pass the new tests; Firefox has a couple of preexisting failures with
the RGBA10_A2/RGBA/UNSIGNED_INT_2_10_10_10_REV combination.

Test both alpha:true and alpha:false in webgl_canvas tests.

---

conformance-suites/1.0.3/conformance/rendering/polygon-offset.html
conformance-suites/2.0.0/conformance/rendering/polygon-offset.html
sdk/tests/conformance/rendering/polygon-offset.html

Two tests in the polygon-offset.html files were incorrectly
testing glPolygonOffset by comparing to the wrong base value.
The section entitled:
'Polygon offset factor of 0.1 should alter order of slanted polygons'
Was comparing gl.polygonOffset(0, 2) to gl.polygonOffset(0.1, 0)
while the goal was to compare it with a baseline of gl.polygonOffset(0, 0)
The section entitled:
'Polygon offset factor of 0.1 should not alter order of flat polygons'
Was comparing gl.polygonOffset(0.1, 0) to gl.polygonOffset(0.1, 0)
(effectively not performing the test at all)
while the goal was to compare it with a baseline of gl.polygonOffset(0, 0)
Fixed the baseline comparison polygon offsets in both cases to fix the test.

Fix polygon-offset tests

---

conformance-suites/1.0.1/conformance/resources/webgl-test-utils.js
conformance-suites/1.0.2/conformance/resources/webgl-test-utils.js
conformance-suites/1.0.3/conformance/resources/webgl-test-utils.js
conformance-suites/2.0.0/js/webgl-test-utils.js
sdk/tests/js/webgl-test-utils.js

The startPlayingAndWaitForVideo function uses various heuristics to
determine whether or not a video has started playing. These heuristics
mostly rely on currentTime progress, but don't aren't necessarily
reliable when determining wether there is actually new video data to
be consumed.
This commit adds cross browser support for the
video.requestVideoFrameCallback API, which can be used to replace the
heuristics, and potentially deflake tests.

Update test utils to use video.rVFC

---

sdk/tests/conformance2/extensions/oes-draw-buffers-indexed.html

Test newly introduced enums for getIndexedParameterTest from OES_draw_buffers_indexed are invalid before requesting the extension.
The expect result for `gl.COLOR_WRITEMASK` is either `gl.INVALID_OPERATION` or `gl.INVALID_ENUM`. This is to fit the angle implementation behavior.

Update invalid enums test for OES_draw_buffers_indexed

---

sdk/tests/conformance/more/functions/readPixelsBadArgs.html
sdk/tests/conformance/more/functions/texImage2DHTML.html
sdk/tests/conformance/more/functions/texSubImage2DHTML.html
sdk/tests/conformance/textures/misc/origin-clean-conformance-offscreencanvas.html
sdk/tests/conformance/textures/misc/origin-clean-conformance.html
sdk/tests/js/webgl-test-utils.js

Change WebGLTestUtils.awaitOrTimeout to offer a default timeout of
5000 ms, and all tests currently using it to use the default.
Tested both manually and in Chromium's automated WebGL test harness.
Unclear whether this will fix the problems seen on Chromium's bots,
but need to try.
Follow-on to #3052. Addresses #3076.

Increase timeout for cross-origin image loading tests.

---

sdk/tests/conformance2/extensions/oes-draw-buffers-indexed.html

According to the [spec](https://www.khronos.org/registry/OpenGL/extensions/OES/OES_draw_buffers_indexed.txt). The non-indexed calls (`gl.enable`, `gl.blendFunc`, etc.) modifies state of all draw buffers. And the non-indexed queries (`gl.isEnabled`, `gl.getParameter`) shall return the state of draw buffer 0 if draw buffers are set separately. Thus updating the oes-draw-buffers-indexed.html.

Update oes-draw-buffers-indexed.html with non-indexed call test

---

sdk/tests/conformance/canvas/to-data-url-test.html

This adds a test to verify the image returned by toDataURL with a premultipliedAlpha=false canvas is the correct orientation.
This was suggested by:
https://bugs.webkit.org/show_bug.cgi?id=156129
I ran the test on Chrome/FireFox and got:
testing 16 by 16 attributes: {"premultipliedAlpha":false}
PASS should be 0,255,0,255
PASS should be 255,0,0,255
PASS should be 0,0,255,255
And got this on Safari:
testing 16 by 16 attributes: {"premultipliedAlpha":false}
FAIL should be 0,255,0,255
at (0, 0) expected: 0,255,0,255 was 255,0,0,255
FAIL should be 255,0,0,255
at (0, 8) expected: 255,0,0,255 was 0,255,0,255
PASS should be 0,0,255,255

Add tests to verify toDataURL images are the correct orientation for premultiplyAlpha=false

---

sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-video.js
sdk/tests/js/webgl-test-utils.js

Disable the use of this new API for the image_bitmap_from_video
conformance tests to work around crbug.com/1090960. It will be
re-enabled once the underlying bug is fixed.
Follow-on to #3065.

Temporarily disable requestVideoFrameCallback for some tests.

---

sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-video.js
sdk/tests/js/webgl-test-utils.js

This reverts commit 616a46a0c0fbd9156e481193954ed5188a346d93 / #3092
now that http://crbug.com/1090960 has been fixed.

Re-enable requestVideoFrameCallback for image_bitmap_from_video tests.

---

sdk/tests/js/webgl-test-utils.js

The earliest version of this code, which was seemingly stable, made the
determination of whether to use a local or remote URL cor cross-origin
images up front.  Network timeouts from machines that deliberately
aren't connected to the open Internet can't be relied upon as a fallback
mechanism. Change the code back to examine the test's URL and choose
whether to load local or remote images based on that. Also attempt to
make runningOnLocalhost more robust to IPv6 loopback addresses.
Follow-on to #3052 and #3077. See http://crbug.com/1082525 for more
background.
Should fix #3076 conclusively.
Note that #3097 was proposed as an alternative solution for this problem
and may still be considered in the future if this change destabilizes some
browsers' CI systems.

Choose which cross-origin URL to use up front.

---

sdk/tests/conformance2/renderbuffers/framebuffer-object-attachment.html

Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1636517

framebufferTexture2D(F, C_A0, T_2D, null, 1000) is not an error.

---

sdk/tests/conformance2/renderbuffers/readbuffer.html

Looks like the test was written to the man page, but the man page disagrees with the spec and with dEQP. The spec should win.

readBuffer of out of range color attachment should cause INVALID_OPERATION

---

sdk/tests/conformance/extensions/webgl-multi-draw.html
sdk/tests/conformance2/extensions/webgl-multi-draw-instanced-base-vertex-base-instance.html

Now multi_draw and base_vertex_base_instance test with buffers setup with `[ gl.STATIC_DRAW, gl.DYNAMIC_DRAW ]`
Corresponds to ANGLE bugs:
http://crbug.com/angleproject/4754
http://crbug.com/1078330

Add DYNAMIC_DRAW bufferUsage to multi draw and base vertex base instance test

---

extensions/EXT_texture_compression_bptc/extension.xml
extensions/EXT_texture_compression_rgtc/extension.xml
sdk/tests/conformance/extensions/ext-texture-compression-bptc.html
sdk/tests/conformance/extensions/ext-texture-compression-rgtc.html

Chromium (ANGLE?) responds with `INVALID_VALUE` instead of `INVALID_OPERATION`.

Clarify texImage2D for RGTC and BPTC

---

extensions/WEBGL_multi_draw/extension.xml
extensions/WEBGL_multi_draw_instanced_base_vertex_base_instance/extension.xml

Update as discussed at WebGL Virtual F2F. Original agreement at https://gitlab.khronos.org/webgl/member-tools/-/wikis/WebGL-F2F-Meeting-Sep-2019#extension-promotion-rejection-burndown-extension-promotion-rejection-burndown

Update MultiDraw and MultiDrawBaseVertexBaseInstance extension

---

sdk/tests/conformance2/glsl3/switch-case.html

Added switch statement tests for default and literal values

---

extensions/EXT_clip_cull_distance/extension.xml

This will allow browsers on mobile to support HW clip planes for those GPU's that expose GL_APPLE_clip_distance only (for example many Imagination Technologies GPU's). In addition, on desktop, it enlarges the ability to implement the extension on all GL versions that are at 4.4 or before. This, for example, includes all Apple desktop hardware.

EXT_clip_cull_distance: allow for an implementation to return 0 for the number of supported cull planes

---

sdk/tests/conformance/extensions/ext-texture-compression-bptc.html
sdk/tests/conformance/extensions/ext-texture-compression-rgtc.html
sdk/tests/js/tests/compressed-texture-utils.js

Updating test according to recent change: https://github.com/KhronosGroup/WebGL/pull/3111
addressing chrome issue: http://crbug.com/1100834

Update bptc and rgtc tests with level and dimension test

---

sdk/tests/conformance/misc/shader-precision-format.html

to weed out implementions that incorrectly report precision
#3059 
I'm not entirely sure this is a valid test but it seems to work. My reading of the spec is that there is all kinds of leeway here about when an were the precision stuff takes effect. 
The 2.0 spec says overflowing an int is undefined so anything could happen. The code is uploading an int that should overflow in Safari iOS and it is failing as it should but I tried a bunch of other things before I got to this example that succeded where I expected it to fail and failed where I expected it to succeed.
All that is a way of saying I'm not confident in this code but it is running and does what I expect on the devices I have to test with.

add rendering test to shader precisions format test

---

sdk/tests/conformance2/reading/read-pixels-pack-parameters.html

All of the existing tests for this pixel pack parameter with a value
greater than 0 were assumed to fail validation. Adding a positive test
reveals an apparent OpenGL driver bug on macOS.
Test case for http://crbug.com/angleproject/4849 .
This new test passes in Chromium and Firefox on macOS, and in WebKit
on top of ANGLE with the necessary driver bug workaround.

Add WebGL 2.0 test of pixelStorei with PACK_SKIP_PIXELS > 0.

---

sdk/tests/js/tests/compressed-tex-image.js

According to the spec:
https://www.khronos.org/registry/webgl/extensions/WEBGL_compressed_texture_etc1/
This WebGL extension does not allow using compressedTexSubImage2D:
"Remove ability to use the format with compressedTexSubImage2D,
as per the GLES extension spec."
The compressed-tex-image test was modified to reflect the spec.

Fix WEBGL_compressed_texture_etc1 section of compressed-tex-image test

---

sdk/tests/webgl-conformance-tests.html

I think it's time to change the default.

Default to WebGL 2 conformance tests instead of WebGL 1.

---

conformance-suites/2.0.0/conformance2/misc/object-deletion-behaviour-2.html

The 2.0.0 snapshot of this test was incorrectly creating a WebGL 1.0
context.

Fix object-deletion-behaviour-2 to create WebGL 2.0 context.

---

conformance-suites/2.0.0/conformance2/renderbuffers/readbuffer.html

Since the required error was changed from INVALID_ENUM to
INVALID_OPERATION in #3099, the 2.0.0 snapshot must allow both values
in order to admit both old and new implementations.

Loosen readBuffer error condition in readbuffer.html.

---

conformance-suites/2.0.0/conformance2/textures/misc/integer-cubemap-specification-order-bug.html

Incorporate fix from #2327, which never made it into the 2.0.0
snapshot. This test was substantially rewritten on top-of-tree in #2806.

Fix integer-cubemap-specification-order-bug.html in 2.0.0 snapshot.

---

sdk/tests/conformance/glsl/bugs/00_test_list.txt
sdk/tests/conformance/glsl/bugs/angle-d3d11-compiler-error.html
sdk/tests/conformance/glsl/bugs/character-set.html

Addressing issue reported at: https://bugs.chromium.org/p/chromium/issues/detail?id=1108588
The main issue is that WebGL should not validate shader string before preprocessing for cases like:
```
#if defined(GL_GOOGLE_cpp_style_line_directive)
#line 45 "foo.txt"
#endif
```
where " is not a valid character but should be cleared by preprocessing step thus not failing the validation and compilation.
(Check https://www.khronos.org/registry/OpenGL/specs/es/3.0/GLSL_ES_Specification_3.00.pdf Section 3.2)
Tested on Win 10 and fails in Chrome and Firefox. Passed for modified local Chromium build.

Shader source character set and preprocess validation test

---

conformance-suites/2.0.0/conformance2/textures/misc/tex-image-with-bad-args-from-dom-elements.html
conformance-suites/2.0.0/conformance2/textures/misc/tex-image-with-different-data-source.html

These tests were invalidated in #2386. In order to allow both old and
new implementations to pass these tests, and to minimize complexity in
the 2.0.0 conformance snapshot, simply remove the now-invalid tests.

Remove invalid RGB10_A2 tests from 2.0.0 conformance snapshot.

---

conformance-suites/2.0.0/js/glsl-conformance-test.js

Backport fixes from #2330 and #2612 to the 2.0.0 snapshot.

Fix 2.0.0 snapshot of glsl-conformance-test runner.

---

sdk/tests/conformance/glsl/bugs/character-set.html

Following up https://github.com/KhronosGroup/WebGL/pull/3124
We now expect `gl.INVALID_VALUE` for `gl.shaderSource` instead of use GLSLConformanceTester for the overall test.

Expect `gl.INVALID_VALUE` for `gl.shaderSource` for invalid shader in character-set.html

---

conformance-suites/2.0.0/conformance2/rendering/clear-srgb-color-buffer.html
sdk/tests/conformance2/rendering/clear-srgb-color-buffer.html

Found necessary in https://bugs.webkit.org/show_bug.cgi?id=214893 .

Increase tolerance to 3 in clear-srgb-color-buffer.html .

---

extensions/WEBGL_multi_draw/extension.xml
extensions/WEBGL_multi_draw_instanced_base_vertex_base_instance/extension.xml

Add "new functions" section to WEBGL_multi_draw.
Add needed parentheses to union types in the Web IDL in
WEBGL_multi_draw_instanced_base_vertex_base_instance.

Fix function signatures in multi-draw extensions.

---

extensions/WEBGL_multi_draw/extension.xml

I'm working on adding WEBGL_multi_draw to emscripten at the same time.
What do you think about promoting?

Promote WEBGL_multi_draw to community approved

---

sdk/tests/js/tests/tex-image-and-sub-image-with-image-bitmap-utils.js

When ImageBitmapOptions is not supported by the browser, the implicit
behavior of the premultiplyAlpha option is the default. Per HTML
specification:
https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#cropped-to-the-source-rectangle-with-formatting
this is implementation-specific (either premultiplied or not), so when
the input ImageData has alpha != 1.0, there isn't a single correct
answer. Skip these tests.
This was discovered while implementing ImageBitmap from ImageData
support in WebKit in https://bugs.webkit.org/show_bug.cgi?id=183438 ,
though WebKit supports ImageBitmapOptions. Firefox currently doesn't
support ImageBitmapOptions and happens to have been passing these
tests, but WebKit wouldn't have.

Skip some ImageBitmap from ImageData tests w/o ImageBitmapOptions.

---

sdk/tests/conformance/attribs/gl-vertexattribpointer-offsets.html
sdk/tests/conformance/attribs/gl-vertexattribpointer.html

INT, UNSIGNED_INT, HALF_FLOAT, INT_2_10_10_10_REV, and UNSIGNED_INT_2_10_10_10_REV.
Also test that FIXED is not supported in WebGL 2, as the restriction from WebGL 1 was not lifted. Firefox seems to currently support FIXED in WebGL 2.

Test WebGL 2's new vertex attribute types

---

extensions/EXT_texture_norm16/extension.xml
sdk/tests/conformance2/extensions/ext-texture-norm16.html

Revise conformance2/extensions/ext-texture-norm16.html to mandate that
16-bit signed normalized textures are not color renderable. That
functionality is covered under EXT_render_snorm, not currently exposed
to WebGL.
Partially addresses #3114.

Specialize EXT_texture_norm16 to WebGL 2.0.

---

conformance-suites/2.0.0/js/js-test-pre.js
sdk/tests/js/js-test-pre.js

This allows the expando-loss.html and expando-loss-2.html tests to be
run correctly in the MiniBrowser with the following two environment
variables set:
export JSC_useDollarVM=1
export __XPC_JSC_useDollarVM=1
Thanks to Yusuke Suzuki from Apple for this tip.

Support WebKit's MiniBrowser in webglHarnessCollectGarbage().

---

extensions/EXT_texture_norm16/extension.xml

Per discussion at WebGL WG on Aug 13 2020.
We still need to expand conformance test to test uploading DOM elements / ImageBitmaps / etc.

Promote EXT_texture_norm16 to community approved

---

sdk/tests/conformance/canvas/render-after-resize-test.html

Tests for a WebKit bug that lost the context if there was an existing GL error in the context during a resize.

Add test for GL error during resize

---

extensions/EXT_color_buffer_half_float/extension.xml
extensions/extension.xsl

Allows floating-point rendering in WebGL 2.0 on devices that only have
16-bit-per-channel floating point render targets (iOS, specifically),
so which can not support EXT_color_buffer_float.
Closes #3093.

Support EXT_color_buffer_half_float in WebGL 2.0 contexts.

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/framebuffer-mismatched-attachment-targets.html
sdk/tests/js/webgl-test-utils.js

Add test for fb with mismatched attachment rb/tex-targets.

---

conformance-suites/2.0.0/conformance/extensions/00_test_list.txt
conformance-suites/2.0.0/conformance/extensions/ext-color-buffer-half-float.html
conformance-suites/2.0.0/conformance2/extensions/00_test_list.txt
conformance-suites/2.0.0/conformance2/extensions/ext-color-buffer-half-float.html
conformance-suites/2.0.0/js/tests/ext-color-buffer-half-float.js
sdk/tests/conformance/extensions/00_test_list.txt
sdk/tests/conformance/extensions/ext-color-buffer-half-float.html
sdk/tests/conformance2/extensions/00_test_list.txt
sdk/tests/conformance2/extensions/ext-color-buffer-half-float.html
sdk/tests/js/tests/ext-color-buffer-half-float.js

There wasn't an extension test for EXT_color_buffer_half_float. This tests the new change in #3146. I added the test to the 2.0.0 suite as well; old browsers will pass because they don't support it.

Test EXT_color_buffer_half_float

---

sdk/tests/conformance/extensions/00_test_list.txt
sdk/tests/conformance/extensions/s3tc-and-rgtc.html

The existing S3TC tests are very thorough. S3TC corresponds to the BC1, BC2, and BC3 formats in DirectX. The RGTC extension adds BC4 and BC5, which are 1 and 2 channel variants of BC3. Rather than build a new test, I just added BC4 and BC5 support to the existing S3TC test.
RGTC was not fully tested before, and unsurprisingly there are bugs in both Chrome and Firefox.

Add RGTC drawing tests to existing S3TC test.

---

serve_localhost.py

It was only binding to [::1], sometimes causing pages to fail to load.
This was probably due to changes in http.server.test, which we probably
shouldn't have been abusing for this.

Fix serve_localhost.py to bind to localhost again.

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/rasterizer-discard-and-implicit-clear.html

Regression test for http://crbug.com/1149176 .

Verify that WebGL's implicit clears obey the rasterizer discard state.

---

extensions/KHR_parallel_shader_compile/extension.xml
sdk/tests/conformance/extensions/00_test_list.txt
sdk/tests/conformance/extensions/khr-parallel-shader-compile.html

This was proposed on the public WebGL mailing list, where it was pointed out that KHR_robustness seems to imply that this should be the behavior of all queries. https://www.khronos.org/webgl/public-mailing-list/public_webgl/1904/msg00004.php. The OpenGL working group agrees: https://github.com/KhronosGroup/OpenGL-Registry/issues/263

KHR_parallel_shader_compile: lost context behavior spec & test

---

extensions/EXT_texture_norm16/extension.xml

Update the spec as discovered during implementing the feature in Chrome:
* Add behavior descriptions for uploading various types of image elements with texImage2d
- Uploading image elements with signed normalized integer type is not allowed (according to https://www.khronos.org/registry/webgl/specs/latest/2.0/#3.7.6
`[throws] void texImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, TexImageSource source) // May throw DOMException (OpenGL ES 3.0.4 §3.8.4, man page)`)
- ~~Uploading image elements with 8-bit content with `UNSIGNED_SHORT` type should raise a `DOMException`. And the behavior is undefined.~~
* Add a getSupportedInputs function to make support for image elements types other than arrayBufferView …

Update EXT_texture_norm16 extension spec with support constrained to ArrayBufferView only

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/precision-side-effects-bug.html

When this test is run on Adreno (no repros on other vendors so far):
- the result of the expression `0 | (int(e0 == e0) * 0x8000)` somehow returns `-32768` instead of `32768` despite the variable using `highp` precision;
- splitting the expression along `|` fixes the issue (could also be observed with other operators).

Add precision-side-effects-bug test

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/uint-int-shift-bug.html

Fixes #2989.
Casting the value twice (`uint(uint(int))`) produces correct result. Vector types are not affected.

Add uint-int-shift-bug test

---

extensions/proposals/EXT_texture_norm16_dom_source/extension.xml

Draft a proposal for EXT_texture_norm16_dom_source based on discussions at WebGL WG 2020-12-03.
There are a lot of details that needs refining such as image source format other than PNG with 8<c<16 bits per channel, potential query function for various image source format, channel mapping, 8bit img src requantization etc.

Proposal for EXT_texture_norm16_dom_source

---

extensions/proposals/WEBGL_webcodecs_video_frame/extension.xml
extensions/proposals/WEBGL_webcodecs_video_frame/webgl_webcodecs_video_frame.js

This lifts the restriction of importing harware video frames only.

WEBGL_webcodecs_video_frame: Allow software video frame support

---

extensions/EXT_disjoint_timer_query_webgl2/extension.xml

Back in the old days [there was no GLuint64](https://github.com/KhronosGroup/WebGL/pull/2076#discussion_r81674534), but [now there is](https://www.khronos.org/registry/webgl/specs/latest/2.0/#3.1).
The current definition causes IDL parser warning because there are two definitions, one here and another in [EXT_disjoint_timer_query](https://www.khronos.org/registry/webgl/extensions/EXT_disjoint_timer_query/).

Replace GLuint64EXT with GLuint64

---

sdk/tests/conformance/extensions/khr-parallel-shader-compile.html

Construct a shader that takes a long time to compile and actually test that COMPLETION_STATUS_KHR 
transitions from false to true without blocking. Also add a button for manual verification that animations aren't blocked.

Extend KHR_parallel_shader_compile test

---

other/get.webgl.org/troubleshooting/DoNotCopyOrLinkThisFileElseYouWillNotGetAutoUpdatedHelpForYourUsers.js

As per comments on https://github.com/KhronosGroup/WebGL/pull/3203
- Change webkit to Safari Technology Preview
- Add Chrome.com links for iOS URLs

Update macOS and iOS support links

---

other/get.webgl.org/troubleshooting/DoNotCopyOrLinkThisFileElseYouWillNotGetAutoUpdatedHelpForYourUsers.js

The author of #3204 forgot to add `,` and the script fails to execute. This patch fixes that problem.

Fix a typo in troubleshooting script

---

conformance-suites/1.0.3/conformance/misc/invalid-passed-params.html
conformance-suites/2.0.0/conformance/misc/invalid-passed-params.html
sdk/tests/conformance/misc/invalid-passed-params.html

After #3206 , the top-of-tree test must expect that shaderSource no
longer generates INVALID_VALUE. This portion of the test is removed in
the 1.0.3 and 2.0.0 snapshots to keep them passing on both old and new
browsers.

Revise invalid-passed-params test.

---

sdk/tests/conformance/glsl/bugs/character-set.html

Follow-on to #3206.
Regression test for http://crbug.com/940865 .

Add test of comment with illegal characters after #define.

---

sdk/tests/conformance/glsl/bugs/00_test_list.txt
sdk/tests/conformance/glsl/bugs/vector-matrix-constructor-scalarization.html

Test case adapted from Shadertoy by Fabrice Neyret.
Also added a test of a shader whose compilation was previously broken
by this workaround.
Regression test for http://crbug.com/1165751 .

Expose bug in SH_SCALARIZE_VEC_AND_MAT_CONSTRUCTOR_ARGS workaround.

---

sdk/tests/conformance/extensions/angle-instanced-arrays.html
sdk/tests/conformance2/rendering/instanced-arrays.html

Related to workaround for latest Mac Intel opengl driver bug http://crbug.com/1144207
Test description: we want to make sure webgl does instanced draw correctly when the non-zero divisor of an attribute is reset to zero. The attribute with the new divisor == 0 should be treated as a regular vertex attribute.
The test turns divisor of color attribute to zero. with `drawArraysInstancedANGLE(gl.TRIANGLES, 3, 3, instanceCount);`, it's the last three yellow vec4 that would be accessed by vertices. The test should draw 4 yellow triangles.
Tested locally on Mac AMD (passes chrome/firefox, patched chrome), Mac Intel (fails chrome/firefox, passes patched chrome)

Extra test for attribute divisor reset to 0 in angle-instanced-arrays.html

---

extensions/proposals/WEBGL_webcodecs_video_frame/webgl_webcodecs_video_frame.js
sdk/tests/conformance/extensions/webgl-webcodecs-video-frame.html
sdk/tests/performance/webgl_webcodecs_video_frame/index.html

VideoTrackReader is deprecated (see crbug.com/1157610), and it needs be replaced by the equivalent MediaStreamTrackProcessor.

Replace VideoTrackReader

---

specs/latest/2.0-compute/index.bs

Automatic regeneration of the index.html from the Bikeshed sources is
giving developers the impression that this specification is being
actively developed. Add a prominent note in the abstract that the
WebGPU spec is the path forward for compute shaders on the web, and
that this one is obsolete, while thanking Intel for their tremendous
contributions.

Mark WebGL 2.0 Compute specification as obsolete.

---

conformance-suites/1.0.1/conformance/resources/webgl-test-utils.js
conformance-suites/1.0.2/conformance/resources/webgl-test-utils.js
conformance-suites/1.0.3/conformance/resources/webgl-test-utils.js
conformance-suites/2.0.0/js/webgl-test-utils.js
sdk/tests/js/webgl-test-utils.js

Some tests will silently hang when playback errors occur, so add
an error listener so the failure reason is more obvious.

Add video element playback error detection, use it to fail test.

---

sdk/tests/js/webgl-test-utils.js

Some tests are finishing as soon as the first frame has come in
and triggering a pause() or other condition which thorws a
'AssertionError: Video failed to play(): AbortError: The play()
request was interrupted by a call to pause().' error.
So just check for no sources and use the error handler like we
do on older WebGL test versions.
Addresses new failures seen while rolling forward WebGL
conformance in Chromium:
https://chromium-review.googlesource.com/2775887/
for http://crbug.com/1136205 .

Don't use await for video.play() promise.

---

specs/latest/1.0/webgl.idl

Somehow many changes were introduced recently that should be fixed
separately from other updates.

Fix whitespace by rerunning IDL extraction scripts.

---

sdk/tests/conformance2/extensions/ext-color-buffer-float.html
sdk/tests/conformance2/extensions/ext-texture-norm16.html
sdk/tests/js/tests/ext-color-buffer-half-float.js

Add a regression test as chrome is missing return for formats added in `EXT_texture_norm16` in `getInternalformatParameter`
`R16`, `RG16`, `RGBA16` should be all multisample-support

Add getInternalformatParameter for EXT_texture_norm16

---

extensions/EXT_disjoint_timer_query/extension.xml
extensions/EXT_disjoint_timer_query_webgl2/extension.xml

Follows best practices for WebGL objects. Also modernize the
JavaScript in these examples (var -> let).

In EXT_disjoint_timer_query examples, delete query objects.

---

sdk/tests/conformance2/context/context-type-test-2.html

Test case for https://bugs.webkit.org/show_bug.cgi?id=222758 .
Already passes in Chrome and Firefox.

Verify that 'webgl' and 'webgl2' context types are distinct.

---

conformance-suites/1.0.3/conformance/context/context-methods.js
conformance-suites/1.0.3/conformance/context/methods.html
conformance-suites/2.0.0/conformance/context/methods.html
conformance-suites/2.0.0/conformance2/context/methods-2.html
conformance-suites/2.0.0/js/tests/context-methods.js
sdk/tests/conformance/context/methods.html
sdk/tests/conformance2/context/methods-2.html
sdk/tests/js/tests/context-methods.js

The WebXR device specification mixes in a new function makeXRCompatible.
The methods.html and methods-2.html tests should allow for the possibility
of the method existing.
While here, update the code to more modern JavaScript.

Allow makeXRCompatible as an optional method

---

extensions/WEBGL_multi_draw/extension.xml
extensions/WEBGL_multi_draw_instanced_base_vertex_base_instance/extension.xml

Parallels changes made in #2387 to the core WebGL 1.0 and 2.0
specifications to support SharedArrayBuffer, and implicitly,
multithreaded WebAssembly.
Fixes #3219 .

Add [AllowShared] to WEBGL_multi_draw APIs' typed array arguments.

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/fragment-shader-loop-crash.html

Issues seen on some Adreno drivers from Qualcomm. Fixed in their
latest driver.
Regression test for http://crbug.com/1076188 .

Verify that loops in ESSL 3.00 fragment shaders compile and link.

---

specs/latest/1.0/index.html
specs/latest/1.0/webgl.idl

Adding VideoFrame as a TexImageSource allows texImage*() methods to
interoperate with VideoFrames. VideoFrames work with texImage*() the
same way the existing point-in-time capture for HTMLVideoElement does.
This adds a non-normative reference on the WebCodecs spec for the
VideoFrame interface and associated properties to accomplish this.
Note: VideoFrame objects are always same-origin, so I did not add
any text around origin restrictions for video frames.
https://www.w3.org/TR/webcodecs/#videoframe-interface
Bug: w3c/webcodecs#158

Add WebCodecs VideoFrame as a TexImageSource.

---

sdk/tests/conformance/extensions/webgl-multi-draw.html

These are likely to require additional browser command-line arguments
since otherwise this functionality requires special configuration of
the web server hosting these tests.
Regression test for #3286.
Associated with http://crbug.com/1211185 .

Add WEBGL_multi_draw tests using SharedArrayBuffer.

---

sdk/tests/conformance/textures/misc/video-rotation.html

Hardware accelerated video decoders on some GPUs on Windows require
this increased tolerance.
Associated with http://crbug.com/1219015 .

Increase video-rotation tolerance to 45 for VP9.

---

sdk/tests/conformance/canvas/00_test_list.txt
sdk/tests/conformance/canvas/to-data-url-after-composite.html

Regression test for https://crbug.com/1216489 , where this path was
broken in Chromium when using SwiftShader.
Test passes in Firefox Nightly and Safari Technology Preview.

Add test of toDataURL after compositing the WebGL canvas.

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/reciprocal-sqrt-of-sum-of-squares-crash.html

This was occurring when the driver's GLSL compiler was identifying an
expression as containing the reciprocal square root of a sum of squares.
Regression test for https://crbug.com/1079309 and NVIDIA bug 2978301 .

Add test case for reciprocal sqrt of sum of squares crash.

---

specs/latest/1.0/index.html
specs/latest/2.0/index.html

As defined in the [definition markup contract](https://tabatkins.github.io/bikeshed/#dfn-contract) that many Web specs are adhering to - these conventions are not specific to bikeshed (they are [being moved to a document on their own](https://github.com/tabatkins/bikeshed/issues/2088#issuecomment-864169459)).
Adhering to these conventions makes it easier for other specifications to reference items defined in WebGL, through projects such as [webref](github.com/w3c/webref/) and [shepherd](http://hg.csswg.org/dev/shepherd/) which themseves are integrated in bikeshed and respec, widely used by other specs.
If this type of changes are acceptable and welcome, I would be happy to provide additional patches for other IDL items, at least those that are known to be referenced from other specs - if …

Markup definitions with their type

---

specs/latest/1.0/index.html

Web IDL should automatically drop the HTMLCanvasElement part from workers, [as in ImageBitmapRenderingContext](https://html.spec.whatwg.org/multipage/canvas.html#the-imagebitmaprenderingcontext-interface):
```webidl
[Exposed=(Window,Worker)]
interface ImageBitmapRenderingContext {
readonly attribute (HTMLCanvasElement or OffscreenCanvas) canvas;
undefined transferFromImageBitmap(ImageBitmap? bitmap);
};
```
Thus there is no need to process it manually. (Doing so makes things hard for IDL processing tools actually, e.g. https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1050.)

Simplify WebGLRenderingContextBase#canvas attribute

---

sdk/tests/conformance/extensions/ext-texture-compression-bptc.html
sdk/tests/conformance/extensions/ext-texture-compression-rgtc.html
sdk/tests/conformance/extensions/s3tc-and-rgtc.html
sdk/tests/conformance/extensions/webgl-compressed-texture-s3tc-srgb.html

WebGL 1.0's NPOT texture support is limited to textures without any
mip levels. Expect that the newly added RGTC and BPTC NPOT test from
PR #3304 generates an error on WebGL 1.0, and no error on WebGL 2.0.
Also change the expectation of an S3TC and S3TC-sRGB subtest which was
not following the new constraints that the size of the implied base
mip level must be a multiple of the block size.
Associated with ANGLE bug https://crbug.com/angleproject/6245 and
Issue #3117.

Update mipmapped NPOT compressed texture expectations.

---

sdk/tests/conformance/glsl/bugs/character-set.html
sdk/tests/js/js-test-pre.js

This ends up being an error in Firefox's harness, so let's prevent it
upstream too.

Add failure if "Duplicate notifyFinishedToHarness()".

---

specs/latest/1.0/index.html

Keeping in sync with webgl.idl change from https://github.com/KhronosGroup/WebGL/pull/3288
Bug: w3c/webcodecs#158

Add VideoFrame to index.html TexImageSource

---

sdk/tests/conformance2/programs/gl-get-frag-data-location.html

This came up in a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1657189
Apparent bug in Mesa: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5221
So let's test it in WebGL!

Add test for e.g. getFragDataLocation('gl_FragColor').

---

sdk/tests/conformance/rendering/00_test_list.txt
sdk/tests/conformance/rendering/clear-default-framebuffer-with-scissor-test.html

This patch adds a conformance test to expose an Intel D3D driver
bug about clearing canvas with scissor test in WebGL.
See https://crbug.com/1206763 for more details.

Expose the clearing canvas with scissor issue on Intel D3D drivers

---

specs/latest/1.0/index.html

This statement is added to prevent WebGL implementations from exposing ETC* formats on platforms that advertise them regardless of hardware support, most notably desktop OpenGL 4.3+ or any older version combined with `GL_ARB_ES3_compatibility`.
Among "desktop" GPUs, only Intel newer than Haswell support ETC* in hardware when using OpenGL.

Disallow emulated compressed formats

---

tools/conformance.py

platform.dist() is deprecated for python 3.9, so lsb_release is used
instead to get Linux version.
Browsers on Windows should be 64-bit, so PROGRAMFILES, instead of
PROGRAMFILES(X86), is used for their paths.
options, instead of chrome_options, is used as parameter of
selenium.webdriver.Chrome() to suppress the deprecation warning.

Fix several compatibility issues in tool

---

.gitmodules

This will make submodule initialization behave more intuitively.

Track main branch of WebGLDeveloperTools submodule.

---

sdk/tests/conformance2/extensions/webgl-multi-draw-instanced-base-vertex-base-instance.html

> The index of any element transferred to the GL by DrawArraysOneInstance
is referred to as its vertex ID, and may be read by a vertex shader as gl_VertexID.
The vertex ID of the ith element transferred is first + i.
From the [OpenGL ES spec section 10.5](https://www.khronos.org/registry/OpenGL/specs/es/3.2/es_spec_3.2.pdf)
Related to #3278

Fix gl_VertexID value in base-vertex-base-instance extension test

---

sdk/tests/conformance2/misc/00_test_list.txt
sdk/tests/conformance2/misc/blend-integer.html

This test was ported from the ANGLE's end2end `BlendIntegerTest` suite.
Known failures:
- [macOS/OpenGL/Intel](https://crbug.com/angleproject/5125) (invalid result after the draw call);
- ~~[Windows/Vulkan/Intel](https://crbug.com/angleproject/5071) (same as above, already fixed in drivers about a year ago)~~;
- [Android/Vulkan/Adreno](https://crbug.com/angleproject/5126) (driver crash).

Add Blend Integer Min/Max Test

---

sdk/tests/conformance/textures/misc/00_test_list.txt
sdk/tests/conformance/textures/misc/format-filterable-renderable.html
sdk/tests/js/js-test-pre.js

Checks all texture formats for filterable and color-renderable.
WebGL 1 and 2.
WebGL 1's RGB8 doesn't look like it's spec-required. Should it be?
Every device and browser I tested supports it, and it's color-renderable
in ES3/webgl2.

Add format-filterable-renderable test.

---

sdk/tests/deqp/functional/gles3/es3fPrimitiveRestartTests.js

Failing to set this was relying on currently-undefined behavior and
causing the tests to fail on Apple's M1.
Related to #2818, #2822 and #3356.

Set gl_PointSize in primitive restart tests for GL_POINTS.

---

sdk/tests/conformance2/extensions/required-extensions.html

This is as much as we could do on the WebGL CTS side to fix #3014. Another part of the fix was added in #3329 as a guidance for the implementors.
We could also add an extra test for WebGL 1.0 to catch a similar issue there:
```js
shouldBeTrue("!has_etc || has_etc1");
```

Require ETC1 support to match ETC2 on WebGL 2.0

---

specs/latest/2.0/index.html

Fixing [GLES30], [GLES30GLSL] and [WEBIDL]. Should fix #3373.
~~**HELP WANTED**: The link for **[GLES30]**:~~
> ~~http://www.khronos.org/registry/gles/specs/3.0/es_spec_3.0.4.pdf~~
~~refers to GLES **3.0.4**, but I can only find the latest pdf for GLES **3.0.6** on Khronos' pages~~
> ~~https://www.khronos.org/registry/OpenGL/specs/es/3.0/es_spec_3.0.pdf~~
~~which I think cannot be replaced directly.~~
~~Do we need to find an old **3.0.4** version of the pdf, or change the spec to fit the latest **3.0.6** version?~~
All references to GLES 3.0.4 are upgraded to 3.0.6.

Fix broken / redirected links in References

---

sdk/tests/conformance/programs/program-test.html
specs/latest/1.0/index.html

Rather than continuing to preserve the current executable as specified
in the OpenGL ES API, generate INVALID_OPERATION for subsequent draw
calls if the currently bound program is relinked, and that relink fails.
Update program-test.html to follow the new behavior.
Agreed upon in the WebGL working group meeting of 2021-10-21.

Immediately invalidate current program if its relink fails.

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/framebuffer-to-texture.html

Mimics the call structure in the following two Three.js demos:
https://threejs.org/examples/webgl_framebuffer_texture
https://threejs.org/examples/webgl_decals
Draws a solid color quad to the center of the viewport, copies a
portion of it to a texture, and blends that texture with the contents
of the framebuffer.
On Intel Macs, reproduced the bug in ANGLE's Metal backend when the
browser was invoked with Metal debug layers and load/store action
validation enabled:
MTL_DEBUG_LAYER=1 \
MTL_DEBUG_LAYER_VALIDATE_LOAD_ACTIONS=1 \
MTL_DEBUG_LAYER_VALIDATE_STORE_ACTIONS=1 \
MTL_DEBUG_LAYER_VALIDATE_UNRETAINED_RESOURCES=4 [browser...]
A similarly structured test is being added to the ANGLE project.
Minimized test case for http://anglebug.com/6972 .

Test multisampled framebuffer draws / copies / blends.

---

resources/generateTOC.js

Currently when following links with a fragment (linking to a specific section of the page, [an example](https://www.khronos.org/registry/webgl/specs/latest/2.0/#TEXTURE_TYPES_FORMATS_FROM_DOM_ELEMENTS_TABLE)) `generateTOC` will always scroll to the top of the page, as the element bounding rect is invalidated (all zeros) by reflow.
Interestingly such links work as expected when removing this code entirely, even in Internet Explorer. However I opted to keep the code and use `scrollIntoView` as it has suitably wide support and I'm unsure whether there are browsers that still need this fix.

Fix generateTOC always scrolling to top of document

---

sdk/tests/conformance/context/context-lost.html

Tests uploading a WebGL-rendered canvas with a lost WebGL context to a
texture in another WebGL context.
Test passes in Firefox Nightly, Safari Technology Preview, and Chrome
Canary.
Regression test for https://crbug.com/1305750 .

Test uploading a lost WebGL context to a texture.

---

sdk/tests/conformance/rendering/gl-scissor-fbo-test.html

Regression test for https://bugs.webkit.org/show_bug.cgi?id=237906 .
Confirmed with Safari 15.4 and Safari Technology Preview Release 141
(Safari 15.4, WebKit 17614.1.3.8) with "WebGL via Metal" that this
test catches the underlying bug. The bug has been fixed in top-of-tree
ANGLE and passes on Chrome Canary 102.0.4955.0 with --use-angle=metal.

Expand gl-scissor-fbo-test to cover antialias:true.

---

sdk/tests/conformance/context/00_test_list.txt
sdk/tests/conformance/context/context-attribute-preserve-drawing-buffer-antialias.html

The Apple Metal backend had an issue that blitting a multisample
renderbuffer could lose its content. Whether or not the contents
is lost is up to the driver. This repoed on M1 Macs.
https://bugs.webkit.org/show_bug.cgi?id=237113

Test the canvas' drawingbuffer keeps its contents when antialiased

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/multisampling-depth-resolve.html

Recent updates to WebKit caused a series of WebGL2 regressions. This test reproduces behavior found in several applications, where rendering to a multisampling framebuffer can break if depth_test is modified during the render.
https://brendan-duncan.github.io/webgl_bug_tests/msaa_depth_buffer.html
The test creates a multisampling framebuffer. It clears the framebuffer with a red color, disables depth_test, draws a large yellow quad, enables depth_test, and draws a smaller blue quad.
A series of conditions causes the behavior:
1) Render from requestAnimationFrame. The first render is correct. Subsequent frames fail.
2) Render into a mutlisampling framebuffer with a color and depth buffer.
3) Disable DEPTH_TEST and depthMask.
4) Render a quad.
5) Enable DEPTH_TEST and depthMask.
6) Render a …

Test depth buffer commands in a multisampling framebuffer

---

sdk/tests/conformance/programs/program-handling.html

In PR #2879, referencing Issue #2842, this test was added in order to
verify the behavior of failed relinks.
Since then, the WebGL specification was changed in PR #3371 to
immediately invalidate the current program upon failed relink. This
was motivated by the discovery of multiple bugs with inconsistent
program states during relinking, including http://crbug.com/1241123
and http://crbug.com/angleproject/6358 .
Revise program-handling.html to expect the current program to be
immediately invalidated upon failed relink, with associated behavioral
changes. Split the test into two cases to retain existing coverage:
failed relinks, and successful drawing after removal of the program's
shaders.
Associated with Chromium bug http://crbug.com/953120 .

Revise program-handling test to follow new spec behavior.

---

extensions/WEBGL_compressed_texture_pvrtc/extension.xml

Guide developers to prefer the ETC or ASTC compressed texture formats
instead, which are more broadly supported and offer better control
over compression fidelity.
Supersedes #2816 - on request from Apple.

Deprecate the WEBGL_compressed_texture_pvrtc extension.

---

specs/latest/1.0/index.html

Define their behavior both for presenting the rendering context's
results, and uploading textures via texImage2D / texSubImage2D from
DOM inputs (the TexImageSource union type).
Follows https://github.com/whatwg/html/pull/6562 , in which the
PredefinedColorSpace enum was defined, and its behavior for 2D canvas
contexts specified.

Add drawingBufferColorSpace/unpackColorSpace attributes to WebGLRenderingContextBase.

---

sdk/tests/js/tests/tex-image-and-sub-image-2d-with-video.js
sdk/tests/js/tests/tex-image-and-sub-image-utils.js
sdk/tests/js/webgl-test-utils.js

Change the test to use named colors, such as 'Red' and 'Green', and add the utility function namedColorInColorSpace to provide color space conversion.
Several tests replicate the behavior of converting a color from an 8-bit RGBA value to how that color will appear when sampled with a given internal format. Move this functionality to a colorAsSampledWithInternalFormat function.
Some of the tests started failing when using RGBA4 as an internal format, because the values being tested were no longer 0 or 255. Add a tolerance utility function to compute the appropriate for a given internalformat, format, and type.
To all test cases in tex-image-and-sub-image-2d-with-video.js, add an unpackColorSpace parameter. Cross-product all tests with the set of all color spaces. Add a utility function to …

Add unpackColorSpace tests to tex-image-and-sub-image-2d-with-video

---

sdk/tests/conformance/context/context-attribute-preserve-drawing-buffer-antialias.html

Certain GPUs (NVIDIA's in particular) are producing values during
multisample resolution that differ by 1 from the expected values.
Allow a tolerance of 2 to accommodate this and any other GPU
variances.
Follow-on to #3390 .
Associated with https://crbug.com/1326332 .

Add tolerance to context-attribute-preserve-drawing-buffer-antialias.

---

sdk/tests/conformance2/renderbuffers/multisample-draws-between-blits.html

conformance2/renderbuffers/multisample-draws-between-blits.html needs
a tolerance of 1 in its image comparisons on certain GPUs (NVIDIA
specifically); add a tolerance of 2 to accommodate other GPUs.
Follow-on to #3390 and #3412 .
Associated with https://crbug.com/1326332 .

Add tolerance to multisample-draws-between-blits.html.

---

sdk/tests/js/webgl-test-utils.js

Follow-on to #3404 .
Associated with http://crbug.com/1208480 .

Fix a variable reference in red-format video-to-texture tests.

---

sdk/tests/README.md
sdk/tests/js/js-test-post.js
sdk/tests/js/webgl-test-utils.js

And for showing the `RENDERER`.
This CL allows you to set any context creation parameters
in the URL. Example:
sometest.html?antialias=false&powerPreference=high-performance
Also, `showRenderer` which will print the renderer, unmasked
if the `WEBGL_debug_renderer_info` exists. Example:
sometest.html?showRenderer=true
These are useful for testing on dual GPU systems and verifying
that the correct GPU is being tested.
`runUntilFail` which will reload the test until it fails. Useful for tracking down flakes.
sometest.html?runUntilFail=true

Allow passing in context creation options in URL

---

extensions/WEBGL_draw_instanced_base_vertex_base_instance/extension.xml
extensions/WEBGL_multi_draw/extension.xml
extensions/WEBGL_multi_draw_instanced_base_vertex_base_instance/extension.xml

- Added links to the GLES extensions.
- Split features to improve readability.
- Fixed non-working XSL transforms due to missing XML tags.
- Fixed `countsList` and `baseInstancesList` types.
- Added missing `instanceCountsList` and `instanceCountsOffset` entries.
- Fixed `drawcount` spelling.

Fix typos in multi-draw extensions

---

sdk/tests/conformance/extensions/webgl-multi-draw.html

The spec requires that `WEBGL_multi_draw` implicitly enables `ANGLE_instanced_arrays`. Test the only JS-visible behavior change.

Test side-effects of WEBGL_multi_draw

---

sdk/tests/conformance/rendering/color-mask-preserved-during-implicit-clears.html
sdk/tests/conformance/rendering/draw-webgl-to-canvas-2d-repeatedly.html

In the tests:
conformance/rendering/color-mask-preserved-during-implicit-clears.html
conformance/rendering/draw-webgl-to-canvas-2d-repeatedly.html
on very slow devices, it seems that the script tag can run before the
document is fully loaded, causing the description() call to fail to
look up the named div.
Associated with https://crbug.com/1341423 .

Move script tag from head to body.

---

sdk/tests/conformance/textures/misc/texture-npot-video.html
sdk/tests/conformance/textures/misc/texture-video-transparent.html

The visibility of these tests isn't changing at runtime; log the
visibility state upon load as well.
Follow-on to #3421.
Associated with http://crbug.com/1293967 .

Log visibility upon load in two video tests.

---

sdk/tests/conformance2/rendering/clearbuffer-and-draw.html

- Added a few more cases to this test, covering depth and stencil clears.
- Added additional test runs with scissor enabled.
Passes in Firefox, various failures in Chromium and WebKit.
WebKit fix: https://github.com/WebKit/WebKit/pull/1625

Expand clearBuffer tests

---

sdk/tests/conformance/extensions/webgl-draw-buffers.html
sdk/tests/conformance2/extensions/oes-draw-buffers-indexed.html
sdk/tests/js/tests/ext-texture-filter-anisotropic.js

Check that `get*Parameter` functions return `null` (instead of `0` or `false`, like native GL) when unextended.

Test unextended get*Parameter results

---

sdk/tests/conformance/rendering/blending.html
specs/latest/1.0/index.html

Update test to test this.
s/GLclampf/GLfloat/ for blendColor args.
Resolves #3413.

Clarify blendColor clamps iff unextended webgl1.

---

sdk/tests/conformance/attribs/gl-enable-vertex-attrib.html
sdk/tests/conformance/extensions/angle-instanced-arrays.html
sdk/tests/conformance/extensions/webgl-multi-draw.html
sdk/tests/conformance2/attribs/00_test_list.txt
sdk/tests/conformance2/attribs/invalid-vertex-attribs.html
sdk/tests/conformance2/extensions/webgl-multi-draw-instanced-base-vertex-base-instance.html
sdk/tests/js/tests/invalid-vertex-attrib-test.js

#3434 
ATM this test only tests if an attribute is enabled but
no buffer is bound that each draw function generates
INVALID_OPERATION
Not sure what else needs to be test. Maybe mis-matching attributes (an ivec4 attribute in shader but float attribute in vao)

Test all draw functions fail if attributes are invalid

---

sdk/tests/conformance/extensions/ext-texture-compression-bptc.html
sdk/tests/conformance2/textures/misc/copy-texture-image.html
sdk/tests/conformance2/textures/misc/tex-image-with-bad-args.html
sdk/tests/js/tests/tex-input-validation.js

ANGLE returns `INVALID_VALUE` only for never-valid `internalformat` values regardless of enabled extensions.
Fixes #3453.

Relax texture error codes

---

extensions/EXT_texture_norm16/extension.xml
sdk/tests/conformance2/extensions/ext-texture-norm16.html

Closes #3417.
In test:
* Forbid RGBA/RGBA/UNSIGNED_SHORT (and SHORT)
* Forbid renderability of RGB16.
* Add more/better debug info for what each subtest is testing.

Clarify working of EXT_texture_norm16, and expand tests.

---

extensions/EXT_color_buffer_float/extension.xml
extensions/EXT_color_buffer_half_float/extension.xml
extensions/WEBGL_color_buffer_float/extension.xml
sdk/tests/conformance/rendering/blending.html
specs/latest/2.0/index.html

This PR updates the test to match the spec. Notable failures:
1. Firefox does not clamp constant blend color on store on unextended WebGL 1.0.
2. Adreno drivers clamp constant blend color internally even on ES 3.2 contexts and correctly reflect that via `getFloatv(GL_BLEND_COLOR, ...)` query.
Instead of permanently suppressing the test on [2], we may consider making this behavior implementation-dependent.

Fix & expand blend color clamping test

---

.github/workflows/lint.yml

Suggested on:
https://github.com/orgs/community/discussions/26649
as solution for failing Github action in:
https://github.com/KhronosGroup/WebGL/runs/7718272204?check_suite_focus=true

Run "sudo apt update" before installing dependencies.

---

specs/latest/1.0/index.html
specs/latest/2.0/index.html

Specify it categorically based on "are allowed to read/write" behavior,
and provide lists and annotations less normatively.
Fixes #3436.

Specify which operations are "Draw Operations" and "Read Operations".

---

sdk/tests/conformance2/buffers/get-buffer-sub-data.html

Add tests where the srcByteOffset is non-zero.
Add tests where the destination for the data returned by `getBufferSubData` does
not coincide with the beginning of array storage.

getBufferSubData with offset ArrayBufferView

---

sdk/tests/js/js-test-pre.js

Fixes testPassedOptions and testSkippedOptions only reporting
results when actually adding the <span> to the page. The test
harness should be notified when a test is done regardless of
whether the page contents are going to be modified.

Fix quiet mode test reporting

---

sdk/tests/js/js-test-pre.js

Adds caching for window.location.pathname and
window.parent.webglTestHarness. These values are accessed every
time reportTestResultsToHarness is called and accessing a variable
via window can be significantly slower than a local copy.
As an extreme example,
deqp/functional/gles3/vertexarrays/multiple_attributes.output.html
reports 33,013,505 results. On my local machine with Chromium, the
test takes ~20 seconds with this fix and ~215 seconds without it.
Related to crbug.com/1357073.

Cache window values

---

sdk/tests/conformance2/transform_feedback/simultaneous_binding.html

When a `bufferData` call is rejected due to simultaneous bindings, the bound buffer size must not reset. The new test fails in Chromium, passes in WebKit and Firefox.

Expand simultaneous XFB binding test

---

sdk/tests/conformance/reading/read-pixels-test.html
sdk/tests/conformance2/textures/misc/tex-new-formats.html

All new assertions fail in WebKit, pass in Chromium & Firefox.

Add depth-stencil type and null read receiver tests

---

sdk/tests/conformance/uniforms/00_test_list.txt
sdk/tests/conformance/uniforms/gl-get-uniform-non-current-program.html

It's possible this is already tested but I didn't see anything obvious and Firefox fails this test
There's 3yr old bug to fix it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1645092
Turns out the bug made [this webgl-state-diagram](https://webglfundamentals.org/webgl/lessons/resources/webgl-state-diagram.html?exampleId=use-2-programs#no-help) fail in Firefox. I've since [hacked in a workaround](https://github.com/gfxfundamentals/webgl-fundamentals/commit/e6d75517941ff1a9895a1a4d051ac32b08b97933) but it would be nice if that hadn't been needed.

Test calling getUniform from non-current program

---

extensions/WEBGL_provoking_vertex/extension.xml
sdk/tests/conformance2/extensions/webgl-provoking-vertex.html

- Reference an ANGLE extension that does not include quads and other desktop GL features.
- Use the same parameter name as all upstream extensions and specs for consistency.

Cleanup WEBGL_provoking_vertex

---

extensions/EXT_sRGB/extension.xml
sdk/tests/conformance/extensions/ext-sRGB.html

- Fixes #3475.
- Exposes a WebKit bug with `getFramebufferAttachmentParameter`.

Adjust EXT_sRGB spec and extend its test

---

extensions/proposals/ANGLE_shader_pixel_local_storage/extension.xml

This brings the ANGLE_shader_pixel_local_storage extension to WebGL.

Add an extension proposal for ANGLE_shader_pixel_local_storage

---

sdk/tests/js/tests/compressed-texture-utils.js

In `GLES2DecoderPassthroughImpl::Initialize`, Chromium implicitly enables many requestable extensions, including those that provide compressed texture formats; the `texStorage` calls defer all validation to ANGLE, and that's why the tests fail there for ASTC, ETC1, S3TC, and S3TC sRGB extensions.
~~On top of that, ANGLE currently behaves as if ETC2/EAC formats are always supported for ES 3.x clients, even in WebGL compatibility mode. WebKit also defers all `texStorage` validation to ANGLE, so ETC2/EAC tests fail both in Chromium and WebKit with this PR.~~

Test compressed formats rejection with texStorage

---

extensions/EXT_color_buffer_half_float/extension.xml
extensions/WEBGL_color_buffer_float/extension.xml
sdk/tests/conformance/extensions/oes-texture-float.html
sdk/tests/js/tests/ext-color-buffer-half-float.js

Both `EXT_color_buffer_half_float` and `WEBGL_color_buffer_float` say:
> The component types of framebuffer object attachments can be queried.
This PR clarifies and tests such queries. Seems like all browsers do not implement them.

Clarify FBO queries for floating-point extensions

---

specs/latest/1.0/index.html

These moved during the recent switchover to registry.khronos.org.
Fixes #3522.

Fix OpenGL ES 2.0 spec links.

---

extensions/WEBGL_shader_pixel_local_storage/extension.xml

This keeps it properly sorted in the draft extensions list.
Follow-on to #3521.

Update WEBGL_shader_pixel_local_storage extension's number to 49.

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/texture-bias.html

In GLSL there's a function `texture(sampler, texcoords, bias)`.
This test tests that `bias` works and that it is limited to
its advertised limits from `MAX_LOD_BIAS`
I believe ANGLE fails this test on several platforms as it returns a `MAX_LOD_BIAS` of `2.0` but actually allows the bias to go past the limit

Test the bias parameter to the texture GLSL function

---

sdk/tests/conformance/textures/misc/00_test_list.txt
sdk/tests/conformance/textures/misc/texture-srgb-upload.html

Test for both webgl1+ext and webgl2.
Test uploads from ArrayBuffer and (inlined) video. Ensure that srgb textures fetch/decode 0x7f as 0.21 not 0.5.
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1696693

Add conformance/textures/misc/texture-srgb-upload.html.

---

extensions/WEBGL_shader_pixel_local_storage/extension.xml
extensions/extension.xsl

Use Float32List, Int32List and Uint32List (defined in the WebGL 1.0 and 2.0 IDL) to allow typed array and ECMAScript arrays to be passed in identically. This matches the style of WebGL 2.0's uniform* entry points.
Update extensions' XSL transform to support optional arguments in function parameter lists.

Simplify framebufferPixelLocalClearValue* overloads.

---

sdk/tests/deqp/framework/common/tcuTestCase.js
sdk/tests/js/webgl-test-harness.js

On my machine, the subtests in multiple_attributes.output.html still run over 100% slower when run in harness (at least in Firefox), but they do run in tolerable time now.

Fix slow tests runs for e.g. multiple_attributes.output.html when run via harness.

---

extensions/proposals/EXT_clip_control/extension.xml

Due to historical reasons, WebGL uses [-1, +1] range for Z values. This leads to suboptimal depth buffer precision utilization because the best precision is allocated to mid-range values. When WebGL is implemented on top of Direct3D, Metal, or Vulkan, that range is rescaled to [0, +1] further increasing the loss and using extra per-vertex shader instructions.
The proposed extension would allow applications to directly use [0, +1] range.

Proposal: EXT_clip_control

---

extensions/proposals/EXT_depth_clamp/extension.xml

Vertices located closer than the near or farther than the far planes are always clipped. Various shadow rendering techniques greatly benefit from being able to squash (aka “pancake”) all geometry outside of the defined range instead of clipping it.
The proposed extension would allow applications to enable depth clamping while implicitly disabling near and far clipping planes.

Proposal: EXT_depth_clamp

---

extensions/proposals/WEBGL_polygon_mode/extension.xml

Rendering only triangle edges, i.e., wireframe, is incredibly useful when debugging GPU applications. For example:
- Preventing an empty screen when the view is accidentally blocked
- Confirming correct assembly of dynamically created geometry
Overlaying wireframe over filled triangles is useful for debugging fragment-based micro-geometry effects such as normal maps, bump maps, parallax maps, etc.
Simply switching primitive mode to LINES is not enough:
- Incompatible vertex arrangement / index buffers
- Depth bias is ignored for LINES, making correct overlay very difficult to achieve
The proposed extension would allow applications to toggle between solid and wireframe polygon rendering as well as enabling wireframe depth bias.

Proposal: WEBGL_polygon_mode

---

extensions/proposals/EXT_conservative_depth/extension.xml

Writing to `gl_FragDepth`, e.g., to render soft particles, disables implicit hardware optimizations and therefore increases the number of wasted fragment shader invocations.
The proposed extension would allow applications to hint hardware in what direction the written fragment depth is different from the rasterizer’s output. This re-enables implicit hardware optimizations and therefore prevents fragment shader invocations that are supposed to fail the depth test anyway.

Proposal: EXT_conservative_depth

---

extensions/proposals/NV_shader_noperspective_interpolation/extension.xml

- Perspective correction is always applied to non-flat varyings
- Extra computations are performed when not needed, e.g., for 2D apps
- Applications that need screen-space interpolation of 3D vectors have to implement workarounds to undo perspective correction
The proposed extension would allow applications to disable perspective correction of non-flat varyings.

Proposal: NV_shader_noperspective_interpolation

---

extensions/proposals/OES_sample_variables/extension.xml

Although WebGL 2.0 supports multisampled rendering, it does not provide relevant fragment built-ins.
The proposed extension would allow applications to control per-fragment sample mask as well as specialize fragment outputs depending on the sample being processed.

Proposal: OES_sample_variables

---

extensions/proposals/OES_shader_multisample_interpolation/extension.xml

Even with multisampled rendering, fragment varyings are interpolated at a pixel center or centroid at best.
The proposed extension would allow applications to enable per-sample varying interpolation and to explicitly query interpolated values at centroid, at a specific sample, or at an arbitrary in-pixel location.

Proposal: OES_shader_multisample_interpolation

---

extensions/proposals/EXT_render_snorm/extension.xml

Signed normalized formats are texturable but not renderable in WebGL 2.0. For values in [-1, +1] range, `snorm16` has much better precision and likely higher throughput than `float16`.
The proposed extension would allow applications to render into signed normalized pixel formats, including 16-bit formats when `EXT_texture_norm16` is enabled.

Proposal: EXT_render_snorm

---

extensions/proposals/WEBGL_render_shared_exponent/extension.xml

Shared exponent floating-point pixel format, i.e., RGB9_E5 is texturable but not renderable in WebGL 2.0. The only other small-float alternative is R11F_G11F_B10F, which may exhibit hue shifts due to asymmetry in channel encodings.
The proposed extension would allow applications in memory-constrained environments to choose between two small-float formats depending on the acceptable tradeoffs.

Proposal: WEBGL_render_shared_exponent

---

extensions/proposals/WEBGL_stencil_texturing/extension.xml

It is not possible to directly fetch stencil values from a combined depth-stencil texture in WebGL 2.0.
The proposed extension would allow applications to toggle between depth and stencil values when accessing combined depth-stencil textures in shaders.

Proposal: WEBGL_stencil_texturing

---

extensions/proposals/EXT_texture_mirror_clamp_to_edge/extension.xml

When a texture is symmetrical, only a part of it (as little as 1/8 in 3D case) could be stored in GPU memory. The existing MIRRORED_REPEAT mode is incompatible with certain effects that rely on the edge color being sampled for out-of-range texture coordinates.
The proposed extension would allow applications to use mirrored clamp-to-edge texture wrapping mode.

Proposal: EXT_texture_mirror_clamp_to_edge

---

specs/latest/1.0/extract-idl.py
specs/latest/1.0/index.html
specs/latest/1.0/webgl.idl
specs/latest/2.0/extract-idl.py
specs/latest/2.0/index.html
specs/latest/2.0/webgl2.idl

See whatwg/webidl#1311 for context.
At the same time adjust extract-idl.py to hold Python correctly ("!=" instead of "is not").
Thanks to @annevk for these changes in #3539 . They were contributed by @annevk and @grorg under Khronos' CLA; merging them separately to bypass the automated checks.

Incorporate @annevk 's SharedArrayBuffer and other Web IDL changes.

---

sdk/tests/conformance2/extensions/webgl-shader-pixel-local-storage.html

Await the results of asynchronous functions, and explicitly call finishTest() at the end of runTest().
Follow-on to #3530 .

Fix async portions of PLS test.

---

sdk/tests/conformance2/extensions/webgl-shader-pixel-local-storage.html

Timeouts were accidentally introduced in the last commit by failing to do this. Follow-on to #3562 and #3530.

Call finishTest() when PLS isn't supported.

---

extensions/rejected/WEBGL_texture_source_iframe/extension.xml

The security constraints needed for this extension were too difficult to define, despite a couple of attempts over a couple of years' time.

Reject WEBGL_texture_source_iframe extension.

---

specs/latest/2.0/index.html

Not sizes right now because we don't expect to support >4G sizes for uploads.
This change better supports large WebAssembly heaps. Related to crbug.com/1476859 ;
conformance test for all browsers forthcoming.

Upgrade ABV offset args from u32->u64.

---

extensions/WEBGL_multi_draw/extension.xml
extensions/WEBGL_multi_draw_instanced_base_vertex_base_instance/extension.xml
extensions/WEBGL_shader_pixel_local_storage/extension.xml

Updates the ArrayBufferView offset arguments in the following extensions:
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_shader_pixel_local_storage
to better support large WebAssembly heaps.
Follow-on to #3586.

Update ABV offset args in extensions from u32->u64.

---

sdk/tests/conformance2/00_test_list.txt
sdk/tests/conformance2/wasm/00_test_list.txt
sdk/tests/conformance2/wasm/readpixels-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/readpixels-4gb-wasm-memory.html
sdk/tests/conformance2/wasm/teximage2d-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/teximage2d-4gb-wasm-memory.html
sdk/tests/conformance2/wasm/texsubimage2d-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/texsubimage2d-4gb-wasm-memory.html
sdk/tests/test-guidelines.md

Add tests for gl.readPixels(), gl.texImage2D() and gl.texSubImage2D() from Wasm Memories of 4GB and 16GB in size.
CC @kenrussell

Add tests for gl.readPixels(), gl.texImage2D() and gl.texSubImage2D() from Wasm Memories of 4GB and 16GB in size.

---

sdk/tests/conformance2/wasm/readpixels-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/readpixels-4gb-wasm-memory.html
sdk/tests/conformance2/wasm/teximage2d-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/teximage2d-4gb-wasm-memory.html
sdk/tests/conformance2/wasm/texsubimage2d-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/texsubimage2d-4gb-wasm-memory.html

This makes them runnable by navigating to them outside of the test harness and without URL query parameters.
Follow-on to #3592.

In new WebGL 2-only Wasm tests, fetch WebGL 2.0 context directly.

---

sdk/tests/conformance2/query/00_test_list.txt
sdk/tests/conformance2/query/occlusion-query-scissor.html

The dEQP occlusionquery_strict test failed on Chrome but
not on Safari. This test provokes the same bug in both
Chrome and Safari.
See https://anglebug.com/7157

Add Occlusion Query Scissor Test

---

sdk/tests/conformance2/transform_feedback/transform_feedback.html

These two tests verify that certain invalid API calls do not affect the WebGL frontend state.

Add more transform feedback tests

---

extensions/EXT_clip_control/extension.xml
extensions/EXT_depth_clamp/extension.xml
extensions/EXT_polygon_offset_clamp/extension.xml
extensions/WEBGL_polygon_mode/extension.xml

WebGL WG resolved to promote the following to community approved during the meeting of 2023-11-02:
EXT_polygon_offset_clamp
EXT_clip_control
EXT_depth_clamp
WEBGL_polygon_mode
WEBGL_polygon_mode includes a warning about its non-portability which must be implemented in browsers.

Promote four extensions to community approved.

---

specs/latest/1.0/index.html
specs/latest/1.0/webgl.idl

Per the bug report, Web IDL syntax does not allow default values to be specified for these attributes. Instead, specify the initial values for the drawingBufferColorSpace and unpackColorSpace attributes as comments in the spec.
Fixes #3407.

Remove default value for interface attributes.

---

sdk/tests/conformance2/wasm/00_test_list.txt
sdk/tests/conformance2/wasm/bufferdata-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/bufferdata-4gb-wasm-memory.html
sdk/tests/conformance2/wasm/buffersubdata-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/buffersubdata-4gb-wasm-memory.html
sdk/tests/conformance2/wasm/getbuffersubdata-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/getbuffersubdata-4gb-wasm-memory.html

Add tests for bufferData, bufferSubData and getBufferSubData from WASM Memories of 4GB and 16GB in size.

Add tests for bufferData, bufferSubData and getBufferSubData from WASM Memories of 4GB and 16GB in size.

---

sdk/tests/conformance/extensions/webgl-depth-texture.html

Adds an epsilon when comparing float values in
conformance/extensions/webgl-depth-texture.html. As-is, it is possible for tests to fail with output such as:
At 2,0, expected within [0.2,0.6], was 0.600
FAIL At 2,0, expected within [0.2,0.6], was 0.600

Add epsilon to float comparison

---

sdk/tests/conformance/extensions/ext-color-buffer-half-float.html
sdk/tests/js/tests/ext-color-buffer-half-float.js

Previously it was hardcoded to test webgl1.

ext-color-buffer-half-float.html now webgl2 when requested.

---

specs/latest/1.0/index.html

This is similar to WebGPU's `GPUObjectBase.label`.

attribute USVString WebGLObject.label, application-provided.

---

sdk/tests/conformance/textures/misc/image-decoder-to-texture.html

The test was fetching nonexistent "width" and "height" properties on the VideoFrame, leading to a (0, 0)-sized texture upload. codedWidth and codedHeight are the best approximation without handling the full visibleRect in the test.
Follow-on to #3641 .
Associated with Chromium bug crbug.com/337904214 .

Fix image-decoder-to-texture in WebGL 2 mode.

---

conformance-suites/1.0.3/conformance/more/conformance/quickCheckAPI.js
conformance-suites/2.0.0/conformance/more/conformance/quickCheckAPI.js

Pick the fixs(#3655) for 2.0.0 and 1.0.3.
Fixes #3654.

Backport changes to fix quickCheckAPI-A fail

---

sdk/tests/conformance2/textures/misc/tex-unpack-params-with-flip-y-and-premultiply-alpha.html

`RGBA16UI` textures, when created with `UNPACK_PREMULTIPLY_ALPHA_WEBGL` set to `true` result in the `1282` (`GL_INVALID_OPERATION`) error despite that being against standards and the same thing not happening on Firefox.
The issue has been reported and a PR/CL has been requested:
Issue: https://issues.chromium.org/issues/40929470
PR/CL: https://chromium-review.googlesource.com/c/chromium/src/+/5525320
This PR is to add a test confirming that the issue's fix works and for future use.
There's also been an independent test made that this PR is based on:
https://github.com/RandomGamingDev/Chrome-UNPACK_PREMULTIPLY_ALPHA_WEBGL-Failure-Demo

Add a test for the creation of `RGBA16UI` textures with `UNPACK_PREMULTIPLY_ALPHA_WEBGL` enabled for chromium issue 40929470

---

sdk/tests/deqp/functional/gles3/es3fNegativeShaderApiTests.js

In particular:
- Ported https://github.com/KhronosGroup/VK-GL-CTS/commit/ec209beb5ee0c9db3808db44e0083d3bd3fd3a6a.
- Removed unused buffer.

Sync NegativeShaderApiTests with upstream CTS

---

sdk/tests/conformance2/transform_feedback/simultaneous_binding.html

Unbind the buffer from the COPY_WRITE_BUFFER target so that it is bound only as XFB for the next test.

Do not leak state between adjacent XFB tests

---

sdk/tests/deqp/framework/common/tcuSkipList.js
sdk/tests/deqp/functional/gles3/es3fShaderDerivateTests.js

Ported:
- https://github.com/KhronosGroup/VK-GL-CTS/commit/d9551dc8ecff19b0bfe50e0a463c49e99997b4a2
- https://github.com/KhronosGroup/VK-GL-CTS/commit/59b032bc7f837293068a2ee0469274c6dfede801
- https://github.com/KhronosGroup/VK-GL-CTS/commit/1dfe5d68bd78ebc44ee80222452e4a5f5656aab6
- https://github.com/KhronosGroup/VK-GL-CTS/commit/964431bd0878c57dde43978cfda34401b334c409
- https://github.com/KhronosGroup/VK-GL-CTS/commit/ce02996d700551a7fcc2889a55c54b20466b8cae
- https://github.com/KhronosGroup/VK-GL-CTS/commit/07b505e709ff516b426556e4593443b8f496c8c0
Confirmed that the updated tests pass on Adreno.

Sync ShaderDerivateTests with upstream CTS

---

extensions/EXT_disjoint_timer_query/extension.xml
extensions/OES_vertex_array_object/extension.xml
sdk/tests/conformance/context/context-lost-restored.html
sdk/tests/conformance/context/context-lost.html
sdk/tests/conformance/offscreencanvas/context-lost-restored.html
sdk/tests/conformance/offscreencanvas/context-lost-worker.html
sdk/tests/conformance/offscreencanvas/context-lost-worker.js
sdk/tests/conformance/offscreencanvas/context-lost.html
sdk/tests/js/tests/canvas-tests-utils.js
specs/latest/1.0/index.html
specs/latest/2.0/index.html

A general design pattern for WebGL is that it should generally be possible for rare failures (like context lost) to be ignorable when possible, such that code Just Works, and doesn't have to be rigorously robust to unusual failure cases. This is particularly important for context loss, since it is absolutely random, and could happen between any two invocations in JS.
For example, getUniformLocation might fail if a program doesn't have an expected uniform name, or fails to link. (or if context is lost!) By making e.g. `uniform1i` take `WebGLUniformLocation? location` and not `WebGLUniformLocation location`, we can paper over certain (rare-ish?) partial failures, rather than snowballing failures into black screens or runtime exceptions. 
It would be helpful to developers if object creation …

WebGLObject creation is now infallible, and starts Lost iff context Lost.

---

other/test-runner/config.json

Chrome now relies solely on ANGLE, and removes the DesktopGL [1]. This commit update the Chrome flag to "--use-gl=angle" accordingly.
[1] https://issues.chromium.org/issues/40848940

Use ANGLE in Chrome test runner

---

specs/latest/2.0/index.html

Clarify GLES/WebGL difference with uninitialized compressed textures.

---

sdk/tests/js/tests/iterable-test.js

Attempting to make this test a bit more stressful.

Change canvas height each iteration in multisample-corruption test.

---

specs/latest/1.0/index.html

UNPACK_COLORSPACE_CONVERSION_WEBGL now applies to all inputs, not just images.

---

sdk/tests/conformance2/wasm/bufferdata-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/buffersubdata-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/getbuffersubdata-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/readpixels-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/teximage2d-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/texsubimage2d-16gb-wasm-memory.html

The JS API for Memory was updated in https://github.com/WebAssembly/memory64/issues/68 to require BigInt parameters.

Use BigInt parameter in 16gb-wasm-memory tests

---

sdk/tests/conformance2/uniforms/00_test_list.txt
sdk/tests/conformance2/uniforms/uniform-block-idents-as-expr.html
sdk/tests/js/webgl-test-utils.js

Fixes #3644.
Fails 4-6 subtests on top-of-tree Chrome and Firefox.

Add conformance2/uniforms/uniform-block-idents-as-expr.

---

sdk/tests/conformance/offscreencanvas/offscreencanvas-transfer-image-bitmap.html
sdk/tests/conformance2/offscreencanvas/offscreencanvas-transfer-image-bitmap.html
sdk/tests/js/tests/offscreencanvas-transfer-image-bitmap.js

Test following spec clarifications:
* the value of preserveDrawingBuffer will have no effect
* the contents of any depth and/or stencil buffers will be cleared to initial values

Test OffscreenCanvas.transferToImageBitmap compositing steps (#3612)

---

sdk/tests/conformance2/wasm/bufferdata-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/buffersubdata-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/getbuffersubdata-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/readpixels-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/teximage2d-16gb-wasm-memory.html
sdk/tests/conformance2/wasm/texsubimage2d-16gb-wasm-memory.html

1) Use 'address' instead of 'index'; this was a last-minute change, see
https://github.com/WebAssembly/memory64/pull/90 and
https://github.com/WebAssembly/memory64/pull/92.
2) Only treat RangeError as passing test.
Note that the tests were passing before because engines threw a TypeError if the memory descriptor used bigints without specifying {address: 'i64'}.

Fix memory64 tests

---

conformance-suites/2.0.0/conformance2/reading/read-pixels-from-fbo-test.html
sdk/tests/conformance2/reading/read-pixels-from-fbo-test.html

Mali GPU need slightly extra tolerance.
Fixes #3705.

Increase the error tolerance for RGB5_A1 format

---

specs/latest/1.0/index.html
specs/latest/2.0/index.html

Drive-by updates to WebGL 2 IDL link and current spec editors' list.
Fixes #3708.

Fix "previous version" link in WebGL 2.0 spec to point to 2.0.0.

---

specs/latest/2.0/index.html

It should have linked to the WebGL 1.0 spec's description of enabled vertex array attributes and range checking.
Fixes #3710.

Fix description of drawRangeElements out-of-range behavior.

---

sdk/tests/conformance2/wasm/00_test_list.txt
sdk/tests/conformance2/wasm/multi-draw-2gb-in-4gb-wasm-memory.html

Test case for Chromium bug https://crbug.com/395670641 and Emscripten bug https://github.com/emscripten-core/emscripten/issues/17539 .

Test WEBGL_multi_draw with offsets 2 GB into a 4 GB typed array.

---

sdk/tests/conformance/misc/shader-precision-format.html

Passes in Mac Safari, fails in Mac Firefox.

Add webgl2 tests to conformance/misc/shader-precision-format.html.

---

sdk/tests/js/tests/tex-image-and-sub-image-2d-with-video.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-video.js
sdk/tests/js/webgl-test-utils.js

It seems to hang sometimes, maybe due to visibility testing. Fortunately, we believe `await video.play()` is enough in Firefox.
In diagnosing and fixing this, did clean-up refactor of tex-image-and-sub-image-*d-with-video.js to use async+await.

Firefox should not call requestVideoFrameCallback to ensure videos are uploadable.

---

serve_localhost.py

Example output:
```
k@pakhet webgl % ./serve_localhost.py
Serving /Users/k/dev/moz/webgl:
http://localhost:8000/
CTS Test Runner:
http://localhost:8000/sdk/tests/webgl-conformance-tests.html
```

When serve_localhost.py of base dir, also print link to CTS Test Runner.

---

sdk/tests/js/webgl-test-utils.js

Imply webgl2 within conformance2/ for getDefault3DContextVersion().

---

extensions/WEBGL_shader_pixel_local_storage/extension.xml
sdk/tests/conformance2/extensions/webgl-shader-pixel-local-storage.html

Remove this enum from the WEBGL_shader_pixel_local_storage extension, and renumber the remaining enums, both of which have already been done in the underlying ANGLE extension.
Remove the use of this enum from the pixel local storage CTS test as well. The new test passes on Chromium with all of these changes made.
Associated with https://anglebug.com/40096838 .

Remove MAX_COLOR_ATTACHMENTS_WITH_ACTIVE_PIXEL_LOCAL_STORAGE enum.

---

sdk/tests/conformance/textures/misc/00_test_list.txt
sdk/tests/conformance/textures/misc/tex-image-svg-image-no-natural-width-and-height.html

The case where an `HTMLImageElement` was referencing an SVG image with no natural width and height wasn't tested.

Add test for tex{Sub}Image2D from HTMLImageElement w/ SVG image w/o natural sizes
