KhronosGroup/WebGL

- sdk/tests/conformance/glsl/bugs/00_test_list.txt
- sdk/tests/conformance/glsl/bugs/sampler-struct-function-arg.html
This test passes on desktops and iOS, but fails on my Nexus 4.
> added a test for a sampler in a struct passed to a function

- extensions/extension.sch
- extensions/extension.xsl
- extensions/registry.html
- extensions/registry.xsl
- extensions/summary.xsl
- resources/Khronos-Rejected.css
extensions have to placed in the folder rejected, change their root tag to rejected and change their path to the folder rejected.
The file logo-Rejected.png doesn't exist yet, I don't have the source to the PNG file to generate it.
> added a rejected category

- extensions/rejected/WEBGL_debug_shader_precision/extension.xml
proposing (pending objections) to reject WEBGL_debug_shader_precision
> reject WEBGL_debug_shader_precision

- extensions/OES_fbo_render_mipmap/extension.xml
Proposing to move OES_fbo_render_mipmap to draft.
> move to draft OES_fbo_render_mipmap

- other/test-runner/README.md
- other/test-runner/index.js
List test cases with 10 or more failing tests in the failing tests
command line in output, and fix a couple of typos in instructions.
> Small fixes to the test runner

- sdk/tests/conformance/extensions/angle-instanced-arrays.html
> Ported ANGLE drawInstancedArrays offset test to WebGL conformance suite

- sdk/tests/conformance/glsl/matrices/00_test_list.txt
- sdk/tests/conformance/glsl/matrices/matrix-compound-multiply.html
This uncovers a bug in ANGLE's HLSL shader translator.
> Add a test for matrix compound multiplication

- extensions/OES_texture_float/extension.xml
- extensions/OES_texture_half_float/extension.xml
- extensions/OES_texture_half_float_linear/extension.xml
- extensions/WEBGL_depth_texture/extension.xml
> remove or promote extensions against WebGL 2.0

- sdk/tests/conformance2/00_test_list.txt
- sdk/tests/conformance2/buffers/00_test_list.txt
- sdk/tests/conformance2/buffers/buffer-type-restrictions.html
Tests the functions bindBuffer, bindBufferRange and bindBufferBase
with all the valid targets in WebGL 2.0.
> Added buffer restriction test

- sdk/tests/conformance/glsl/misc/00_test_list.txt
- sdk/tests/conformance/glsl/misc/shader-with-comma-separated-variable-declarations.html
Thanks to Florian Boesch for pointing out this oversight.
> Fixed #381 : Add test for comma separated var declarations

- sdk/tests/conformance2/state/00_test_list.txt
- sdk/tests/conformance2/state/gl-get-calls.html
- specs/latest/2.0/index.html
Also fixed a couple of typos in the spec found while verifying the values.
> Added WebGL 2 test for new getParameter enums

- sdk/tests/extra/cube-map-uploads-out-of-order.html
Thanks to Gregg Tavares for the original bug report and test case.
> Added test of uploading cube map faces out of order.

- sdk/tests/conformance/resources/gl-object-get-calls.js
> add GLenums to getVertexAttrib in conformance test for WebGL 2

- sdk/tests/conformance/resources/gl-object-get-calls.js
PTAL when you have time. Thanks!
> fix errors for resource loading when call it from conformance2/

- sdk/tests/conformance/resources/gl-object-get-calls.js
- sdk/tests/conformance/resources/uniformBlockShader.frag
- sdk/tests/conformance/resources/uniformBlockShader.vert
- sdk/tests/conformance/resources/webgl-test-utils.js
PTAL when you have time. 
The new shaders with uniform block are quite simple, we can add more code into it for other conformance tests later.
> update getProgramParameter in Conformance test for WebGL 2

- sdk/tests/conformance2/buffers/00_test_list.txt
- sdk/tests/conformance2/buffers/buffer-copying-contents.html
- sdk/tests/conformance2/buffers/buffer-copying-restrictions.html
Tests the function copyBufferSubData with all the valid targets in WebGL 2.0.
> Added buffer copying test

- sdk/tests/conformance/resources/gl-object-get-calls.js
> update getTexParameter for WebGL 2

- sdk/tests/conformance/resources/gl-object-get-calls.js
- sdk/tests/conformance/resources/matForWebGL2UniformShader.vert
- sdk/tests/conformance/resources/samplerForWebGL2UniformShader.frag
- sdk/tests/conformance/resources/uintUniformShader.vert
- sdk/tests/conformance/resources/uniformBlockShader.vert
> Conformance test: update getUniform for WebGL 2

- specs/latest/1.0/index.html
I wasn't sure on how to format this. I think this works.
> Add reasoning for buffer alignment.

- sdk/tests/conformance/resources/gl-object-get-calls.js
> update getFramebufferAttachmentParameter for WebGL 2

- sdk/tests/conformance/misc/expando-loss.html
@toji please help to review, thanks!
> Initialize variable expandoValue before using it

- sdk/tests/conformance/glsl/bugs/conditional-discard-in-loop.html
- sdk/tests/conformance/glsl/bugs/conditional-discard-optimization.html
- sdk/tests/conformance/glsl/bugs/sampler-struct-function-arg.html
Also fix sampler-struct-function-arg.html test so that it fails rather
than runs into an exception if compilation fails.
> Add shader logging to some tests

- sdk/tests/conformance/misc/expando-loss.html
@kenrussell , Please help to review this, thanks.
> Update expando test for WebGL 2.0

- specs/latest/2.0/index.html
PTAL when you have time. Thanks!
> Add a section <More binding points> in WebGL 2 spec explicitly, considering that some APIs can support more binding points in WebGL 2

- sdk/tests/conformance/glsl/bugs/00_test_list.txt
- sdk/tests/conformance/glsl/bugs/logic-inside-block-without-braces.html
TOT ANGLE hoists statements that belong inside an if statement outside
the if statement if the if statement doesn't have braces. Test for this.
> Add test for ANGLE short-circuiting logic unfolding issue

- sdk/tests/deqp/00_test_list.txt
- sdk/tests/deqp/framework/opengl/gluObjectWrapper.js
- sdk/tests/deqp/framework/opengl/simplereference/00_test_list.txt
- sdk/tests/deqp/framework/opengl/simplereference/referencecontext.html
- sdk/tests/deqp/framework/opengl/simplereference/sglrReferenceContextTest.js
- sdk/tests/deqp/framework/referencerenderer/rrUtil.js
- sdk/tests/deqp/functional/gles3/es3fFboCompletenessTests.js
- sdk/tests/deqp/functional/gles3/es3fFboMultisampleTests.js
- sdk/tests/deqp/functional/gles3/es3fFboStencilbufferTests.js
- sdk/tests/deqp/functional/gles3/es3fFboTestCase.js
- sdk/tests/deqp/functional/gles3/es3fFboTestUtil.js
- sdk/tests/deqp/functional/gles3/es3fFragmentOutputTests.js
- sdk/tests/deqp/functional/gles3/es3fFramebufferBlitTests.js
- sdk/tests/deqp/functional/gles3/es3fVertexArrayTests.js
- sdk/tests/deqp/functional/gles3/fbocompleteness.html
- sdk/tests/deqp/functional/gles3/fbomultisample.html
- sdk/tests/deqp/functional/gles3/fbostencilbuffer.html
- sdk/tests/deqp/functional/gles3/fragmentoutput.html
- sdk/tests/deqp/functional/gles3/framebufferblit.html
- sdk/tests/deqp/functional/gles3/vertexarrays.html
> Added files missing from the previous commit.

- sdk/tests/conformance2/glsl3/00_test_list.txt
- sdk/tests/conformance2/glsl3/array-as-return-value.html
The added test covers some simpler cases compared to
array-in-complex-expression.html
> Add tests for arrays as return values

- sdk/tests/conformance2/buffers/buffer-copying-contents.html
Now the test thoroughly covers all buffer copying pairs.
> Expand buffer-copying-contents.html

- sdk/tests/conformance/glsl/misc/00_test_list.txt
- sdk/tests/conformance/glsl/misc/sequence-operator-returns-constant.html
> Added test for checking sequence operators returns constant values for WebGL 1.0

- sdk/tests/conformance/glsl/misc/sequence-operator-returns-constant.html
PTAL when you have time. A patch is submitted before #1011 , but merged after #1011 without code rebase. I think that patch is the first and also the last one.
> fix a small bug, for resources has been moved out of conformance file folder

- sdk/tests/conformance2/00_test_list.txt
- sdk/tests/conformance2/renderbuffers/00_test_list.txt
- sdk/tests/conformance2/renderbuffers/multisampled-renderbuffer-initialization.html
Tested with local CLs applied to Chromium ToT build.
> Add multisampled-renderbuffer-initialization.html

- sdk/tests/conformance/glsl/bugs/00_test_list.txt
- sdk/tests/conformance/glsl/bugs/pow-with-constant-exponent-should-not-crash.html
This reveals a bug in NVIDIA 331 series OpenGL drivers.
> Add test for pow with constant vector exponent

- sdk/tests/conformance/glsl/misc/00_test_list.txt
- sdk/tests/conformance2/glsl3/00_test_list.txt
- sdk/tests/conformance2/glsl3/ternary-operator-on-arrays-glsl3.html
Also add the glsl3 version of the test.
> Correct ternary-operator-on-arrays.html version

- sdk/tests/conformance2/glsl3/00_test_list.txt
- sdk/tests/conformance2/glsl3/compare-structs-containing-arrays.html
This is a special case for HLSL implementation
> Add test for comparing structs containing arrays

- sdk/tests/js/tests/tex-input-validation.js
1. Adjust some functions location to make clearer.
2. Add test cases of texImage3D and texSubImage3D.
> Add test cases in tex-input-validation.js for WebGL 2.0

- sdk/tests/conformance2/buffers/buffer-copying-contents.html
Per discussion in https://github.com/KhronosGroup/WebGL/issues/1027
> Fix incorrect behavior in buffer-copying-contents.html

- sdk/tests/conformance/renderbuffers/00_test_list.txt
- sdk/tests/conformance2/renderbuffers/00_test_list.txt
- sdk/tests/conformance2/renderbuffers/framebuffer-test.html
> fix bug in conformance test in framebuffer-test.html under WebGL 2 rendering context

- README.md
- sdk/demos/google/image-texture-test/index.html
Updated URL missed in previous commit.
> Updated README.md to give hint about new git submodule.

- sdk/tests/conformance2/glsl3/00_test_list.txt
- sdk/tests/conformance2/glsl3/array-complex-indexing.html
Related Discussion: https://cvs.khronos.org/bugzilla/show_bug.cgi?id=13850
> Add test for indexing complex array expressions

- specs/latest/2.0/index.html
> Finish tex{Sub}Image*D related spec.

- specs/latest/2.0/index.html
> Add {compressed}tex{Sub}Image*D entry points with server side data.

- sdk/tests/conformance2/context/00_test_list.txt
- sdk/tests/conformance2/context/context-attributes-depth-stencil-antialias-obeyed.html
> Add a test to verify context creation attributes obeyed in WebGL2

- specs/latest/2.0/index.html
Dealing with PIXEL_PACK_BUFFER situation.
> Add readPixels in WebGL 2 spec.

- sdk/tests/conformance2/renderbuffers/framebuffer-test.html
> framebufferTexture2D can support mipmap level in WebGL 2 rendering context

- sdk/tests/conformance2/00_test_list.txt
- sdk/tests/conformance2/query/00_test_list.txt
- sdk/tests/conformance2/query/query.html
Not the full set of tests needed by any means, but verifies baseline query object behavior.
> Added basic WebGL 2 query object management tests

- sdk/tests/conformance/manual/angle-instanced-arrays-state-leakage.html
- sdk/tests/conformance/manual/canvas-clear-on-zero-count-draw.html
- sdk/tests/conformance/manual/canvas-no-clear-on-readpixels.html
- sdk/tests/conformance/manual/canvas-no-clear-on-unsuccessful-draw.html
- sdk/tests/conformance/manual/framebuffers-keep-contents-exiting-fullscreen-mode.html
- sdk/tests/conformance/more/functions/isTestsBadArgs.html
- sdk/tests/conformance/more/functions/readPixelsBadArgs.html
- sdk/tests/conformance/more/functions/texImage2DHTML.html
- sdk/tests/conformance/more/functions/texSubImage2DHTML.html
conformance/manual/
conformance/more/
> Switch to use js files from js/ instead of /resources/

- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-image-data-rgb565.html
- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-image-data-rgba4444.html
- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-image-data-rgba5551.html
- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-image-data.html
- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-image-rgb565.html
- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-image-rgba4444.html
- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-image-rgba5551.html
- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-image.html
- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-svg-image.html
- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-video-rgb565.html
- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-video-rgba4444.html
- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-video-rgba5551.html
- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-video.html
- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-webgl-canvas-rgb565.html
- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-webgl-canvas-rgba4444.html
- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-webgl-canvas-rgba5551.html
- sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-webgl-canvas.html
- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-data.js
- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image.js
- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-svg-image.js
- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-video.js
- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-webgl-canvas.js
Note that I didn't add the actual tests, to make reviewing easier.
Once this lands, the next CL will be the actual new tests.
> Add a test generator for tex-image-and-sub-image-* tests.

- sdk/tests/conformance2/renderbuffers/00_test_list.txt
- sdk/tests/conformance2/renderbuffers/readbuffer.html
PTAL when you have time. Thanks!
> add conformance test to readBuffer for WebGL 2

- other/get.webgl.org/troubleshooting/DoNotCopyOrLinkThisFileElseYouWillNotGetAutoUpdatedHelpForYourUsers.js
currently the page is detecting edge as chrome. this knocks that silliness off.
> update UA sniffing for Edge

- sdk/tests/conformance2/renderbuffers/readbuffer.html
> add test cases for reading from framebuffer and readBuffer is GL_NONE

- sdk/tests/conformance/glsl/misc/00_test_list.txt
- sdk/tests/conformance/glsl/misc/global-variable-init.html
> Add a test for global variable initializer restrictions

- sdk/tests/conformance/renderbuffers/00_test_list.txt
- sdk/tests/conformance2/renderbuffers/00_test_list.txt
- sdk/tests/conformance2/renderbuffers/framebuffer-object-attachment.html
Note that I didn't add tests for various combinations because deqp already has
a very thorough tests for that.
> Add WebGL 2 version of framebuffer-object-attachment.html

- sdk/tests/conformance2/renderbuffers/framebuffer-object-attachment.html
- sdk/tests/conformance2/renderbuffers/framebuffer-test.html
> quite a small fix

- other/get.webgl.org/index.html
> Add text Hosted by Digital Ocean

- specs/latest/1.0/webgl.idl
Just run make once, it's removing all of them automatically.
> Fix webgl.idl unnecessary whitespaces.

- specs/latest/1.0/index.html
- specs/latest/1.0/webgl.idl
Used to be GLsizeiptr, should be GLintptr.
> Fix getVertexAttribOffset return type.

- sdk/tests/conformance2/00_test_list.txt
- sdk/tests/conformance2/reading/00_test_list.txt
- sdk/tests/conformance2/reading/read-pixels-from-fbo-test.html
Testing reading from FBO with various formats/types.
> Add a readPixels test for WebGL 2 cases.

- sdk/tests/conformance2/reading/read-pixels-from-fbo-test.html
Add all the sized ES3 texture formats/types as fbo's color image.
> Improve read-pixels-from-fbo-test.html

- sdk/tests/conformance/glsl/bugs/00_test_list.txt
- sdk/tests/conformance/glsl/bugs/qualcomm-crash.html
Based on http://crbug.com/498947
> Added conformance test for shaders that crash some Qualcomm drivers.

- sdk/tests/conformance2/reading/read-pixels-from-fbo-test.html
> Fix a bug in read-pixels ES3 test

- sdk/tests/conformance2/reading/read-pixels-from-fbo-test.html
This may not be the last fix for this test, as Chrome doesn't work in this area yet.
> Use clearBufferiv and clearBufferuiv for INT and UINT buffers.

- sdk/tests/conformance2/samplers/samplers.html
Refactor the test steps:
default value -> valid value set/get -> invalid value.
> Add params checking for sampler parameter test

- sdk/tests/conformance2/reading/read-pixels-from-fbo-test.html
Minor fixes, please take a look.
> Fix minor bugs in read-pixels-from-fbo-test.html

- sdk/tests/conformance2/reading/read-pixels-from-fbo-test.html
Fix the implementation dependent format/type testing
> More improvements for read-pixels-from-fbo-test.html

- sdk/tests/conformance2/reading/00_test_list.txt
- sdk/tests/conformance2/reading/read-pixels-into-pixel-pack-buffer.html
- specs/latest/2.0/index.html
> add test cases for reading pixels to pixel pack buffer

- sdk/tests/conformance2/rendering/draw-buffers.html
- sdk/tests/js/webgl-test-utils.js
> Fix minor bugs.

- sdk/tests/conformance/glsl/constructors/glsl-construct-vec-mat-index.html
Make it use the GLSL test framework instead of having custom testing
code, and add mention of the relevant spec section.
> Clean up GLSL constructor corner case test

- sdk/tests/conformance/textures/misc/tex-sub-image-2d-bad-args.html
Out of range values for texture level should raise INVALID_VALUE.
> Add test for level parameter of texSubImage2D

- sdk/tests/deqp/functional/gles3/es3fTransformFeedbackTests.js
These fixes make more of the tests pass but it's unclear whether all of
them will; Chromium must virtualize transform feedback handling better.
> Fixed bugs in primitive type handling, queries and loop structure.

- sdk/tests/conformance2/buffers/buffer-type-restrictions.html
The behavior being changed is described by section 5.1 and 5.2 of the WebGL 2 spec
> Fix spec compliance of conformance2/buffers/buffer-type-restrictions

- specs/latest/2.0/index.html
- specs/latest/2.0/webgl2.idl
> Added vertexAttribI4i and vertexAttribI4ui variants.

- specs/latest/2.0/index.html
> Fixed typos.

- sdk/tests/conformance/extensions/ext-disjoint-timer-query.html
- sdk/tests/conformance/extensions/oes-texture-float-with-canvas.html
- sdk/tests/conformance/extensions/oes-texture-float-with-image-data.html
- sdk/tests/conformance/extensions/oes-texture-float-with-image.html
- sdk/tests/conformance/extensions/oes-texture-float-with-video.html
- sdk/tests/conformance/extensions/oes-texture-half-float-with-canvas.html
- sdk/tests/conformance/extensions/oes-texture-half-float-with-image-data.html
- sdk/tests/conformance/extensions/oes-texture-half-float-with-image.html
- sdk/tests/conformance/extensions/oes-texture-half-float-with-video.html
> Fix a bunch of tests timeing out

- sdk/tests/js/tests/gl-object-get-calls.js
- sdk/tests/resources/uniformBlockShader.frag
I am sure this is not the end of bug fixes for this test
> Fix bugs in gl-object-get-calls.js

- sdk/tests/js/tests/gl-object-get-calls.js
Please help review the code. Thanks~!
> Add getInternalformatParameter in gl-object-get-call.js

- sdk/tests/js/tests/gl-object-get-calls.js
- sdk/tests/resources/matForWebGL2UniformShader.vert
- sdk/tests/resources/noopUniformShaderES3.frag
- sdk/tests/resources/noopUniformShaderES3.vert
- sdk/tests/resources/samplerForWebGL2UniformShader.frag
> Fix more bugs in gl-object-get-calls.js

- sdk/tests/conformance2/buffers/00_test_list.txt
- sdk/tests/conformance2/buffers/buffer-overflow-test.html
buffer overflow will not lead to failure in bindBufferRange.
PTAL. Thanks.
> Conformance2: add buffer overflow test for bindBufferRange

- sdk/tests/conformance/textures/misc/texparameter-test.html
1. Remove world transformation.
2. Use WebGLTestUtils to setup texture quad.
> Simplify test case of texparameter-test.html

- sdk/tests/js/tests/gl-object-get-calls.js
(I think this is the last fix for this test for now!)
> Small fix in gl-object-get-calls.js

- sdk/tests/js/tests/gl-object-get-calls.js
Please help review the code, thanks!
> Add getIndexedParameter in gl-object-get-call.js

- extensions/ANGLE_instanced_arrays/extension.xml
> Clarify ANGLE_instanced_arrays and  OES_vertex_array_object interaction

- sdk/tests/deqp/functional/gles3/es3fShaderBuiltinVarTests.js
- sdk/tests/deqp/functional/gles3/es3fShaderDerivateTests.js
- sdk/tests/deqp/functional/gles3/es3fShaderOperatorTests.js
- sdk/tests/deqp/functional/gles3/es3fShaderSwitchTests.js
- sdk/tests/deqp/modules/shared/glsShaderExecUtil.js
> Formatting fixes.

- sdk/tests/conformance2/transform_feedback/transform_feedback.html
- sdk/tests/js/webgl-test-utils.js
Verifies basic draw call behavior and varying queries.
> Expand Transform Feedback test

- sdk/tests/deqp/framework/common/tcuPixelFormat.js
- sdk/tests/deqp/framework/common/tcuTexVerifierUtil.js
- sdk/tests/deqp/framework/opengl/gluVarType.js
- sdk/tests/deqp/framework/opengl/simplereference/sglrReferenceContext.js
- sdk/tests/deqp/functional/gles3/es3fDrawTests.js
- sdk/tests/deqp/functional/gles3/es3fFboTestCase.js
- sdk/tests/deqp/functional/gles3/es3fFragDepthTests.js
- sdk/tests/deqp/functional/gles3/es3fIndexedStateQueryTests.js
- sdk/tests/deqp/functional/gles3/es3fIntegerStateQueryTests.js
- sdk/tests/deqp/functional/gles3/es3fMultisampleTests.js
- sdk/tests/deqp/functional/gles3/es3fNegativeShaderApiTests.js
- sdk/tests/deqp/functional/gles3/es3fNegativeTextureApiTests.js
- sdk/tests/deqp/functional/gles3/es3fNegativeVertexArrayApiTests.js
- sdk/tests/deqp/functional/gles3/es3fReadPixelTests.js
- sdk/tests/deqp/functional/gles3/es3fShaderBuiltinVarTests.js
- sdk/tests/deqp/functional/gles3/es3fStringQueryTests.js
- sdk/tests/deqp/functional/gles3/es3fTextureFilteringTests.js
- sdk/tests/deqp/functional/gles3/es3fTextureSpecificationTests.js
- sdk/tests/deqp/functional/gles3/es3fUniformApiTests.js
- sdk/tests/deqp/functional/gles3/es3fVertexArrayTests.js
- sdk/tests/deqp/modules/shared/glsAttributeLocationTests.js
- sdk/tests/deqp/modules/shared/glsShaderExecUtil.js
- sdk/tests/deqp/modules/shared/glsStateQuery.js
> Simplified closure annotations.

- sdk/tests/js/tests/tex-image-and-sub-image-3d-with-canvas.js
- sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-data.js
- sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image.js
- sdk/tests/js/tests/tex-image-and-sub-image-3d-with-svg-image.js
- sdk/tests/js/tests/tex-image-and-sub-image-3d-with-video.js
- sdk/tests/js/tests/tex-image-and-sub-image-3d-with-webgl-canvas.js
- sdk/tests/js/tests/tex-image-and-sub-image-utils.js
This is intermediate work. May contains bugs.
> Adding tests: Tex{Sub}Image3D with web elements as input.

- sdk/tests/js/tests/gl-object-get-calls.js
Simplify the test. Verified locally. (Portions of this test are still failing.)
> Incorporate test from @renchenglei in #1239.

- extensions/EXT_disjoint_timer_query/extension.xml
There was support on the public_webgl mailing list and no objections after several days.
> Promoted EXT_disjoint_timer_query to community approved.

- specs/latest/2.0/index.html
Also fixed some broken links to es_full_spec_3.0.3.pdf. No other changes.
> Updated GLES spec references from 3.0.3 to 3.0.4.

- sdk/tests/deqp/data/gles3/shaders/linkage.test
- sdk/tests/deqp/functional/gles3/es3fNegativeShaderApiTests.js
- sdk/tests/deqp/functional/gles3/es3fNegativeStateApiTests.js
- sdk/tests/deqp/functional/gles3/es3fUniformBlockTests.js
> Removed shared and packed layouts tests.

- sdk/tests/js/tests/gl-object-get-calls.js
Please help review the code, thanks!
> Add getSamplerParameter to gl-object-get-call.js

- sdk/tests/conformance2/state/gl-get-calls.html
- sdk/tests/js/js-test-pre.js
Add shouldBeLessThanOrEqual primitive and use it for this test.
Verified in Chrome Canary.
> Fix #1286: MIN_PROGRAM_TEXEL_OFFSET should be <= -8.

- sdk/tests/conformance2/buffers/uniform-buffers.html
> To define the same uniform in two uniform blocks should fail

- sdk/tests/js/tests/gl-object-get-calls.js
Please help review the code, thanks!
> Add getSyncParameter to gl.object-get-call.js

- sdk/tests/conformance/limits/00_test_list.txt
- sdk/tests/conformance/limits/gl-line-width.html
Test written in response to http://crbug.com/551081
The behavior here is very non-obvious, (storing and returning out of range values without erroring) but it's what the spec says should happen.
> Added test that checks the behavior of gl.lineWidth

- sdk/tests/conformance/context/context-lost-restored.html
- sdk/tests/conformance/extensions/ext-sRGB.html
- sdk/tests/conformance/extensions/oes-texture-float.html
- sdk/tests/conformance/extensions/oes-texture-half-float.html
- sdk/tests/conformance/extensions/webgl-depth-texture.html
- sdk/tests/conformance/more/functions/texImage2DBadArgs.html
- sdk/tests/conformance/more/functions/texSubImage2DBadArgs.html
- sdk/tests/conformance/renderbuffers/framebuffer-test.html
- sdk/tests/conformance/textures/misc/tex-sub-image-2d-bad-args.html
- sdk/tests/conformance/textures/misc/texture-formats-test.html
- sdk/tests/js/webgl-test-utils.js
Fixing some of the changes made in #1303 after discussion. Undid the
changes to webgl-test-utils (except for the whitespace fix) and
adjusted all tests. Re-ran all affected tests and verified they
continue to work.
> Revise fix for ambiguous error cases.

- specs/latest/2.0/index.html
Also, fix a small related bug.
> Add WebGL2/ES3 PixelStorei difference from WebGL1/ES2.

- sdk/tests/conformance/glsl/bugs/00_test_list.txt
- sdk/tests/conformance/glsl/bugs/sketchfab-lighting-shader-crash.html
Unclear at this time whether Nexus 4 (Adreno 320) is also affected.
Adreno 400 series GPUs appear to be unaffected. Tracked under
http://crbug.com/551937 .
> Added test case from Sketchfab team failing on Nexus 5 with Android 6.0.

- sdk/tests/deqp/functional/gles3/es3fNegativeBufferApiTests.js
One of the CL to fix http://code.google.com/p/chromium/issues/detail?id=565347 
PTAL. Thanks a lot.
> Copy buffer sub data

- sdk/tests/deqp/functional/gles3/es3fNegativeBufferApiTests.js
Fix the bug of http://code.google.com/p/chromium/issues/detail?id=565347. 
PTAL. Thanks a lot.
> fix the errors when calling drawBuffers in negativebufferapi

- sdk/tests/conformance/textures/image_bitmap/tex-image-and-sub-image-2d-with-image-bitmap-rgb-rgb-unsigned_byte.html
- sdk/tests/conformance/textures/image_bitmap/tex-image-and-sub-image-2d-with-image-bitmap-rgb-rgb-unsigned_short_5_6_5.html
- sdk/tests/conformance/textures/image_bitmap/tex-image-and-sub-image-2d-with-image-bitmap-rgba-rgba-unsigned_byte.html
- sdk/tests/conformance/textures/image_bitmap/tex-image-and-sub-image-2d-with-image-bitmap-rgba-rgba-unsigned_short_4_4_4_4.html
- sdk/tests/conformance/textures/image_bitmap/tex-image-and-sub-image-2d-with-image-bitmap-rgba-rgba-unsigned_short_5_5_5_1.html
Adding conformance/textures/image_bitmap/ folder and manually created several tests without creating 00_test_list.txt.
> Manually adding new test

- sdk/tests/conformance2/reading/read-pixels-into-pixel-pack-buffer.html
in conformance2/reading/read-pixels-into-pixel-pack-buffer.html
> Refactor: using object instead for function parameters

- sdk/tests/conformance2/reading/00_test_list.txt
- sdk/tests/conformance2/reading/read-pixels-into-pixel-pack-buffer.html
- sdk/tests/conformance2/reading/read-pixels-pack-parameters.html
> Testing pack parameters for ReadPixels into client array buffer.

- sdk/tests/js/tests/gl-object-get-calls.js
Please help review the code, thanks a lot~
> Add getFragDataLocation to gl.object-get-call.js

- sdk/tests/js/tests/gl-object-get-calls.js
per the request when reviewing this Chromium patch: https://codereview.chromium.org/1508313002/. 
> add test cases for getActiveUniforms

- sdk/tests/conformance2/reading/read-pixels-pack-parameters.html
@kenrussell This is per your request.  PTAL.
> Check more pixels in read-pixels-pack-parameters.html

- sdk/tests/js/tests/gl-object-get-calls.js
Please help review the code, thanks a lot~
> Add getUniformBlockIndex to gl.object-get-call.js

- sdk/tests/conformance/glsl/bugs/00_test_list.txt
- sdk/tests/conformance/glsl/bugs/gl-fragcoord-multisampling-bug.html
Exposes bug discovered by Three.js developers in
https://github.com/mrdoob/three.js/issues/7769 .
> Added regression test for gl_FragCoord.zw behavior with multisampling.

- sdk/tests/conformance/misc/bad-arguments-test.html
- sdk/tests/js/webgl-test-utils.js
Synchronous XMLHttpRequest on the main thread is deprecated.
Both chrome and firefox report error on this.
> Load file asynchronously in bad-arguments-test.html

- sdk/tests/js/tests/gl-object-get-calls.js
Please help review the code, thanks a lot~
> Add getActiveUniformBlockName to gl.object-get-call.js

- sdk/tests/conformance2/reading/read-pixels-pack-parameters.html
Make it thourough, interaction between all pack parameters and
out-of-bounds read, etc.
> Improve read-pixels-pack-parameters.

- sdk/tests/conformance2/reading/read-pixels-pack-parameters.html
conformance2/reading/read-pixels-pack-parameters.html
Add validation of buffer size.
> More improvement to

- sdk/tests/deqp/functional/gles3/es3fTransformFeedbackTests.js
The verification of a given test case may need to be retried because
the query's result was not available yet. Fixed the logic in this area.
Thanks to Shuai Shao for pointing out these failures.
> Fixed verification in the transform feedback test.

- sdk/tests/conformance2/reading/read-pixels-pack-parameters.html
- specs/latest/2.0/index.html
and PACK_ROW_LENGTH is (0, width).
> Out-of-bound behaviors for readPixels when a PACK_BUFFER is bound

- conformance-suites/1.0.1/conformance/buffers/buffer-data-array-buffer.html
- conformance-suites/1.0.1/conformance/more/functions/texImage2DBadArgs.html
- conformance-suites/1.0.1/conformance/more/util.js
- conformance-suites/1.0.2/conformance/buffers/buffer-data-array-buffer.html
- conformance-suites/1.0.2/conformance/extensions/webgl-depth-texture.html
- conformance-suites/1.0.2/conformance/more/functions/texImage2DBadArgs.html
- conformance-suites/1.0.2/conformance/more/util.js
- conformance-suites/1.0.3/conformance/buffers/buffer-data-array-buffer.html
- conformance-suites/1.0.3/conformance/extensions/webgl-depth-texture.html
- conformance-suites/1.0.3/conformance/more/functions/texImage2DBadArgs.html
- conformance-suites/1.0.3/conformance/more/util.js
All of these are due to spec change after the snapshots were taken.
> Fix bugs in conformance suites 1.0.1, 1.0.2, 1.0.3

- sdk/tests/conformance2/reading/read-pixels-from-fbo-test.html
Mentioned in #1433. I create this pr for following fix.
> Support more types in getTypeString.

- sdk/tests/js/tests/gl-object-get-calls.js
Please help review the code, thanks a lot~
> Add getActiveUniformBlockParameter to gl.object-get-call.js

- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap.js
- sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap.js
@zhenyao @toji @kenrussell Please review, both parameters are now removed from the test
> Remove flipY and premultiplyAlpha from the test

- sdk/tests/deqp/functional/gles3/es3fPixelBufferObjectTest.js
This change will fix failures in pixelbufferobject.html in deqp test.
PTAL. Thanks!
> Fix bugs for pixelbufferobject.html in deqp

- sdk/tests/deqp/modules/shared/glsUniformBlockCase.js
> Resolve the big-litte endian issue and read pixel out of range issue.

- sdk/tests/conformance2/misc/00_test_list.txt
- sdk/tests/conformance2/misc/uninitialized-test-2.html
I just realized I should also test texStorage2D.  Will do it in a followup CL.
> Add test to verify texImage3D and texStorage3D won't leak memories.

- sdk/tests/deqp/framework/common/tcuTexture.js
This makes deqp/framework/opengl/simplereference/referencecontext.html
pass.
> Fix missing {} for if-else

- sdk/tests/deqp/modules/shared/glsUniformBlockCase.js
> Corret a logical error when setting vec4 alignment.

- sdk/tests/deqp/framework/opengl/simplereference/sglrReferenceContextTest.js
> Remove extra tests in referencecontext.html

- sdk/tests/deqp/framework/common/tcuFloat.js
The code was correct but the documentation was confusing. Addresses #1474.
> Update documentation for deFloatParameters and newDeFloatFromParameters.

- sdk/tests/conformance2/misc/uninitialized-test-2.html
1) Cover TexStorage2D
2) Cover for int and uint formats
3) Cover the partially initialized cases
> Enhance uninitialized-test-2.html

- conformance-suites/1.0.1/conformance/programs/program-test.html
- conformance-suites/1.0.2/conformance/programs/program-test.html
- conformance-suites/1.0.3/conformance/programs/program-test.html
- sdk/tests/conformance/programs/program-test.html
Fixed "shoud" typos in program-test.html
> Fixed some spelling mistakes

- sdk/tests/deqp/functional/gles3/es3fLifetimeTests.js
- sdk/tests/deqp/modules/shared/glsLifetimeTests.js
C++ code: https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fLifetimeTests.cpp#343
> Align dEQP lifetime tests with C++ code

- sdk/tests/conformance2/buffers/uniform-buffers.html
Test named uniform blocks with instance array.
> Improve uniform-buffers.html

- sdk/tests/deqp/functional/gles3/es3fLifetimeTests.js
Align js code with C++ code.
C++ code: https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fLifetimeTests.cpp#489
> Implement lifetime.delete_active.transform_feedback test

- sdk/tests/deqp/modules/shared/glsVertexArrayTests.js
> Correct the vertex count when drawArrays with a offset.

- sdk/tests/conformance2/textures/misc/00_test_list.txt
- sdk/tests/conformance2/textures/misc/tex-unpack-params.html
This tests all ES3 unpack parameters.
Note that this is not an fully implemented test yet. I plan to add pixel
verification in a followup CL.
> Add tex-unpack-params.html

- sdk/tests/deqp/modules/shared/glsUniformBlockCase.js
> Print the successful results of UniformBlockCase cases.

- sdk/tests/deqp/functional/gles3/es3fShaderLoopTests.js
C++ code: https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fShaderLoopTests.cpp#1198
> Skip unvailable test case in shaderloop.html

- sdk/tests/deqp/functional/gles3/texturefiltering_3d_combinations.html
- sdk/tests/deqp/functional/gles3/texturefiltering_cube_combinations_04.html
- sdk/tests/deqp/functional/gles3/texturefiltering_cube_combinations_05.html
- sdk/tests/deqp/functional/gles3/texturefiltering_test_generator.py
It's not fully done yet.  The current status of this script is
to make minimum change to the existing files.
> Add a python script to generate all texturefilter* tests

- sdk/tests/deqp/functional/gles3/es3fShaderCommonFunctionTests.js
C++ code:
https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fShaderCommonFunctionTests.cpp#1251
> Use correct trunc function to align with C++ code

- sdk/tests/deqp/framework/common/tcuFloat.js
tcuFloat has been identified as a major bottleneck in multiple DEQP tests. These optimizations (most specifically the change to `tcuFloat.numberToHalfFloat`) speed up some tests like `texturefiltering_3d_formats` around 100x. I think other tests may benefit from similar conversions of `tcuFloat.numberToFloat10` and `tcuFloat.numberToFloat11`.
> Performing some optimization on tcuFloat.

- sdk/tests/deqp/functional/gles3/es3fShaderCommonFunctionTests.js
C++ code:
https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fShaderCommonFunctionTests.cpp#978
https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fShaderCommonFunctionTests.cpp#1050
> Make real output and ref output in the same type

- sdk/tests/deqp/functional/gles3/es3fShaderCommonFunctionTests.js
This aligns with C++ code.
https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fShaderCommonFunctionTests.cpp#324
> Handle multiple input and output case

- sdk/tests/deqp/framework/common/tcuFloat.js
Allows tests like deqp/functional/gles3/texturefiltering_3d_formats_07.html and friends to go significantly faster. (From around 8 seconds runtime to < 2 seconds on my system.) `tcuFloat.convertFloat32Inline` is a specialization of `tcuFloat.FloatDescription.convert` that takes a floating point number in and returns a number formatted with the description provided. Because we know the input format and don't expect a tcuFloat back out it can run much much faster.
> Optimized tcuFloat.numberToFloat10 and numberToFloat11

- sdk/tests/deqp/framework/common/tcuTexLookupVerifier.js
This cut off 2/3 of running time for tests like deqp/functional/gles3/texturefiltering_3d_formats_29.html
(the test is still too slow and needs further optimization though)
> Optimize some code in tcuTexLookupVerifier.js

- sdk/tests/deqp/framework/common/tcuFuzzyImageCompare.js
This aligns with C++ code:
https://android.googlesource.com/platform/external/deqp/+/master/framework/common/tcuFuzzyImageCompare.cpp#58
https://android.googlesource.com/platform/external/deqp/+/master/framework/common/tcuFuzzyImageCompare.cpp#186
> Round float color to uint8 and clamp it in [0, 255]

- sdk/tests/deqp/functional/gles3/es3fShaderTextureFunctionTests.js
This fixes shadertexturefunction13.html.
C++ code:
https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fShaderTextureFunctionTests.cpp#466
> Correct truncate function

- sdk/tests/deqp/functional/gles3/es3fShaderTextureFunctionTests.js
C++ code:
https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fShaderTextureFunctionTests.cpp#728
> Fix texture initialization for shadertexturefunction05.html

- sdk/tests/deqp/modules/shared/glsBuiltinPrecisionTests.js
Please have a look. Thanks.
I have written a native code to modify the modf() functionality. The result turned out that the int_part of the modf(x) equals to ceil(x) if x is negative.
> Fix the logic error in the js implementation of modf() function

- sdk/tests/deqp/modules/shared/glsTextureTestUtil.js
Align with C++ code. This fixes texturefiltering_cube_formats_04.html.
C++ code:
https://android.googlesource.com/platform/external/deqp/+/master/modules/glshared/glsTextureTestUtil.cpp#2043
> Correct result and reference pixels for cube texture filtering

- sdk/tests/conformance2/renderbuffers/readbuffer.html
- sdk/tests/conformance2/rendering/00_test_list.txt
- sdk/tests/conformance2/rendering/framebuffer-completeness-unaffected.html
Remove that situation from an unrelated test.
> Add a new test for mac driver bug on fbo completeness

- sdk/tests/conformance/extensions/ext-sRGB.html
Please help to review it, thank you. @zhenyao @qkmiao @Richard-Yunchao
> GL_SRGB_EXT format is valid texture internal format

- sdk/tests/deqp/framework/common/tcuTexLookupVerifier.js
- sdk/tests/deqp/framework/common/tcuTexture.js
- sdk/tests/deqp/modules/shared/glsTextureTestUtil.js
With this patch, all texturefiltering_3d_formats/size_* tests passed.
> Fix bugs in dEQP texturefiltering_3d_{formats|size}_* tests

- sdk/tests/deqp/modules/shared/glsFboCompletenessTests.js
- sdk/tests/deqp/modules/shared/glsFboUtil.js
> Correct some case issues in deqp/functional/gles3/fbocompleteness.html

- sdk/tests/deqp/modules/shared/glsBuiltinPrecisionTests.js
> simple implementation of alternative for mix() built-in function

- sdk/tests/deqp/framework/referencerenderer/rrFragmentOperations.js
This part caused a regression in deqp/functional/gles3/fbostencilbuffer.html
> Revert part of https://github.com/KhronosGroup/WebGL/pull/1643

- sdk/tests/deqp/functional/gles3/00_test_list.txt
- sdk/tests/deqp/functional/gles3/shadertexturefunction/00_test_list.txt
- sdk/tests/deqp/functional/gles3/shadertexturefunction/shadertexturefunction00.html
- sdk/tests/deqp/functional/gles3/shadertexturefunction/shadertexturefunction01.html
- sdk/tests/deqp/functional/gles3/shadertexturefunction/shadertexturefunction02.html
- sdk/tests/deqp/functional/gles3/shadertexturefunction/shadertexturefunction03.html
- sdk/tests/deqp/functional/gles3/shadertexturefunction/shadertexturefunction04.html
- sdk/tests/deqp/functional/gles3/shadertexturefunction/shadertexturefunction05.html
- sdk/tests/deqp/functional/gles3/shadertexturefunction/shadertexturefunction06.html
- sdk/tests/deqp/functional/gles3/shadertexturefunction/shadertexturefunction07.html
- sdk/tests/deqp/functional/gles3/shadertexturefunction/shadertexturefunction08.html
- sdk/tests/deqp/functional/gles3/shadertexturefunction/shadertexturefunction09.html
- sdk/tests/deqp/functional/gles3/shadertexturefunction/shadertexturefunction10.html
- sdk/tests/deqp/functional/gles3/shadertexturefunction/shadertexturefunction11.html
- sdk/tests/deqp/functional/gles3/shadertexturefunction/shadertexturefunction12.html
- sdk/tests/deqp/functional/gles3/shadertexturefunction/shadertexturefunction13.html
- sdk/tests/deqp/functional/gles3/shadertexturefunction/shadertexturefunction14.html
- sdk/tests/deqp/functional/gles3/shadertexturefunction/shadertexturefunction_test_generator.py
and auto-genetae the .html files.
> Move shadertexturefunction* tests to its own folder

- specs/latest/2.0/index.html
@kenrussell @jdashg Please review.
> Disallow FLOAT_32_UNSIGNED_INT_24_8_REV in TexSubImage{2|3}D

- sdk/tests/deqp/functional/gles3/es3fFboCompletenessTests.js
- sdk/tests/deqp/modules/shared/glsFboCompletenessTests.js
- sdk/tests/deqp/modules/shared/glsFboUtil.js
> Save Fbo statuses and GL errors in different arrays as native code

- sdk/tests/deqp/functional/gles3/es3fTextureSpecificationTests.js
including:
basic_teximage3d.html
texstorage2d.html
texstorage3d.html
> Make more texturespecification tests pass

- sdk/tests/conformance/state/00_test_list.txt
- sdk/tests/conformance/state/gl-initial-state.html
- sdk/tests/deqp/functional/gles3/es3fIntegerStateQueryTests.js
Make a better version of the fix for the IntegerStateQuery as suggested in https://github.com/KhronosGroup/WebGL/pull/1685
> Better fix for the IntegerStateQuery blendfunc test

- sdk/tests/conformance2/misc/expando-loss-2.html
@kenrussell  please help to review this.
> Add expando loss test for second query object

- sdk/tests/deqp/modules/shared/glsShaderExecUtil.js
This change can fix all failures in outerproduct,html, with some coding style change like indentation. 
PTAL. Thanks.
> Remove redundant array allocation to fix the bugs for outerproduct

- sdk/tests/conformance/context/context-attributes-alpha-depth-stencil-antialias.html
> Some anti-alias algorithms may not effect on diagonal line pixels

- sdk/tests/deqp/functional/gles3/00_test_list.txt
- sdk/tests/deqp/functional/gles3/es3fShaderPrecisionTests.js
- sdk/tests/deqp/functional/gles3/shaderprecision_float.html
- sdk/tests/deqp/functional/gles3/shaderprecision_int.html
- sdk/tests/deqp/functional/gles3/shaderprecision_uint.html
> Split shaderprecision.html into 3 tests

- sdk/tests/deqp/functional/gles3/00_test_list.txt
- sdk/tests/deqp/functional/gles3/es3fShaderLoopTests.js
- sdk/tests/deqp/functional/gles3/shaderloop_do_while.html
- sdk/tests/deqp/functional/gles3/shaderloop_for.html
- sdk/tests/deqp/functional/gles3/shaderloop_while.html
> Split shaderloop.html into 3 tests.

- sdk/tests/deqp/functional/gles3/es3fInstancedRenderingTests.js
With this fix, all tests passed in instancedrendering.html.
> Fix wrong attribute data used in instancedrendering

- sdk/tests/deqp/modules/shared/glsBuiltinPrecisionTests.js
Align the JS code with native C++ code for Div() and Modf(). There is no improvement and no regression for test cases from the test result. 
> update the JS code for Div and Modf

- conformance-suites/1.0.0/conformance/webgl-specific.html
- conformance-suites/1.0.1/conformance/misc/webgl-specific.html
- conformance-suites/1.0.2/conformance/misc/webgl-specific.html
- conformance-suites/1.0.3/conformance/misc/webgl-specific.html
Original pr is at: https://github.com/KhronosGroup/WebGL/pull/1727.
> Backport: Attach buffer to VAO before draw call

- sdk/tests/deqp/functional/gles3/es3fSyncTests.js
It's legal for a sync object to become signaled within a given frame.
Reverify sync status within several frames after gl.finish. See some
discussions in https://github.com/KhronosGroup/WebGL/pull/1506.
> Verify sync status in next several frames

- sdk/tests/deqp/functional/gles3/es3fFboTestCase.js
- sdk/tests/deqp/functional/gles3/fboinvalidate.html
> Fix a bug so all float formats get tested also.

- sdk/tests/deqp/framework/referencerenderer/rrRenderer.js
- sdk/tests/deqp/framework/referencerenderer/rrVertexAttrib.js
- sdk/tests/deqp/functional/gles3/es3fDrawTests.js
- sdk/tests/deqp/modules/shared/glsDrawTests.js
PTAL, this fixes gles3/draw.html
> Fix gles3 draw

- sdk/tests/deqp/framework/opengl/simplereference/sglrReferenceContext.js
If rendering to a target with sRGB format, the pixels should be
converted to sRGB format before setting.
> Fix reference render for sRGB target

- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-webgl-canvas.js
Clean up from https://github.com/KhronosGroup/WebGL/pull/1820
> Clean up some debugging code from last commit.

- sdk/tests/deqp/framework/common/tcuSkipList.js
See https://github.com/KhronosGroup/WebGL/issues/1832
> Skip a bunch of deqp test cases due to R11F_G11F_B10F bug in Mac OSX.

- sdk/tests/conformance/misc/invalid-passed-params.html
- sdk/tests/conformance2/glsl3/shader-with-invalid-characters.html
This fixes comments#11 in https://codereview.chromium.org/2082483002/.
> Add invalid case for line-continuation character

- sdk/tests/conformance2/reading/format-r11f-g11f-b10f.html
See https://github.com/KhronosGroup/WebGL/issues/1832.
> Add a test for format R11F_G11F_B10F.

- sdk/tests/conformance2/reading/format-r11f-g11f-b10f.html
> Set tolerance for format r11f-g11f-b10f to fix bug in format-r11f-g11f-b10f.html.

- sdk/tests/conformance2/glsl3/shader-with-invalid-characters.html
Remove invalid test cases according discussion in
https://github.com/KhronosGroup/WebGL/pull/1836.
> Allow line-continuation character in middle of line

- sdk/tests/conformance2/reading/format-r11f-g11f-b10f.html
@kenrussell Please review
@Richard-Yunchao @qkmiao FYI
> Add testcases for R11F_G11F_B10F to check texture sampling in shaders.

- extensions/WEBGL_draw_buffers/extension.xml
- sdk/tests/conformance/extensions/webgl-draw-buffers.html
- specs/latest/2.0/index.html
Also add a few test cases for that.
> Define a few undefined behaviors related to DrawBuffers.

- sdk/tests/deqp/functional/gles3/00_test_list.txt
@jdashg @kenrussell @Kangz PTAL
> Move builtinprecision/* tests to WebGL 2.0.1.

- specs/latest/2.0/index.html
- specs/latest/2.0/webgl2.idl
Just realized I missed these functions.
@kenrussell PTAL
@jdashg FYI
> Add missing compressedTex{Sub}Image{2|3}D functions.

- specs/latest/2.0/index.html
@kenrussell @jdashg @grorg @RafaelCintron PTAL
Once this is approved, I'll add test cases.
> Clarify a few undefined behaviors in WebGL 2 spec.

- sdk/tests/conformance2/transform_feedback/00_test_list.txt
- sdk/tests/conformance2/transform_feedback/unwritten-output-defaults-to-zero.html
defaults to zero.
Note that this test fails in Linux NVidia with random output values.
This is WebGL2 specific behavior.
See https://github.com/KhronosGroup/WebGL/pull/1861
> Add a test to verify that transformfeedback unwritten output

- sdk/tests/deqp/framework/common/tcuSkipList.js
using getSkipsStatus function can skip a list of test cases by testname*
> Add getWildcardSkipStatus function

- extensions/WEBGL_draw_buffers/extension.xml
- specs/latest/1.0/index.html
- specs/latest/2.0/index.html
@kenrussell @grorg @jdashg @RafaelCintron Please take a look.
> Update DrawBuffers related behaviors (regarding unwritten output variables)

- sdk/tests/deqp/data/gles3/shaders/linkage.test
- sdk/tests/deqp/data/gles3/shaders/preprocessor.test
@zhenyao PTAL, this fixes the preprocessor.html Chromium failures as well as part of the linkage tests. (the rest are addressed in the interface blocks CL).
> Update shader tests

- sdk/tests/deqp/functional/gles3/es3fShaderDerivateTests.js
> Fix clear() conflicts with integer format images in shaderderivate.

- sdk/tests/conformance2/rendering/00_test_list.txt
- sdk/tests/conformance2/rendering/clear-func-buffer-type-match.html
compatible with fbo buffer types.
> Add a test verifying clear and clearBuffer* func type should be

- sdk/tests/deqp/functional/gles3/es3fFragmentOutputTests.js
@kenrussell Thank you for noticing this.
@qkmiao FYI.
> Fix a typo from https://github.com/KhronosGroup/WebGL/pull/1893

- sdk/tests/deqp/functional/gles3/es3fInstancedRenderingTests.js
> Deinit vertex attrib array state in InstancedRenderingCase

- sdk/tests/conformance2/rendering/00_test_list.txt
- sdk/tests/conformance2/rendering/uniform-block-buffer-size.html
- specs/latest/2.0/index.html
This is another undefined behavior in ES3
Also add a test to make sure the WebGL2 behavior.
> Spec uniform block data source large enough issue

- specs/latest/2.0/index.html
1) clarify drawRangeELements behavior
2) consolidate draw call extra constraints into one place
3) Remove duplicated UniformBlock data backing constaint.
> Update a few items in the spec.

- sdk/tests/conformance2/rendering/framebuffer-unsupported.html
@zhenyao Please review. This adds tests as your comments in https://codereview.chromium.org/2159183002/#msg5.
> Add tests for CUBE and 3D texture in framebuffer-unsupported.html

- sdk/tests/conformance2/textures/misc/00_test_list.txt
- sdk/tests/conformance2/textures/misc/copy-texture-image-webgl-specific.html
gl.INVALID_OPRATION is generated if the source and destination textures are the same.
Valid operation if the layer or level of soure and destination are different.
> Add test cases for function copyTexSubImage3D to detect feedback loop

- specs/latest/2.0/index.html
- specs/latest/2.0/webgl2.idl
Remove old ArrayBufferView requirements.
Remove restriction against D32F_X24_S8 uploads.
> Add ByteBuffer+byteOffset entrypoints for WebGL2.

- sdk/tests/conformance/extensions/ext-disjoint-timer-query.html
This should address the issue that @qkmiao reported in #1969 .
> Fix query availability check in EXT_disjoint_timer_query test.

- sdk/tests/conformance2/buffers/00_test_list.txt
- sdk/tests/conformance2/buffers/buffer-data-and-buffer-sub-data-sub-source.html
@jdashg @kenrussell Please review
> Add test cases for buffer{Sub}Data with ArrayBufferView sub source.

- specs/latest/2.0/index.html
- specs/latest/2.0/webgl2.idl
related with texImage3D taking ArrayBufferView.
> Fix an inconsistency in WebGL2 spec

- extensions/extension.xsl
- extensions/proposals/EXT_clip_cull_distance/extension.xml
This fairly new OpenGL ES 3.0 / WebGL 2.0 extension has already been
requested by a couple of partners.
> Add EXT_clip_cull_distance extension proposal.

- sdk/tests/conformance2/rendering/00_test_list.txt
- sdk/tests/conformance2/rendering/rgb-format-support.html
> Add a test to verify RGB8 renderbuffer/texture works

- sdk/tests/conformance2/misc/expando-loss-2.html
This adds test for expando properties on:
* TEXTURE_BINDING_3D
* TEXTURE_BINDING_2D_ARRAY
* READ_FRAMEBUFFER_BINDING
* draw_framebuffer_binding
* copy_read_buffer_binding
* copy_write_buffer_binding
* pixel_pack_buffer_binding
* pixel_unpack_buffer_binding
* transform_feedback_buffer_binding (single and indexed)
* uniform_buffer_binding (single and indexed)
> Improve test conformance2/misc/expando-loss-2

- sdk/tests/conformance/glsl/bugs/00_test_list.txt
- sdk/tests/conformance/glsl/bugs/nested-sequence-operator.html
Covers https://bugs.chromium.org/p/chromium/issues/detail?id=638313
> Add a test with a tricky nested sequence operator

- sdk/tests/conformance2/textures/misc/00_test_list.txt
- sdk/tests/conformance2/textures/misc/integer-cubemap-specification-order-bug.html
PTAL, this adds a test for the NVIDIA driver bug related to cubemap specification order.
> Conformance test for the nv driver bug

- sdk/tests/conformance2/misc/getextension-while-pbo-bound-stability.html
This is introduced in https://github.com/KhronosGroup/WebGL/pull/1994.
> Fix wrong link which causes timeout

- conformance-suites/1.0.0/conformance/object-deletion-behaviour.html
- conformance-suites/1.0.1/conformance/misc/object-deletion-behaviour.html
- conformance-suites/1.0.2/conformance/misc/object-deletion-behaviour.html
- conformance-suites/1.0.3/conformance/misc/object-deletion-behaviour.html
- sdk/tests/conformance/misc/object-deletion-behaviour.html
- specs/latest/1.0/index.html
- specs/latest/2.0/index.html
> Yield an INVALID_OPERATION error when trying to bind a deleted object

- sdk/tests/conformance/glsl/bugs/00_test_list.txt
- sdk/tests/conformance/glsl/bugs/bool-to-int.html
It is not working properly on Mac AMD drivers.
> Add a test to verify int(bool) works correctly.

- sdk/tests/conformance2/rendering/00_test_list.txt
- sdk/tests/conformance2/rendering/blitframebuffer-outside-readbuffer.html
PTAL. Thanks!
https://github.com/KhronosGroup/WebGL/pull/2010 is not correct.
> Test blitframebuffer when bliting pixels outside of read framebuffer

- sdk/tests/conformance2/rendering/blitframebuffer-outside-readbuffer.html
PTAL. @zhenyao  and @kenrussell
> The src region and/or dst region may be reversed during bliting, add tests to cover this feature

- sdk/tests/conformance2/rendering/00_test_list.txt
- sdk/tests/conformance2/rendering/instanced-rendering-bug.html
- sdk/tests/deqp/framework/common/tcuSkipList.js
Skip the failing test cases in instancedrendering.html
(because it is seperated into a single test and pushed to 2.0.1)
> Add a test to verify the instanced rendering bug on MacAMD.

- sdk/tests/conformance2/reading/00_test_list.txt
- sdk/tests/conformance2/reading/read-pixels-from-rgb8-into-pbo-bug.html
- sdk/tests/deqp/framework/common/tcuSkipList.js
Also, skip the two related failing cases from pixelbufferobject.html.
> Add a test to catch the Mac AMD readPixels from RGB buffer into PBO bug

- sdk/tests/conformance/glsl/bugs/bool-type-cast-bug-int-float.html
Related to http://crbug.com/643866 .
> Expand the tests for conversions from bool values.

- sdk/tests/conformance/misc/object-deletion-behaviour.html
- sdk/tests/conformance2/misc/00_test_list.txt
- sdk/tests/conformance2/misc/object-deletion-behaviour-2.html
Add cases on bindBufferBase and bindBufferRange to object-deletion-behaviour.html
> Add missing bind* tests to object-deletion-behaviour.html

- sdk/tests/conformance2/rendering/blitframebuffer-multisampled-readbuffer.html
@kenrussell , per your suggestions at https://github.com/KhronosGroup/WebGL/pull/2034, this small change use functions in WebGLTestUtils to simplify the test. PTAL. Thanks a lot!
> Use existed function in wtu js library to simplify the test

- extensions/WEBGL_compressed_texture_es3_0/extension.xml
- sdk/tests/conformance2/rendering/00_test_list.txt
- sdk/tests/conformance2/rendering/blitframebuffer-multisampled-readbuffer.html
- sdk/tests/conformance2/rendering/blitframebuffer-srgb-and-linear-drawbuffers.html
- sdk/tests/conformance2/rendering/blitframebuffer-stencil-only.html
- sdk/tests/conformance2/rendering/blitframebuffer-test.html
- sdk/tests/deqp/framework/common/tcuSkipList.js
- sdk/tests/deqp/functional/gles3/es3fIntegerStateQueryTests.js
- sdk/tests/deqp/functional/gles3/es3fMultisampleTests.js
- sdk/tests/deqp/functional/gles3/es3fPixelBufferObjectTest.js
- sdk/tests/js/webgl-test-utils.js
@kenrussell , PTAL. Thanks a lot!
Add conformance test for this TODO: https://cs.chromium.org/chromium/src/gpu/command_buffer/service/gles2_cmd_decoder.cc?q=gles2_cmd_decoder&sq=package:chromium&l=7734.
> Add test cases to verify blitFramebuffer with multiple drawbuffers

- specs/latest/2.0/index.html
> Clean up some text that's outdated in copyBufferSubData.

- sdk/tests/conformance2/rendering/blitframebuffer-filter-outofbounds.html
Sorry, stay too late yesterday... 
PTAL. Thanks! @zhenyao , @kenrussell .
> Fix bugs in blitFramebuffer-filter-outofbounds.html

- sdk/tests/conformance2/transform_feedback/00_test_list.txt
- sdk/tests/conformance2/transform_feedback/two-unreferenced-varyings.html
See http://crbug.com/651493
PTAL @kenrussell @zhenyao
> Add a test to cover an unreferenced varyings bug in ANGLE.

- sdk/tests/conformance2/buffers/getBufferSubData.html
- specs/latest/2.0/index.html
> clarify and test corner cases of getBufferSubData

- sdk/tests/conformance/buffers/00_test_list.txt
> Add a test to 00_test_list.txt

- sdk/tests/conformance/buffers/buffer-uninitialized.html
@zhenyao does this cover the case you mentioned?
I also repeated the test 50 times, because when I came in this morning the test was flaky on my machine.
> buffer-uninitialized: repeat 50 times, and test bufferSubData

- sdk/tests/conformance2/buffers/get-buffer-sub-data.html
- sdk/tests/conformance2/transform_feedback/transform_feedback.html
This error case from the spec was previously untested.
@zhenyao yet another PR for you to review :)
> add test for getBufferSubData when transform feedback is active

- sdk/tests/conformance2/extensions/00_test_list.txt
- sdk/tests/conformance2/extensions/ext-disjoint-timer-query-webgl2.html
> Test EXT_disjoint_timer_query_webgl2

- sdk/tests/conformance2/transform_feedback/transform_feedback.html
1) getBufferSubData params are wrong
2) The last two test are async, so we need to run all the sync tests first
> Fix a bug in transform_feedback.html

- sdk/tests/conformance2/00_test_list.txt
- sdk/tests/conformance2/sync/00_test_list.txt
- sdk/tests/conformance2/sync/sync-webgl-specific.html
@kenrussell @kainino0x @jdashg PTAL
> Add a test to verify WebGL2 specific sync object behaviors

- sdk/tests/deqp/functional/gles3/es3fSyncTests.js
@kenrussell @jdashg @kainino0x PTAL
> Fix sync.html according to WebGL2 rules.

- sdk/tests/deqp/functional/gles3/es3fNegativeFragmentApiTests.js
> Use timeout=0 for clientWaitSync

- sdk/tests/conformance2/rendering/00_test_list.txt
- sdk/tests/conformance2/rendering/rendering-sampling-feedback-loop.html
PTAL. @zhenyao  and @kenrussell. Thanks a lot!
> Detecte feedback loop between sampling textures and drawing framebuffer attachments

- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image.js
Verified against Chromium's implementation in https://codereview.chromium.org/2458943002 .
> Add tests for uploading sub-rectangles of HTMLImageElements.

- specs/latest/1.0/index.html
- specs/latest/1.0/webgl.idl
- specs/latest/2.0/index.html
- specs/latest/2.0/webgl2.idl
This does not include test updates yet.
> Non nullable

- specs/latest/1.0/index.html
- specs/latest/1.0/webgl.idl
- specs/latest/2.0/index.html
- specs/latest/2.0/webgl2.idl
due to overload conflicts.
See discussions in https://github.com/KhronosGroup/WebGL/pull/2099
> bufferData can't take non-nullable ArrayBuffer{View} arg

- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-data.js
- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image.js
Verified against Chromium's implementation in https://codereview.chromium.org/2489203002
> add tests for upload sub-rectangles of ImageData

- sdk/tests/conformance/extensions/webgl-compressed-texture-s3tc.html
texStorage(compressed_format)
texSubImage(compressed_format)
> Add test cases to catch a chrome bug in the following path

- extensions/EXT_disjoint_timer_query/extension.xml
- sdk/tests/conformance/extensions/ext-disjoint-timer-query.html
- sdk/tests/conformance/extensions/webgl-debug-shaders.html
- sdk/tests/conformance2/extensions/ext-disjoint-timer-query-webgl2.html
@kenrussell @jdashg @grorg @RafaelCintron @kainino0x 
forgot to update extension behaviors.
> Make WebGLObject args non nullable in extensions.

- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-video.js
- sdk/tests/js/tests/tex-image-and-sub-image-3d-with-video.js
@kenrussell @zhenyao @jdashg 
These do NOT conform with the changes per the discussion we had today. Those changes will probably be made wholesale throughout the tests at once.
> test tex(Sub)Image2D/3D with HTMLVideoElement

- conformance-suites/1.0.2/conformance/uniforms/gl-uniform-arrays.html
- conformance-suites/1.0.3/conformance/uniforms/gl-uniform-arrays.html
- sdk/tests/conformance/uniforms/gl-uniform-arrays.html
The variable "positionLoc" is undefined. Chrome (and other browsers) doesn't report error because a variable with exactly the same name is defined in the following code by chance. 
PTAL when you have time.
> Fix gl uniform arrays

- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-data.js
Verified against Chrome on MacBook Air, Intel HD 4000, OS X 10.11.4.
> Work around #1819 in conformance2/textures/image_data/tex-2d-*_integer-unsigned_byte.html

- sdk/tests/js/tests/tex-image-and-sub-image-with-image-bitmap-utils.js
@kenrussell @kainino0x @jdashg
> Add sub source test cases for texture uploading from ImageBitmap

- specs/latest/1.0/index.html
- specs/latest/2.0/index.html
> Add links to Github repo and issue tracker.

- specs/latest/2.0/index.html
Follow-on pull request to #2179.
> Fix feedback from @zhenyao and @bzbarsky on buffer{Sub}Data overloads.

- sdk/tests/conformance2/rendering/clear-srgb-color-buffer.html
This should make the test pass on Linux AMD and Intel.
> Add tolerance to pixel comparison in clear-srgb-color-buffer.html

- sdk/tests/conformance2/rendering/depth-stencil-feedback-loop.html
> a small fix to make test clear

- conformance-suites/2.0.0/conformance2/renderbuffers/invalidate-framebuffer.html
- sdk/tests/conformance2/renderbuffers/invalidate-framebuffer.html
GLES 3.0.5 p219-220, plus Table 4.6 on p206.
> COLOR_ATTACHMENT1000 can be either INVALID_ENUM or _OPERATION.

- specs/latest/1.0/index.html
- specs/latest/2.0/index.html
Update the spec per #2137. 
PTAL when you have time. Thanks a lot! @zhenyao and @kenrussell .
> Update the spec to cover the situation when reading from or drawing to a missing attachment

- conformance-suites/2.0.0/conformance/extensions/oes-texture-half-float.html
- sdk/tests/conformance/extensions/oes-texture-half-float.html
- specs/latest/1.0/index.html
Reverts KhronosGroup/WebGL#2195
> Revert "Error for querying FB-dependent limit should error as if asking to re…"

- sdk/tests/conformance2/rendering/read-draw-when-missing-image.html
PTAL. @zhenyao and @kenrussell . Thanks a lot!
> Add some tests for depth/stencil buffer when there is no image attached during blitting

- sdk/tests/conformance2/rendering/read-draw-when-missing-image.html
@zhenyao , PTAL. Thanks a lot! 
A small change to expose a bug in Chromium. See the fix at https://codereview.chromium.org/2588653002/
> Add some tests when fbo miss image

- sdk/tests/conformance2/rendering/blitframebuffer-size-overflow.html
Please take a look. Thanks a lot!
> Fix a typo in test, and deinit resources

- specs/2.0.0/index.html
- specs/latest/2.0/index.html
I think we already have tests in this, and the language was meant for this but
ended up narrower than intended.
> Clarify an undefined behavior related with MRT in WebGL2.

- sdk/tests/conformance2/rendering/00_test_list.txt
- sdk/tests/conformance2/rendering/draw-buffers-dirty-state-bug.html
See crbug.com/678153
This test fails without https://codereview.chromium.org/2611403002/, and passes with it.
> Add a test for a chrome bug related with draw buffers dirty state.

- sdk/tests/conformance2/programs/00_test_list.txt
- sdk/tests/conformance2/programs/sampler-uniforms.html
@kenrussell @kainino0x Please review
@greggman FYI
> Test getUniform with ES3 sampler types.

- conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-with-image-bitmap-utils.js
- sdk/tests/js/tests/tex-image-and-sub-image-with-image-bitmap-utils.js
PTAL. Thanks!
@zhenyao , @kenrussell , @jdashg . Please see my comment at https://github.com/KhronosGroup/WebGL/pull/2224/files
> fix a bug in image_bitmap related tests

- sdk/tests/conformance2/textures/misc/npot-video-sizing.html
Just a typo, but make the test fail. 
PTAL. @kenrussell , @zhenyao .
> Fix in npot-video-sizing.html

- conformance-suites/2.0.0/conformance/extensions/webgl-compressed-texture-etc.html
- sdk/tests/conformance/extensions/webgl-compressed-texture-etc.html
@kenrussell , @zhenyao , @jdashg , PTAL. 
FYI, @qkmiao 
Please see my comment at https://github.com/KhronosGroup/WebGL/pull/2210/files.
> Fix bug in webgl-compressed-texture-etc.html

- extensions/proposals/OES_EGL_image_external/extension.xml
* Add VideoFrameInfo interface and function to return it.
> Add OES_EGL_image_external extension

- sdk/tests/conformance2/glsl3/vector-dynamic-indexing.html
This is a repro case for the following ANGLE bug:
https://bugs.chromium.org/p/angleproject/issues/detail?id=1672
> Add a l-value nested dynamic indexing test

- sdk/tests/conformance2/uniforms/00_test_list.txt
- sdk/tests/conformance2/uniforms/gl-uniform-arrays-sub-source.html
Tested with Firefox and all test cases pass.
> Add a test for gl.uniform*() with optional args: srcOffset / srcLength.

- extensions/WEBGL_lose_context/extension.xml
> Document that WEBGL_lose_context extension should destroy graphics

- sdk/tests/conformance2/uniforms/gl-uniform-arrays-sub-source.html
Pure refactoring, no logic changing
> Simplify a test by consilidating two test paths.

- conformance-suites/2.0.0/conformance/glsl/bugs/sampler-struct-function-arg.html
- conformance-suites/2.0.0/conformance/glsl/bugs/sequence-operator-evaluation-order.html
- conformance-suites/2.0.0/conformance2/glsl3/array-in-complex-expression.html
- conformance-suites/2.0.0/conformance2/glsl3/compare-structs-containing-arrays.html
- conformance-suites/2.0.0/conformance2/glsl3/short-circuiting-in-loop-condition.html
- conformance-suites/2.0.0/conformance2/glsl3/vector-dynamic-indexing.html
- conformance-suites/2.0.0/conformance2/rendering/blitframebuffer-filter-outofbounds.html
- conformance-suites/2.0.0/conformance2/rendering/uniform-block-buffer-size.html
- conformance-suites/2.0.0/deqp/framework/common/tcuSkipList.js
I'll be updating all of the crbug links to point at specific bugs.
> 2.0.0: disable tests failing on Pixel in Chrome+FF

- specs/latest/1.0/index.html
> Specify current tested behavior on drawElement offset < 0

- specs/2.0.0/index.html
- specs/latest/2.0/index.html
Use latest/1.0 instead of 1.0.2
> Fix latest/2.0 spec link to 1.0.

- sdk/tests/conformance2/glsl3/tricky-loop-conditions.html
Correct sideEffectCounter = 3 to sideEffectCounter == 3 in
tricky-loop-conditions.html
> Fixed a typo error

- specs/latest/1.0/index.html
- specs/latest/1.0/webgl.idl
> Fix escaping of angle brackets in sequence definitions.

- sdk/tests/conformance2/rendering/00_test_list.txt
- sdk/tests/conformance2/rendering/clearbuffer-sub-source.html
Surprisingly this is not tested, so here you are!
> Add a test for sub source clearBuffer*().

- sdk/tests/conformance/glsl/misc/uninitialized-local-global-variables.html
(Addition to #2366.) Also corrects the expected result (should be [0,0,0,0], not [0,0,0,255]).
> Test more types of uninitialized local/global variable

- sdk/tests/conformance2/textures/misc/tex-image-with-bad-args.html
See https://crrev.com/2767063002/#msg48
> Verify that EXT_texture_norm16 enums are not supported.

- sdk/tests/conformance2/buffers/uniform-buffers-second-compile.html
Regression test for http://crbug.com/716018
> Regression test for cached-load of programs w/ uniform blocks

- sdk/tests/conformance2/buffers/00_test_list.txt
- sdk/tests/conformance2/buffers/uniform-buffers-state-restoration.html
Regression test for http://crbug.com/722060 , already passes in Firefox.
Also adds the test from #2388 into 00_test_list.txt.
> Add a test for uniform buffer restoration across frames.

- sdk/tests/conformance/state/gl-enable-enum-test.html
- specs/latest/1.0/index.html
* Spec update
* Add tests verifying getParameter works like isEnabled
* Test enable queries (via isEnabled and getParameter) for multiple sets of context creation attributes
Fixes #2384
> Allow all isEnabled queries in getParameter

- sdk/demos/webkit/resources/J3DIMath.js
Fixes #2408. Thanks @kg1992 for pointing out the error.
> Fix computation of yz in J3DIMatrix4.prototype.lookat.

- sdk/tests/conformance/renderbuffers/framebuffer-object-attachment.html
- sdk/tests/conformance2/renderbuffers/framebuffer-object-attachment.html
- specs/latest/2.0/index.html
and also add test cases for this difference
> Add a WebGL 1.0/2.0 difference in getFramebufferAttachmentParameter

- sdk/tests/conformance/glsl/misc/00_test_list.txt
- sdk/tests/conformance/glsl/misc/local-variable-shadowing-outer-function.html
Regression test for:
https://bugs.chromium.org/p/angleproject/issues/detail?id=2095
> Add test where local variable shadows outer function definition.

- sdk/tests/conformance/rendering/texture-switch-performance.html
- sdk/tests/conformance2/rendering/texture-switch-performance.html
> Fixed copyright dates on texture switching tests

- sdk/tests/conformance/glsl/bugs/sampler-struct-function-arg.html
This exposes a bug in ANGLE's HLSL translator.
ANGLE bug link: http://anglebug.com/2103
> Add a test for an array of structs containing samplers as function arg

- sdk/tests/conformance2/00_test_list.txt
- sdk/tests/conformance2/canvas/00_test_list.txt
- sdk/tests/conformance2/canvas/to-data-url-with-pack-params.html
> Add a regression test for crbug.com/740603

- sdk/tests/js/tests/texture-corner-case-videos.js
This change will expose bug http://crbug.com/733172.
> Expose TexSubImage2D bad dimensions bug

- sdk/tests/conformance/glsl/bugs/00_test_list.txt
- sdk/tests/conformance/glsl/bugs/sampler-array-struct-function-arg.html
- sdk/tests/conformance/glsl/bugs/sampler-struct-function-arg.html
This is broken on ANGLE's HLSL backend.
Includes some cleanup in an older similar test.
> Test passing a sampler array in a struct to a function

- conformance-suites/2.0.0/deqp/framework/common/tcuSkipList.js
> Edit comment for dfdy tests in tcuSkipList

- sdk/tests/conformance/textures/misc/texture-size.html
Saw a flake of this form on a MacBook Pro with AMD GPU:
https://luci-milo.appspot.com/buildbot/tryserver.chromium.mac/mac_chromium_rel_ng/531253
> Add tolerance of 1 to texture-size test.

- sdk/tests/conformance2/transform_feedback/00_test_list.txt
- sdk/tests/conformance2/transform_feedback/non-existent-varying.html
This covers the following ANGLE bug:
https://bugs.chromium.org/p/angleproject/issues/detail?id=2141
> Add a test for non-existent transform feedback varyings

- sdk/tests/deqp/framework/common/tcuFloat.js
- sdk/tests/deqp/framework/delibs/debase/deMath.js
- sdk/tests/deqp/functional/gles3/es3fShaderPrecisionTests.js
Reverts KhronosGroup/WebGL#2501
I want to reland this as two commits.
> Revert "Fixes for dEQP shader.precision.float.mediump_add_fragment"

- sdk/tests/deqp/framework/common/tcuFloat.js
- sdk/tests/deqp/framework/delibs/debase/deMath.js
- sdk/tests/deqp/functional/gles3/es3fShaderPrecisionTests.js
> Fixes for dEQP shader.precision.float.mediump_add_fragment

- sdk/tests/conformance2/rendering/00_test_list.txt
- sdk/tests/conformance2/rendering/clearbufferfv-with-alpha-false.html
Regression test for http://crbug.com/765729 .
> Test for clearBufferfv against back buffer of alpha:false canvas.

- sdk/tests/conformance2/renderbuffers/multisampled-depth-renderbuffer-initialization.html
Small fixes, follow up to #2418
> Improve/fix comments in multisampled-depth-renderbuffer-initialization

- extensions/EXT_color_buffer_half_float/extension.xml
- extensions/OES_texture_float/extension.xml
- extensions/OES_texture_half_float/extension.xml
- extensions/WEBGL_color_buffer_float/extension.xml
- sdk/tests/conformance/extensions/oes-texture-float.html
- sdk/tests/conformance/extensions/oes-texture-half-float.html
> Clarify WebGL1 float color buffer extensions behaviors

- extensions/EXT_color_buffer_half_float/extension.xml
> Fix a typo in extension spec.

- extensions/EXT_color_buffer_half_float/extension.xml
> Improve EXT_color_buffer_half_float extension spec.

- specs/2.0.0/index.html
- specs/latest/2.0/index.html
This is addressing https://github.com/KhronosGroup/WebGL/issues/2516
> Fix a note related with TIMEOUT_IGNORED in WebGL2 spec.

- sdk/tests/conformance2/rendering/blitframebuffer-test.html
Test case for crbug.com/768969 .
> Add test case performing repeated blitFramebuffer calls without clears.

- sdk/tests/conformance2/glsl3/00_test_list.txt
- sdk/tests/conformance2/glsl3/switch-case.html
This test case covers some bugs in ANGLE's HLSL translation.
> Add a test for switch/case corner cases

- sdk/tests/conformance/glsl/bugs/00_test_list.txt
- sdk/tests/conformance/glsl/bugs/vector-scalar-arithmetic-inside-loop.html
This exposes a bug in the NVIDIA GL driver.
> Add test for vector/scalar arithmetic inside a for loop

- sdk/tests/conformance2/glsl3/switch-case.html
These tests expose bugs in ANGLE, most of which have been already
fixed in ANGLE TOT.
> Add tests for switch/case validation corner cases

- sdk/tests/conformance/rendering/00_test_list.txt
- sdk/tests/conformance/rendering/preservedrawingbuffer-leak.html
- sdk/tests/js/tests/iterable-test.js
This test provoks a crash on Samsung Galaxy S6 devices running Android 6.0.1. Other devices seem to handle it fine.
> Added a test to ensure preserveDrawingBuffer isn't leaking resources

- sdk/tests/conformance2/glsl3/00_test_list.txt
- sdk/tests/conformance2/glsl3/varying-struct-inline-definition.html
This test exposes a bug that was recently fixed in ANGLE.
> Add a test for varying struct with an inline definition

- sdk/tests/conformance/rendering/00_test_list.txt
- sdk/tests/conformance/rendering/scissor-rect-repeated-rendering.html
Regression test for http://crbug.com/778770 .
> Add test for scissor rectangle maintenance bug during implicit clears.

- sdk/tests/conformance/canvas/render-after-resize-test.html
- sdk/tests/js/webgl-test-utils.js
Fix latent bug in wtu.setupSimpleColorProgram. Fix copyright date.
Follow-on to #2543.
Acts as regression test for http://crbug.com/775202 .
> Simplify test: eliminate 2D canvas, draw triangles instead of point.

- sdk/tests/conformance/glsl/bugs/00_test_list.txt
- sdk/tests/conformance/glsl/bugs/init-array-with-loop.html
This attempts to reproduce a driver bug seen on Adreno 418.
> Add test that initializes an array inside a loop

- sdk/tests/conformance/canvas/render-after-resize-test.html
> Fix fencepost errors covered up by wtu.checkCanvasRect.

- sdk/tests/conformance2/renderbuffers/multisampled-depth-renderbuffer-initialization.html
> clarify "clip z" in multisampled-depth-renderbuffer-initialization.html

- sdk/tests/conformance/renderbuffers/00_test_list.txt
- sdk/tests/conformance/renderbuffers/depth-renderbuffer-initialization.html
- sdk/tests/conformance/renderbuffers/stencil-renderbuffer-initialization.html
- sdk/tests/conformance2/renderbuffers/00_test_list.txt
- sdk/tests/conformance2/renderbuffers/multisampled-depth-renderbuffer-initialization.html
- sdk/tests/conformance2/renderbuffers/multisampled-stencil-renderbuffer-initialization.html
Both multisampled for WebGL 2.0 and non-multisampled for WebGL 1.0.
> More depth/stencil renderbuffer initialization tests

- sdk/tests/conformance2/textures/misc/00_test_list.txt
- sdk/tests/conformance2/textures/misc/tex-unpack-params-with-flip-y-and-premultiply-alpha.html
- specs/latest/2.0/index.html
> Add a test for FLIP_Y and PREMULTIPLY_ALPHA behaviors in WebGL2.

- conformance-suites/1.0.1/conformance/textures/tex-input-validation.html
- conformance-suites/1.0.2/conformance/textures/tex-input-validation.html
- conformance-suites/1.0.3/conformance/textures/tex-input-validation.html
- conformance-suites/2.0.0/js/tests/tex-input-validation.js
- sdk/tests/js/tests/tex-input-validation.js
These tests should also accept INVALID_OPERATION for the same reason we discussed in https://github.com/KhronosGroup/WebGL/pull/2550
> Tests should accept multiple valid error conditions

- sdk/tests/conformance2/uniforms/00_test_list.txt
- sdk/tests/conformance2/uniforms/draw-with-uniform-blocks.html
@kainino0x @kenrussell @jdashg PTAL
@jdarpinian FYI
> Add a regression test for ANGLE bug (crbug.com/793307).

- conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-blob.js
- conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-blob.js
- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-blob.js
- sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-blob.js
Possible cause of http://crbug.com/795945 .
> Fix possible race condition in image-bitmap-from-blob tests.

- sdk/tests/conformance2/rendering/00_test_list.txt
- sdk/tests/conformance2/rendering/framebuffer-texture-changing-base-level.html
This exposes a bug in ANGLE's D3D backend.
http://anglebug.com/2291
> Add a test for framebuffer tex attachment with changing base level.

- sdk/tests/conformance2/uniforms/00_test_list.txt
- sdk/tests/conformance2/uniforms/incompatible-texture-type-for-sampler.html
See #2585
note: shadow sampler types are not tested here.
they probably need a separate test as they have
more requirements related to texture parameters
> add test for incompatible texture types for samplers

- sdk/tests/conformance2/transform_feedback/switching-objects.html
> Explanatory comment for transform feedback buffer ownership change.

- sdk/tests/conformance/extensions/webgl-depth-texture.html
Add a test for UNPACK_FLIP_Y_WEBGL = true for the depth textures extension.
> Add UNPACK_FLIP_Y_WEBGL test for depth textures

- README.md
I'm just getting ready to try digest everything I can about using webGL and thought I'd make a small contribution if its welcome.
Thank you for your work and making this available.
> Light amendment of http to https in the readme

- sdk/tests/conformance2/textures/misc/00_test_list.txt
- sdk/tests/conformance2/textures/misc/tex-unpack-params-imagedata.html
Regression test for https://crbug.com/804123
This is a pretty minimal test covering the case we saw - it certainly could be expanded.
>  Add a test for texImage3D from ImageData with unpack params

- sdk/tests/conformance2/extensions/00_test_list.txt
See #2653.
I missed these in the previous PR.
> Remove getBufferSubDataAsync tests from 00_test_list.txt

- sdk/tests/conformance/glsl/bugs/00_test_list.txt
- sdk/tests/conformance/glsl/bugs/struct-with-single-member-constructor.html
This is a regression test for a Swiftshader bug.
> Test constructing a struct with a single member

- sdk/tests/conformance2/textures/misc/00_test_list.txt
- sdk/tests/conformance2/textures/misc/tex-subimage3d-canvas-bug.html
> Add a regression test for crbug.com/859400

- sdk/tests/extra/workload-simulator.html
This demonstrates the performance benefits from using WEBGL_multiview.
> Add WEBGL_multiview support to workload simulator

- sdk/tests/extra/texture-from-camera-stress.html
This will be used as a perf test for Chrome.
> Add stress test for camera-to-texture upload

- sdk/tests/conformance2/glsl3/00_test_list.txt
- sdk/tests/conformance2/glsl3/const-struct-from-array-as-function-parameter.html
This covers bug http://crbug.com/871434 . The root cause seems to be
in the NVIDIA OpenGL driver.
> Add a test for passing a struct from a const array

- sdk/tests/conformance2/extensions/00_test_list.txt
- sdk/tests/conformance2/extensions/webgl_multiview_depth.html
- sdk/tests/conformance2/extensions/webgl_multiview_transform_feedback.html
- sdk/tests/js/tests/webgl_multiview_util.js
These tests pass on the latest prototype implementation in Chromium.
> Add WEBGL_multiview tests for depth buffer and transform feedback

- sdk/tests/conformance2/context/00_test_list.txt
- sdk/tests/conformance2/context/context-mode.html
This test covers the following HTML spec pull request:
https://github.com/whatwg/html/pull/3971
> Test webgl2 vs. webgl canvas context modes.

- sdk/tests/conformance/textures/misc/00_test_list.txt
- sdk/tests/conformance/textures/misc/canvas-teximage-after-multiple-drawimages.html
Add test case uploading a 2D-rendered canvas which has had a series of
drawImage operations (from both images and other 2D-rendered canvases)
applied to it.
Regression test for http://crbug.com/878545 .
> Add canvas-teximage-after-multiple-drawimages.html test.

- sdk/tests/conformance/more/functions/bufferSubDataBadArgs.html
- sdk/tests/conformance/more/functions/texImage2DBadArgs.html
- sdk/tests/conformance/more/functions/texSubImage2DBadArgs.html
- sdk/tests/conformance/more/util.js
- sdk/tests/conformance/textures/misc/compressed-tex-image.html
- sdk/tests/js/webgl-test-utils.js
There are a couple tests in https://github.com/w3c/web-platform-tests/tree/master/webgl that we should match.
> Integrate tests from web-platform-tests.

- extensions/proposals/EXT_multi_draw_arrays/extension.xml
Upon request from multiple CAD customers.
> Add EXT_multi_draw_arrays extension proposal.

- sdk/tests/conformance/extensions/oes-texture-float-with-video.html
- sdk/tests/conformance/extensions/oes-texture-half-float-with-video.html
- sdk/tests/conformance/more/conformance/quickCheckAPI.js
- sdk/tests/conformance/textures/misc/tex-video-using-tex-unit-non-zero.html
- sdk/tests/conformance/textures/misc/texture-npot-video.html
- sdk/tests/conformance2/textures/misc/npot-video-sizing.html
- sdk/tests/extra/tex-image-with-video-test.js
- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-video.js
- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-video.js
- sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-video.js
- sdk/tests/js/tests/tex-image-and-sub-image-3d-with-video.js
- sdk/tests/js/tests/texture-corner-case-videos.js
- sdk/tests/js/webgl-test-utils.js
Just ran into this while debugging some tests.
Autoplay policy explainer: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
> Mute all videos so they don't get blocked by autoplay policy.

- sdk/tests/conformance/extensions/oes-vertex-array-object.html
- sdk/tests/conformance2/vertex_arrays/vertex-array-object.html
Test that isBuffer always returns false after deletion.
> Follow up fixes for lifetime changes from #2731.

- sdk/tests/conformance/rendering/draw-webgl-to-canvas-2d-repeatedly.html
> Clean up unused variable.

- sdk/tests/conformance/rendering/draw-webgl-to-canvas-2d-repeatedly.html
Another small follow-on to #2741 .
> Clear background of 2D canvas as originally intended.

- sdk/tests/performance/parallel_shader_compile/index.html
- sdk/tests/performance/parallel_shader_compile/shaders/aquarium/README
- sdk/tests/performance/parallel_shader_compile/shaders/aquarium/shader-cache.txt
Chromium bug: http://crbug.com/849576
> Add KHR_parallel_shader_compile benchmark

- specs/latest/1.0/webgl.idl
Neglected to do this in #2699.
> Re-run IDL generator after OffscreenCanvas changes.

- extensions/proposals/EXT_draw_buffers_indexed/extension.xml
> First draft of EXT_draw_buffers_indexed

- extensions/proposals/WEBGL_blend_equation_advanced_coherent/extension.xml
> Fix typo in WEBGL_blend_equation_advanced_coherent

- extensions/proposals/EXT_draw_buffers_indexed/extension.xml
#2777 had an error in XML. This PR fixes that.
/cc @jdashg
> Fix XML error in EXT_draw_buffers_indexed

- extensions/proposals/EXT_draw_buffers_indexed/extension.xml
Finally, it builds. Sorry for not checking these errors before.
/cc @jdashg
> Fix yet another XML error in EXT_draw_buffers_indexed

- extensions/proposals/EXT_draw_buffers_indexed/extension.xml
Described `isEnablediEXT` behavior.
> Revision 2 of EXT_draw_buffers_indexed

- extensions/EXT_float_blend/extension.xml
- sdk/tests/conformance/extensions/oes-texture-float.html
- sdk/tests/conformance2/extensions/00_test_list.txt
- sdk/tests/conformance2/extensions/ext-float-blend.html
- sdk/tests/js/tests/ext-float-blend.js
Also test that float32 blending is forbidden without EXT_float_blend.
> Add basic test for EXT_float_blend.

- sdk/tests/conformance2/textures/misc/tex-unpack-params-imagedata.html
Follow-up to https://github.com/KhronosGroup/WebGL/pull/2646
> Add correctness tests to tex-unpack-params-imagedata.html

- conformance-suites/2.0.0/deqp/framework/common/tcuTestCase.js
- conformance-suites/2.0.0/deqp/functional/gles3/es3fShaderOperatorTests.js
- conformance-suites/2.0.0/deqp/functional/gles3/es3fShaderTextureFunctionTests.js
- conformance-suites/2.0.0/deqp/functional/gles3/es3fTextureFilteringTests.js
- sdk/tests/deqp/framework/common/tcuTestCase.js
- sdk/tests/deqp/functional/gles3/es3fShaderOperatorTests.js
- sdk/tests/deqp/functional/gles3/es3fShaderTextureFunctionTests.js
- sdk/tests/deqp/functional/gles3/es3fTextureFilteringTests.js
Also spew time elapsed when finishTest() is called from deqp if not in
quiet mode.
> Add quick mode support to more tests.

- sdk/tests/conformance2/transform_feedback/00_test_list.txt
- sdk/tests/conformance2/transform_feedback/default_transform_feedback.html
> Add default transform feedback object test

- sdk/tests/conformance2/rendering/00_test_list.txt
- sdk/tests/conformance2/rendering/vertex-id.html
- sdk/tests/js/webgl-test-utils.js
In response to #2770, tests drawArrays, drawElements, and drawArrays+transform-feedback.
> Add test for gl_VertexID.

- specs/latest/2.0-compute/Makefile
- specs/latest/2.0-compute/index.bs
@kenrussell , this is a very initial version about WebGL 2.0 compute specification via bikeshed. PTAL from a high level perspective if you have time. Meanwhile, I will continue polishing the detailed text of this spec these days. 
FYI. @gyagp , @qjia7
> Add specification for WebGL 2.0 compute

- specs/latest/1.0/index.html
seems like this example should use webgl?
> experimental-webgl to webgl

- sdk/tests/conformance/attribs/00_test_list.txt
- sdk/tests/conformance/attribs/gl-vertex-attrib-context-switch.html
See http://crbug.com/920033 for rationale for this test.
> Test that vertex attribute is preserved across context switches

- sdk/tests/conformance/textures/misc/texture-size-limit.html
- sdk/tests/js/tests/iterable-test.js
- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-canvas.js
- sdk/tests/js/tests/tex-image-and-sub-image-2d-with-webgl-canvas.js
- sdk/tests/js/tests/webgl-compressed-texture-size-limit.js
- sdk/tests/js/webgl-test-utils.js
- sdk/tests/test-guidelines.md
Makes it really easy to write code like:
```
async function Test() {
for (const x of TEST_ARGS) {
await wtu.dispatchPromise(() => {
TestOnce(x);
});
}
finishTest();
}
Test();
```
> Replace dispatchTask with awaitable dispatchPromise.

- sdk/demos/intel/fluid/LICENSE
- sdk/demos/intel/fluid/README.md
- sdk/demos/intel/fluid/demo.js
- sdk/demos/intel/fluid/index.html
- sdk/demos/intel/fluid/shaders/shader.frag
- sdk/demos/intel/fluid/shaders/shader.vert
- sdk/demos/intel/fluid/shaders/shaderBitonicSort.comp
- sdk/demos/intel/fluid/shaders/shaderBuildGrid.comp
- sdk/demos/intel/fluid/shaders/shaderBuildGridIndices.comp
- sdk/demos/intel/fluid/shaders/shaderClearGridIndices.comp
- sdk/demos/intel/fluid/shaders/shaderDensityGrid.comp
- sdk/demos/intel/fluid/shaders/shaderDensityShared.comp
- sdk/demos/intel/fluid/shaders/shaderDensitySimple.comp
- sdk/demos/intel/fluid/shaders/shaderForceGrid.comp
- sdk/demos/intel/fluid/shaders/shaderForceShared.comp
- sdk/demos/intel/fluid/shaders/shaderForceSimple.comp
- sdk/demos/intel/fluid/shaders/shaderIntegrate.comp
- sdk/demos/intel/fluid/shaders/shaderIntegrateGrid.comp
- sdk/demos/intel/fluid/shaders/shaderRearrange.comp
- sdk/demos/intel/fluid/shaders/shaderTranspose.comp
This example is ported from
https://github.com/walbourn/directx-sdk-samples/tree/master/FluidCS11.
Try this example using latest chrome canary with below commands:
Chrome.exe --use-cmd-decoder=passthrough --enable-webgl2-compute-context --use-gl=angle
> Add Fluid example

- sdk/tests/conformance/rendering/00_test_list.txt
- sdk/tests/conformance/rendering/blending.html
- sdk/tests/js/js-test-pre.js
- sdk/tests/js/webgl-test-utils.js
Also:
* Add wtu.destroyContext and wtu.destroyAllContexts to facilitate
cleanup.
* Add maxArrayDiff and expectArray.
> Add conformance/rendering/blending.html.

- extensions/OVR_multiview2/extension.xml
Also wrap this super long line.
> Add rationale for baseViewIndex matching requirement.

- extensions/OVR_multiview2/extension.xml
> Fix markup in OVR_multiview2.

- extensions/KHR_parallel_shader_compile/extension.xml
Include more example code for best-practices.
> Clarify behavior of KHR_parallel_shader_compile.

- specs/latest/1.0/index.html
- specs/latest/1.0/webgl.idl
- specs/latest/2.0/index.html
- specs/latest/2.0/webgl2.idl
> Add missing semicolons

- .travis.yml
- sdk/tests/py/lint/lint.py
- specs/latest/1.0/extract-idl.py
- specs/latest/2.0/extract-idl.py
> Fix Python 3 errors

- extensions/proposals/WEBGL_video_texture/extension.xml
This commit change some names in the proposed extension and add limitations
@kainino0x @kenrussell  PTAL.
> Change WEBGL_video_texture proposal extension

- sdk/tests/conformance2/uniforms/00_test_list.txt
- sdk/tests/conformance2/uniforms/large-uniform-buffers.html
https://bugs.chromium.org/p/angleproject/issues/detail?id=3388
> Add compliance test for UBOs sized over 65536

- sdk/tests/js/tests/ext-float-blend.js
ES 2.0 requires that all color buffers attached to application-created framebuffer objects must have the same number of bitplanes.
Thus modify the MRT part of EXT_float_blend test for WebGL 1.
> Fix MRT EXT_float_blend test for WebGL 1

- extensions/proposals/WEBGL_draw_instanced_base_vertex_base_instance/extension.xml
- extensions/proposals/WEBGL_multi_draw_instanced_base_vertex_base_instance/extension.xml
As discussed in WebGL working group meeting, I added first revision of the proposals of the base vertex base instance extension. Open a pull request here to create a thread for further discussions.
> WEBGL base vertex base instance extension proposals

- extensions/WEBGL_blend_equation_advanced_coherent/extension.xml
Agreed upon at WebGL F2F of September 2019.
> Move WEBGL_blend_equation_advanced_coherent to draft.

- specs/latest/1.0/index.html
Also:
* Use stronger language to encourage robust context loss handling for
high-performance contexts.
> Remove context-loss handling requirement from powerPreference.

- sdk/tests/conformance2/extensions/00_test_list.txt
- sdk/tests/conformance2/extensions/webgl-multi-draw-instanced-base-vertex-base-instance.html
Add conformance test for new extensions: WEBGL_draw_instanced_base_vertex_base_instance and WEBGL_multi_draw_instanced_base_vertex_base_instance.
Referencing #2937
> BaseVertex BaseInstance Conformance Test

- extensions/WEBGL_multi_draw_instanced_base_vertex_base_instance/extension.xml
> Update reference to WEBGL_multi_draw in WEBGL_multi_draw_instanced_base_vertex_base_instance extension

- sdk/tests/conformance/extensions/00_test_list.txt
- sdk/tests/conformance/extensions/oes-fbo-render-mipmap.html
Add test for `OES_fbo_render_mipmap` extension
> Add oes-fbo-render-mipmap test

- sdk/tests/conformance2/extensions/ext-texture-norm16.html
> Delete commented code

- extensions/OVR_multiview2/extension.xml
> s/getFramebufferStatus/checkFramebufferStatus/ in OVR_multiview2 spec.

- sdk/tests/webgl-conformance-tests.html
- tools/.gitignore
- tools/README.md
- tools/conformance.py
A collection of commits that update the tools/conformance.py script to:
- be compatible with Python3
- support Safari/WebKit
- various minor clean-ups
The documentation is also updated to show how to set up a virtual
python environment.
> Webdriver tools update

- tools/conformance.py
This patch adds support for iOS devices.
- Renamed generic "device"-like things from mentioning Android
- Took the existing Android objects and made base classes with
Android and iOS subclasses if necessary
> Add support for iOS to WebDriver script

- sdk/tests/conformance/canvas/buffer-offscreen-test.html
There are more concise assert functions available. Let's use them.
> Use more concise assertions in buffer-offscreen-test.html

- sdk/tests/deqp/functional/gles3/es3fShaderCommonFunctionTests.js
This patch fixes the error messages in es3fShaderCommonFunctionTests.js
by referencing the related code in dEQP-GLES3 test
[es3fShaderCommonFunctionTests.cpp](https://android.googlesource.com/platform/external/deqp/+/refs/heads/master/modules/gles3/functional/es3fShaderCommonFunctionTests.cpp#282).
Previously the error message in the console is as follows:
> ERROR: comparison failed for value 2:
undefinedExpected [0] = (0.020406484603881836) + (-2) =
-1.9795935153961182 with ULP threshold 4194303, got ULP diff 8559790
...
ERROR: comparison failed for value 3:
Expected [0] = (0.5) + (7401585) = 7401585.5 with ULP threshold 0, got
ULP diff 199352547
inputs:
in0 = [object Object] undefined
outputs:
out0 = [object Object] undefined
With this patch, the error message will be more useful for …
> Fix error messages in es3fShaderCommonFunctionTests.js

- sdk/tests/conformance2/glsl3/matrix-row-major-dynamic-indexing.html
- sdk/tests/conformance2/glsl3/matrix-row-major.html
> Update test for dynamically-indexed row-major matrices.

- sdk/tests/conformance2/glsl3/00_test_list.txt
> Re-alphabetize tests in test list.

- sdk/tests/conformance/textures/misc/compressed-tex-image.html
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1606830
> Test that compressedTex(Sub)Image w/PBO checks size properly.

- sdk/tests/conformance/extensions/webgl-draw-buffers.html
- sdk/tests/conformance2/rendering/draw-buffers.html
Regression test for a bug in Firefox.
> Add test for bindFramebuffer+getParameter(DRAW_BUFFERn) without drawing.

- extensions/WEBGL_lose_context/extension.xml
This resolves ambiguities discovered in
https://bugzilla.mozilla.org/show_bug.cgi?id=1144115
> Clarify behaviors and timelines in WEBGL_lose_context.

- sdk/tests/conformance/canvas/00_test_list.txt
- sdk/tests/conformance/canvas/webgl-to-2d-canvas.html
https://github.com/KhronosGroup/WebGL/issues/3008
> Add WebGL to 2D Canvas test

- sdk/tests/conformance/buffers/buffer-data-and-buffer-sub-data.html
From Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1611837
> Add bufferSubData(new ArrayBuffer(0)) tests.

- sdk/tests/conformance/programs/program-test.html
Otherwise YouTube 360 videos silently fail.
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1616132
> Test that getProgramParameter(ATTACHED_SHADERS) is correct.

- sdk/tests/conformance/rendering/00_test_list.txt
- sdk/tests/conformance/rendering/bind-framebuffer-flush-bug.html
Regression test for http://crbug.com/1018028 .
> Test Intel driver bug where clear/drawArrays reorder across bindFramebuffer.

- sdk/tests/conformance2/rendering/00_test_list.txt
- sdk/tests/conformance2/rendering/framebuffer-render-to-layer-angle-issue.html
- sdk/tests/conformance2/rendering/framebuffer-render-to-layer.html
- sdk/tests/js/webgl-test-utils.js
> Greggman render to framebuffer layer

- sdk/tests/conformance/glsl/preprocessor/00_test_list.txt
- sdk/tests/conformance/glsl/preprocessor/comments.html
- sdk/tests/js/glsl-conformance-test.js
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1617512
> Add GLSL preprocessor comment behavior tests.

- sdk/tests/conformance/glsl/preprocessor/comments.html
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1620876
> Add testcase for minimal glsl line comment, and related.

- sdk/tests/conformance/canvas/render-after-resize-test.html
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1621523
> Add Render();NoOpResize();Render(); tests.

- sdk/tests/conformance/textures/misc/compressed-tex-image.html
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1622536
> Add test for compressedTex(Sub)Image2D(DataView).

- sdk/tests/conformance/textures/misc/00_test_list.txt
- sdk/tests/conformance/textures/misc/texture-copying-and-deletion.html
Regression test for http://anglebug.com/4267 and linked bugs.
Added to, and re-alphabetized, test list.
> Test texture deletion after CopyTexImage2D/CopyTexSubImage2D.

- sdk/tests/conformance/buffers/buffer-data-and-buffer-sub-data.html
- sdk/tests/conformance/reading/read-pixels-test.html
- sdk/tests/conformance/textures/misc/tex-image-and-sub-image-2d-with-array-buffer-view.html
- sdk/tests/conformance/uniforms/gl-uniform-arrays.html
- sdk/tests/conformance/uniforms/gl-uniformmatrix4fv.html
- sdk/tests/js/js-test-pre.js
- sdk/tests/js/tests/compressed-tex-image.js
- sdk/tests/js/webgl-test-utils.js
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1624944
> Add tests for SharedArrayBuffers to entrypoints that should take them.

- sdk/tests/conformance/extensions/oes-texture-float-linear.html
- sdk/tests/conformance/extensions/oes-texture-half-float-linear.html
- sdk/tests/js/tests/oes-texture-float-and-half-float-linear.js
- sdk/tests/js/webgl-test-utils.js
> Add and use WebGLTestUtils.isWebGL2 helper.

- sdk/tests/conformance2/extensions/00_test_list.txt
- sdk/tests/conformance2/extensions/oes-draw-buffers-indexed.html
https://www.khronos.org/registry/webgl/extensions/OES_draw_buffers_indexed/
nothing fancy
> Add oes_draw_buffer_indexed test

- sdk/demos/intel/js/renderer.js
VideoElementTargetVideoTexture -> shareVideoImageWEBGL
add releaseVideoImageWEBGL call.
> Update demo to align with latest WEBGL_video_texture proposal

- conformance-suites/1.0.3/conformance/extensions/webgl-compressed-texture-pvrtc.html
- conformance-suites/2.0.0/conformance/extensions/webgl-compressed-texture-pvrtc.html
Replace drawQuad with clearAndDrawUnitQuad.
> PVRTC tests call non-existent helper function

- sdk/demos/intel/WEBGL_video_texture.html
@kenrussell  Sry for these typo. I hot-fix them in my local but forget to upload them in last CL. PTAL
> Fix WEBGL_video_texture demo typo

- sdk/tests/conformance/textures/misc/00_test_list.txt
- sdk/tests/conformance/textures/misc/upload-from-srcset-with-empty-data.html
Regression test for http://crbug.com/1085044 .
> Test uploading an image with a srcset with empty data.

- extensions/proposals/EXT_shader_framebuffer_fetch/extension.xml
EXT_shader_framebuffer_fetch proposal v1
> EXT_shader_framebuffer_fetch proposal v1

- sdk/tests/conformance2/query/query.html
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1636525
> Check that Create+Delete+BeginQuery fails.

- sdk/tests/conformance/rendering/draw-with-changing-start-vertex-bug.html
> Fix comments in draw-with-changing-start-vertex-bug.html.

- extensions/proposals/EXT_shader_framebuffer_fetch/extension.xml
> Update revision date in EXT_shader_framebuffer_fetch proposal.

- sdk/tests/conformance/state/00_test_list.txt
- sdk/tests/conformance/state/fb-attach-implicit-target-assignment.html
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1636524
> Check that framebufferTexture requires bindTexture.

- extensions/WEBGL_multi_draw_instanced_base_vertex_base_instance/extension.xml
Change types of countsList, offsetsList, and instanceCountsList from sequence&lt;GLint&gt; to sequence&lt;GLsizei&gt;
Change type of baseInstances from sequence&lt;GLint&gt; to sequence&lt;GLuint&gt;
> Fix WEBGL_multi_draw_instanced_base_vertex_base_instance argument types

- sdk/tests/conformance/textures/misc/texture-video-transparent.html
- sdk/tests/js/webgl-test-utils.js
Print detailed pixels value error when neither left is green nor right is blue to help better understanding of flakiness.
> Print error log when neither left is green nor right is blue

- extensions/proposals/WEBGL_webcodecs_video_frame/extension.xml
- extensions/proposals/WEBGL_webcodecs_video_frame/webgl_webcodecs_video_frame.js
- sdk/tests/performance/webgl_webcodecs_video_frame/index.html
> WebGL_webcodecs_video_frame demo

- sdk/tests/conformance2/glsl3/precision-side-effects-bug.html
> Add more comments to precision-side-effects test

- extensions/WEBGL_multi_draw/extension.xml
Try not to imply that they only work with UNSIGNED_SHORT indices.
> Change WEBGL_multi_draw examples for variety.

- other/get.webgl.org/troubleshooting/DoNotCopyOrLinkThisFileElseYouWillNotGetAutoUpdatedHelpForYourUsers.js
- other/get.webgl.org/webgl2/troubleshooting/DoNotCopyOrLinkThisFileElseYouWillNotGetAutoUpdatedHelpForYourUsers.js
Verify and update troubleshooting support links for WebGL and WebGL2
> Update support URLs

- specs/latest/1.0/index.html
Follow-on to #3206 and #3209 .
> Add normative text about supporting line continuation character.

- extensions/proposals/WEBGL_webcodecs_video_frame/webgl_webcodecs_video_frame.js
- sdk/tests/conformance/extensions/webgl-webcodecs-video-frame.html
Hi. Could any one take a look at this PR?
This PR try to add a test for webgl-webcodecs-video-frame extension.
> Add webgl webcodecs video frame test

- sdk/tests/conformance/glsl/bugs/vector-matrix-constructor-scalarization.html
Found necessary on multiple platforms in http://crbug.com/1165751 .
Follow-up to #3214 .
> Increase tolerance to 8 from 3.

- sdk/tests/js/glsl-conformance-test.js
Addresses regressions in the following tests:
conformance/glsl/misc/boolean_precision.html
conformance2/glsl3/switch-case.html
conformance2/glsl3/texture-offset-non-constant-offset.html
conformance2/glsl3/uniform-block-layouts.html
Follow-up to #3215 .
> Fix negative compilation tests in glsl-conformance-test.js.

- specs/latest/1.0/index.html
- specs/latest/1.0/webgl.idl
- specs/latest/2.0/index.html
- specs/latest/2.0/webgl2.idl
This is the bulk of the changes we need to modernize our webidl, so this gets us most of the way there.
> s/void/undefined/ in specs/latest/*.

- sdk/tests/conformance2/textures/misc/00_test_list.txt
- sdk/tests/conformance2/textures/misc/immutable-tex-render-feedback.html
- sdk/tests/js/webgl-test-utils.js
Combinatorial test for framebuffer attachment completeness of mipmaps,
and sampling from them with/without feedback.
> Add conformance2/textures/misc/immutable-tex-render-feedback.html.

- sdk/tests/conformance/textures/misc/video-rotation.html
Follow-on to #3199 and #3262 .
Associated with http://crbug.com/1191456 .
> Increase tolerance for video-rotation.html test.

- specs/latest/1.0/index.html
- specs/latest/1.0/webgl.idl
Proposed by @autokagami in #3260 .
> Align WebGLContextEvent with Web IDL spec.

- LICENSE.txt
Add copyright year and holder.
> Modify LICENSE.TXT

- sdk/tests/conformance/extensions/ext-texture-compression-bptc.html
- sdk/tests/conformance/extensions/ext-texture-compression-rgtc.html
- sdk/tests/conformance/extensions/s3tc-and-rgtc.html
- sdk/tests/conformance/extensions/webgl-compressed-texture-s3tc-srgb.html
- sdk/tests/js/tests/compressed-texture-utils.js
Fixes #3117.
The updated tests pass on Chrome Stable .
Related to http://crbug.com/angleproject/4841 .
/cc @kenrussell @vonture
> Add simple NPOT tests to S3TC

- extensions/WEBGL_compressed_texture_s3tc_srgb/extension.xml
> Fix upstream S3TC_sRGB extension name & link

- sdk/tests/conformance/textures/misc/00_test_list.txt
- sdk/tests/conformance/textures/misc/png-image-types.html
- specs/latest/2.0/index.html
Partly reverts #2805 and fixes #2814.
> Add PNG Image types test

- sdk/tests/conformance/textures/misc/png-image-types.html
> Remove unused variable

- sdk/tests/conformance/glsl/constructors/glsl-construct-vec-mat-index.html
> Fix duplicate notifyFinishedToHarness in glsl-construct-vec-mat-index.

- sdk/tests/conformance/extensions/oes-element-index-uint.html
- sdk/tests/conformance2/rendering/element-index-uint.html
- sdk/tests/conformance2/vertex_arrays/vertex-array-object.html
- sdk/tests/js/tests/no-over-optimizations-on-uniform-array.js
Use:
blacklist -> blocklist
whitelist -> allowlist
> Use inclusive terminology in WebGL test suite #3275

- sdk/tests/conformance2/extensions/oes-draw-buffers-indexed.html
> [oes-draw-buffers-indexed.html] Reset colorMask and blend disable.

- sdk/tests/conformance2/glsl3/array-equality.html
- sdk/tests/js/glsl-conformance-test.js
There doesn't appear to be a test of comparing arrays
> Compare arrays

- sdk/tests/conformance2/glsl3/matrix-row-major-dynamic-indexing.html
Looking at the code in one of the backends I see this is problematic
so it seemed there should be a test.
> Test double indirect row_matrix access.

- extensions/OES_draw_buffers_indexed/extension.xml
> Move OES_draw_buffers_indexed to community approved

- sdk/tests/conformance/textures/misc/format-filterable-renderable.html
- specs/latest/1.0/index.html
Testing this PR:
https://github.com/KhronosGroup/WebGL/pull/3364
off the main branch of the KhronosGroup/WebGL repository.
> Testing PR: Require rgb renderable webgl1.

- specs/latest/1.0/index.html
- specs/latest/2.0/index.html
Mention that it is the living standard, and update the author list.
> Revise [WEBIDL] specification reference.

- sdk/tests/conformance/misc/00_test_list.txt
- sdk/tests/conformance/misc/hint.html
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1749302
> Add conformance/misc/hint.html for gl.hint().

- sdk/tests/conformance2/renderbuffers/00_test_list.txt
- sdk/tests/conformance2/renderbuffers/multisample-draws-between-blits.html
The Apple Metal backend had an issue that blitting a multisample
renderbuffer could lose its content.
> Test resolving a multisample renderbuffer keeps its contents.

- sdk/tests/conformance2/buffers/get-buffer-sub-data-validity.html
Small, functional typo I spotted.
> Fix typo in test

- extensions/rejected/WEBGL_texture_multisample/extension.xml
> Reject WEBGL_texture_multisample.

- extensions/rejected/WEBGL_subarray_uploads/extension.xml
> Reject WEBGL_subarray_uploads proposal.

- extensions/rejected/EXT_shader_framebuffer_fetch/extension.xml
At this point, this functionality should be pursued in WebGPU instead.
> Reject proposed extension EXT_shader_framebuffer_fetch.

- extensions/rejected/EXT_shader_framebuffer_fetch/extension.xml
- extensions/rejected/WEBGL_subarray_uploads/extension.xml
- extensions/rejected/WEBGL_texture_multisample/extension.xml
These are breaking the build of the extensions/ directory.
> Fix recently-rejected extensions' URLs.

- sdk/tests/conformance2/rendering/00_test_list.txt
- sdk/tests/conformance2/rendering/vertex-id-large-count.html
This test calls gl.drawArrays with a count of 4194304 which happens to reveal bugs in certain WebGL implementations.
> gl_VertexID test with a large count

- sdk/tests/conformance2/renderbuffers/invalidate-framebuffer.html
These new cases fail on the Metal backend
See Issue: https://anglebug.com/7397
> Add more cases to invalidate-framebuffer test

- sdk/tests/deqp/data/gles3/shaders/00_test_list.txt
- sdk/tests/deqp/data/gles3/shaders/conversions.template
- sdk/tests/deqp/data/gles3/shaders/conversions_matrix_combine.html
- sdk/tests/deqp/data/gles3/shaders/conversions_matrix_combine.test
- sdk/tests/deqp/data/gles3/shaders/conversions_matrix_to_matrix.html
- sdk/tests/deqp/data/gles3/shaders/conversions_matrix_to_matrix.test
- sdk/tests/deqp/data/gles3/shaders/conversions_scalar_to_matrix.html
- sdk/tests/deqp/data/gles3/shaders/conversions_scalar_to_matrix.test
- sdk/tests/deqp/data/gles3/shaders/conversions_scalar_to_scalar.html
- sdk/tests/deqp/data/gles3/shaders/conversions_scalar_to_scalar.test
- sdk/tests/deqp/data/gles3/shaders/conversions_scalar_to_vector.html
- sdk/tests/deqp/data/gles3/shaders/conversions_scalar_to_vector.test
- sdk/tests/deqp/data/gles3/shaders/conversions_vector_combine.html
- sdk/tests/deqp/data/gles3/shaders/conversions_vector_combine.test
- sdk/tests/deqp/data/gles3/shaders/conversions_vector_illegal.html
- sdk/tests/deqp/data/gles3/shaders/conversions_vector_illegal.test
- sdk/tests/deqp/data/gles3/shaders/conversions_vector_to_scalar.html
- sdk/tests/deqp/data/gles3/shaders/conversions_vector_to_scalar.test
- sdk/tests/deqp/data/gles3/shaders/conversions_vector_to_vector.html
- sdk/tests/deqp/data/gles3/shaders/conversions_vector_to_vector.test
- sdk/tests/deqp/data/gles3/shaders/split-conversions.js
conversions.html was taking around 5 minutes to run on some
devices so split it into mulitple tests.
> Split conversions.html

- sdk/tests/conformance/extensions/angle-instanced-arrays.html
- sdk/tests/conformance/extensions/webgl-multi-draw.html
- sdk/tests/conformance2/canvas/compositing.html
- sdk/tests/conformance2/extensions/webgl-multi-draw-instanced-base-vertex-base-instance.html
- sdk/tests/js/tests/compositing-test.js
See:
http://crbug.com/1333620
https://bugs.webkit.org/show_bug.cgi?id=241347
I think this tests this feature. At least locally the default draw functions pass and the extension draw functions do not.
> Test compositing with webgl-multi-draw-instanced-base-vertex-base-instance

- sdk/tests/conformance2/extensions/oes-draw-buffers-indexed.html
Fails in Chromium and WebKit, passes in Firefox.
> Add testColorMaskAfterComposite

- extensions/proposals/EXT_provoking_vertex/extension.xml
Breaking "make" of extensions/ directory.
Follow-on to #3442.
> Fix href of EXT_provoking_vertex proposal.

- extensions/EXT_provoking_vertex/extension.xml
> Move EXT_provoking_vertex to draft.

- extensions/OES_vertex_array_object/extension.xml
> Fix typo in createVertexArrayOES description

- sdk/tests/conformance2/transform_feedback/transform_feedback.html
Fails in WebKit & Chromium. Passes in Firefox.
WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=242632
WebKit PR: https://github.com/WebKit/WebKit/pull/2335
Chromium bug: https://crbug.com/1343722
> Expand transform feedback tests

- sdk/tests/conformance2/context/incorrect-context-object-behaviour.html
Fails in WebKit, passes in Chromium & Firefox.
https://bugs.webkit.org/show_bug.cgi?id=242580
> Expand incorrect context object tests

- extensions/WEBGL_multi_draw/extension.xml
- extensions/WEBGL_multi_draw_instanced_base_vertex_base_instance/extension.xml
> Clarify ESSL usage of multi-draw extensions

- sdk/tests/conformance2/renderbuffers/framebuffer-object-attachment.html
Assert all three attachment points after each state change.
> Expand FBO DS attachment test

- specs/2.0.0/index.html
- specs/latest/2.0/index.html
> Spec shadow sampler filterability as implementation-defined.

- specs/latest/2.0/index.html
> Clarify TRANSFORM_FEEDBACK_BUFFER bindings

- tools/conformance.py
Add Firefox support on Linux
Selenium has deprecated some old APIs, so this PR also adapts the
changes for Firefox and Chrome.
Bug: #3481
> tools: Add Firefox support on Linux and adapt Selenium changes

- sdk/tests/js/tests/canvas-tests-utils.js
> Allow makeXRCompatible in OffscreenCanvas contexts

- sdk/tests/conformance/extensions/ext-texture-compression-rgtc.html
Follow-up to a similar BPTC update in #3454.
> Relax RGTC error codes

- sdk/tests/conformance2/extensions/00_test_list.txt
> Add EXT_provoking_vertex to the test list

- sdk/tests/conformance2/programs/00_test_list.txt
- sdk/tests/conformance2/programs/get-uniform-indices.html
Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1755973
> Add test for getUniformIndices.

- README.md
> Added information about license and CLA.

- sdk/tests/conformance/extensions/webgl-polygon-mode.html
- sdk/tests/conformance2/extensions/oes-sample-variables.html
- sdk/tests/conformance2/extensions/oes-shader-multisample-interpolation.html
> Address new tests feedback

- sdk/tests/conformance2/textures/misc/00_test_list.txt
> Add tex-image-10bpc.html to 00_test_list.txt

- extensions/WEBGL_draw_instanced_base_vertex_base_instance/extension.xml
Fixed typo in another BVBI extension docs.
> Fixed typo in BVBI extension docs.

- specs/latest/1.0/index.html
> Fix "code" tags causing incorrect HTML rendering.

- other/get.webgl.org/troubleshooting/DoNotCopyOrLinkThisFileElseYouWillNotGetAutoUpdatedHelpForYourUsers.js
I choose a very similar forum thread, pointing to an identical answer.
> Fix broken Chrome troubleshooting URL

- sdk/tests/conformance/uniforms/uniform-location.html
Associated with crbug.com/331119482 .
> Verify invalidated uniform locations when there is no current program.

- sdk/tests/extra/tex-image-with-video-test.js
- sdk/tests/js/tests/tex-image-and-sub-image-3d-with-video.js
- sdk/tests/py/lint/lint.allowlist
> Remove more theora/.ogv from sdk/*.

- sdk/tests/js/tests/canvas-tests-utils.js
> Add drawingBufferStorage to known context methods

- sdk/tests/deqp/functional/gles3/es3fShaderTextureFunctionTests.js
Ported https://github.com/KhronosGroup/VK-GL-CTS/commit/69110dc5ed0c1db29f38a06c9bb7b4edb6d77f03.
> Sync ShaderTextureFunctionTests with upstream CTS

- sdk/tests/deqp/functional/gles3/es3fShaderMatrixTest.js
- sdk/tests/deqp/modules/shared/glsShaderRenderCase.js
Includes:
- https://github.com/KhronosGroup/VK-GL-CTS/commit/a4bd68b910c1134d15932f07e65d578dbcac9bb9
- https://github.com/KhronosGroup/VK-GL-CTS/commit/0de8d1dcac618e160e4d01cf0f01fe146d87eb7d
- https://github.com/KhronosGroup/VK-GL-CTS/commit/e76a7b0b4b7cdc8c442a6e9203aba6d7d4fc9759
> Sync ShaderRenderCase with upstream CTS

- sdk/tests/js/js-test-pre.js
- sdk/tests/js/tests/gl-vertex-attrib.js
Passes on at least macOS Firefox/Safari/Chrome.
> Add DRNG (Deterministic RNG) and use it to do fuzzing in attribs/gl-vertex-attrib.html.
