KhronosGroup/WebGL

sdk/tests/conformance/canvas/00_test_list.txt
sdk/tests/conformance/canvas/framebuffer-bindings-affected-by-to-data-url.html

This test is copied from Blink. https://codereview.chromium.org/805273005/

Verifies than GL framebuffer bindings do not change by toDataURL()

---

conformance-suites/1.0.3/conformance/extensions/angle-instanced-arrays.html
sdk/tests/conformance/extensions/angle-instanced-arrays.html

Conformance tests notify the harness of completeness one of two ways:
1) Manually include "var successfullyParsed = true;" and
js-test-post.js at the end of the test. js-test-post.js calls notifyFinishedToHarness
2) Call finishTest at the of the test. FinishTest performs the first method programatically.
Angle-instanced-arrays does both of these things. The "TEST COMPLETED" message shows
up twice in the final output.
Since finishTest is called as part of multiple setTimeout callbacks, we end up
notifying the harness of completeness (through the manually inserted script tag)
before the test actually finishes.
The fix is to delete js-test-post.js from the end of the test and rely on finishTest exclusively.

Angle-instanced-arrays calls notifyFinishedToHarness multiple times

---

sdk/tests/conformance/canvas/framebuffer-bindings-affected-by-to-data-url.html

The framebuffer-bindings-affected-by-to-data-url test needs to report completeness back to
the test harness. Otherwise, the test harness will timeout the test.
To fix this we add js-test-post.js to the end of the test.

framebuffer-bindings-...-to-data-url does not report completeness to test harness

---

sdk/tests/test-guidelines.md

Fix documentation to match current code and practices, and bump up the
copyright notice year to 2015.

Small updates to test guidelines

---

sdk/tests/conformance/extensions/angle-instanced-arrays.html

This test catches a bug that is currently present in Chrome/ANGLE DX11:
https://code.google.com/p/chromium/issues/detail?id=447140
https://code.google.com/p/angleproject/issues/detail?id=864
I'm setting up a different quad and offset buffer, because the setup used for the existing tests draws outside of the full viewport (each instance is centered at one corner of the viewport and 3/4 of it lie outside of the viewport). With that setup, it would be impossible to check if the last instance has drawn, because its second triangle lies completely outside of the viewport.

Add test for call to drawArraysInstancedANGLE with 'first' > 0

---

sdk/tests/conformance/resources/red-green.svg
sdk/tests/conformance/resources/tex-image-and-sub-image-2d-with-canvas.js
sdk/tests/conformance/resources/tex-image-and-sub-image-2d-with-image-data.js
sdk/tests/conformance/resources/tex-image-and-sub-image-2d-with-image.js
sdk/tests/conformance/resources/tex-image-and-sub-image-2d-with-svg-image.js
sdk/tests/conformance/resources/tex-image-and-sub-image-2d-with-video.js
sdk/tests/conformance/resources/tex-image-and-sub-image-2d-with-webgl-canvas.js
sdk/tests/conformance/resources/webgl-test-utils.js
sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-array-buffer-view.html

Make tex-image-and-sub-image-2d-with-webgl-canvas-* cover TEXTURE_CUBE_MAP.
Improve tex-image-and-sub-image-2d-with-webgl-canvas-* to check http://crrev.com/735623003/
Change from setCanvasTo1x2 to setCanvasTo2x2 because cube map allows only square source.

Make tex-image-and-sub-image-2d-with-webgl-canvas-* cover TEXTURE_CUBE_MAP.

---

sdk/tests/conformance/resources/glsl-conformance-test.js
sdk/tests/conformance/resources/tex-image-and-sub-image-2d-with-video.js
sdk/tests/conformance/resources/webgl-test-utils.js
sdk/tests/resources/js-test-post.js
sdk/tests/resources/js-test-pre.js

Only output the buffered logs if the test fails -- i.e., calls testFailed().
This reduces the amount of debugging output for a typical run of the
conformance suite, while still remaining debuggable in case of errors.
Tested by injecting a synthetic failure in a test which previously had
debugging output; verified that the output was printed, and only then.

Buffer calls to console.log to reduce amount of debugging output.

---

extensions/rejected/WEBGL_texture_from_depth_video/extension.xml

Proposing to reject WEBGL_texture_from_depth video because it's not required to do it as an extension.

reject WEBGL_texture_from_depth_video

---

specs/latest/2.0/index.html
specs/latest/2.0/webgl2.idl

Added subsection under compatibility differences describing the behavior and rationale.

Per discussion in WebGL WG, removed PRIMITIVE_RESTART_FIXED_INDEX enum.

---

extensions/rejected/WEBGL_draw_elements_no_range_check/extension.xml

Olli indicated that this extension might be best dropped.

rejecting WEBGL_draw_elements_no_range_check

---

specs/latest/2.0/index.html

It's important to have all the incompatibilities listed in one place to have an
easy reference for developers.

Mention the lack of PRIMITIVE_RESTART_FIXED_INDEX in incompatibility section

---

specs/latest/1.0/index.html
specs/latest/2.0/index.html

DRAW_BINDING was incorrect, it should have been DRAW_BUFFER<i>.
PACK_IMAGE_HEIGHT and PACK_SKIP_IMAGES were removed in GLES3.0.1 (see spec
section E.4), so they should not be in WebGL 2.0 either.
IMPLEMENTATION_COLOR_READ_FORMAT and IMPLEMENTATION_COLOR_READ_TYPE are not
new in WebGL 2.0 any more, since they were added to WebGL 1.0, so remove them
from the table that should only list the new enums.

Fix mistakes in WebGL 2.0 getParameter enum list

---

sdk/tests/conformance/extensions/ext-frag-depth.html
sdk/tests/conformance/extensions/ext-shader-texture-lod.html
sdk/tests/conformance/extensions/oes-standard-derivatives.html
sdk/tests/conformance/extensions/webgl-draw-buffers.html

Add conformance tests to check that cached shaders take into account extensions.
Due to the complexity of caching shaders with global extensions that affect shader compilations,
it is necessary to test for these special conditions by running these shader tests twice. The tests
for the following extensions have been modified to catch cache problems:
GL_OES_standard_derivatives
GL_EXT_frag_depth
GL_EXT_draw_buffers
GL_EXT_shader_texture_lod
Additionally, an issue with the "missingPragmaFragmentShader shader" inside of
ext-shader-texture-lod.html has been fixed. This shader was not properly catching pragma
errors because the shader itself was invalid with other errors such as undeclared variables.
This has been fixed now so the only error is that the pragma extension is missing.

Fixed conformance tests

---

conformance-suites/1.0.3/conformance/more/functions/uniformMatrixBadArgs.html
conformance-suites/1.0.3/conformance/more/unit.js

The uniformMatrixBadArgs test culminates with a call to glReadPixels and expects to get an exact result of [1,2,3,8].
The fragment shader output color is calculated like this:
gl_FragColor = vec4(fm4[0][0]/256.0, fm4[1][1]/256.0, fm4[2][2]/256.0, fm4[3][3]*texCoord0.z/256.0);
While the vertex position is calculated like this:
gl_Position = vec4(Vertex, 1.0 + d * 0.0001);
The framebuffer value therefore depends on an iterated texture coordinate (texCoord0.z) which has been subject to perspective projection by a non 1.0f vertex W-value. These operations may introduce small errors on some implementations, along with the usual float-to-unorm rounding issues.
As such, we propose that the test allows 1 shade of tolerance in the framebuffer value, as is typical in GLES Conformance tests. We have …

uniformMatrixBadArgs test: allow 1 shade of tolerance in framebuffer value

---

conformance-suites/1.0.1/conformance/more/functions/uniformMatrixBadArgs.html
conformance-suites/1.0.1/conformance/more/unit.js
conformance-suites/1.0.2/conformance/more/functions/uniformMatrixBadArgs.html
conformance-suites/1.0.2/conformance/more/unit.js

As discussed in pull request #849, apply change to uniformMatrixBadArgs test to 1.0.1 and 1.0.2 WebGL Conformance suites.

uniformMatrixBadArgs test: allow 1 shade of tolerance in framebuffer value (1.0.1 and 1.0.2)

---

other/test-runner/config.json

This makes sure that a new instance of the browser is opened with newer
versions of Firefox.

Pass -no-remote option to Firefox in test runner

---

sdk/tests/conformance/extensions/ext-frag-depth.html
sdk/tests/conformance/extensions/ext-shader-texture-lod.html
sdk/tests/conformance/extensions/oes-standard-derivatives.html
sdk/tests/conformance/resources/webgl-test-utils.js

Add conformance test for deferred shader compilations with extensions.
If shader compilation is deferred until the link time, a test has been added to be sure the shader compiler uses its state as seen during the compilation request, not the link request. The added conformance test does the following to test this:
1. Create a new GL context which does not have the tested extension enabled.
2. Compile the vertex and fragment shaders which would fail if the extension were disabled.
3. Enable the extension by querying if the extension is supported.
4. Link the shader and check the link status, this should fail since at the time of the compilation the extension was disabled.

Add conformance test for deferred shader compilations with extensions.

---

specs/latest/2.0/index.html

On a program that failed to link, queries to that program's active variables and interface blocks should always generate an INVALID_OPERATION.

Add a difference between ES3 and WebGL 2.

---

specs/latest/1.0/index.html
specs/latest/2.0/index.html

The WebGL 1 spec had a link to a W3C page that has moved, and the WebGL 2
spec had some missing references and one broken internal link.

Fix broken links in specs

---

specs/latest/2.0/index.html
specs/latest/2.0/webgl2.idl

Size should be implied by the ArrayBufferView size, which is consistent with compressedTex{Sub}Image2D.

Removed imageSize from compressedTex{Sub}Image3D

---

sdk/tests/conformance/context/constants-and-properties.html
sdk/tests/conformance2/context/constants-and-properties-2.html

There's code to write error messages specifically for the removed constants, they don't need to be handled later when the code is looking for extra constants.

Don't print error messages from removed properties twice

---

conformance-suites/1.0.2/conformance/glsl/literals/float_literal.vert.html

1.0.3 has this, but 1.0.2 does not. The GLSL spec requires it.
It looks like this was missed when this test was updated. (Note that 1.0.3 has -1E100 for negHuge, which is obviously a bug with 1.0.2. That said, it's not hurting anything, so there's no reason to change it, according to our rules for backporting fixes)

Backport gl_Position assignment from test.

---

sdk/tests/deqp/data/gles2/shaders/functions.test
sdk/tests/deqp/data/gles2/shaders/scoping.test

Remove shader functionality that's not supported according to the
restrictions in Appendix A of the OpenGL ES Shading Language 1.00 spec.

Remove illegal constructs from deqp tests used for WebGL 1

---

conformance-suites/1.0.2/conformance/glsl/literals/float_literal.vert.html

This reverts commit 78f9793a4f327d0e2427836ee20c386d8174cfd1.
Writing gl_Position is not required by the spec (see OpenGL ES Shading
Language 1.00 section 10.13) so the patch being reverted did not fix a
bug as it was intended, but reduced test coverage in the 1.0.2 suite.

Revert "Backport gl_Position assignment from test."

---

sdk/tests/deqp/modules/shared/glsShaderLibrary.js
sdk/tests/resources/js-test-pre.js

Include the name of the failed/passed test when reporting the results
back to the test runner, and add a bit of documentation for the filter
parameter.

Small improvements in the deqp test framework

---

specs/latest/1.0/index.html

It looks like a whitespace change snuck in, oops.
This is the outcome from https://github.com/KhronosGroup/WebGL/pull/877 .

Add errata for initial gl_Position value.

---

sdk/tests/conformance/extensions/webgl-draw-buffers.html

Always log both vertex and fragment shaders and leverage the utils to log
translated shaders when possible. This can help with diagnosing bugs.
Also remove an unused variable from the test.

Improve shader logging in the WEBGL_draw_buffers test

---

sdk/tests/conformance/extensions/00_test_list.txt
sdk/tests/conformance/extensions/webgl-draw-buffers-max-draw-buffers.html

The test relies on OpenGL ES Shading Language spec section 4.1.9: It is
illegal to index an array with an integral constant expression greater
than or equal to its declared size. gl_MaxDrawBuffers is declared as a
const int in section 7.4, so it qualifies as an integral constant
expression.

Add a test for indexing gl_FragData with gl_MaxDrawBuffers

---

conformance-suites/1.0.2/conformance/typedarrays/resources/typed-array-worker.js
conformance-suites/1.0.3/conformance/typedarrays/resources/typed-array-worker.js
sdk/tests/conformance/typedarrays/resources/typed-array-worker.js

This was https://github.com/KhronosGroup/WebGL/pull/886, but with the summary line fixed.

Use undefined instead of null for optional arg omission.

---

sdk/tests/conformance/resources/webgl-test-utils.js
sdk/tests/conformance/state/gl-object-get-calls.html

Fix bugs in conformance/state/gl-object-get-calls.html for WebGL 2.0
It is the same with https://github.com/Richard-Yunchao/WebGL/tree/Conformance_addGetters, but squash all commits into one.

fix bugs in conformance/state/gl-object-get-calls.html for WebGL 2.0

---

sdk/tests/conformance/resources/gl-object-get-calls.js
sdk/tests/conformance/resources/webgl-test-utils.js
sdk/tests/conformance/state/00_test_list.txt
sdk/tests/conformance2/00_test_list.txt
sdk/tests/conformance2/state/00_test_list.txt
sdk/tests/conformance2/state/gl-object-get-calls.html

Remove the context query function from webgl-test-utils.js. Tests should not change behavior depending on the WebGL version on which they are running.
Added separate WebGL 1.0 and 2.0 versions of the gl-object-get-calls.html test, sharing basically all of their code.

Refactored gl-object-get-calls.html into separate JavaScript source.

---

conformance-suites/1.0.2/conformance/ogles/ogles-utils.js
conformance-suites/1.0.3/conformance/ogles/ogles-utils.js
sdk/tests/conformance/ogles/ogles-utils.js

At least two tests (biuDepthRange_001_to_001 and gl_FragCoord_001_to_003) check that there are no active uniforms they didn't request, but since they use gl_DepthRange.far and .near, these count as active uniforms. (GLES 2.0.25 p36: "The returned uniform name can be the name of a built-in uniform state as well")
NB: The test also uses gl_DepthRange.diff, but does not return this as an active uniform. The compiler likely emits `far - near` instead of using a separate value for `diff`, thus it does not consider `diff` to be an active uniform. Whether or not this is spec-compliant is beyond the scope of this bug.

Built-ins can be active uniforms

---

sdk/tests/conformance/resources/gl-object-get-calls.js

rebase #898. I should rebase and update the original pull request... 
@kenrussell , The code refactoring is OK for me. It is clear. Differences of GL state getters between WebGLRenderingContext and WebGL2RenderingContext can be distinguished by contextVersion. And If a big change is needed, I can implement a new function for that getter to override the old one for WebGL2RenderingContext, and execute different ones according to contextVersion.

update getBufferParameter for WebGL 2.0

---

extensions/WEBGL_depth_texture/extension.xml

Following up to #903, this extension's limitations have been removed in WebGL 2.0 so the extension should probably be marked as removed.

Mark WEBGL_depth_texture as removed in WebGL 2.0 instead of in core.

---

sdk/tests/conformance/extensions/00_test_list.txt

This change comes from #897. It skips extensions those have been promoted or removed in WebGL 2.0 by adding max-version for them.
I go through all GL extensions in WebGL Extension Registry webpage(https://www.khronos.org/registry/webgl/extensions/) , these extensions are promoted into core in WebGL 2.0:
ANGLE_instanced_arrays, 
OES_element_index_uint, 
OES_standard_derivatives,
OES_vertex_array_object,
WebGL_draw_buffers,
EXT_blend_minmax,
EXT_frag_depth,
EXT_sRGB,
EXT_shader_texture_lod. 
Aligned with #903 , WEBGL_depth_texture is also promoted into core. 
And these extensions are removed in WebGL 2.0:
OES_texture_float
OES_texture_half_float
OES_texture_half_float_linear.
Please have a look. Thanks a lot!

Fix bugs in extensions for WebGL 2, they are promoted to core or removed 

---

sdk/tests/conformance/extensions/00_test_list.txt

Following up to #906, if the WEBGL_draw_buffers test is disabled in WebGL 2.0, this one should be too.

Disable webgl-draw-buffers-max-draw-buffers.html on WebGL 2.0.

---

sdk/tests/conformance/resources/gl-object-get-calls.js

Add WebGL 2.0 specific functionality in conformance2/state/gl-object-get-calls-2.html for GL state getters. Please take a look. If this is OK, more WebGL 2.0 specific functionalities for getters (getTexParameter, getBufferParameter, getFramebufferAttachmentParameter, etc.) will be added later.

update getRenderbufferParameter for WebGL 2.0

---

sdk/tests/conformance/glsl/misc/00_test_list.txt
sdk/tests/conformance/glsl/misc/struct-assign.html
sdk/tests/conformance/glsl/misc/struct-equals.html

Comparing or assigning structs that contain arrays or samplers is "not
defined" in ESSL 1.00 (spec section 5.7). In addition the spec
mentions in section 5.8 that
"structures containing arrays may be passed to parameters declared as out
or inout but may not be used as the target of an assignment."
and in section 5.9:
"The equality operators equal (==), and not equal (!=) operate on all
types except arrays, structures containing arrays, sampler types and
structures containing sampler types"
It is also not allowed to use samplers as l-values, so it makes sense
that using structs containing samplers as l-values would be disallowed as
well.
Add tests to enforce that equality and assignment of structs containing
arrays or samplers are disallowed in WebGL. Spec clarification doesn't
seem …

Add tests disallowing operators on certain types of structs

---

specs/latest/2.0/index.html
specs/latest/2.0/webgl2.idl

This makes uniform[1234]uiv consistent with uniform[1234]iv.

WebGL2 Allow uniform1234uiv to take TypedArrays

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/array-assign.html
sdk/tests/conformance2/glsl3/array-equality.html

Test ESSL3 array assignment and equality operators with arrays of ints
and arrays of structs. These use ESSL1-compatible code for array
initialization, which helps with developing these features independently
of array constructors. This complements dEQP array tests, which require
constructors to be supported.

Add simple ESSL3 tests for array assignment and equality

---

specs/latest/2.0/index.html
specs/latest/2.0/webgl2.idl

https://www.khronos.org/registry/webgl/specs/latest/2.0/#3.7.2 says for `getBufferSubData()`:
> If returnedData is null then an INVALID_VALUE error is generated.
The current webidl doesn't allow null. Instead, in FF for example, a TypeError is caused:
```javascript
var data = null;
gl.getBufferSubData(gl.ARRAY_BUFFER, 0, data);
```
results in
```
TypeError: Argument 3 is not valid for any of the 3-argument overloads of WebGL2RenderingContext.getBufferSubData.
```
PS: I hope I updated the correct date.

getBufferSubData should accept null param for returnedData.

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/array-assign-constructor.html

The test covers assigning array constructor return values as opposed to
initializing arrays using array constructors. A HLSL backend of WebGL
might have very different implementations for initialization and
assignment, so it is good to have separate coverage for both. dEQP tests
have some coverage for both, but there are some limitations: dEQP
coverage for constructors of arrays of structs only uses initialization
as opposed to assignment, for example.

Add an ESSL3 test for assigning array constructor results

---

resources/default.css
specs/latest/2.0/index.html

Add rationale for some of the WebGL 2 spec items for future reference and
to avoid repeating discussions.
Use a different CSS class for these notes to make them stand out from
other kinds of non-normative comments.

Add notes about rationale for WebGL 2 - GLES3 incompatibility

---

sdk/tests/conformance2/state/gl-get-calls.html
specs/latest/2.0/index.html

I removed TRANSFORM_FEEDBACK_BUFFER_BINDING and UNIFORM_BUFFER_BINDING in a prior patch because they were indexed parameters. I didn't realize that it was also valid to query them non-indexed. Sorry for the confusion.
TRANSFORM_FEEDBACK_BINDING, on the other hand, seems to have simply been overlooked previously.

Fixed erronious removal of some enums from getParameter table

---

sdk/tests/conformance/glsl/misc/00_test_list.txt
sdk/tests/conformance/glsl/misc/empty_declaration.html

This corner case has been discussed on the Khronos bug tracker, with the conclusion that empty declarations including ones followed by declarators are valid outside structs.
IE11 fails two of the tests, NVIDIA GL driver fails one of them.

Add a conformance test for empty declarations

---

sdk/tests/conformance/attribs/00_test_list.txt
sdk/tests/conformance/resources/gl-vertex-attrib.js
sdk/tests/conformance2/00_test_list.txt
sdk/tests/conformance2/attribs/00_test_list.txt
sdk/tests/conformance2/attribs/gl-vertex-attrib.html

1. Separate JavaScript source into gl-vertex-attrib.js.
2. Add vertexAttribI* functions for WebGL 2.0.
3. Add the type checking for getVertexAttrib function.

Update gl-vertex-attrib.html for WebGL 2.0

---

sdk/tests/conformance/resources/webgl-test-utils.js
sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-array-buffer-view.html

Quick optimization to make the test run faster.  readPixels can be slow, so call readPixels once on a union of the rects, and check each subrect for matching color.

Allow multiple checkCanvasRectColor checks with one readPixels call

---

sdk/tests/conformance2/buffers/00_test_list.txt
sdk/tests/conformance2/buffers/getBufferSubData.html

Tests the function getBufferSubData and its restrictions in WebGL 2.0

Add getBufferSubData test

---

sdk/tests/conformance/misc/expando-loss.html

Without this patch the expando test fails in a peculiar way in Chrome by
generating an exception, which prevents it from running into completion
and marking successfullyParsed = true. Make sure that expando2 property
is set before querying its properties to generate a better error message.

Clarify error msg in expando test

---

sdk/tests/conformance/glsl/bugs/compare-loop-index-to-uniform.html
sdk/tests/conformance2/buffers/buffer-copying-contents.html
sdk/tests/conformance2/buffers/buffer-copying-restrictions.html
sdk/tests/conformance2/buffers/buffer-type-restrictions.html
sdk/tests/conformance2/buffers/getBufferSubData.html
sdk/tests/conformance2/core/frag-depth.html
sdk/tests/conformance2/glsl3/array-assign.html
sdk/tests/conformance2/glsl3/array-equality.html

Prefer checkCanvas to checkCanvasRect, and remove unnecessary script tags
and an unnecessary uniform that were left over to tests from copy-pasted
code.

Clean up small issues in some ESSL and WebGL 2 tests

---

sdk/tests/conformance/resources/glsl-conformance-test.js
sdk/tests/conformance2/glsl3/misplaced-version-directive.html
sdk/tests/conformance2/glsl3/shader-linking.html

This makes the WebGL 2 GLSL tests easier to use, since specifying the
context version separately with webglVersion=2 is no longer necessary.

Add WebGL version to GLSL conformance test parameters

---

sdk/tests/conformance/glsl/misc/empty-declaration.html

Empty struct declarations need some special handling since they can't
be pruned unlike other empty declarations. That makes empty struct
declarations followed by a declarator an important corner case to test.

Add one more struct test to the empty declaration test

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/array-length-side-effects.html

ESSL3 defines expressions in section 5.9 so that the length() method is
only allowed to be called on array names, not on complex expressions that
return arrays. Enforce this restriction, which simplifies constant
folding of length() method calls.

Add a WebGL 2 test for array length expressions that have side effects

---

sdk/tests/conformance2/core/draw-buffers.html

Shader outputs declared as arrays can only be indexed by constant
integral expressions, as specified in section 4.3.6 of the ESSL3 spec.
This restriction doesn't exist in the WebGL 1 extension, so only the
WebGL 2 test needs to be changed.

Fix shader in WebGL 2 draw buffers test

---

sdk/tests/conformance/glsl/misc/00_test_list.txt
sdk/tests/conformance/glsl/misc/shader-with-two-initializer-types.html

The bug would happen with declarator lists where a first variable
is an array, and the second is not (or a different size). Already
fixed in ANGLE.

Add test for ANGLE initializer list bug.

---

specs/latest/1.0/index.html
specs/latest/2.0/index.html

As decided by the working group on the April 16 conference call.
Looks like I stripped an EOL whitespace as well.

Add Jeff Gilbert to spec editor(s) list.

---

specs/latest/2.0/index.html

More targets and pnames are added into texParameter against WebGL 2.0. Moreover, the pnames are not exactly the same with those in texParameter in GLES 3.0. This small change add texParameterf and texParameteri, who are updated since WebGL 1.0,  in the section <Texture objects> in WebGL 2 spec. 
PTAL when you have time. Thanks!

update texParameter for WebGL 2 spec

---

sdk/tests/conformance/resources/webgl-test-utils.js
sdk/tests/deqp/data/gles3/shaders/arrays.html
sdk/tests/deqp/data/gles3/shaders/conditionals.html
sdk/tests/deqp/data/gles3/shaders/constant_expressions.html
sdk/tests/deqp/data/gles3/shaders/constants.html
sdk/tests/deqp/data/gles3/shaders/conversions.html
sdk/tests/deqp/data/gles3/shaders/declarations.html
sdk/tests/deqp/data/gles3/shaders/fragdata.html
sdk/tests/deqp/data/gles3/shaders/functions.html
sdk/tests/deqp/data/gles3/shaders/invalid_texture_functions.html
sdk/tests/deqp/data/gles3/shaders/keywords.html
sdk/tests/deqp/data/gles3/shaders/linkage.html
sdk/tests/deqp/data/gles3/shaders/negative.html
sdk/tests/deqp/data/gles3/shaders/preprocessor.html
sdk/tests/deqp/data/gles3/shaders/qualification_order.html
sdk/tests/deqp/data/gles3/shaders/scoping.html
sdk/tests/deqp/data/gles3/shaders/switch.html
sdk/tests/deqp/data/gles3/shaders/swizzles.html
sdk/tests/deqp/data/gles3/shaders/template.html

This removes the need to supply ?webglVersion=2 in the URL when running
one of these tests by itself. A function is added to WebGLTestUtils to
set the default context version, since it is a lot simpler than passing
the context version through the fairly complex test framework.

Set dEQP-based GLES3 tests to use WebGL 2 contexts by default

---

sdk/tests/conformance/ogles/GL/biuDepthRange/biuDepthRange_001_to_002.html

This test was accidentally checking the reference shader for the
presence of the gl_DepthRange built-in uniform. Modify the check
to happen on the expected shader instead.

Fix the gl_DepthRange vertex shader test.

---

sdk/tests/conformance/context/premultiplyalpha-test.html
sdk/tests/conformance/resources/tex-image-and-sub-image-2d-with-canvas.js
sdk/tests/conformance/resources/tex-image-and-sub-image-2d-with-image.js
sdk/tests/conformance/resources/tex-image-and-sub-image-2d-with-svg-image.js
sdk/tests/conformance/resources/tex-image-and-sub-image-2d-with-webgl-canvas.js
sdk/tests/conformance/resources/webgl-test-utils.js
sdk/tests/conformance/textures/gl-teximage.html

Avoid overly-verbose logging when these calls generate no error.

Report errors when setting colorspace conversion unpack parameters.

---

sdk/tests/conformance2/00_test_list.txt
sdk/tests/conformance2/textures/00_test_list.txt
sdk/tests/conformance2/textures/texel-fetch-undefined.html

Tests accessing a texel outside the texture dimensions would return the
color (0, 0, 0, 0).
This test should also be expanded in the future to consider the "lod"
parameter of the texelFetch function.

Added texel fetch test

---

sdk/tests/00_test_list.txt

These tests were introduced in that version of the conformance suite, so the bookkeeping should reflect that fact.

Add 1.0.4 --min-version for ported GLES2 dEQP tests.

---

specs/latest/2.0/index.html

This makes WebGL 2 shading language version number consistent with GLSL
ES 3.00.

Change 'WebGL GLSL ES 3.0' to 'WebGL GLSL ES 3.00' for WebGL 2 spec

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/array-in-complex-expression.html

HLSL doesn't natively support arrays as return values. To translate
shaders to HLSL, expressions where arrays are being returned need to be
converted into a form where arrays are not being returned. There are some
cases where implementing this is somewhat tricky, and should be tested.
All the new tests already pass on Chrome's current WebGL 2 prototype on
Linux/NVIDIA.

Add test for arrays being returned inside complex expressions

---

sdk/tests/deqp/modules/shared/glsShaderLibraryCase.js

Compilation failures are not guaranteed to be detected at compile time,
so dEQP tests should not require that. Other tests, like ones using
tests/conformance/resources/glsl-conformance-test.js are already built
to only check for link errors in case compilation errors are expected.

Relax dEQP compilation error checks (consistent with other tests)

---

sdk/tests/conformance/glsl/bugs/00_test_list.txt
sdk/tests/conformance/glsl/bugs/sequence-operator-evaluation-order.html

This reveals a bug in ANGLE's HLSL translation.
The test passes in Chrome on Linux/NVIDIA and also in current version of
IE.

Add a test for ternary operator affected by earlier operand in sequence

---

sdk/tests/conformance/resources/tex-image-and-sub-image-2d-with-canvas.js

Redoing the change discussed at:
https://github.com/KhronosGroup/WebGL/pull/977#issuecomment-100169188

Add test case to oes-texture-float-with-canvas to verify texture is actually backed by FLOATs.

---

conformance-suites/1.0.1/conformance/glsl/misc/shader-with-for-loop.html
conformance-suites/1.0.2/conformance/glsl/misc/shader-with-for-loop.html
conformance-suites/1.0.3/conformance/glsl/misc/shader-with-for-loop.html
sdk/tests/conformance/glsl/misc/shader-with-for-loop.html

ESSL 1.00 section 4.3 says that global initializers need to be constant
expressions. It is still being discussed how strictly this rule should
apply to WebGL, but initializing globals with uniforms is clearly not
allowed by the spec, so fix the conformance test doing that.
The fix is backported all the way to 1.0.1 conformance suite.

Fix global initializer containing an uniform in conformance tests

---

specs/latest/2.0/index.html

Rationale that was documented inside the spec body is moved into proper
rationale boxes, and rationale is added for texture fetch behavior.

Add a few more spec rationale notes

---

sdk/tests/conformance/resources/tex-image-and-sub-image-2d-with-canvas.js

PR #984 used tab instead of space.

Fix indentation in tex-image-and-sub-image-2d-with-canvas.js

---

sdk/tests/conformance/resources/gl-enum-tests.js
sdk/tests/conformance/state/00_test_list.txt
sdk/tests/conformance2/state/00_test_list.txt
sdk/tests/conformance2/state/gl-enum-tests.html

1. Refactor sources of HTML and Javascript.
2. Fix several incompatible test cases.
3. Add some related test cases.

Update gl-enum-tests.html for WebGL 2.0

---

sdk/tests/conformance/glsl/bugs/conditional-discard-optimization.html

This can expose incomplete workarounds to the same underlying bug the
other two tests in the file are testing.

Add unfolded version of conditional discard test

---

sdk/tests/conformance/extensions/00_test_list.txt
sdk/tests/conformance/extensions/ext-disjoint-timer-query.html

The draft extension EXT_disjoint_timer_query is currently being implemented in Firefox- it would be valuable to include some simple sanity checks for it as part of the WebGL conformance tests.
Thanks!

Added tests for draft EXT_disjoint_timer_query.

---

sdk/tests/conformance/resources/glsl-conformance-test.js
sdk/tests/conformance2/glsl3/array-as-return-value.html
sdk/tests/conformance2/glsl3/array-assign.html
sdk/tests/conformance2/glsl3/array-equality.html
sdk/tests/conformance2/glsl3/array-in-complex-expression.html
sdk/tests/conformance2/glsl3/array-length-side-effects.html

This includes adding default ESSL3 shaders to the GLSLConformanceTester and converting the test files to use that.

Convert WebGL 2 shader tests to use GLSLConformanceTester

---

specs/latest/2.0/index.html

Since SAMPLES will just return an Int32Array, NUM_SAMPLE_COUNTS is useless;
for other parts of the WebGL spec, we always remove such redundant enums.

Remove NUM_SAMPLE_COUNTS from WebGL 2.

---

sdk/tests/conformance2/attribs/gl-vertex-attrib-i-render.html
sdk/tests/conformance2/attribs/gl-vertexattribipointer-offsets.html

Fix compile error of directive `#version 300 es` not on the first line.
1. sdk/tests/conformance2/attribs/gl-vertex-attrib-i-render.html
2. sdk/tests/conformance2/attribs/gl-vertexattribipointer-offsets.html

Fix incorrect position of glsl3 directive

---

sdk/tests/conformance/glsl/bugs/essl3-shaders-with-webgl1.html

GLSLConformanceTester was recently updated to support default ESSL3
shaders. This unintentionally affected some subtests in
essl3-shaders-with-webgl1.html. Restore the intended testing of
mixing ESSL1 shaders with ESSL3 shaders.

Fix default shaders in ESSL3 shaders with WebGL 1.0 test

---

sdk/tests/conformance2/state/gl-get-calls.html

I found a couple of bugs in this test:
1. The default value for gl.getParameter(gl.READ_BUFFER) should be gl.BACK not gl.NONE 
```
The initial value of the read framebuffer for the default framebuffer is BACK
if there is a default framebuffer associated with the context, otherwise it is 
NONE. (GL ES 3 3.0.4, Section 4.3.1, page 191)
```
2. An instance of `context.MAX_ARRAY_TEXTURE_LAYERS` that should have been `context.MAX_CLIENT_WAIT_TIMEOUT_WEBGL`

WebGL2 Conformance - state/gl-get-calls fixes

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/invalid-default-precision.html

The test covers a small selection of invalid types.
It reveals a bug in ANGLE which allows "precision mediump uint;"

Add a test for invalid default precision statements

---

sdk/tests/deqp/modules/shared/glsShaderLibrary.js

Strip leading whitespace from generated shaders to make sure that '#version' is on the first line.

Fixed shader code generation.

---

sdk/tests/conformance/glsl/bugs/constant-precision-qualifier.html

After fixing the bug in ANGLE that made this test fail, it was discovered
that some NVIDIA mobile drivers also have a bug making this test fail.
Add two more versions of the test, one that doesn't use constants and one
that only uses highp variables, so it's easier to narrow down
platform-specific failures of this test.

Add different versions of constant-precision-qualifier test

---

specs/latest/2.0/index.html

Instead of taking third param, texture, as a GLuint it should accept
WebGLTexture? instead.
This change brings framebufferTextureLayer inline with framebufferTexture2D.

The function framebufferTextureLayer has an error.

---

specs/latest/2.0/index.html

So that binding a buffer object has been bound to COPY_READ_BUFFER or COPY_WRITE_BUFFER to ELEMENT_ARRAY_BUFFER will also generate INVALID_OPERATION.
This is because we can upload data directly to a buffer object bound to these
two binding points, so they are no different from other non ELEMENT_ARRAY_BUFFER
binding points.

Change Buffer Object Binding rule

---

specs/latest/2.0/index.html

With an ES3 capable GPU/driver, I don't think it's possible that such requests can't be honored.

Make depth/stencil/antialias drawing buffer attributes required

---

sdk/tests/conformance2/renderbuffers/framebuffer-test.html

Chromium failed on several tests. My patch (https://codereview.chromium.org/1120953002/) can fix some (NOT all) failures in chromium. The other failed cases can be passed in firefox nightly build, although firefox has some other failures too. 
I think the conformance test itself is OK. We should fix the failures in browsers. PTAL.

add test cases for read/draw binding points for framebuffer related APIs against webgl 2.0

---

specs/latest/2.0/index.html
specs/latest/2.0/webgl2.idl

Moved from `Framebuffer` section to `Renderbuffer` section.
Rebuilt webgl2.idl.
fixes #1057

Refiled method `getInternalformatParameter`.

---

sdk/tests/conformance/typedarrays/array-unit-tests.html

As of ES6, the prototypes for typed array constructors point to an intrinsic object whose internal
prototype is Object.prototype. Relevant spec section is 22.2.5.2: TypedArray.prototype.
For test purposes, instead of testing for Object.getPrototypeOf(Int8Array.prototype) being equal
to Object.prototype, we now test Object.getPrototypeOf(Object.getPrototypeOf(Int8Array.prototype)) being equal to Object.prototype. Same goes for the rest of the typed array types.

Modify inheritance hierarchy test to be ES6 compliant

---

conformance-suites/1.0.3/conformance/typedarrays/array-unit-tests.html
sdk/tests/conformance/typedarrays/array-unit-tests.html

While the WebGL conformance suite doesn't focus on ECMAScript
behavior, this test is still useful, and should work with both ES
versions for the time being.
Related to #1052.

Allow both ES5 and ES6 behavior in typed array unit test.

---

sdk/tests/js/tests/gl-object-get-calls.js

Leaving PIXEL_UNPACK_BUFFER bound causes gl.texImage2D(...) to fail in
`getFramebufferAttachmentParameter` section.

Unbind PIXEL_UNPACK_BUFFER after testing.

---

sdk/tests/conformance2/renderbuffers/00_test_list.txt
sdk/tests/conformance2/renderbuffers/invalidate-framebuffer.html

PTAL when you have time.
invalidate framebuffer on default framebuffer in chromium will fail. I suppose there are some errors in command buffer in chromium.

add test cases to invalidateFramebuffer and invalidateSubFramebuffer against WebGL 2

---

sdk/tests/conformance2/query/query.html

Test assumed ANY_SAMPLES_PASSED and ANY_SAMPES_PASSED_CONSERVATIVE were interchangeable types. This was, apparently, a misunderstanding of the manpage language on my part.

Removed small section of query test 

---

sdk/tests/conformance/glsl/bugs/nested-loops-with-break-and-continue.html

Adding together floating point values of different magnitude and without
exact representations could cause error to accumulate in the previous
version of the test. The test failed when being run with
--emulate-shader-precision flag of Chromium, for example. Add integers
instead of floats so that precision issues can be avoided.

Fix a precision issue in nested loop test

---

sdk/tests/deqp/modules/shared/glsShaderLibrary.js

Some dEQP test shaders are indented in an inconsistent way: for example,
some lines might be indented with \<tab\>\<tab\> whereas others have
\<tab\>\<space\>\<tab\>. These two indentations may look the same in an editor,
but when the framework indentation removal function looks at the
indentations, it counts <tab> as indentation by 4 and <space> as
indentation by one. The first line is used as reference and the rest of
the lines get the same amount of indentation removed. With inconsistent
indentation in the source, this could remove some meaningful characters,
like turning "void main()" into "oid main()" unless it is separately
checked that no non-whitespace characters are removed.
This fixes several shader tests, particularly in
deqp/data/gles2/shaders/constants.html.

Don't remove non-whitespace characters when stripping indentations

---

sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-canvas-rgb565.html
sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-canvas-rgba4444.html
sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-canvas-rgba5551.html
sdk/tests/conformance/textures/tex-image-and-sub-image-2d-with-canvas.html
sdk/tests/conformance2/textures/00_test_list.txt
sdk/tests/conformance2/textures/misc/00_test_list.txt
sdk/tests/conformance2/textures/misc/gl-get-tex-parameter.html
sdk/tests/conformance2/textures/misc/tex-input-validation.html
sdk/tests/conformance2/textures/misc/tex-mipmap-levels.html
sdk/tests/conformance2/textures/misc/tex-new-formats.html
sdk/tests/conformance2/textures/misc/tex-storage-2d.html
sdk/tests/conformance2/textures/misc/tex-storage-and-subimage-3d.html
sdk/tests/conformance2/textures/misc/texel-fetch-undefined.html
sdk/tests/conformance2/textures/misc/texture-npot.html
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-canvas.js

So we can put tests for canvas/image/video into sub folders.
Also, refactor tex-image-and-sub-image-2d-with-canvas to accordomate ES3 needs.

Move conformance2/textures tests into conformance2/textures/misc

---

sdk/tests/js/tests/gl-object-get-calls.js

The intent of the WebGL 2.0 version of this test was clearly that a
DEPTH24_STENCIL8 renderbuffer be used. Allocation of this renderbuffer
isn't working correctly in either Chromium or Firefox yet, but the
WebGL 1.0 version of this test still passes with this change.

Fixed #1061: WebGL 2 Conformance - state/gl-object-get-calls

---

sdk/tests/resources/uniformBlockShader.vert

The shader is supposed to be in ESSL 3.00, with "in" instead of
"attribute".
Also, it is somewhat unclear in the spec whether a semicolon is required
after a uniform block declaration (it's not present in all the examples),
but the grammar seems to suggest so.

Fix uniformBlockShader.vert

---

specs/latest/1.0/index.html

Historically WebGL implementations have not posed many restrictions to
operations or variables in global variable initializers. This is a
violation of the OpenGL ES Shading Language spec.
Specify what is allowed in global variable initializers in WebGL.
The new spec is halfway between the actual ESSL spec and the old
de-facto functionality. It is intended to avoid widespread compatibility
regressions in browsers while bringing WebGL closer to the restrictions
in the ESSL spec.

Loosen global variable initialization spec to meet implementations

---

sdk/tests/conformance/glsl/misc/ternary-operator-on-arrays.html
sdk/tests/conformance2/glsl3/ternary-operator-on-arrays-glsl3.html

Require a WebGL 2 context on the ESSL 3 version of the test when it is
run without parameters, and remove extra context init.

Clean up ternary-operator-on-arrays tests

---

specs/latest/2.0/index.html

1) allow DEPTH_STENCIL in renderbufferStorage
2) max token size 1024 for both ESSL1 and ESSL3 shaders.

Small spec updates

---

sdk/tests/conformance/rendering/gl-drawelements.html
sdk/tests/conformance/textures/misc/00_test_list.txt
sdk/tests/js/webgl-test-utils.js

Hook it up with gl-drawelements.html so it runs correctly in both WebGL 1/2.
Also, mark a few tests as WebGL 1 only.

Add a wtu function to query the default context version.

---

sdk/tests/js/tests/gl-enum-tests.js

The shader this was trying to load previously was `#version 300 es`, but this js file was used by both WebGL 1 and WebGL 2 tests. Switched it to use something that works for both.

Fixed failing program creation in gl-enum-tests

---

sdk/tests/conformance2/renderbuffers/framebuffer-test.html

Reorganized the JS code to fix the strict mode failure to resolve #1118.

Move test to function to remove 'use strict' parsing failure.

---

sdk/tests/js/tests/tex-image-and-sub-image-2d-with-canvas.js

When testing with R or RG formats, we won't get the channels that's not there,
so need to filter the expectations of these channels to be 0.

fix a small bug in tex-image-and-sub-image-2d-with-canvas.js

---

sdk/tests/js/tests/tex-input-validation.js

GL_INVALID_ENUM is generated if internalformat, format, or type is not
an accepted constant. GL_INVALID_OPERATION should be generated if
combination of internalformat, format and type is not valid.

Fix format and type validation for TexImage2D and TexSubImage2D

---

sdk/tests/conformance2/rendering/draw-buffers.html

The test was assuming that the first half color attachments would all be red. Update the test to clear all color attachments to red to satisfy this expectation.

Fixup logic error in drawing to MRTs.

---

sdk/tests/conformance2/textures/misc/tex-storage-2d.html

Exercises a previously failing path in Chrome where uploading textures to a cube map allocated with texStorage2d only worked on the TEXTURE_CUBE_MAP_POSITIVE_X face.

Added tests for TexStorage2D + Cube maps

---

sdk/tests/conformance/textures/misc/tex-sub-image-2d-bad-args.html

GL_INVALID_OPERATION is generated if the texture array has not been
defined by a previous glTexImage2D or glCopyTexImage2D operation when
calling glTexSubImage2D.

Add test for texSubImage2D

---

sdk/tests/conformance2/buffers/uniform-buffers.html

Checks basic binding and drawing behavior. Currently fails in Chrome due to ANGLE shader translator bugs (https://code.google.com/p/angleproject/issues/detail?id=1110), but works with Firefox's WebGL2 prototype.

Add simple uniform buffer object test.

---

sdk/tests/webgl-conformance-tests.html

Useful for debugging a subset of the tests. So, for example: If you only wanted to see the WebGL2 portion of the conformance test you could use
`?version=2.0.0&root=conformance2`
Or maybe you're only testing WebGL1 extensions?
`?root=conformance/extensions`

Added query arg to change the test root folder.

---

specs/latest/2.0/index.html

1) when sampler type does not match texture internal format
2) when frag shader output does not match color buffer format.
3) when draw buffers don't have the same color formats, and GRBA bits are queried.

Update WebGL 2 spec to define a few undefined cases in ES3.

---

sdk/tests/conformance/misc/object-deletion-behaviour.html

the test case conformance/misc/object-deletion-behaviour.html failed under WebGL 2 rendering context in Chromium. Because getFramebufferAttachmentParameter gets different value under WebGL 1 and WebGL 2 rendering context. 
GLES 2.0 spec: https://www.khronos.org/opengles/sdk/docs/man/xhtml/glGetFramebufferAttachmentParameteriv.xml, error section: GL_INVALID_ENUM is generated if there is no attached object at the named attachment point and pname is not GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE.
GLES 3.0 spec: https://www.khronos.org/opengles/sdk/docs/man3/html/glGetFramebufferAttachmentParameteriv.xhtml, 
If the value of GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE is GL_NONE, no framebuffer is bound to target. In this case querying pname GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME will return zero (not …

getFramebufferAttachmentParameter gets different value under WebGL 1 and WebGL 2 rendering context

---

sdk/tests/conformance/reading/read-pixels-test.html

And this CL divides the original test into two parts:
1. report INVALID_ENUM for invalid format or type
2. report INVALID_OPERATION for invalid combination of format/type,
but standalone formats or types are valid enums.

fix bugs in read-pixels-test.html in WebGL 2

---

sdk/tests/conformance2/samplers/samplers.html

Test targets are getSamplerParameter and samplerParameter[if].
Checking the pnames and if the default and setting params are correct.
Will add params checking cases later.

Add test cases in sampler for WebGL 2

---

sdk/tests/deqp/framework/opengl/gluShaderProgram.js

This was creating a massive amount of log spew on Chrome's build bots. Left it in when shader compile fails for easy debugging.

Removed unnecessary shader logging

---

specs/latest/2.0/index.html

1. Add unit and sampler states of bindSampler.
2. Add pname states of samplerParameter[if].
3. bindSampler accepts null object but others not.

Supplement WebGLSampler part in WebGL 2 spec

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/vector-dynamic-indexing.html

This test goes through cases where bugs might slip into certain type of
code transformations done to replace dynamic indexing with static
indexing as is required on a HLSL backend of WebGL.

Add test for dynamic indexing of matrices and vectors

---

sdk/tests/webgl-conformance-tests.html

Outputs page and folder level timing information to help diagnose excessively long-running tests.

Added simple timing information to test runs

---

sdk/tests/conformance2/glsl3/short-circuiting-in-loop-condition.html

Fix path to webgl-test-utils.js, add call to finish test and add shader
logging for easier debugging.

Fix minor issues in short-circuiting in loop condition test

---

sdk/tests/conformance/more/unit.js
sdk/tests/conformance/ogles/ogles-utils.js
sdk/tests/js/glsl-conformance-test.js
sdk/tests/js/js-test-pre.js
sdk/tests/js/webgl-test-harness.js
sdk/tests/js/webgl-test-utils.js
sdk/tests/webgl-conformance-tests.html

This mode drastically decreases the amount of DOM output the tests do, which can lead to decent speed-ups on automated testing systems which don't care about this output anyway.

Implemented quiet mode

---

sdk/tests/webgl-conformance-tests.html

It was pointed out that Safari on Mavericks and iOS8 don't have performance.now yet. This is a less accurate replacement, but I don't think the precision is needed in this case.

Replaced performance.now with Date.now for broader compatibility

---

sdk/tests/conformance/extensions/ext-disjoint-timer-query.html

The isQueryEXT() call should return false until beginQueryEXT() is
called. This should match the OpenGL ES 3.0 behavior outlined in
section 2.13:
These names are marked as used, for the purposes of GenQueries
only, but no object is associated with them until the first time
they are used by BeginQuery.
This same behavior is outlined in the original OpenGL ES
EXT_Disjoint_Timer_Query spec.
The failure values tested for beginQueryEXT and getQueryObjectEXT
should both be INVALID_OPERATION as outlined in the error section
of the EXT_disjoint_timer_query spec.

Modified EXTDisjointTimerQuery conformance tests to match the spec.

---

sdk/tests/conformance2/buffers/buffer-copying-restrictions.html

The behavior being changed is described by section 5.1 and 5.2 of the WebGL 2 spec

Fix conformance2/buffers/buffer-copying-restrictions spec conflicts.

---

sdk/tests/conformance/extensions/ext-disjoint-timer-query.html

Previously the conformance test for EXT_disjoint_timer_query
only looked for error results. I've added a simple test which
tests that the query makes sure the results become available
and give reasonable results.

Added more real query tests to ext-disjoint-timer-query.html.

---

sdk/tests/js/tests/gl-object-get-calls.js

Fix a getFramebufferAttachmentParameter bug

---

sdk/tests/conformance/glsl/misc/global-variable-init.html

This is to restore coverage that was lost when
glsl/misc/ternary-operators-in-global-initializers.html was recently
changed.
See #1168.

Add new tests for ternary operators in global initializers

---

sdk/tests/deqp/framework/opengl/gluShaderProgram.js
sdk/tests/deqp/functional/gles3/es3fTransformFeedbackTests.js

- Don't resume transform feedback after every draw call.
- Fixed vector type iteration in es3fTransformFeedbackTests.isProgramSupported.
- Fixed bug in es3fTransformFeedbackTests.hasArraysInTFVaryings.
- Fixed ShaderProgram.isOk() to properly report link errors.
- Dump program info log if link fails.

Fixed bugs affecting transform feedback test.

---

sdk/tests/conformance/rendering/00_test_list.txt
sdk/tests/conformance/rendering/default-texture-draw-bug.html

Issue uncovered by the OES_element_index_uint extension test, as described here: https://code.google.com/p/chromium/issues/detail?id=524144

Added test for default texture draw bug in Chrome

---

sdk/tests/conformance2/textures/misc/tex-storage-and-subimage-3d.html

When testing dimension out of range, level should be correct. Otherwise,
test result isn't what we want.

Fix wrong level of texSubimage3D

---

sdk/tests/conformance/extensions/oes-element-index-uint.html

This test was accidentally rendering with the 0 texture, which worked
because it was expecting black to be drawn. This exposed a bug in
Chrome, and a separate test has been created to provoke it and ensure
drawing with texture 0 results in black, but for this test it's better
for the draw call to explicitly draw a black quad without unnecessary
texture sampling.

Fix draw referencing a texture that was never bound

---

sdk/tests/js/tests/tex-image-and-sub-image-2d-utils.js

A minor fix to get integer format texture tests to work.
Otherwise these two shaders won't compile.

Fix a bug in js/tests/tex-image-and-sub-image-2d-utils.js

---

sdk/tests/deqp/build.py
sdk/tests/deqp/framework/delibs/debase/deMath.js
sdk/tests/deqp/framework/opengl/simplereference/referencecontext.html
sdk/tests/deqp/framework/referencerenderer/rrRenderer.js
sdk/tests/deqp/functional/gles3/00_test_list.txt
sdk/tests/deqp/functional/gles3/booleanstatequery.html
sdk/tests/deqp/functional/gles3/es3fFboRenderTest.js
sdk/tests/deqp/functional/gles3/es3fFloatStateQueryTests.js
sdk/tests/deqp/functional/gles3/es3fIntegerStateQueryTests.js
sdk/tests/deqp/functional/gles3/es3fOcclusionQueryTests.js
sdk/tests/deqp/functional/gles3/es3fSamplerStateQueryTests.js
sdk/tests/deqp/functional/gles3/es3fShaderStateQueryTests.js
sdk/tests/deqp/functional/gles3/es3fTextureStateQuery.js
sdk/tests/deqp/functional/gles3/es3fTransformFeedbackTests.js
sdk/tests/deqp/functional/gles3/floatstatequery.html
sdk/tests/deqp/functional/gles3/integerstatequery.html
sdk/tests/deqp/functional/gles3/rasterizerdiscard.html
sdk/tests/deqp/functional/gles3/samplerstatequery.html
sdk/tests/deqp/functional/gles3/texturestatequery.html
sdk/tests/deqp/modules/shared/glsShaderExecUtil.js
sdk/tests/deqp/modules/shared/glsStateQuery.js

New tests for: sampler state, texture state, integer and floating point state parameters.
Fixed querying result in occlusion query test.
Added stencil context creation parameter where tests are using stencil buffer.
Fixed Fbo render test to skip over unsupported formats instead of reporting errors.
Fixed TF test to skip unsupported cases.
Fixed framework code for getting test results in transform feedback buffers.

Added state query tests and bugfixes.

---

extensions/proposals/WEBGL_debug/extension.xml

This extension mirrors the KHR_debug GLES extension.
I am not totally sure about the level of detail required in such an extension, everything being already defined in the mirrored specification, but I tried to be exhaustive in the changes done.
I am also unsure about the naming of functions and tokens, but following some other extensions it seems the original suffixes are to be kept in the WebGL version.
And finally, should I put those questions in the issues section instead? :)

Added proposal for the WEBGL_debug extension

---

sdk/tests/conformance2/glsl3/vector-dynamic-indexing.html

This makes sure that indexing workarounds work also for uints.

Add a test that indexes a vector using a uint

---

extensions/proposals/EXT_texture_storage/extension.xml

I've started [discussion](https://www.khronos.org/webgl/public-mailing-list/archives/1509/msg00000.php) on webgl_public about texture_storage extension, and people suggested to make a proposal for such an extension.
There is no contribution guide for extensions, so I've copied template and filled it with information which made sence to me. I'm keen to make it right though.

Added proposal for EXT_texture_storage

---

sdk/tests/conformance/extensions/angle-instanced-arrays.html
sdk/tests/js/webgl-test-utils.js

Problems with interaction between these two extensions was noted in
Issue #1228. Test currently fails on Chrome when using ANGLE, but
succeeds with --use-gl=desktop. Firefox also handles the new test
correctly.

Extend angle-instanced-arrays test to check VAO interaction

---

sdk/tests/deqp/functional/gles3/es3fBufferCopyTests.js

For copyBufferSubData, ELEMENT_ARRAY_BUFFER are compatible with
COPY_READ_BUFFER and COPY_WRITE_BUFFER only if the COPY_READ/WRITE
buffer had been initially bound to an ELEMENT_ARRAY_BUFFER
This behavior is covered in buffer-copying-restrictions.html,
so skip these tests in buffercopy.js

fix the bugs in buffercopy.js

---

sdk/tests/conformance/extensions/ext-sRGB.html

This uncovers bugs related to the sRGB color space conversion.

Updated EXT_sRGB conformance test to use checkCanvasRect correctly

---

sdk/tests/conformance/glsl/bugs/pow-with-constant-exponent-should-not-crash.html
sdk/tests/js/glsl-conformance-test.js

Result of (x^2)^0.5 may differ from x enough to affect the result of the
test if the mediump pow function is run at the precision suggested in the
GLSL ES 3.00 spec, where it inherits its precision from exp2(y*log2(x)).
The lack of tolerance caused the test to fail at least on Nexus 5.

Add tolerance to pow-with-constant-exponent test

---

specs/latest/2.0/index.html

This specification language is derived from that in the EXT_disjoint_timer_query extension. It is intended to ensure best portability and performance of code using query objects. The ported dEQP tests in the WebGL 2.0 conformance suite have already been adjusted to follow this requirement. The EXT_disjoint_timer_query conformance test will be updated shortly to follow the same requirement.

A query's result must not become available the same frame it was issued.

---

sdk/tests/conformance/buffers/buffer-data-and-buffer-sub-data.html

bufferData has an integer overload and an ArrayBuffer overload.
Per the WebIDL spec, the overload resolution algorithm should resolve types as follows:
- If the argument is null or undefined, pick the nullable type, which is ArrayBuffer.
Per the WebGL spec, null should flag INVALID_VALUE.
- If the argument is an ArrayBuffer, then pick the ArrayBuffer overload
- Everything else should pick the numeric overload. This means things like objects, strings, floating point numbers, arrays of numbers and strings, etc should convert themselves to an integer.
Unlike bufferData, bufferSubData is typed to accept an ArrayBuffer. No overloads.
Per the WebIDL spec, passing undefined should convert to null.  Per the WebGL spec, null should
flag an INVALID_VALUE error.

Add bufferData and bufferSubData test cases

---

sdk/tests/conformance/extensions/ext-disjoint-timer-query.html

This is a follow-up to #1240 enforcing the behavior for
EXT_disjoint_timer_query. Has been tested with Chromium's
work-in-progress CL. Will revise more of the WebGL 2.0 tests that use
query objects in a follow-on pull request.

Verify that queries' results don't become available in a spin loop.

---

sdk/tests/conformance/extensions/angle-instanced-arrays.html
sdk/tests/conformance/extensions/ext-blend-minmax.html
sdk/tests/conformance/extensions/ext-frag-depth.html
sdk/tests/conformance/extensions/ext-shader-texture-lod.html
sdk/tests/conformance/extensions/oes-standard-derivatives.html
sdk/tests/conformance/extensions/oes-texture-half-float.html

A few of these tests were leaving around a global reference to the
extension object, so the attempted garbage collection of the JavaScript
wrapper was having no effect. Nulling out the global reference exposes
more bugs in WebGL implementations.

Fixed bugs in extensions' unique object tests.

---

sdk/tests/conformance/misc/expando-loss.html

It was attaching renderbuffers that hadn't yet been fully
initialized (never bound to the RENDERBUFFER binding point) to a
framebuffer object, causing an INVALID_OPERATION error.

Fixed bug in expando-loss.html test.

---

sdk/tests/deqp/data/gles2/shaders/preprocessor.test
specs/latest/1.0/index.html
specs/latest/2.0/index.html

When ANGLE implemented a fix to this test in May 2015, significant issues
with backwards compatibility were detected. It was decided that the ESSL1
compiler should issue a warning rather than an error in this case, though
the WebGL spec was not updated.
The spec is still strictly enforced in the case of ESSL3 shaders and
WebGL 2 with a similar gles3 dEQP test.

Remove dEQP #extension directive test to keep backwards compatibility

---

sdk/tests/conformance/extensions/ext-disjoint-timer-query.html

This is per David Yen's review of https://codereview.chromium.org/1385793002 .

Verify that fetching result or availability from active query fails.

---

extensions/EXT_disjoint_timer_query/extension.xml
specs/latest/2.0/index.html

Based on feedback from Jeff Gilbert from Mozilla, revised language to indicate solely that control must return to the browser's main loop in order for queries' results to become available. Follow-on to #1240.

Revised language regarding queries' result availability.

---

conformance-suites/1.0.2/conformance/textures/mipmap-fbo.html
conformance-suites/1.0.3/conformance/textures/mipmap-fbo.html
sdk/tests/conformance/textures/misc/mipmap-fbo.html

Improve the existing test case in the following ways:
-Change the size of the mipmapped texture so that it is minified when
drawing and two levels actually need to be sampled.
-Specify viewport when the framebuffer dimensions change.
-Use RGBA format. Support for RGB framebuffer attachments is not
guaranteed by the spec. This bugfix is ported also to versions 1.0.3
and 1.0.2 of the conformance suite.
Also add a separate subtest for using a cube map face with incomplete
mipmaps as a framebuffer attachment.
These tests already pass at least on Chrome and Firefox on Windows and
Linux with NVIDIA HW.

Improve mipmap-fbo test

---

sdk/tests/conformance/textures/misc/00_test_list.txt
sdk/tests/conformance/textures/misc/cube-incomplete-fbo.html
specs/latest/1.0/index.html

This rule is added to improve the portability of WebGL implementations -
some underlying GL implementations enforce this restriction found in
newer OpenGL specs and working around it is complex. The backwards
compatibility impact of enforcing this rule in WebGL is expected to be
minimal.
This rule is not extended to require mipmap completeness as well, as
using non-mipmap complete attachments is already covered by WebGL tests
and working, and there might be content relying on that.

Require that framebuffer attachments are cube complete

---

sdk/tests/conformance2/misc/expando-loss-2.html

Added WebGL 2 version of conformance2misc/expando-loss.html. Currently fails in Chrome but succeeds in Firefox nightlies.

Added expando loss test for WebGL 2 object types

---

sdk/tests/conformance2/query/00_test_list.txt
sdk/tests/conformance2/query/occlusion-query.html
sdk/tests/conformance2/transform_feedback/transform_feedback.html
sdk/tests/deqp/functional/gles3/es3fTransformFeedbackTests.js
sdk/tests/deqp/functional/gles3/transformfeedback.html

Queries' results must not become available until control returns to the browser's event loop. Verify this for ANY_SAMPLES_PASSED and ANY_SAMPLES_PASSED_CONSERVATIVE occlusion queries in a new targeted test, and modify the transform_feedback test to verify this for TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN queries (which require more setup code).
Change the ported dEQP transform feedback test to enforce that the query's result is as expected, since the logic was recently changed to obey the new specification rules. Fix a bug in the computation of the expected number of primitives.

Test availability of queries' results per WebGL 2.0 spec rules.

---

sdk/tests/conformance2/textures/misc/tex-storage-2d.html

Float type texture isn't texture filterable in ES 3.0.
A texture isn't complete if its internal color format is not
texture-filterable and either the magnification filter is not NEAREST or
the minification filter is neigher NEAREST nor NEAREST_MIPMAP_NEAREST.
Chrome will use a black texture for texture being accessed is not
complete which causes tex-storage-2d.html to fail.

Restrict mag filter to NEAREST for float type texture

---

sdk/tests/deqp/data/gles2/shaders/keywords.test
sdk/tests/deqp/data/gles3/shaders/keywords.test

This removes double underscore test cases from dEQP. After this commit,
the dEQP tests don't address double underscores in identifiers in any
way. Using double underscores in identifiers is covered elsewhere in the
WebGL conformance suite, so the intent of this patch is simply to bring
the copy of the tests closer to latest native dEQP, not to change the
expected behavior.
The other test that makes sure double underscores are not allowed in
identifiers is:
/conformance/glsl/misc/shader-with-reserved-words.html

Update dEQP shader keywords tests from deqp-dev

---

sdk/tests/conformance/extensions/oes-texture-float-with-image-data.html
sdk/tests/conformance/extensions/oes-texture-half-float-with-image-data.html
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-data.js

The test script [sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-data.js](../blob/master/sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-data.js) populates a 2x2 test image, but `conformance/extensions/oes-texture*-with-image-data.html` tests use 1x2 canvas, which results in no-op checks. This is fixed in the pull request.
Additionally, the test script checks all four image pixels, and it should not check out-of-canvas-bounds areas.

Fix OES 2D texture with image data tests.

---

sdk/tests/conformance/glsl/bugs/floor-div-cos-should-not-truncate.html

This test exposes a bug in the floor() funtion on Intel GPUs with ANGLE's Direct3D 9 backend.
Will add this to the 00_test_list.txt as soon as it's been confirmed that this reproduces on the target hardware.

Incorporated regression test from Austin Appleby from Google Maps team.

---

sdk/tests/conformance/glsl/bugs/00_test_list.txt

Confirmed that this fails in Chrome Canary on an Intel GPU with the command line argument --disable-d3d11.

Add test from Austin Appleby from Google Maps team.

---

sdk/tests/conformance/textures/misc/tex-sub-image-2d-bad-args.html

ES3 doesn't have such limitation for texSubImage2D. Chrome removed the
restrict in https://codereview.chromium.org/1344373004/.

Don't match the type for TexSubImage2D in ES3

---

specs/latest/2.0/index.html

This was resolved by the working group a long time ago for portability but was never incorporated into the specification. At the time, confirmed with the OpenGL ES working group that this restriction does not impose a performance penalty.

Declare that only the std140 layout is supported for uniform blocks.

---

specs/latest/2.0/index.html

This restriction seems to have been based on a too-strict reading of the ES 2.0 spec, and is no longer a useful restriction for ES 3.0. See https://codereview.chromium.org/1344373004/ and http://crbug.com/532708 for more background.

Remove restriction on texture type in texSubImage2D calls.

---

sdk/tests/deqp/data/gles2/shaders/preprocessor.test
sdk/tests/deqp/data/gles3/shaders/preprocessor.test
sdk/tests/deqp/modules/shared/glsShaderLibrary.js
sdk/tests/deqp/modules/shared/glsShaderLibraryCase.js

Pull in latest changes to the tests from deqp-dev branch.
This contains the following changes:
-Double underscores in macro names are now expected to be accepted by the
compiler. See previous discussion in pull request #1230.
-Unrecognized pragmas are now expected to be accepted by the compiler.
ESSL 1.00 and 3.00 specs say "If an implementation does not recognize
the tokens following #pragma, then it will ignore that pragma".
-Non-matching varying invariance is fixed in some #pragma tests.
-Added tests for "defined" operator corner cases for ESSL 3.00 (now
covered by WebGL 1.0 spec section 6.31)
-Added tests for backslash in a comment for ESSL 3.00
gles2/shaders/preprocessor.test is not a direct copy from dEQP, since
WebGL-specific changes apply to the behavior of extension directives. …

Update dEQP shader preprocessor tests from deqp-dev

---

sdk/tests/deqp/framework/common/tcuImageCompare.js
sdk/tests/deqp/framework/common/tcuLogImage.js
sdk/tests/deqp/functional/gles3/es3fFragmentOutputTests.js
sdk/tests/deqp/functional/gles3/es3fShaderCommonFunctionTests.js

After these fixes, a lot of the tests pass in latest Chromium.
Bugs fixed:
1. Pass the whole array being indexed to readVec4 and readIVec4,
JavaScript doesn't have pointers.
2. Keep indices bound to ELEMENT_ARRAY_BUFFER when calling drawElements.
3. Remove incorrect Math.floor() calls in places where the intent is to
do calculations in floating point (see native dEQP).
4. Call setPixelInt instead of setPixel when rendering int reference.
5. Upload integer buffer data converted to Int32's instead of Float32's.
6. Fix minimum integer in integer range. Also fix similar issue in
another test.
7. Add in missing gl.readBuffer call for tests that draw into multiple
buffers.
Also fix general issues in tcuImageCompare:
1. Report failed image comparison to test harness.
2. Set error mask values …

Fix bugs in dEQP fragment output test

---

sdk/tests/deqp/framework/common/tcuTexture.js

These bring the port in line with native dEQP, fixing the reference
rendering in most of the texture2darrayshadow tests.
1. Pass entire offset instead of just the first value when calling
sampleNearest2D() in sample2DCompare().
2. Remove extraneous Math.round from sampleNearest*().

Fix dEQP texture sampling when generating reference images

---

sdk/tests/conformance2/glsl3/short-circuiting-in-loop-condition.html

Test having a short circuiting operator in the for loop expression, in
do-while loop condition, and inside a sequence operator in a loop
condition.
Also make the while loop test a bit more intuitive. Shuffling around
a few operations makes the sideEffectCounter value at the end match
the number "iterations" is compared against.

Improve short circuiting in loop condition test

---

sdk/tests/conformance/more/functions/uniformi.html

Will fix our being puzzled when looking at that failure. http://build.chromium.org/p/chromium.gpu.fyi/builders/Linux%20Release%20%28ATI%29/builds/43033
It says it runs uniformi and fails with testUniformf

Fix typo in uniformi.html

---

sdk/tests/conformance/misc/expando-loss.html

In WebGL 2.0, DEPTH_STENCIL_ATTACHMENT is considered an alias for
DEPTH_ATTACHMENT + STENCIL_ATTACHMENT. Attaching a different render
buffer to STENCIL_ATTACHMENT would make different images bound to depth
and stencil attachment points.
If attachment is DEPTH_STENCIL_ATTACHMENT and different images are bound
to the depth and stencil attachment points, getFramebufferAttachmentParameter
generates an INVALID_OPERATION error. Move DEPTH_STENCIL_ATTACHMENT to
the end of the attachments array to avoid such issue.

Fix invalid operation on framebuffer in expando-loss.html

---

sdk/tests/conformance/rendering/framebuffer-switch.html
sdk/tests/conformance/rendering/framebuffer-texture-switch.html
sdk/tests/conformance/textures/misc/texture-fakeblack.html

The WebGL 1 spec guarantees that RGBA/UNSIGNED_BYTE textures are renderable (valid framebuffer formats), but it does not guaratee that RGB/UNSIGNED_BYTE textures are. 
(See GLES 2.0.25, p117, Table 4.5 for the list of renderable formats in GLES2)

Use RGBA for renderable textures, as RGB isn't renderable.

---

sdk/tests/conformance2/buffers/uniform-buffers.html

multiple uniform blocks in shader will expose an bug in Chromium. PTAL.

multiple uniform blocks in shader should be well-supported

---

sdk/tests/conformance/context/context-lost-restored.html
sdk/tests/conformance/extensions/ext-sRGB.html
sdk/tests/conformance/extensions/oes-texture-float.html
sdk/tests/conformance/extensions/oes-texture-half-float.html
sdk/tests/conformance/extensions/webgl-depth-texture.html
sdk/tests/conformance/extensions/webgl-draw-buffers.html
sdk/tests/conformance/more/functions/texImage2DBadArgs.html
sdk/tests/conformance/more/functions/texSubImage2DBadArgs.html
sdk/tests/conformance/more/util.js
sdk/tests/conformance/renderbuffers/framebuffer-test.html
sdk/tests/conformance/textures/misc/tex-sub-image-2d-bad-args.html
sdk/tests/conformance/textures/misc/texture-formats-test.html
sdk/tests/js/webgl-test-utils.js

There are a number of tests that assume the most obvious GL errors will be generated. However, a single function call can match multiple error generation criteria.
I add functions that take a list of possible errors, and make sure that the generated error in the given list.

Fix some tests to allow ambiguous error cases.

---

extensions/extension.xsl

The extension registry front page already mentions that extensions
promoted to core are no longer available in the version where they were
promoted, but it's nicer if that is also clearly stated on each
individual extension's page.

Make extension status in WebGL 2.0 clearer on extension pages

---

sdk/tests/conformance2/renderbuffers/invalidate-framebuffer.html

Samplers for all attachments of the fbo should be the same.
Otherwise, it will lead to FRAMEBUFFER_INCOMPLETE

Fix bug in invalidate-framebuffer.html.

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/const-array-init.html

Constant array initialization in the global scope can be problematic,
for the combination of these reasons:
1. It's often undesirable to constant fold array constructors.
2. Constant array constructors that are not folded may need to be
implemented using function calls on HLSL.
3. Function calls are not allowed in the global scope.
So a WebGL test for this is necessary.

Add a simple ESSL3 test for constant array initialization

---

sdk/tests/conformance/glsl/bugs/00_test_list.txt
sdk/tests/conformance/glsl/bugs/angle-constructor-invalid-parameters.html

Passing invalid parameters to constructors can pass shader validation
with the current version of ANGLE. Most driver compilers should fail
compilation and the test will still pass, but running the test does cause
issues at least on OSS NVIDIA Linux driver stack.

Add a test for ANGLE constructor bugs

---

sdk/tests/conformance2/textures/misc/tex-storage-compressed-formats.html

Trying with TEXTURE_3D is INVALID_OPERATION.
TEXTURE_2D_ARRAY should work though.

ES3 (ETC2/EAC) textures work with 2D_ARRAY, but not 3D.

---

sdk/tests/conformance2/00_test_list.txt
sdk/tests/conformance2/extensions/00_test_list.txt
sdk/tests/conformance2/extensions/ext-color-buffer-float.html

This is largely a copy of the OES_texture_float extension test, but with the format creation checks removed (they should be implicit with WebGL 2.0) and some checks added to ensure those formats can't be bound until the extension is enabled.

Added conformance test for EXT_color_buffer_float

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/forbidden-operators.html
specs/latest/2.0/index.html

Supporting ternary and sequence operators on void and arrays is likely to
be made optional in GLSL ES 3.00 according to current draft for a future
version of the spec. For WebGL, it's the best to disallow any features
that may not be implemented on all reasonable target platforms. These
restrictions on target platforms could be worked around, but that adds an
extra burden on implementations for very little gain in corner case
features in this case.

Add disallowed variants of ESSL3 operators to spec

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/texture-offset-out-of-range.html
specs/latest/2.0/index.html

Texture offset is required to be constant, so validating it against the
correct range can be done at compile time. Add a test for this and edit
the WebGL 2.0 spec.

Mandate texture offset validation at compile time

---

conformance-suites/1.0.3/conformance/extensions/webgl-draw-buffers.html
sdk/tests/conformance/extensions/webgl-draw-buffers.html

When the default framebuffer is bound, EXT_draw_buffers defines certain
error cases as generating INVALID_OPERATION, not INVALID_VALUE. Thanks
to @jdashg for discovering this issue in #1303. This test fix has been
backported to 1.0.3, where the test was introduced. It causes Chrome and
Firefox to begin to fail the test, but the browsers must be fixed.

Fixed expected errors in WEBGL_draw_buffers conformance test.

---

sdk/tests/js/tests/tex-image-and-sub-image-utils.js
sdk/tests/resources/samplerForWebGL2UniformShader.frag

New sampler types introduced in ESSL 3.00 don't have a default precision
qualifier according to ESSL 3.00.4 section 4.5.4.

Add missing precision qualifiers for samplers in shaders

---

sdk/tests/conformance2/extensions/00_test_list.txt
sdk/tests/conformance2/extensions/promoted-extensions-in-shaders.html

Test that trying to enable promoted extensions in shaders results in
compilation failure, and that the compiler flags for the shaders are
not defined.

Add test for extensions that have been promoted to core

---

sdk/tests/conformance/extensions/00_test_list.txt

This extension is exposed against the WebGL 2.0 context as well as the 1.0 context and the test should be run there as well.

Run EXT_disjoint_timer_query test against WebGL 2.0 contexts.

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/sampler-no-precision.html

Sampler types introduced in ESSL3 don't have predefined default
precision. Test that trying to declare samplers with no precision
qualifier fails compilation.

Add a test for sampler variables with no precision

---

sdk/tests/conformance/textures/misc/00_test_list.txt
sdk/tests/conformance2/textures/misc/00_test_list.txt
sdk/tests/conformance2/textures/misc/compressed-tex-image.html

This is copied from conformance/textures/misc/compressed-tex-image.html.
Modified number of supported compressed texture format from 0 to 10. ES3
adds 10 compressed texture formats for CompressedTex{Sub}Image{2D|3D}.

Added new compressed texture formats for WebGL 2.0

---

sdk/tests/deqp/functional/gles3/es3fNegativeTextureApiTests.js

Don't need to test "-1" image size for compressedTexImage2D in WebGL due
to no such parameter for WebGL api.

Fix dEQP test compressedteximage2d_invalid_size

---

sdk/tests/conformance/extensions/webgl-compressed-texture-atc.html
sdk/tests/conformance/extensions/webgl-compressed-texture-pvrtc.html
sdk/tests/conformance/extensions/webgl-compressed-texture-s3tc.html

WebGL 2.0 supports 10 new compressed texture formats.

Update compressed texture extension tests for WebGL 2.0

---

sdk/tests/deqp/functional/gles3/es3fTextureFormatTests.js

glsTextureTestUtil.sampleTexture2DArray requires a
tcuTexture.Texture2DArrayView object but a tcuTexture.Texture2DArray
object is passed in. In the native dEQP test, there is an implicit type
conversion from Texture2DArray to Texture2DArrayView. This patch does
explict type conversion in js.

Fix wrong parameter passed to glsTextureTestUtil.sampleTexture2DArray

---

sdk/tests/deqp/functional/gles3/es3fNegativeTextureApiTests.js

Two violations are tested in a test: format mismatch and invalid null
data. This patch isolates them. Validate format mismatch in
compressedtexsubimage2d. Invalid null data is already validated in
compressedtexsubimage2d_invalid_size.

Isolate different testing for compressedtexsubimage2d

---

sdk/tests/deqp/functional/gles3/es3fNegativeBufferApiTests.js

Fix the bug of http://code.google.com/p/chromium/issues/detail?id=565347. The Blink side CL is at https://codereview.chromium.org/1495963002. 

fix the bug when calling renderbufferStorageMultisample in negativebufferapi

---

sdk/tests/deqp/modules/shared/glsAttributeLocationTests.js

In dEQP test, set is emulated with array type. We should avoid duplicate
elements in such set. "conditions" in the native implementation is a
set, so check if element is already in it before inserting.

dEQP: avoid duplicate elements in set emulated with array type

---

sdk/tests/conformance2/reading/read-pixels-into-pixel-pack-buffer.html

This is the ReadPixels with a bound PIXEL_PACK_BUFFER case.
I'll add another test for ReadPixels with no bound PIXEL_PACK_BUFFER in a followup CL.

Upgrade ReadPixels to take into consideration ES3 pack parameters.

---

sdk/tests/conformance2/reading/read-pixels-into-pixel-pack-buffer.html
sdk/tests/conformance2/reading/read-pixels-pack-parameters.html

Now read-pixels-pack-parameters.html tests both using and not using PIXEL_PACK_BUFFER.

Move tests around to reduce code duplication.

---

sdk/tests/deqp/functional/gles3/es3fNegativeStateApiTests.js

getActiveUniform and getActiveAttrib have no bufSize argument at all. This feature is different from that in native API. I suppose the implementation in browser always allocate memory and set a correct bufSize to call into native API, no glError will be generated. 
This patch deleted these 2 code snippets to fix failures in negativestateapi.html in WebGL dEQP conformance test. Here is the crbug: http://code.google.com/p/chromium/issues/detail?id=565347

test cases of bufSize < 0 for getActiveUniform and getActiveAttrib are not necessary

---

sdk/tests/js/tests/gl-enum-tests.js

The original test case use a standard program, which have no uniformBlock at all. When call into
getActiveUniformBlockParameter(program, 0, desktopGL['UNIFORM_BLOCK_NAME_LENGTH'])
, both the index and pname are invalid. We should generate INVALID_VALUE and INVALID_ENUM for invalid index and invalid pname respectively. But the original test case expect an INVALID_ENUM. This lead to my CL(https://chromiumcodereview.appspot.com/1495113004/) failed.
See the [Errors] section in gles3 man page for invalid index and invalid pname: https://www.khronos.org/opengles/sdk/docs/man3/html/glGetActiveUniformBlockiv.xhtml. 
"GL_INVALID_VALUE is generated if uniformBlockIndex is greater than or equal to the value of GL_ACTIVE_UNIFORM_BLOCKS or is not the index of an active uniform block in program"
This …

fix the ambiguous test case of getActiveUniformBlockParameter

---

sdk/tests/deqp/functional/gles3/es3fNegativeBufferApiTests.js

Native implementation is here: https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fNegativeBufferApiTests.cpp#1198

Fix wrong destination framebuffer in es3fNegativeBufferApiTests.js

---

specs/latest/1.0/index.html
specs/latest/2.0/index.html

A too-small ArrayBufferView should generate INVALID_OPERATION, not INVALID_VALUE, because under different circumstances the same ArrayBufferView argument could be valid. Clarified this in both the 1.0 and 2.0 specs. This is already tested by conformance/textures/misc/tex-image-with-invalid-data.html . Recent changes to the 2.0 spec were incorrect.
Passing an ImageData whose data attribute has been neutered should generate INVALID_VALUE, since such an ImageData object is never a valid argument. This will be tested by a forthcoming pull request.

Clarify TexImage and TexSubImage errors.

---

sdk/tests/conformance/glsl/bugs/constant-precision-qualifier.html

All of the cases in this test try to assign highp 4096.5 to "c" and then
check that the precision qualification of that variable affects the
result of a subsequent operation. One of the cases had the error that
"4096.5 + uTest" could be evaluated at mediump due to uTest being
mediump, even if the target of the assignment was highp. Fix this by
adding a separate highp uniform variable to the test.
The earlier version of this test in 1.0.3 doesn't have this bug.

Fix one test case in constant-precision-qualifier.html

---

sdk/tests/conformance/glsl/misc/shaders-with-constant-expression-loop-conditions.html

The same identical test should only be run once.

Remove duplicate test case for constants in loop conditions

---

sdk/tests/conformance/glsl/bugs/undefined-index-should-not-crash.html

The shaders contained an invalid assignment, even though they were only
intended to contain invalid indexing with "int()".

Fix unintentional error in undefined index test shaders

---

sdk/tests/deqp/functional/gles3/es3fRboStateQueryTests.js

Max samples supported for a specific internalformat may differs from max samples for multisampling. The former should be less than or equal to the latter. 
This is the root cause of the failures in the WebGL 2 CTS on OSX. See this reverted CL: https://codereview.chromium.org/1495963002/.
PTAL, thanks a lot!

use the max samples supported for the specific internalformat

---

sdk/tests/deqp/functional/gles3/es3fRboStateQueryTests.js

Reverts KhronosGroup/WebGL#1368

Revert "use the max samples supported for the specific internalformat"

---

sdk/tests/deqp/functional/gles3/es3fNegativeVertexArrayApiTests.js

The original code uses 'null' program for instanced drawing. It always generate INVALID_OPERATION. This is ambiguous for many other case to generate appropriate glError, except the one that need to test this feature. 
When count or primcount are negative in drawArraysInstanced/drawElementsInstanced,  Chromium should generates INVALID_VALUE, but it generated INVALID_OPERATION because the original code uses 'null' program for all cases. Now it is fixed. 
I think the original deqp code need to be revised too: https://android.googlesource.com/platform/external/deqp/+/deqp-dev/modules/gles3/functional/es3fNegativeVertexArrayApiTests.cpp
PTAL. Thanks.

fix the ambiguous test cases for instanced drawing in NegativeVertexArrayAPI

---

sdk/tests/deqp/functional/gles3/es3fNegativeTextureApiTests.js

Related chromium fix is at: https://codereview.chromium.org/1527723003/.

Disallow null pixels data for CompressedTex{Sub}Image{2D|3D}

---

sdk/tests/conformance2/textures/misc/compressed-tex-image.html

https://codereview.chromium.org/1527723003/ fixes this test.

Throw exception if pixels data is null for CompressedTex{Sub}Image

---

sdk/tests/deqp/functional/gles3/es3fNegativeVertexArrayApiTests.js

According to the WebGL spec, If no buffer bound to ARRAY_BUFFER object, INVALID_OPERATION should be generated against vertexAttribPointer. Then no tests in vertex_attrib_pointer will succeed. 
This small change create a buffer and bind it to ARRAY_BUFFER. 
PTAL. Thanks.

bind buffer to ARRAY_BUFFER target for vertexAttribPointer

---

sdk/tests/deqp/functional/gles3/es3fNegativeVertexArrayApiTests.js

According to the WebGL spec, If no buffer bound to ARRAY_BUFFER object, INVALID_OPERATION should be generated against vertexAttribIPointer. This is ambiguous to test other invalid operations. 
See the similar one https://github.com/KhronosGroup/WebGL/pull/1378. 
PTAL. Thanks!

bind buffer to ARRAY_BUFFER target for vertexAttribIPointer

---

sdk/tests/deqp/functional/gles3/es3fNegativeShaderApiTests.js

A small change to fix the bug. 
We need to add variables into 'tfVaryings' to make the array length exceed the max number of supported transformFeedbackVarying separate attribs.

add variables into tfVaryings to test transformFeedbackVaryings

---

sdk/tests/deqp/functional/gles3/es3fNegativeShaderApiTests.js

However, it is not possible to set a uniform location directly in WebGL.
This change removed uniformf_invalid_location in negativeshaderapi.html.
We can get uniform location from one program, then compile and link another program and call into uniform[1234]f to that uniform location. But this is different from the native deqp tests. And it is covered by conformance test already.  So I prefer to remove these tests directly.
WDYT?

In native tests, we can set a uniform location and call uniform[1234]f.

---

sdk/tests/deqp/functional/gles3/es3fNegativeShaderApiTests.js

According to the WebGL spec: If the array passed to any of the vector forms (those ending in v) has an invalid length, an INVALID_VALUE error will be generated. The length is invalid if it is too short for or is not an integer multiple of the assigned type. 
So the original tests are ambiguous, which lead to failures. The change set appropriate vectors to those uniform*fv APIs, in order to get the only expected error.

vector's length should be conform to WebGL spec in uniform*fv

---

sdk/tests/js/webgl-test-utils.js

The bug was already fixed (where RAF can be dropped in Chrome)
This makes log much longer on our bots.  Remove it.

Remove unnecessary logging from previous debugging

---

sdk/tests/deqp/functional/gles3/es3fFboCompletenessTests.js
sdk/tests/deqp/modules/shared/glsFboUtil.js

and a typo: s_latersParams -> s_layersParams.
According to JavaScript operator precedence, the precedence of inequality (!=) is higher than that of bitwise-and(&). see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
This change fixed some bugs in deqp fbo related tests, for example, test cases in fobcompleteness.html. 
PTAL. Thanks!

fix a bug caused by incorrect javascript operator precedence

---

sdk/tests/js/tests/tex-image-and-sub-image-2d-with-canvas.js

I am adding an additional check to existing webgl canvas tests to check whether image data of a 2d canvas change pixel values when used as webgl texture source. The test was written because of an issue reported by users and reproducible by some developers on Mac devices in previous Chrome versions (https://code.google.com/p/chromium/issues/detail?id=446380). Similar changes have already been landed in the corresponding webgl tests in Chromium (https://chromium.googlesource.com/chromium/src/+/190da73405a8a3393d8b96f423e961326de1c7b3).

Checking if the 2d canvas used in webgl texture source change pixel values

---

specs/latest/1.0/index.html
specs/latest/2.0/index.html

The space and vendor-specific information should be optional to clear up confusion in #1397 .

Made vendor-specific information optional.

---

sdk/tests/conformance/reading/read-pixels-test.html
sdk/tests/conformance/textures/misc/copy-tex-image-and-sub-image-2d.html
specs/latest/1.0/index.html

Before we set these pixels to (0, 0, 0, 0), now the working group
decided these pixels should remain untouched.
Note that I only changed the readPixels behavior in the test.  I will change the copyTexSubImage2D behavior in the test(s) in a separate CL.

Change spec for readPixels/copySubImage2D out of bounds read.

---

sdk/tests/deqp/functional/gles3/fbocompleteness.html

Before this patch, any GL error caused a test failure.
However, some of the tests expect GL errors.
Removed throwing exceptions when a GL error occurs in fbo completeness
tests.

Changed error checking in fbo completeness tests.

---

specs/latest/1.0/index.html
specs/latest/1.0/webgl.idl
specs/latest/2.0/index.html

Change type of internalformat from GLenum to GLint.

Update WebGL spec to align internalformat type of TexImage{2D|3D} with ES spec

---

sdk/tests/deqp/functional/gles3/es3fNegativeTextureApiTests.js

Accept INVALID_ENUM or INVALID_OPERATION for ambiguous tests. Remove
texParameteriv and texParameterfv because WebGL doesn't have these apis.

Fix ambiguous texParameter tests

---

sdk/tests/conformance2/rendering/draw-buffers.html

This is different from GLES 3.0. This change fixed a bug in draw-buffers.html. 
The Blink side code is here: https://codereview.chromium.org/1549393002/. It was landed already. 
PTAL. Thanks!

WebGL generates FRAMEBUFFER_INCOMPLETE_DIMENSIONS when attached images have different sizes

---

sdk/tests/js/tests/tex-input-validation.js

According to the spec https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexImage2D.xml. GL_INVALID_VALUE is generated if internalformat is not an accepted format and GL_INVALID_ENUM is generated if format or type is not an accepted value. So this expectedError should be INVALID_VALUE or gl.INVALID_ENUM.

Fix ambiguous texture input test.

---

sdk/tests/deqp/functional/gles3/es3fNegativeTextureApiTests.js

This is a follow-up patch of https://github.com/KhronosGroup/WebGL/pull/1407. Aligned with native code.

dEQP: use same framebuffer as C++ code

---

sdk/tests/deqp/functional/gles3/es3fNegativeTextureApiTests.js

This aligns with test for TexImage3D. C++ code also misses such checks.

dEQP: add format and internalformat checks for TexImage2D

---

sdk/tests/js/tests/tex-input-validation.js

Align with spec change in https://github.com/KhronosGroup/WebGL/pull/1402.

Generate INVALID_VALUE for TexImage with invalid internalformat

---

sdk/tests/js/tests/gl-vertex-attrib.js

Found that these cases weren't covered when attempting to refactor some validation within Chrome.

Added validation for vertexAttrib error conditions

---

conformance-suites/1.0.1/conformance/textures/tex-input-validation.html
conformance-suites/1.0.2/conformance/textures/tex-input-validation.html
conformance-suites/1.0.3/conformance/textures/tex-input-validation.html

Backport https://github.com/KhronosGroup/WebGL/pull/1408 to older snapshot to align with spec change in https://github.com/KhronosGroup/WebGL/pull/1402.

Fix ambiguous texture input test in older snapshot

---

sdk/tests/js/tests/gl-vertex-attrib.js

The second-last block of tests checks out-of-range vertexAttrib indexes, by passing in the MAX_VERTEX_ATTRIBS as the index.  The last block of tests is meant to check invalid array lengths, but it still uses numVertexAttribs as the max.  We only want the last block of tests to be testing one invalid parameter at a time, not two, so we change the numVertexAttribs to a valid value.

Change numVertexAttribs to a valid value when testing invalid array lengths

---

sdk/tests/conformance2/buffers/uniform-buffers.html

Should be noted that compiling the new shader in Chrome crashes the GPU process with a call stack that bottoms out in gpu::gles2::Program::GetUniformBlockMembers<>(). Joy.

Added test for using instance names with uniform blocks

---

specs/latest/1.0/index.html
specs/latest/1.0/webgl.idl
specs/latest/2.0/index.html

This change adds ImageBitmap support to texImage2D and
texSubImage2D. The origin restrictions logic was updated to take
into account the origin-clean flag of an ImageBitmap's bitmap.
The terminology for the origin-clean flag was tweaked to match the
language used in the HTML spec: "the origin-clean flag of an
HTMLCanvasElement" becomes "the origin-clean flag of an
HTMLCanvasElement's bitmap".

Add ImageBitmap to TexImageSource

---

sdk/tests/conformance2/reading/read-pixels-pack-parameters.html

i.e., if pack_row_length < width, the bytes after pack_row_length should
be pixel data until the row end of |width| pixels are reached.

Add another ReadPixels test case

---

sdk/tests/conformance2/renderbuffers/framebuffer-object-attachment.html
sdk/tests/conformance2/renderbuffers/framebuffer-texture-layer.html

https://codereview.chromium.org/1584723003/ fixes this pull request in chrome. Without the CL, these two tests will crash for chrome debug version.

Test depth_stencil attachment for framebufferTexture2D|Layer

---

sdk/tests/deqp/functional/gles3/es3fNegativeBufferApiTests.js

This test is ambiguous:
1. the read buffer contains unsigned integer, while the draw buffer contain floating-point data. It should generate INVALID_OPERATION.
2. the linear interpolation will be applied to unsigned integer data. It should generate INVALID_OPERATION.
This case tend to test 2#, so 1# is not necessary. This small change make sure that the format of the read buffer is the same with the format of the draw buffer. 
PTAL. Thanks!
The native dEQP have the same problem too. See https://android.googlesource.com/platform/external/deqp/+/deqp-dev/modules/gles3/functional/es3fNegativeBufferApiTests.cpp#1157.

fix ambiguous test for blitFramebuffer

---

sdk/tests/deqp/functional/gles3/es3fRasterizerDiscardTests.js

To clear stencil buffer, we should use clearBufferiv, instead of clearBufferfv.  The original code will lead to INVALID_VALUE error. 
The native dEQP is correct. see https://android.googlesource.com/platform/external/deqp/+/deqp-dev/modules/gles3/functional/es3fRasterizerDiscardTests.cpp#338

To clear stencil buffer, we should use clearBufferiv, instead of clearBufferfv

---

sdk/tests/conformance/textures/00_test_list.txt
sdk/tests/conformance/textures/image_bitmap/00_test_list.txt
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap.js

We need to add a detection in the conformance test for ImageBitmap to detect whether or not createImageBitmap and ImageBitmap is available. If not, then we should quit the test right away. Also, we add the 00_test_list.txt for the ImageBitmap test so that they can be picked up by the bot.

Add detection for createImageBitmap and ImageBitmap

---

sdk/tests/webgl-conformance-tests.html

The startTime of skipped case is always 0, thus the totalTime for
it would be wrongly a very large number.

Set test time for skipped case to 0

---

sdk/tests/webgl-conformance-tests.html

For better statistics, sometimes we need to know the number of
successful and total cases in each folder.
This PR also removes an unnecessary space for result of each page.

Add successful and total case number to folder

---

sdk/tests/deqp/functional/gles3/es3fFboTestUtil.js

This small change fixed a bug about uniform1fv. The data type of the original code is not correct, we should use an array. 
Attach the native code FYI: https://android.googlesource.com/platform/external/deqp/+/deqp-dev/modules/gles3/functional/es3fFboTestUtil.cpp#821

fix a bug about uniform1fv

---

sdk/tests/deqp/functional/gles3/es3fNegativeVertexArrayApiTests.js

In GLES, when call drawing APIs (drawElements, drawArrays and instanced drawing) with an invalid program (for example, call useProgram(0); ), the result is undefined, but it will not generate error. 
However, in WebGL, it will generate INVALID_OPERATION in the same situation. So these test cases are ambiguous. This pr removed these ambiguous test cases against invalid program.
PTAL. Thanks!

remove ambiguous drawing test cases against invalid program

---

sdk/tests/conformance2/reading/read-pixels-from-fbo-test.html

In the chromium, IMPLEMENTATION_COLOR_READ_TYPE/FORMAT always return pre defined value if there is no extension GL_OES_read_format. (see https://chromium.googlesource.com/chromium/src/gpu/+/master/command_buffer/service/gles2_cmd_decoder.cc#5111)
In my machine, GL_OES_read_format doesn't exist. But I still able to query this parameter because I have ES2_compatibility extension or latest OpenGL(seems latest OpenGL supports this without extension). And the value I queried is different from the pre defined value created by chromium.
So I add more functions for handling the extra formats that I've found. I think those changes would break the test result of chromium because of the problem I mentioned in first paragraph.

fix read-pixels-from-fbo-test. 

---

sdk/tests/conformance/attribs/gl-bindAttribLocation-aliasing.html
sdk/tests/conformance/attribs/gl-bindAttribLocation-matrix.html
sdk/tests/conformance/attribs/gl-matrix-attributes.html
sdk/tests/conformance/extensions/oes-texture-float.html
sdk/tests/conformance/extensions/oes-texture-half-float.html
sdk/tests/conformance/misc/expando-loss.html
sdk/tests/conformance/textures/misc/tex-sub-image-2d.html
sdk/tests/conformance/textures/misc/texture-active-bind.html
sdk/tests/conformance2/extensions/ext-color-buffer-float.html
sdk/tests/extra/slow-shader-example.html
sdk/tests/js/webgl-test-utils.js

Instead of exposing a lot of rarely used functions that simply load a
predefined shader from source, expose WTU collection of shader source as
read-only string properties on the WTU API. These are simple to use with
loadShader() or setupProgram().
Also rely on setupProgram() more in WTU functions that load a shader
program based on predefined shader sources to reduce complexity.

Simplify WebGLTestUtils shader program setup functionality

---

sdk/tests/deqp/functional/gles3/es3fTextureFilteringTests.js

deqp/functional/gles3/texturefiltering09.html complains
"src.sample is not a function".
glsTextureTestUtil.verifyTexture2DArrayResult requires
tcuTexture.Texture2DArrayView object for the second argument. This patch
fixes the bug which is similar to https://github.com/KhronosGroup/WebGL/pull/1340.

Fix wrong texture 2d array view

---

sdk/tests/deqp/framework/opengl/simplereference/sglrReferenceContext.js

"Intentionally empty. Call method from child class instead" error was
reported when running deqp/functional/gles3/texturespecification25.html.
Add sample() for sglrReferenceContext.Texture2DArray. This also aligns
with C++ code: https://android.googlesource.com/platform/external/deqp/+/master/framework/opengl/simplereference/sglrReferenceContext.cpp#5133.

Add sample function for Texture2DArray to run texturespecification25.html

---

sdk/tests/deqp/functional/gles3/es3fShaderStructTests.js

This fixes deqp/functional/gles3/shaderstruct.html which failed before
because uniform1fv was used for a vec2 uniform variable.

Use correct uniform2fv for vec2 uniform variable

---

sdk/tests/deqp/functional/gles3/es3fShaderStateQueryTests.js

Use slice to replace wrong splice function. splice will remove elements
from array while slice returns a copy of part of an array.

Fix uniform_value_matrix test in shaderstatequery.html

---

sdk/tests/conformance2/textures/misc/tex-mipmap-levels.html

When extensions EXT_color_buffer_float and OES_texture_float_linear are
enabled, generateMipmap should success for float type texture.

Add float texture test for generateMipmap

---

sdk/tests/conformance2/textures/misc/tex-mipmap-levels.html

In ES 3.0.4 spec page 158, it defines how to generate texture mipmap.
For TEXTURE_2D_ARRAY target, depth size of generated image for non-base
levels should be same as base level. This is different with TEXTURE_3D.
This patch also fixes generate mipmaps for a 0x0 texture.

Check level size of generated mipmap texture

---

specs/latest/2.0/index.html

This change specifies what this dEQP test already requires:
dEQP-GLES3.shaders.linkage.uniform.block.layout_qualifier_mismatch_3
It makes sure shaders stay portable across GLES 3.0 implementations.

Stricter spec for uniform block matching

---

sdk/tests/conformance2/textures/misc/tex-mipmap-levels.html

This patch adds generateMipmap test with zero texture. Also, It checks
generateMipmap with float texture will fail if related extensions isn't
enabled.

Add more tests for generateMipmap

---

sdk/tests/conformance/textures/misc/tex-sub-image-2d-bad-args.html
sdk/tests/conformance2/textures/misc/compressed-tex-image.html
sdk/tests/js/tests/tex-input-validation.js

This patch valids TEXTURE_3D is invalid enum for 2d texture apis.
deqp/functional/gles3/negativetextureapi.html already covers validation
of TEXTURE_2D target for 3d texture apis.

3D targt should be INVALID_ENUM for 2d texture apis

---

sdk/tests/deqp/functional/gles3/es3fNegativeBufferApiTests.js

Framebuffer attached a non-color-renderable texture is incomplete.
ClearBufferfv on incomplete framebuffer will fail. Check and enable
EXT_color_buffer_float extension before clearing a framebuffer attached
a float texture which isn't color-renderable.

Fix non-color-renderable texture attachment

---

specs/latest/1.0/index.html

Fixed duplicate "the".

---

sdk/tests/js/tests/instanceof-test.js

When we load the shader source from setupProgram, we check for GL errors, assuming that they would've been set from the preceding function call.  However, a GL error that is set during one of the instanceof tests won't be caught until setting up the program, and would be incorrectly attributed to a problem with loading the shaders. To fix this, we check for errors after each GL call, if only for the purpose of clearing the flag.

Adding error checking after instanceof calls to clear any set error flags

---

sdk/tests/js/webgl-test-utils.js

They're not enums but have numerical values.

Don't return drawingBufferWidth/Height from glEnumToString

---

sdk/tests/deqp/framework/delibs/debase/deMath.js
sdk/tests/deqp/functional/gles3/es3fShaderOperatorTests.js

GLSLangSpec.3.30.6 defines mod(x, y) = x - y * floor(x/y), see page.84 https://www.opengl.org/registry/doc/GLSLangSpec.3.30.6.clean.pdf.  
C++ dEQP also use this define, see: https://android.googlesource.com/platform/external/deqp/+/master/framework/common/tcuVectorUtil.hpp#58.   The mod in line 57 is not used in mod cases in deqp/functional/gles3/shaderoperator.html.
In JS -1.1 % 1 = -0.1, while -1.1 - 1 * Math.floor(-1.1/1) = 0.9.

Use same mod algorithm as C++ version

---

sdk/tests/deqp/functional/gles3/es3fShaderOperatorTests.js

C++ code can be found at: https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fShaderOperatorTests.cpp#996.
Index of z element should be 2 other than 3.

Select correct z element for vec4

---

sdk/tests/deqp/functional/gles3/es3fShaderOperatorTests.js

Some constant values are not aligned with C++ version. These wrong
values make related cases in es3fShaderOperatorTests.html fail:
(1) float number with all zero decimal part is handled as an integer in js. It caused integer overflow errors in shader
(2) wrong values cause image comparison failure.
(3) wrong input and output type cause image comparison failure.
C++ version can be found at: https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fShaderOperatorTests.cpp.

Fix constant values in shader

---

sdk/tests/deqp/functional/gles3/es3fShaderBuiltinVarTests.js

This aligns with int type for result in C++ code. Some constant values
can be negative, e.g. MIN_PROGRAM_TEXEL_OFFSET in
deqp/functional/gles3/shaderbuiltinvar.html.
C++ code: https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fShaderBuiltinVarTests.cpp#133

Use correct integer type

---

sdk/tests/deqp/functional/gles3/es3fShaderBuiltinVarTests.js

The number of vectors is number of components divided by four.
getVectorsFromComps checks "value%4 === 0", but it forgets doing the
division.
C++ code for reference: https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fShaderBuiltinVarTests.cpp#71

Correct reference number of vector

---

sdk/tests/deqp/modules/shared/glsStateQuery.js

The test vertex_attrib_offset in shaderstatequery.html need to get the gl.VERTEX_ATTRIB_ARRAY_POINTER info, we should use getVertexAttribOffset(), instead of getVertexAttrib(). Otherwise, the pname is invalid. 
This change fixed this bug.

fix bug in shaderstatequery when query vertex attribute offset

---

sdk/tests/deqp/framework/opengl/gluShaderUtil.js
sdk/tests/deqp/functional/gles3/es3fAttribLocationTests.js
sdk/tests/deqp/modules/shared/glsAttributeLocationTests.js

Vertex attribute aliasing causes link error (WebGl 2.0 spec section 5.17
Vertex Attribute Aliasing). So remove related tests. Also align shader
source code generation with C++ code. 
deqp/functional/gles3/attriblocation.html passed with this patch.
C++ code: https://android.googlesource.com/platform/external/deqp/+/master/modules/glshared/glsAttributeLocationTests.cpp#254

Remove unsupported attribute aliasing tests

---

specs/latest/1.0/index.html
specs/latest/2.0/index.html

We basically add a note for the parameters of UNPACK_FLIP_Y_WEBGL, UNPACK_PREMULTIPLY_ALPHA_WEBGL and UNPACK_COLORSPACE_CONVERSION_WEBGL, stating that these three parameters will be ignored if the texImageSource is an ImageBitmap.
Please review @kenrussell @zhenyao @toji

change the specs of pixel storage parameters for ImageBitmap

---

sdk/tests/deqp/functional/gles3/es3fShaderStateQueryTests.js

This feature differs from that of native gles3. see the section <Buffer Offset and Stride Requirements> in webgl spec: https://www.khronos.org/registry/webgl/specs/latest/1.0/index.html#6.4 
Considering that the stride alignment is not covered in conformance test. I add the expected GL_ERROR into this case to test this feature, instead of deleting the cases that will generate INVALID_OPERATION error. 
PTAL. Thanks!

Vertex attribute stride should be aligned with the size of vertex attribute type in WebGL 2.

---

sdk/tests/conformance2/misc/uninitialized-test-2.html

Test with larger texture sizes.  This triggers different code paths in chrome.

Add more test cases for uninitialized-test-2.html

---

sdk/tests/conformance/misc/uninitialized-test.html

If we create texture using TexImage2D with null data, and then
initialize part of it using TexSubImage2D, and then ReadPixels() the
entire texture. The uninitialized part should be cleared to 0, and the
initialized part should stay untouched.
Chrome has a bug where the initialized part will also be cleared to 0.
This is fixed in https://codereview.chromium.org/1706773003/

Add a new case to uninitialized-test.html

---

specs/latest/1.0/index.html
specs/latest/2.0/index.html

Clarify that the WebGL-specific pixel storage parameters do not apply to passed ImageBitmaps, since their parameters are already baked in when the ImageBitmap's promise is resolved. Reorganize the text to make this more clear, and to leave the description of all errors at the end of each function's documentation.

Update docs for tex{Sub}Image[23]D taking TexImageSource.

---

sdk/tests/deqp/functional/gles3/es3fNegativeTextureApiTests.js

The feature differs from that of native gles, in which the data(type is void*) can be null. 
The original code make many test ambiguous. It may generate INVALID_VALUE error if pixels is null. 
PTAL. Thanks!

pixels(type is ArrayBufferView) in texSubImage* can not be null in WebGL

---

sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-image-data.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-image-data.js

createImageBitmap(validSource, flipY=true) is fully supported for all valid sources. Let's try it. I change the test of image-bitmap-from-image-data with flipY options. All conformance(2) tests passed locally on a Linux desktop.
The future plan it to apply flipY to all sources and after that, premultiplyAlpha.

Let's flip ImageBitmap ^o^

---

sdk/tests/deqp/functional/gles3/es3fLifetimeTests.js

Detach array buffer from vertex attribute isn't implemented in js. This
patch gets the vertex buffer first, then removes it which makes the
vertex buffer detach from vertex attribute.

Fix vertex array life time test

---

sdk/tests/conformance2/transform_feedback/transform_feedback.html

This exposes a bug of bindBufferBase in chrome. Between two calls of
"gl.bindBuffer(gl.TRANSFORM_FEEDBACK_BUFFER, out_add_buffer);"
bound_transform_feedback_buffer_ doesn't change, so
GLES2Implementation::BindBufferHelper doesn't issue bindBuffer to
command buffer server side.
Please refer chrome command buffer client code: https://code.google.com/p/chromium/codesearch#chromium/src/gpu/command_buffer/client/gles2_implementation.cc&q=BindBufferHelper&sq=package:chromium&type=cs&l=3811

Check single transform feedback output

---

specs/latest/1.0/index.html

At this moment, the WebGL spec has a statement that is pointing to a whatwg wiki for ImageBitmapOptions, now that ImageBitmapOptions is in the whatwg specs, let's change that statement to point to the whatwg spec instead of wiki.

Let WebGL spec points to whatwg specs of ImageBitmapOptions

---

sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-image-data.js
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-image.js
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-video.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-image-data.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-image.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-video.js

This change adds flipY option to conformance(2) tests for ImageBitmap that is created from an HTMLImageElement or HTMLVideoElement. With this change, flipY is covered in all the current tests for ImageBitmap.

Add flipY to ImageBitmap created from image and video

---

sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-canvas.js
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-image.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-canvas.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-image.js

Using HTMLCanvasElement as example, I set canvas to be rgba(255, 0, 0, 0.5) and create an ImageBitmap from it. When premultiplyAlpha=default, the color we see should be somewhere around 128 (usually won't be exactly 128 because of rounding error). Now if we create an ImageBitmap from it with premultiplyAlpha=false, we should see solid red color.
In the case of HTMLImageElement, I use canvas.toDataURL to obtain an img element and create ImageBitmap from it.
Locally conformance tests all pass, the tests always fail for 7 format under conformance2:
r8_red_unsigned_byte
r16f_red_half_float
r16f_red_float
r32f_red_float
r8ui_red_integer_unsigned_byte
srgb8_rgb_unsigned_byte
srgb8_alpha8_rgba_unsigned_byte
I don't know exactly why these 7 format failed, but will investigate later. What I plan …

Add premultiplyApha=false for ImageBitmap from HTMLImageElement and Canvas

---

sdk/tests/conformance/extensions/oes-vertex-array-object.html
sdk/tests/conformance2/vertex_arrays/vertex-array-object.html

When a buffer is deleted, its name immediately becomes invalid. But the
underlying container which the deleted buffer is attached to may
continue using the object (page 315 ES spec 3.0.4).

Deleted buffer should be invalid

---

sdk/tests/deqp/framework/opengl/gluDrawUtil.js

This patch fixes two bugs exposed by deqp/functional/gles3/shaderprecision.html:
1. Use 32-bit int array for 32-bit int type.
2. Use glVertexAttribIPointer for int vertex array buffer.
C++ code: https://android.googlesource.com/platform/external/deqp/+/master/framework/opengl/gluDrawUtil.cpp#415

Fix wrong array type in shaderprecision.html

---

conformance-suites/1.0.2/conformance/extensions/oes-vertex-array-object.html
conformance-suites/1.0.3/conformance/extensions/oes-vertex-array-object.html

When a buffer is deleted, its name immediately becomes invalid. But the
underlying container which the deleted buffer is attached to may
continue using the object.

Backport: Deleted buffer should be invalid

---

other/post-commit

The hook notifies the user if they've changed
specs/latest/*/index.html files but haven't changed the line with the
date, identified by the "Editor's Draft" string in the script.
It's implemented as a post-commit hook so it also runs on git commit
--amend. Users should link or copy it to their .git/hooks/ directory.

Add a helpful post-commit hook for spec editing

---

sdk/tests/deqp/functional/gles3/es3fVertexArrayTests.js

This feature in WebGL differs from that in gles. See the spec in WebGL: https://www.khronos.org/registry/webgl/specs/latest/1.0/index.html#BUFFER_OFFSET_AND_STRIDE. 
This change can fix all remaining bugs in vertexarrays.html in webgl deqp. 
However, the unaligned tests can still pass in native deqp on Linux desktop. Moreover, when I remove the validation code for vertexAttribPointer in command buffer, the unaligned webgl tests can pass too. The underlying driver will not report gl error in this situation. I suppose the driver will re-calculate the stride and discard the one that user provides. 
PTAL. Thanks!

unaligned stride is not allowed in WebGL

---

sdk/tests/conformance/glsl/bugs/00_test_list.txt
sdk/tests/conformance/glsl/bugs/angle-ambiguous-function-call.html

HLSL compiler can't resolve between float4 and float2x2 parameters
when determining which overloaded function is being called. ANGLE
exposes this property to ESSL, but ESSL should be able to resolve
which function is being called in this case. Add a test for this.

Add test for ANGLE ambiguous function call bug

---

sdk/tests/deqp/framework/delibs/debase/deMath.js
sdk/tests/deqp/functional/gles3/es3fShaderPrecisionTests.js

Max safe integer number is 2^53 -1 in JS. Two 32bit integer
multiplication may overflow. Just return correct low 32bit of the
result which is same method used in C++. This fixes
deqp/functional/gles3/shaderprecision.html.

Handle 32bit integer multiplication overflow

---

sdk/tests/deqp/functional/gles3/es3fDrawTests.js

This feature differs from that in gles.
This limitation is added to keep compatible with D3D.
See the WebGL spec: https://www.khronos.org/registry/webgl/specs/latest/2.0/index.html#5.6. 
This change removed the test cases when no vertex divisor equals to zero during drawing. It can fix some bugs in draw.html in WebGL deqp tests. PTAL.

There should be at least one enabled vertex attribute array that has a divisor of zero

---

sdk/tests/deqp/functional/gles3/es3fPrimitiveRestartTests.js

I suppose that this is a typo. See the original code in native deqp: https://android.googlesource.com/platform/external/deqp/+/deqp-dev/modules/gles3/functional/es3fPrimitiveRestartTests.cpp#545. 
This small change can fix bugs in primitiverestart.html in webgl deqp. 
PTAL. Thanks!

fix bug for primitive restart test

---

sdk/tests/deqp/functional/gles3/es3fPixelBufferObjectTest.js

This aligns with C++ code:
https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fPixelBufferObjectTests.cpp#485

Fix wrong format and type for readPixels in pixelbufferobject.html

---

sdk/tests/deqp/functional/gles3/es3fRasterizerDiscardTests.js

This aligns with C++ code:
https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fRasterizerDiscardTests.cpp#347

Draw correct fullscreen square in rasterizerdiscard.html

---

sdk/tests/conformance2/vertex_arrays/vertex-array-object.html

New test where we delete buffers that are attached to the currently bound VAO, expecting that they get automatically unbound, and shouldn't be accessible or usable in a draw call. We expect these buffers to exist until they are unbound from their last binding point.

Adding new test to vertex array object. 

---

sdk/tests/deqp/framework/common/tcuTestCase.js
sdk/tests/deqp/functional/gles3/es3fMultisampleTests.js
sdk/tests/js/js-test-pre.js

1. Add support to skip unavailable tests.
2. Reset GL states in deinit to avoid affecting subsequent tests.
With this patch, all tests passed in multisample.html.
C++ code:
https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/tes3TestPackage.cpp#69
https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fMultisampleTests.cpp#281

Fix bugs in multisample.html

---

sdk/tests/conformance2/reading/read-pixels-from-fbo-test.html

When we have a texture with internal format SRGB8_ALPHA8, the texture uses SRGB color encoding, and doing a glClearColor/glClear operation converts from linear to SRGB. When we do a glReadPixels, the read format is RGBA, as glReadPixels doesn't support SRGB8_ALPHA8 reads, so no SRGB -> linear conversion occurs. When we compare against the expected color, we must convert linear -> SRGB. We must convert depending on the internal format (as the internal type tells us if the pixels are in SRGB format), and regardless of the read type (since the read type can't be SRGB8_ALPHA8 anyways).

Convert expected colors from linear -> SRGB when reading from an SRGB texture.

---

sdk/tests/conformance/extensions/ext-disjoint-timer-query.html

Allow the counter bits for timestamps to be 0 for the WebGL
EXT_disjoint_timer_query conformance test and disable the timestamp
portion of the test if that is the case. Certain backing drivers for
WebGL such as the OSX drivers and ANGLE on D3D11 do not support
timestamps and it is within the spec to disable timestamp functionality
in the extension by setting the number of counter bits for the
timestamps to be 0. This updates the test to check if the timestamp
counter bits is set to 0 and to skip the timestamp portion of the test
if that is the case.

Make timestamps optional in timestamp WebGL test.

---

sdk/tests/conformance2/glsl3/array-complex-indexing.html

From section 5.7 in the ESSL spec, ternary operators are not permitted to operate on arrays or structures.
https://www.khronos.org/registry/gles/specs/3.2/GLSL_ES_Specification_3.20.withchanges.pdf

Ternary operators not permitted on arrays

---

specs/latest/2.0/index.html

This GLSL ES revision was made after taking feedback from the WebGL
WG. The spec references that are updated in this patch were reviewed
to make sure they are still correct.

Update GLSL ES 3.00 references in WebGL 2.0 to 3.00.6

---

sdk/tests/deqp/modules/shared/glsShaderExecUtil.js

Boolean output is converted to an int type varying whose name is
constructed by adding 'o_' before the original name. Correct name should
be specified for transform feedback output.
C++ code: 
https://android.googlesource.com/platform/external/deqp/+/master/modules/glshared/glsShaderExecUtil.cpp#446
Also see code about creating vertex shader in line 156 of glsShaderExecUtil.js:
https://www.khronos.org/registry/webgl/sdk/tests/deqp/modules/shared/glsShaderExecUtil.js

Fix transform feedback boolean output varying

---

sdk/tests/deqp/functional/gles3/es3fShaderCommonFunctionTests.js

Scalarsize should be considered when set inputs.
C++ code: 
https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fShaderCommonFunctionTests.cpp#532
The C++ code has bug too. It doesn't move ptr for different special values.
Other place in the same file does the same thing:
see code in es3fShaderCommonFunctionTests.TruncCase.prototype.getInputValues().

Set correct inputs for special cases

---

sdk/tests/deqp/functional/gles3/es3fShaderCommonFunctionTests.js

-0 is treated as different with 0 for high precision case. WebGL do
return -0 but the reference output is still 0. This patch updates the
reference output calculation. 
C++ dEQP also has such bug, but due to the
input isn't set correctly -0 case will not appear in C++ dEQP.
For input initialization bug, please see discussion in https://github.com/KhronosGroup/WebGL/pull/1565.

Generate -0 for roundeven reference value in shadercommonfunction.html

---

sdk/tests/deqp/functional/gles3/es3fShaderCommonFunctionTests.js

In C++ input values for isnan and isinf cases is generated in unsigned int format:
https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fShaderCommonFunctionTests.cpp#809
and read in float format:
https://android.googlesource.com/platform/external/deqp/+/master/modules/glshared/glsShaderExecUtil.cpp#500.
This patch does the same thing as C++: generate a unsigned int value, then use it as float32 value.

Initialize input values with correct type

---

sdk/tests/deqp/framework/common/tcuFloat.js
sdk/tests/deqp/functional/gles3/es3fShaderPackingFunctionTests.js

This patches fix several bugs:
1. Clear status of tcuFloat when setting a new value.
2. Wrong type for output and ref output.
3. Support NaN value.
With this patch, all tests passed in shaderpackingfunction.html.
C++:
https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fShaderPackingFunctionTests.cpp
https://android.googlesource.com/platform/external/deqp/+/master/framework/common/tcuFloat.hpp#242

Fix wrong types in shaderpackingfunction.html

---

sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-utils.js

When we premultiply a pixel value 255 in sRGB space with alpha = 0.5,
the result in sRGB space should be 55 instead of 128.

Fix a bug with sRGB and RED texture uploading through ImageBitmap.

---

sdk/tests/deqp/functional/gles3/es3fShaderMatrixTest.js

C++ code:
https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fShaderMatrixTests.cpp#525
tcuMatrix.Mat4 in deqp/framework/common/tcuMatrix.js will generate an identity matrix while a zero matrix is needed here:
https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fShaderMatrixTests.cpp#1668

Correct input values in shadermatrix.html

---

sdk/tests/deqp/framework/opengl/gluDrawUtil.js

gluDrawUtil.VertexArrayBinding requires stride and offset for VAO binding.
C++ code:
https://android.googlesource.com/platform/external/deqp/+/master/framework/opengl/gluDrawUtil.cpp#220
With this patch, part of tests in shadermatrix.html passed. But there are still some other failures.

Fix wrong parameter VAO

---

sdk/tests/deqp/modules/shared/glsBuiltinPrecisionTests.js

See the corresponding code in native deqp: https://android.googlesource.com/platform/external/deqp/+/deqp-dev/modules/glshared/glsBuiltinPrecisionTests.cpp#4936. 
PTAL, Thanks!

Make the code aligned with native deqp, in order to fix shader compilation failure

---

sdk/tests/deqp/modules/shared/glsBuiltinPrecisionTests.js

A small change. The builtin function should be 'roundEven', instead of 'roundeven'. After the change applied, builtinprecision31.html can pass in Chromium.

fix error to make builtinprecision31.html pass

---

sdk/tests/conformance/rendering/00_test_list.txt
sdk/tests/conformance/rendering/draw-with-changing-start-vertex-bug.html

This bug would occur after the app would render several times with the
same vertex attributes and buffers, but using a different start offset.
One of the buffers would likely have to be DYNAMIC.
See http://anglebug.com/1327 and http://crbug.com/594509

Add a test to cover an ANGLE rendering bug.

---

README.md

This is a simple correction but Ken, please check the information is valid for your Windows environment before merging.

Fix notes about installing gitconfig.

---

sdk/tests/deqp/framework/common/tcuFloat.js

It's introduced in https://github.com/KhronosGroup/WebGL/pull/1588
(and I failed to catch it during review)

Fix a bug in tcuFloat.js

---

sdk/tests/deqp/framework/common/tcuSurface.js
sdk/tests/deqp/framework/opengl/gluDrawUtil.js
sdk/tests/deqp/modules/shared/glsDrawTests.js
sdk/tests/deqp/modules/shared/glsShaderLibraryCase.js

Found that a fair amount of time was being spent in some tests creating intermediate color objects, so I've put in place some optimizations that allow colors to be returned as an unsigned int. This adds some bit shifting math but the reduction in temporary object creation appears to be worth it. For example,  shaved of about 5 seconds a piece from shaders/swizzles.html and shaders/conversions.html on my machine, and a full **20 seconds** (out of 75) off of gles3/draw.html. Other tests may benefit, but I haven't checked rigorously.

Misc optimizations for DEQP tests

---

sdk/tests/deqp/framework/common/tcuBilinearImageCompare.js
sdk/tests/deqp/framework/common/tcuTexture.js
sdk/tests/deqp/framework/referencerenderer/rrMultisamplePixelBufferAccess.js

On my machine reduced rundeqp/functional/gles3/fbocolorbuffer.html from 252 seconds to 158 seconds. Other tests that utilize the same code paths should see similar improvements.

More DEQP optimizations, this time focused on tcuTexture.get/setPixel

---

sdk/tests/deqp/framework/opengl/simplereference/sglrReferenceContext.js
sdk/tests/deqp/framework/opengl/simplereference/sglrReferenceContextTest.js
sdk/tests/deqp/framework/referencerenderer/rrRenderer.js
sdk/tests/deqp/functional/gles3/es3fShaderBuiltinVarTests.js

PTAL, this fixes the gl_VertexID test reference in two parts:
- Fix it not rendering anything because the software FS output to the wrong variable
- Add triangle rasterization because quad rasterization didn't match with what the GPU produced.
The drawQuads -> drawTriangles is very significant as many tests inderectly used drawQuads to generate reference images. The dEQP functional draw test have equivalent results with Chrome stable between both version, and the simple_reference_renderer test results are more correct now.
While this is in review, I'm running the WebGL2 CTS on Chrome stable both with and without this change to see if any new failure is introduced. New failures would either point to bugs in the drawTriangles, or bugs in the tests when they used drawQuads to render …

Fix the gl_VertexID test reference not being rendered.

---

sdk/tests/conformance2/reading/read-pixels-from-fbo-test.html

0.5 maps to 127 or 128, but in RGBA4, if it's 8, 8 / 15 * 255 is 136.
This makes some test cases pass on Mac OSX.

Relax pixel comparison tolerance.

---

sdk/tests/deqp/modules/shared/glsBuiltinPrecisionTests.js

In JS implementation of round(), (-inf) - (-inf) equals to NaN.
While it is -0 in native deqp case.
So when the input of round() is inf or -inf, the fract part is neither >=0.5 nor <= 0.5. Then it returns a wrong result to the caller. 
PTAL, thanks!

Fix the error against builtinprecision30.html in webgl deqp.

---

sdk/tests/conformance/glsl/misc/global-variable-init.html
sdk/tests/js/glsl-conformance-test.js

Add a test where a ternary operation condition references a uniform,
and another test where a uniform struct is assigned to a global.
An option to specify uniform values for GLSL tests is added for the
second test. This could be also used to refactor other existing tests
that currently are not using the GLSL test helpers because they need
to set uniforms.

Improve global variable initialization test

---

sdk/tests/deqp/functional/gles3/es3fDefaultVertexAttributeTests.js

The bug exists in the original c++ tests.

Fix a bug in defaultvertexattribute.html

---

sdk/tests/deqp/framework/common/tcuTexLookupVerifier.js

This makes all texturefiltering_2d_array_formats_*.html pass except texturefiltering_2d_array_formats_48.html.
C++ code:
https://android.googlesource.com/platform/external/deqp/+/master/framework/common/tcuTexLookupVerifier.cpp#101

Correct elements order for lookup quad

---

conformance-suites/1.0.2/conformance/extensions/oes-vertex-array-object.html
conformance-suites/1.0.3/conformance/extensions/oes-vertex-array-object.html
sdk/tests/conformance/extensions/oes-vertex-array-object.html

In previous loop, we will bind vao for checking vertex arrtib. If we
don't unbind the vao before deleting position buffer, the link between
this vao and position buffer will be broken.

Unbind vao before delete position buffer.

---

sdk/tests/deqp/framework/common/tcuTexLookupVerifier.js

This fixes deqp/functional/gles3/texturefiltering_cube_formats_08.html.
C++ code:
isNearestSampleResultValid() call lookup<ScalarType>(level, sampler, x, y, coordZ). Due looup is a C++ template funciton the function really call is "inline Vector<float, 4> lookup (const ConstPixelBufferAccess& access, const Sampler& sampler, int i, int j, int k)". 
https://android.googlesource.com/platform/external/deqp/+/master/framework/common/tcuTexLookupVerifier.cpp#541
https://android.googlesource.com/platform/external/deqp/+/master/framework/common/tcuTexLookupVerifier.cpp#65
This patch isn't aligned with C++ code because JS doesn't support template function. Any suggestions about the fix?

Fix sRGB format cube texture lookup

---

sdk/tests/deqp/framework/common/tcuTestCase.js

This fixes the wrong name of skipped tests and extra skip info at the
end of result page of each html file.
@kenrussell  I found some bugs about the skipped list. PTAL.

Correct name of skipped tests

---

sdk/tests/deqp/framework/common/tcuSkipList.js

Native dEQP also fails on these tests and suppresses them.
Please refer:
https://android.googlesource.com/platform/external/deqp/+/7c5323116bb164d64bfecb68e8da1af634317b24.
https://bugs.chromium.org/p/angleproject/issues/detail?id=1092

Skip some shader texture tests

---

sdk/tests/deqp/functional/gles3/es3fTextureFilteringTests.js
sdk/tests/deqp/modules/shared/glsTextureTestUtil.js

With this patch, all texturefiltering* tests can pass now.

Fix wrapR mode and wrong texCoord used

---

specs/latest/2.0/index.html

Demand after invalidate{Sub}Framebuffer, the affected region's
contents either stay unchanged or become all 0.

Spec update for WebGL 2.

---

specs/latest/1.0/index.html

Make the specification change agreed upon in the issue.

Fix #1596 - clarify behavior of extensions' methods after context loss.

---

sdk/tests/conformance/uniforms/gl-uniformmatrix4fv.html

ES3 spec allows transpose argument to be true now.

WebGL 2.0 supports transpose for uniformatirx functions

---

sdk/tests/conformance/extensions/oes-texture-half-float.html

These tests ensure:
1) For LUMINANCE, LUMINANCE_ALPHA and ALPHA half float textures:
- checkFramebufferStatus should return FRAMEBUFFER_INCOMPLETE_ATTACHMENT.
- getParameter with IMPLEMENTATION_COLOR_READ_FORMAT and IMPLEMENTATION_COLOR_READ_TYPE should return null and flag INVALID_OPERATION
- readPixels should flag a FRAMEBUFFER_INCOMPLETE_ATTACHMENT error.
2) For RGBA and RGB half float buffers
- RGBA and FLOAT should always be an accepted format and type combination for readPixels.
- IMPLEMENTATION_COLOR_READ_FORMAT should be RGB or RGBA.
- IMPLEMENTATION_COLOR_READ_TYPE must be UNSIGNED_BYTE, HALF_FLOAT_OES, or one of the UNSIGNED_SHORT combinations
- If the type of the arrayBuffer does not match the glType passed into readPixels, fail the test.

Add framebuffer tests to oes-texture-half-float

---

sdk/tests/deqp/framework/common/tcuFloat.js
sdk/tests/deqp/functional/gles3/es3fShaderDerivateTests.js

The bug causes shaderderivate.html regression. It's introduced in
https://github.com/KhronosGroup/WebGL/pull/1588. It also exposed
an uninitialization error in es3fShaderDerivateTests.js.

Fix wrong sign bit calculation in tcuFloat.js

---

sdk/tests/deqp/data/gles2/shaders/scoping.test

from deqp/data/gles2/shaders/scoping
See https://github.com/KhronosGroup/WebGL/issues/1635

Remove local_variable_hides_function_parameter test case

---

specs/latest/2.0/index.html

The parameters should include the dimensions of the texture when
uploading from a pixel unpack buffer.

Fix texSubImage from pixel unpack buffer parameter list in spec

---

sdk/tests/deqp/framework/opengl/simplereference/sglrGLContext.js
sdk/tests/deqp/framework/opengl/simplereference/sglrReferenceContext.js
sdk/tests/deqp/functional/gles3/es3fFboRenderTest.js

(1) Add maps from internalFormat to format before function texImage2D in sglrGLContext.js and sglrReferenceContext.js
(2) Fix an index error in es3fFboRenderTest.SharedColorbufferClearsTest
(3) Fix a misuse of function bindFramebuffer in es3fFboRenderTest.js:1044
(4) Fix bugs in function getWidth and getHeight in sglrGLContext.js since the return values of these functions should be the width and the height of current viewport instead of the ones of current canvas
(5) In function iterate in es3fFboRenderTest.js, remove the call of gles3Frame.setSize since after setSize is called the frame will be cleared
(6) In function iterate in es3fFboRenderTest.js, set default value of failReason to "" instead of null since a null pointer exception occurs when a message for success should be shown
This …

Fix several bugs in fborender.html

---

sdk/tests/deqp/functional/gles3/es3fTextureSpecificationTests.js

This fixes texturespecification01.html on chromeOS. But
texturespecification01.html still fails on my linux desktop with nVidia
graphics card. The failure is about texture filtering. I suppose it's a
driver bug: wrong level is selected as input texture for nVidia.
C++ code:
https://android.googlesource.com/platform/external/deqp/+/master/modules/gles3/functional/es3fTextureSpecificationTests.cpp#928

Fix texture initialization for texturespecification tests

---

sdk/tests/conformance/extensions/webgl-compressed-texture-s3tc.html

This is the first time that uninitialized compressed textures can be
exposed to the JavaScript level, and they must be tested. The new
tests assert that the texture contains either transparent or opaque
black, depending on the specific DXT internal format.
See http://crbug.com/605129 for fixes for this test in Chromium.

Expand tests for S3TC compressed textures to cover TexStorage2D.

---

sdk/tests/conformance/context/00_test_list.txt
sdk/tests/conformance/context/context-size-change.html

Add a context size change test.
The test makes an antialiased, no alpha context. Then it resizes it, and checks
that clearing/reading the resized context still works.

Add a context size change test.

---

extensions/EXT_color_buffer_half_float/extension.xml
extensions/WEBGL_color_buffer_float/extension.xml
extensions/extension.xsl
extensions/standards.xsl
sdk/tests/conformance2/extensions/00_test_list.txt
sdk/tests/conformance2/extensions/promoted-extensions.html

These include both extensions promoted to core, and extensions subsumed by other extensions.
Explicitly point out that EXT_color_buffer_half_float and WEBGL_color_buffer_float are no longer available in WebGL 2.0, subsumed by EXT_color_buffer_float.

Add conformance test for extensions no longer available in WebGL 2.0.

---

sdk/tests/conformance2/buffers/bound-buffer-size-change-test.html

return 0 if it's not specified at binding time (for example, through
BinBufferBase)

Fix a bug that UNIFORM_BUFFER_SIZE or TRANSFORM_BUFFER_SIZE should

---

sdk/tests/conformance/extensions/oes-texture-half-float.html

There is nothing in the specifications which forbids this, and we've
found that Intel's Linux OpenGL driver, which supports the
GL_OES_read_format extension, reports RGBA/FLOAT as the implementation
color read format and type. Relax the newly-expanded test.

Allow FLOAT as one of the implementation color read types.

---

sdk/tests/js/tests/gl-enum-tests.js
sdk/tests/js/tests/gl-get-tex-parameter.js
sdk/tests/js/tests/gl-object-get-calls.js
sdk/tests/js/tests/gl-vertex-attrib.js
sdk/tests/js/tests/instanceof-test.js
sdk/tests/js/tests/tex-input-validation.js

Some WebGL 2 tests would default to a WebGL 1 context if
?webglVersion=2 was not added to the URL. Fix this to make the tests
easier to run standalone.

Create WebGL 2 context by default in conformance2 tests using js/tests

---

sdk/tests/deqp/functional/gles3/lifetime.html
sdk/tests/deqp/modules/shared/glsLifetimeTests.js

In WebGL, a buffer bound to TRANSFORM_FEEDBACK_BUFFER cannot be bound to
any other targets. See section 5.1 Buffer Object Binding in WebGL 2.0
spec. This is a difference between GLES and WebGL. This patch detaches
the buffer from TRANSFORM_FEEDBACK_BUFFER before other binding, then
reattaches it after other binding.

Fix transform feedback buffer binding issue

---

specs/latest/2.0/index.html

ABout color conversion rules for copyTex{Sub}Image2D.

Add a WebGL 1 / 2 difference in the spec.

---

sdk/tests/deqp/framework/delibs/debase/deMath.js

This cut many builtinprecision tests run time from 2min/test to
1min/test.

Optimize deMath.frexp

---

sdk/tests/deqp/functional/gles3/es3fTextureSpecificationTests.js

WebGL 2 disallow this format from Tex{Sub}Image{2|3}D with non-null ArrayBuffer.

Remove a few DEPTH32F_STENCL8 test cases.

---

specs/latest/1.0/index.html
specs/latest/1.0/webgl.idl

Members of EventInit dicts must either have default values or be 'required' values.

Add default value of "" to WebGLContextEventInit::statusMessage.

---

sdk/tests/deqp/functional/gles3/es3fTextureSpecificationTests.js

The offset should be 0, but instead, it is set to the buffer size.
So the ArrayBufferView passed to the teximage call become size 0.

Fix a bug in es3fTextureSpecificationTests.js

---

sdk/tests/conformance/rendering/negative-one-index.html

Primitive restart is always enabled in WebGL 2.0. -1 index is treated as
a primitive restart and nothing is rendered. This is different with
WebGL 1.0.

Fix negative one index for WebGL 2.0

---

sdk/tests/deqp/functional/gles3/es3fTextureSpecificationTests.js

The c++ tests specifies number of levels, whereas the js tests compute number
of levels based on width/height. So js tests include the 1 pixel level, which
caused rendering to 3x1 or 2x1 destinations failing.

Fix texturespecification/teximage2d_align.html

---

sdk/tests/conformance/rendering/line-loop-tri-fan.html
sdk/tests/js/tests/out-of-bounds-test.js

In WebGL 2.0, primitive restart is always enabled. Avoid using primitive
restart fixed index for element index.

Fix array index bug in WebGL 2.0

---

sdk/tests/deqp/functional/gles3/es3fTextureSpecificationTests.js

This patch makes teximage3d_pbo.html and texsubimage3d_pbo.html pass

More fixes in es3fTextureSpecificationTests.js

---

sdk/tests/deqp/functional/gles3/es3fIntegerStateQueryTests.js

Previously the initial value for that blendfunc parameter was used to
reset all of the blendfunc parameters, which was wrong because the
default for SRC parameters is ONE while the DST parameters's is ZERO
Here we take care to only touch the one parameter being modified. If we wanted to stay 100% close to dEQP could instead not use an initial value and reset the blendfunc with the known default values. I didn't choose this approach because it would make the testing of the initial value of blendfunc useless as it would be reset just before.

Fix the ES3 IntegerStateQuery blendfunc tests reset

---

sdk/tests/deqp/framework/opengl/simplereference/sglrReferenceContext.js
sdk/tests/deqp/functional/gles3/es3fTextureSpecificationTests.js

This makes the following two tests passing (at least on Linux):
texturespecification/basic_copyteximage2d.htm
texturespecification/basic_copytexsubimage2d.htm

Implement copyTex{Sub}Image2D in sglrReferenceContext

---

sdk/tests/deqp/functional/gles3/es3fFboColorbufferTests.js
sdk/tests/deqp/functional/gles3/es3fFboMultisampleTests.js
sdk/tests/deqp/functional/gles3/es3fFboRenderTest.js
sdk/tests/deqp/functional/gles3/es3fFboTestCase.js
sdk/tests/deqp/functional/gles3/es3fNegativeTextureApiTests.js
sdk/tests/deqp/functional/gles3/es3fShaderStateQueryTests.js

Many cases fail because some related gl states fail to be reset after the completion of last case, such as cases in FboRender and FboMultisamples, etc. 
Original deinit() functions in es3fFboRenderTest.js and es3fFboTestCase.js are moved to function deinit() in tcuTestCase.js.
16 (of 46) cases in FboMultisample will pass after this patch

Realize function deinit() in tcuTestCase.js

---

sdk/tests/deqp/framework/common/tcuTexture.js
sdk/tests/deqp/framework/common/tcuTextureUtil.js
sdk/tests/deqp/functional/gles3/es3fTextureSpecificationTests.js

THis cuts running time from 645s to 568s on my local Linux,
about 12% gain.

Optimize texturespecification tests.

---

sdk/tests/conformance/attribs/gl-vertexattribpointer.html

It looks like this was never tested. It fails in Firefox
Should probably test more than attribute 0? Also should probably test rendering with each combination?

check gl.getVertexAttrb and gl.getVertexAttribOffset

---

sdk/tests/deqp/functional/gles3/es3fFboInvalidateTests.js

In InvalidateFboUnbindReadCase the result picture should be rendered from the buffer that is not invalidated.

Fix an error in FboInvalidateTests

---

sdk/tests/deqp/modules/shared/glsBuiltinPrecisionTests.js

I have come back to office this week from honeymoon, :). Long time not to touch the code. Please take a look at this small patch, @zhenyao and @kenrussell . It can fix all failures for outerproduct.html against vertex shader tests. 
Thanks a lot!

indexing to shader output is not correct in outerproduct

---

sdk/tests/conformance/rendering/00_test_list.txt
sdk/tests/conformance/rendering/point-size-varyings.html

This check attempts to provoke a [bug in ANGLE](https://bugs.chromium.org/p/angleproject/issues/detail?id=1380) on Windows. 
The test passes in Edge on Windows and in Firefox and Chrome on Linux, and fails in Chrome (version 50.0.2661.102) on Windows and in Firefox (version 46.0.1) on Windows. I heard it also fails in Chrome on OS X. 
When gl_PointSize is mentioned but not set in vertex shader and gl_PointCoord is mentioned but not read in fragment shader, rendering a triangle coloured with varyings fails. The check is based on triangle.html in same folder.

add point-size-varyings.html

---

sdk/tests/conformance/rendering/00_test_list.txt
sdk/tests/conformance/rendering/point-specific-shader-variables.html

- Renamed the test.
- Added back in variants that only conditionally write gl_PointSize.
- Changed the writes of gl_PointSize to write 1.0, since that's the only guaranteed supported maximum point size.
Future work to test point rendering in these scenarios is TBD. At least some of this functionality is already covered by other tests.

Clarified recently-added test of point-specific shader variables.

---

sdk/tests/conformance2/vertex_arrays/vertex-array-object.html

Name of deleted buffer immediately becomes invalid. Though the
underlying container which the deleted buffer is attached to may
continue using the object ("D.1.3 Deleted Object and Object Name
Lifetimes", page 315 ES spec 3.0.4).
Also in section 3 "WebGL Resources" in WebGL 1.0 spec,
"If authors wish to control when the underlying
resource is released then the delete call can be made explicity".
So the deleted object cannot be used any more.

Deleted objects should not exist

---

sdk/tests/deqp/functional/gles3/es3fTextureShadowTests.js

The textureType of Texture2DArrayShadowCase should be TEXTURETYPE_2D_ARRAY

Fix a miuse of texture type in TextureShadowTests

---

sdk/tests/deqp/modules/shared/glsFboCompletenessTests.js

Issue a warning instead of fail in fbo completeness checking.

---

sdk/tests/conformance/misc/webgl-specific.html

If no buffer is bound to enabled attribution, draw call will genetate
invalid operation error. Refer section 6.5 Enabled Vertex Attributes and
Range Checking in WebGL 1.0 spec.
See some discussion in https://codereview.chromium.org/2019513004/

Attach buffer to VAO before draw call

---

sdk/tests/deqp/modules/shared/glsShaderExecUtil.js

This bug is a little deep, which takes me a lot of time these days. Now, all matrix related failures in builtin precision can pass. They are matirxcompmult.html, transpose.html, determinant.html and inverse.html. 
PTAL. Thanks!

fix bugs against builtin precision for matrix operation

---

sdk/tests/deqp/functional/gles3/es3fNegativeVertexArrayApiTests.js

This is a WebGL 2.0 limitation different from C++ code. See section 5.6
Enabled Attribute in WebGL 2.0 spec.

At least one enabled attribute with 0 divisor for instanced drawing

---

specs/latest/2.0/index.html

These are in section 2.9.3, not 2.8.3. Perhaps they moved between dot releases of the ES 3.0 spec.

Fix references to instancing and drawing commands.

---

sdk/tests/conformance2/rendering/draw-buffers.html

Without specifying draw buffers, gl_FragColor only writes to color
number zero (GLES3 spec section 3.9.2 Shader Outputs). But with
specifying draw buffers with drawBuffer, gl_FragColor should write to
all enabled color buffers (GLES3 spec section 4.2.1 Selecting Buffers
for Writing). Also refer Issues 3) in Ext_draw_buffers extension.

Broadcast writes to gl_FragColor to enabled color buffers

---

sdk/tests/deqp/framework/common/tcuSkipList.js

Native dEQP also fails on these tests. Please refer:
https://android.googlesource.com/platform/external/deqp/+/master/android/cts/master/src/gles3-test-issues.txt
https://android.googlesource.com/platform/external/deqp/+/master/android/cts/master/src/gles3-driver-issues.txt

Suppress some shader texture function tests

---

sdk/tests/deqp/framework/common/tcuInterval.js

Built-in function clamp(x, min, max) will clamp x to the range [min, max]. However, if min > max, the result is undefined, we should not check the result's precision in this situation. This small change fix a bug to detect this edge case, which finally make clamp.html pass. 
It also follows the design of native deqp.
PTAL. Thanks!

fix the bug for builtin_precision.clamp

---

sdk/tests/deqp/modules/shared/glsBuiltinPrecisionTests.js

The precision calculated by JS against trigomometric functions is not accurate, making some cases failed. This change updates the precision for trigomometric functions according to the latest native deqp: https://android.googlesource.com/platform/external/deqp/+/deqp-dev/modules/glshared/glsBuiltinPrecisionTests.cpp#2290. It can fix a number of failures in webgl deqp files, say, sin.html, cos.html, tan.html, and so on. 
PTAL. Thanks!

update the precision for trigomometric functions

---

sdk/tests/deqp/framework/common/tcuBilinearImageCompare.js
sdk/tests/deqp/functional/gles3/es3fFboMultisampleTests.js

- Fixing the masks which extracts the different channels on bilinearCompare.
- Using a different random seed because the bilinearCompare (even in C++'s deqp) does not handle a few boundary cases correctly.

FboMultisample Fix

---

sdk/tests/deqp/modules/shared/glsBuiltinPrecisionTests.js

There are failures in arc trig funcs under deqp builtin precision, for example, asin, acos, atan. The corresponding native code has been updated a lot. For example, the Math.PI used by Web side equals to 3.141592653589793 in browsers (tested against Chrome and Firefox). It is not so accurate as that in native C++ code, which is defined to DE_PI_DOUBLE (3.14159265358979323846), see https://android.googlesource.com/platform/external/deqp/+/deqp-dev/framework/delibs/debase/deMath.h#42. But the C++ variables can not hold such an accurate PI too. 
Finally, it turns out that the native deqp has landed a patch to relax the restrictions for the precision, so the native tests can pass. In fact, the results calculated by builtin functions in WebGL shader and GLES shader are exactly the same. The …

fix the builtin precision related bugs for arc trig funcs

---

conformance-suites/1.0.0/conformance/context-attributes-alpha-depth-stencil-antialias.html
conformance-suites/1.0.1/conformance/context/context-attributes-alpha-depth-stencil-antialias.html
conformance-suites/1.0.2/conformance/context/context-attributes-alpha-depth-stencil-antialias.html
conformance-suites/1.0.3/conformance/context/context-attributes-alpha-depth-stencil-antialias.html

add this change to suite1.0.3
Hi, zhenyao  & ken,
Because we test anti-alias feature based on suite1.0.3, I am not sure that it is suitable to add the anti-alias change to suite1.0.3. If not, please ignore this patch. Thank you.

Some anti-alias algorithms may not effect on diagonal line pixels,

---

sdk/tests/deqp/framework/opengl/gluTextureUtil.js
sdk/tests/deqp/functional/gles3/es3fFragmentOutputTests.js

This aligns with native C++ dEQP. But it doesn't fix any failures.

Enable color renderable check for fragmentoutput.html

---

sdk/tests/deqp/framework/common/tcuFloatFormat.js
sdk/tests/deqp/modules/shared/glsBuiltinPrecisionTests.js

Fix more bugs against builtin precision. This change is aligned with the corresponding native code. With this change applied, most cases in inversesqrt.html and atan2.html can pass. 

fix bugs for atan2 and inversesqrt in builtin precision

---

sdk/tests/deqp/framework/common/tcuTexCompareVerifier.js
sdk/tests/deqp/framework/delibs/debase/deMath.js
sdk/tests/deqp/functional/gles3/es3fTextureShadowTests.js
sdk/tests/deqp/modules/shared/glsTextureTestUtil.js

Realize function isNearestMipmapLinearCompareResultValid() to ensure the correctness of result comparisons in nearest_mipmap_linear related cases.
With this patch, all the nearest_mipmap_linear related cases in es3fTextureShadowTests will pass.

Fix bugs in nearest_mipmap_linear cases in es3fTextureShadowTests

---

sdk/tests/deqp/modules/shared/glsBuiltinPrecisionTests.js

Div operation will lead to precision loss, we should not use
a constant value to store the result of constant division for
derived functions, for example: PI / 180. We should use Div
function in derived functions, which will bring in the precision
calculation.

Fix deqp builtin precision bugs in radians.html

---

sdk/tests/deqp/functional/gles3/occlusionquery.html

Query's result must not be made available in the current frame. So
occlusion query test does query result check in next frame, so does
pixles check. By default, color buffer should be cleared before a new
frame. So set preserveDrawingBuffer as true when creating WebGL context
to preserve color buffer in next frame. Please refer section 2.2 "The
Drawing Buffer" in WebGL 1.o spec and section 5.23 "Queries' results
must not be make available in the current frame" in WebGL 2.0 spec.

Fix occlusion query test

---

sdk/tests/deqp/framework/common/tcuTexCompareVerifier.js
sdk/tests/deqp/functional/gles3/es3fTextureShadowTests.js

1. deMath.max and deMath.min should be used to compare arrays instead of numbers
2. Add missed tcuTexture.CubeFace.CUBEFACE_NEGATIVE_X in function es3fTextureShadowTests.clampFloatingPointTextureCube()
All cases in TextureShadowTests can pass with this patch.

More bug fixes in TextureShadowTests

---

extensions/proposals/WEBGL_compressed_texture_s3tc_srgb/extension.xml

Hi,
I am currently working on [linear rendering](http://docs.unity3d.com/Manual/LinearLighting.html) for mobile which led me to look at WebGL to figure out what's missing to enable linear rendering on this platform as well and the much higher rendering quality that correct mathematics provides.
WebGL 2.0 supports sRGB framebuffers and sRGB textures which is required for linear rendering. 
However, the supported texture formats are either uncompressed sRGB which consumes a lot of bandwidth and space or ETC2 sRGB textures which are not actually supported by the hardware on desktop and expected to be uncompressed.
With our WebGL support with rely on DXT to benefit hardware compressed texture hence for linear rendering we need sRGB DXT.
This proposal is an extension to expose sRGB DXT …

Added WEBGL_compressed_texture_s3tc_srgb proposal

---

sdk/tests/deqp/functional/gles3/es3fSyncTests.js

This bug would cause the comparison "[number] > undefined" to be
repeatedly reevaluated, which would always return false. Thus the
timeout would never be applied.

Fixed typo in name of constant in sync tests.

---

sdk/tests/conformance2/extensions/ext-color-buffer-float.html
sdk/tests/deqp/functional/gles3/es3fFboColorbufferTests.js
sdk/tests/deqp/functional/gles3/es3fFboTestCase.js
sdk/tests/deqp/functional/gles3/fbocolorbuffer/blend.html
sdk/tests/deqp/functional/gles3/fbocolorbuffer/clear.html
sdk/tests/deqp/functional/gles3/fbocolorbuffer/fbocolorbuffer_test_generator.py
sdk/tests/deqp/functional/gles3/fbocolorbuffer/tex2d.html
sdk/tests/deqp/functional/gles3/fbocolorbuffer/tex2darray.html
sdk/tests/deqp/functional/gles3/fbocolorbuffer/tex3d.html
sdk/tests/deqp/functional/gles3/fbocolorbuffer/texcube.html

We don't expose EXT_color_buffer_half_float and it is not part of the
EXT_color_buffer_float extension.

RGB16F isn't color renderable in WebGL2.

---

extensions/EXT_color_buffer_float/extension.xml

@zhenyao PTAL. Goes with #1778 .

Added note about EXT_color_buffer_float not making RGB16F renderable.

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/loops-with-side-effects.html

These are variations on loops that would either cause a GPU reset on
macOS 10.9, or give bad results. Seems fixed in macOS 10.10

Loops with side effects

---

sdk/tests/deqp/functional/gles3/es3fFboMultisampleTests.js
sdk/tests/deqp/functional/gles3/es3fFboTestCase.js

Multi-sample floating-point color buffers are not supported.
Skip tests against those color formats.

Fix bugs in fbomultisample.html

---

specs/latest/1.0/index.html
specs/latest/2.0/index.html

In GLES 2.0 and 3.0 this is undefined behavior. The WebGL 1.0 spec
already specified this for drawArrays and drawElements, but this patch
documents it also in the spec differences section and in the WebGL 2.0
spec.
There are already tests for this, including tests for WebGL 2.0 in
dEQP.

Clarify that an error is generated when drawing without program

---

sdk/tests/deqp/framework/referencerenderer/rrRenderer.js

The failure is a little deep, the variables and the shaders feed to real renderer and renference renderer are exactly the same. However, the generated reference image looks much sharper than the real result, I guess that either the msaa is not applied to the reference image, or the reference image doesn't change the colos space from srgb8_alhph8 to linear (rgba). After tracing the native code, it turns out the deduction is true. 
Now fboMultisample.html can pass. PTAL. Thanks!

fix the bugs in fboMultisample.html against sRGB color format

---

sdk/tests/deqp/framework/common/tcuRGBA.js
sdk/tests/deqp/functional/gles3/es3fFramebufferBlitTests.js

- Added a function to convert an array of floats into an RGBA object.
- Used the aforemention function to solve some framebufferblit tests'
issues.

Create an RGBA from an array of floats

---

sdk/tests/conformance/misc/00_test_list.txt
sdk/tests/conformance/misc/out-of-bounds-index-buffers.html

Out-of-bounds-index-buffers.html tests whether implementations successfully handle
the "Out-of-Range Array Accesses" section of the WebGL 1 specification.
The test accomplishes this by having a vertex shader with two attributes: a position
and value. The position attribute will come from large position vertex buffer
filled with tri-strips that form quads which cover the entire canvas. This vertex
buffer will not be indexed off the end. The value attribute will come from a tiny
vertex buffer that is filled with a known-ahead-of-time "random" value. This buffer
will be indexed off the end. The shader tests whether the random value is either
found in the vertex buffer or is the zero index. Upon success, the shader outputs
green. On failure, the shader outputs red.
The test passes if …

Add out-of-bounds-index-buffers.html conformance test

---

sdk/tests/deqp/framework/opengl/simplereference/sglrReferenceContext.js

After apply the latest Chromium patches about sRGB, fboMultisample.html failed on Linux platform. It turns out that there is one more color space mapping between sRGB color space and linear color space. 
PTAL.

fix bugs in fboMultisample.html for Linux

---

sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-bitmap-from-canvas.js

The last parameter of runImageBitmapTest() indicates whether this is a tex-3d test or not. I checked and found that all the other ImageBitmap tests pass "true" for 3d tests except the one from canvas. This is the fix.

Fix error in image-bitmap-from-canvas tex-3d tests

---

sdk/tests/deqp/framework/referencerenderer/rrRenderer.js
sdk/tests/deqp/functional/gles3/fborender.html

In former implementation of drawTriangles, all points on the sides of a triangle are regarded as being inside the triangle, so points on the border of two triangles will be rendered twice, which leads to the problem that when blending is enabled, points on the common side of two triangles will be blended twice and get wrong color.
e.g. SharedColorbuffer tests in FboRenderTest
Based on native dEQP codes, this patch re-implements drawTriangle which specifies the inclusiveness of the sides of a triangle.

Fix a bug in rrRenderer.drawTriangles

---

sdk/tests/deqp/functional/gles3/es3fFboRenderTest.js

Also, remove RGB16F because it's not color-renderable.

Fix wrong extension in fborender.html

---

sdk/tests/deqp/framework/common/tcuImageCompare.js
sdk/tests/deqp/framework/common/tcuTexture.js
sdk/tests/deqp/framework/referencerenderer/rrUtil.js
sdk/tests/deqp/functional/gles3/es3fFboTestUtil.js
sdk/tests/deqp/functional/gles3/es3fFramebufferBlitTests.js

Fix two main problems in current code:
1. Set alpha channel as 1 instead of 255 for RGB format.
2. Don not need to clamp float format color to [0, 1]. The value is
always in [valueMin, valueMax].

Fix reference color in framebufferblit test

---

sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image-bitmap-from-image.js
sdk/tests/js/tests/tex-image-and-sub-image-with-image-bitmap-utils.js

A WebGL conformance test for ImageBitmap seems to time out some times:
https://bugs.chromium.org/p/chromium/issues/detail?id=596622
Here we add more logs to that test so that next time when it timed out, we will have enough info to know which point it timed out.

Add more logging to ImageBitmap test

---

sdk/tests/conformance2/rendering/draw-buffers.html

In ES3, when there is only a single output, it defaults to location zero. It
should not broadcast to all buffers.

Fix a bug in draw-buffers.html

---

sdk/tests/deqp/functional/gles3/es3fFboInvalidateTests.js

The type of the result of the fragment shader should not always be vec4, or when the input color has an integer type, the fragment shader will not get the correct color as you wish.
This patch also changes part of WebGL settings to align with those of native dEQP.
All cases in fboinvalidate/format can pass after this patch

Fix a bug in FboInvalidateTest

---

sdk/tests/deqp/functional/gles3/es3fFragmentOutputTests.js

Image comparison was done with a threshold of 1 for unwritten integer
channels, which forced them to be in the [-1, 1] range, This was not
correct because the integer formats are not normalized, use UINT_MAX
instead.
This makes the code match the C++ version of dEQP.

deqp/gles3/fragmentoutput: for ints, the threshold is UINT_MAX

---

sdk/tests/deqp/functional/gles3/es3fFboRenderTest.js

C++ dEQP uses bind to create in the fborender recreate tests. This
doesn't work in WebGL so instead we explicitly use glCreateTexture and
glCreateRenderbuffer and (grossly) set the fbo state to these new
objects.

deqp/gles3/fborender: Bind to create doesn't work in WebGL

---

extensions/WEBGL_draw_buffers/extension.xml
sdk/tests/conformance/extensions/webgl-draw-buffers.html

While upgrading to WebGL 2.0 it has been discovered that some of the behaviors defined by WebGL 1.0 with the WEBGL_draw_buffers extension will impose severe performance penalties as implementations are upgraded. Revise the extension and the conformance test to avoid these penalties.

Revise WEBGL_draw_buffers behavior.

---

sdk/tests/conformance2/glsl3/compound-assignment-type-combination.html
sdk/tests/js/tests/compound-assignment-type-combination.js

1. Refactor the test logic into a JavaScript file
2. Test that vecX *= matX is a valid operation
3. Test non-square matrices in ESSL 3.00 shaders
The WebGL 2.0 version of the test reveals a bug in ANGLE that got
fixed recenty.

Improve compound assignment type combination testing

---

sdk/tests/conformance2/buffers/uniform-buffers.html

The case cannot pass on mesa+i965, but pass on nvidia platform. It seems that shader uniform block members' default value is 0 on mesa+i965, but is 1 on nvidia driver.

Uniform block does not be initialized

---

sdk/tests/conformance/glsl/bugs/00_test_list.txt
sdk/tests/conformance/glsl/bugs/global-invariant-does-not-leak-across-shaders.html

This test fails in Chrome Canary on Mac OS, at least. Does not fail in Firefox or Safari. Not sure about Chrome on other platforms yet. Filed http://crbug.com/625363 to track it.

Add test asserting that global invariant pragma does not leak state.

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/shader-with-invalid-characters.html

Line-continuation character (backslash) is supported in WebGL 2.0. See
ESSL spec 3.00.4 in section 3.1 Character Set. This patch adds test
which is not covered by deqp/data/gles3/shaders/preprocessor.html.

Test line-continuation character in shader for WebGL 2.0

---

sdk/tests/deqp/framework/common/tcuSkipList.js

See https://github.com/KhronosGroup/WebGL/issues/1832

Another test case skipped due to R11F_G11F_B10F bug on Mac OSX.

---

sdk/tests/deqp/data/gles2/shaders/shader-lib-test.html

@zhenyao When I cleaned the lint errors in sdk folders, I modified shader-lib-test.html by mistake. I'm so sorry, PTAL. 
BTW: There are still 14576 lint errors in sdk folders. Most of them are in *.frag and *.vert files. Wheather it need help?

fix an error from pull #1795

---

sdk/tests/js/tests/gl-object-get-calls.js

After fencSync, the commands can be completed even if the getSyncParameter is
called right away.

Fix a flakiness in gl-object-get-calls.js

---

sdk/tests/conformance/textures/misc/tex-sub-image-2d-bad-args.html

When we test against the argument 'format', we should keep the argument 'type' correct. 

Fix ambiguous test cases in tex-sub-image-2d-bad-args.html

---

sdk/tests/deqp/data/gles2/shaders/preprocessor.test

This test is buggy and is in the skip list for the native dEQP (in
android/cts/master/src/gles2-failures.txt). The test is never going to
be updated (the invariace matching rules are different between ESSL 1.00
and 3.00) so to avoid confusion the test is being removed rather than
added to tcuSkipList.js.
See http://crbug.com/625363 .

Remove incorrect preprocessor.pragmas.pragma_fragment test.

---

specs/latest/2.0/index.html
specs/latest/2.0/webgl2.idl

To include tex upload from pbo functions and readPixels from unpack buffer.
@kenrussell @jdashg PTAL

Update WebGL 2 spec.

---

sdk/tests/conformance2/reading/00_test_list.txt
sdk/tests/conformance2/textures/misc/00_test_list.txt

Let's mark it as 2.0.1 for now (in case we forget about them)
@kenrussell PTAL
@Richard-Yunchao FYI

Add two Mac driver bug tests to 2.0.1+

---

specs/latest/1.0/index.html
specs/latest/1.0/webgl.idl
specs/latest/2.0/index.html

This keeps unified words in other parts of spec.

Fix typo: indx -> index

---

sdk/tests/deqp/framework/referencerenderer/rrFragmentOperations.js

A previous commit forced the fragment depth to be converted to the depth
buffer format. The behavior didn't match the C++ dEQP code for float
formats where the incoming fragment depth is just clamped.
This also reduces the amount of allocation done when we convert to the depthbuffer format.

rrFragmentOutput: fix depth compare for floats

---

sdk/tests/conformance2/glsl3/00_test_list.txt

compound-assignment-type-combination test for WebGL 2 was missing from
the test runner test list.

Fix missing entry in WebGL 2.0 test list

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/attrib-type-match.html

needs to match the function type that sets its value.
This is a WebGL2 specific behavior.
See https://github.com/KhronosGroup/WebGL/pull/1861

Add a test to verify that an active attrib's base type

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/tricky-loop-conditions.html

Some types of transformations in shader translation may need to add
new statements to implement certain types of expressions. In case an
expression inside a loop condition or loop expression requires this
kind of a transformation, it needs special handling. Add a test for
bugs in this area.
There are known failures in this test on ANGLE's DirectX backend and
NVIDIA's OpenGL drivers.

Add a test for tricky loop conditions

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/array-element-increment.html

This hits a bug in NVIDIA 364.19 OpenGL drivers. The bug is specific
to arrays that are initialized when they are declared, so it does not
affect ESSL 1.00.

Add a test for incrementing array elements

---

sdk/tests/deqp/framework/common/tcuSkipList.js

It's not supported in D3D11. Let's move them out of WebGL 2.0.0.
See https://github.com/KhronosGroup/WebGL/issues/1870
They should be added back for later versions of WebGL 2.

Skip a bunch of shadow sampler function tests in deqp

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/shader-with-mis-matching-uniform-block.html

"The same uniform declared in different shaders that are linked together
must have the same precision qualification.". See Section 4.5.3
Precision Qualifiers in GLSL ES 3.00.4 spec.

Add a test for mis-matching uniform block

---

sdk/tests/deqp/data/gles3/shaders/preprocessor.test

This is functionally equivalent to a revert of a82c23a05 but adds notes
on the expected to fail tests.
PTAL @Oletus @qkmiao @zhenyao

Revert changes to preprocessor.test

---

sdk/tests/deqp/framework/opengl/gluShaderProgram.js

The log is only printed to console when test fails. This is useful for
debugging failing cases.

Add program link info for debug purpose

---

sdk/tests/js/webgl-test-utils.js

opt_msg is ignored for failed case, so the description of it will have
no way to display. This PR fixes this so that we can easily find the
failed case with description in output.

Print description for failed test case

---

sdk/tests/conformance2/attribs/gl-vertex-attrib-i-render.html
sdk/tests/conformance2/attribs/gl-vertexattribipointer-offsets.html

update the test cases, in order to make them conform to the spec: vertex attrib function must match shader attrib type: https://www.khronos.org/registry/webgl/specs/latest/2.0/#5.31
I'd like to submit this pr to fix a couple of test cases at first. Then merge more cases in one pr later.

update attrib type in shader to match with attrib type set by vertexAttribI4{u}i{v}

---

sdk/tests/deqp/functional/gles3/es3fPixelBufferObjectTest.js

When using PBO, the result rounded by Intel GPU would have slight
difference with the one from CPU, but it still follows the spec well.
See detailed discussion at
https://bugs.freedesktop.org/show_bug.cgi?id=89314.

Add some tolerance to PBO RGB10_A2 case

---

sdk/tests/deqp/functional/gles3/es3fTextureFormatTests.js

ANGLE passes this test on native dEQP so I looked into the test source and found it uses a threshold of 17!  A threshold of 6 was enough for Chrome to pass the test on Windows and Mac.

Increase the threshold on the dEQP compressed_cube tests.

---

specs/latest/2.0/index.html

@zhenyao I will try to add test on same image attach to two different attachment points in the same fbo and fix it for chrome.

Fix a typo in WebGL 2.0 spec

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/framebuffer-unsupported.html

If an image is attached to more than one color attachment point in a
framebuffer, checkFramebufferStatus returns FRAMEBUFFER_UNSUPPORTED. See
Section 5.34 Framebuffer color attachments in WebGL 2.0 spec.

Add test to check framebuffer unsupported

---

sdk/tests/conformance/glsl/misc/shaders-with-invariance.html

According to the section 4.6.1 of GLSL ES specification 3.00.4 and 4.8.1
of GLSL specification 4.40, the pragma invariant(all) is not allowed to
be used by a fragment shader.

Fix the invariant(all) pragma in fragment shader

---

sdk/tests/conformance2/glsl3/tricky-loop-conditions.html

Using exact float comparisons makes some of the tests fail on D3D once
the other bugs are fixed, so add a little bit of tolerance to the
float comparisons.
WebGL has also made it illegal to use the sequence operator on arrays,
so remove the incorrect test for that.
One test description is also clarified.

Improve tricky loop conditions test

---

sdk/tests/py/lint/LICENSE
sdk/tests/py/lint/README.md
sdk/tests/py/lint/lint.py
sdk/tests/py/lint/lint.whitelist

@kenrussell @zhenyao @Honry I modified the lint tool to make it more suitable for WebGL. In WebGL conformance tests, most of lint errors are TRAILING WHITESPACE, INDENT TABS and CR AT EOL. So we removed non-existent lint error scansion and ran the tool without installing libraries. Since there are many \*.js, \*.frag and \*.vert files in WebGL tests, we also scanned this three file formats in our new tool. You can try the tool from the root of your local WebGL/sdk/tests working directory as follow:
**If you want to check your pull request:**
`./py/lint/lint.py -p`
**If check specified folder, the specified folder must be relative path of WebGL/sdk/tests:**
`./py/lint/lint.py -d conformance/attribs`
**If check other repos, you can specify the repo name with `-r`, default is …

Add a lint tool for catching common mistakes in test files

---

sdk/tests/conformance2/reading/read-pixels-pack-parameters.html
sdk/tests/conformance2/textures/misc/tex-unpack-params.html
specs/latest/2.0/index.html

This is @jdashg 's proposal. @jdashg made two valid points: 1) this is the most strict constraints, and it's always easier to loose constraints than to tighten them in the future; 2) unconstrained skip parameters usage always can be achieved through adjusting the data store offset.
Also, I verified deqp tests are all within this constraints, i.e., anything violating these constraints are not tested, therefore, bug prone.
Let's go with this for now.
@kenrussell @jdashg Please take a look.
All tests are modified according to the bots from this CL (https://codereview.chromium.org/2154153002/)
@Oletus @qkmiao @Richard-Yunchao @Kangz @null77 @vonture @grorg @RafaelCintron FYI

Fix PixelStore tests according to the new WebGL2 constraints.

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/vector-dynamic-indexing-nv-driver-bug.html
sdk/tests/conformance2/glsl3/vector-dynamic-indexing.html

So we can enable most of the test cases in WebGL 2.0.0

Split the NV driver bug from general vector-dynamic-indexing.html

---

sdk/tests/deqp/framework/common/tcuSkipList.js

Some of these tricky tests were failing on various drivers and Hw,
so they were removed from the Android CTS. The tests themselves
might not be buggy, but they are not required to pass on Android.
PTAL, this should fix some failures on Windows, probably on other platforms.

Skip WebGL 2 blit tests mark as having issues in GLES3.

---

sdk/tests/deqp/framework/common/tcuSkipList.js

These have been fixed in ANGLE's preprocessor so they can now be removed.

Remove suppressions for preprocessor tests.

---

sdk/tests/js/tests/tex-input-validation.js

Sorry for the mistake, but if the destination format is unsized,
then we don't require component size to match, just that requiured
components are available.

Revert https://github.com/KhronosGroup/WebGL/pull/1908

---

sdk/tests/conformance2/textures/misc/tex-unpack-params.html

Unpack param constraints should not apply.

Test the case in TexImage{2|3}D where no source data is provided.

---

sdk/tests/deqp/framework/common/tcuSkipList.js

These were prefixed with 'fbo' when it seems they should start
directly at 'blit'.
PTAL, I think this is the correct syntax.

Fix WebGL 2 skips for fbo.blit.

---

sdk/tests/deqp/framework/common/tcuSkipList.js

Corentin (@Kangz) diagnosed these failures in ANGLE and determined that they are due to the HLSL compiler generating invalid bytecode.
His findings, along with a shader that reproduces them, can be found here: https://gist.github.com/Kangz/a0624ca46fb1da5e7804ee80900bf291

Skip some tests on which the HLSL compiler generates invalid code.

---

sdk/tests/conformance/glsl/misc/shaders-with-invariance.html

After studying the specifications, the rules are as follows:
- ESSL 1.0 allows "#pragma STDGL invariant(all)" in both vertex and
fragment shaders, no matter whether the context is WebGL 1.0 or 2.0.
When linking ESSL 1.0 shaders in either context type, the invariant
qualifier must match on varyings shared between vertex and fragment
shaders.
- ESSL 3.00 allows the invariant #pragma only in vertex shaders. The
invariant qualifier is allowed only on output variables. (The
specification isn't clear on whether it is allowed on output
variables of fragment shaders, or just vertex shaders.) Because the
invariant qualifier is not allowed on input variables, it is not
required to match on varyings shared between vertex and fragment
shaders.
These tests, which all use ESSL 1.0, must apply equally …

Revise ESSL 1.0 invariance tests for WebGL 1.0 and 2.0.

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/invalid-invariant.html

Add negative tests for invariance in ESSL 3.00 shaders.

---

specs/latest/1.0/index.html

The intent of the specification was to short-circuit the
implementation of all methods when the context was lost. The
INVALID_OPERATION error for previously-invalidated WebGLObject
arguments is only supposed to be generated if the context is not lost.

Clarify context lost behavior of methods taking WebGLObjects.

---

sdk/tests/deqp/functional/gles3/es3fInstancedRenderingTests.js

This patch delete one line from https://github.com/KhronosGroup/WebGL/pull/1906. 
Calling to vertexAttribPointer for all attribs in native deqp during deinit is valid. However, It is not valid in webgl according to the latest spec: https://www.khronos.org/registry/webgl/specs/latest/2.0/#5.31. 

fix the bug that caused by difference between webgl and gles

---

sdk/tests/conformance/glsl/bugs/sequence-operator-evaluation-order.html
sdk/tests/conformance2/glsl3/tricky-loop-conditions.html
sdk/tests/conformance2/glsl3/vector-dynamic-indexing.html

1. Check that all short-circuiting operators work as the second
operand of a sequence operator.
2. Check that a sequence operator with indexing an array constructor
inside works inside a loop condition or loop expression.
3. Check that dynamic indexing of vectors as an l-value works inside
a sequence operator.

Add more tests for sequence operator corner cases

---

sdk/tests/deqp/modules/shared/glsBuiltinPrecisionTests.js

We implement "Alternatives" class according to native deqp.

add class Alternative to glsBuiltinPrecision.js according to native deqp

---

sdk/tests/conformance2/rendering/attrib-type-match.html

Add some test cases to cover generic attribs when check the vertex type by vertexAttrib API with the corresponding type in shader. 
Fortunately, add these new added test cases can pass after the Chromium CL https://codereview.chromium.org/2148723004/ applied. 
@zhenyao , PTAL.

add some test cases to test generic attrib

---

sdk/tests/deqp/functional/gles3/es3fMultisampleTests.js

This was the only dEQP test using "testSkippedOptions", causing the
pass rate of the conformance suite to be less than 100%.

Turn skipped multisample tests into warnings.

---

sdk/tests/js/tests/gl-object-get-calls.js

In webgl2 3.7.5 Renderbuffer objects:
To be backward compatible with WebGL 1, also accepts internal format
DEPTH_STENCIL, which should be mapped to DEPTH24_STENCIL8 by implementations.

Add DEPTH_STENCIL to depth-renderable list.

---

sdk/tests/deqp/functional/gles3/es3fFboMultisampleTests.js
sdk/tests/deqp/functional/gles3/es3fFboTestCase.js

Enable the tests and move related files to 2.0.1

Multi-sample floating-point color buffers can be optional supported.

---

sdk/tests/conformance/programs/00_test_list.txt
sdk/tests/conformance/programs/program-infolog.html

Chrome fails this test both on nVidia and Intel. Firefox passes this test.

Check getProgramInfoLog does not return correct empty string

---

sdk/tests/deqp/functional/gles3/es3fFboTestCase.js

GLES3 spec, section 6.1.15
"Since multisampling is not supported for signed and unsigned integer internal formats, the value of
NUM_SAMPLE_COUNTS will be zero for such formats. For every other accepted internalformat, the value of NUM_SAMPLE_COUNTS is guaranteed to be at least one, and the maximum value in SAMPLES is guaranteed to be at least the value of MAX_SAMPLES."
@Richard-Yunchao please have a look, 3x!

Add sample count check on GL_MAX_SMAPLES

---

conformance-suites/1.0.1/conformance/typedarrays/array-unit-tests.html
conformance-suites/1.0.2/conformance/typedarrays/array-unit-tests.html
conformance-suites/1.0.2/conformance/typedarrays/data-view-test.html
conformance-suites/1.0.3/conformance/typedarrays/array-unit-tests.html
conformance-suites/1.0.3/conformance/typedarrays/data-view-test.html
sdk/tests/conformance/typedarrays/array-unit-tests.html
sdk/tests/conformance/typedarrays/data-view-test.html

Several tests are making outdated assertions about various TypedArray and DataView related functions. Their behavior was changed by TC39 [recently](https://github.com/tc39/ecma262/pull/410).
This PR amends those tests so that either the old or new behavior is accepted. I'm not sure if there's a way to officially mark one behavior as deprecated. This PR doesn't update the snapshots, just the tests under sdk/.
Ping @kenrussell; we discussed this briefly over email a while ago. @littledan @leobalter

Update tests for recent ECMAScript changes

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/no-attribute-vertex-shader.html

RE #1954 
I'm not sure this test is needed actually
There's a test here
https://www.khronos.org/registry/webgl/sdk/tests/conformance/rendering/point-no-attributes.html?webglVersion=1&quiet=0
That already tests no attributes and Safari fails it. 
Please push Apple to fix that. Also iOS has never supported `preserveDrawingbuffer: true` (which given Canvas2D works just fine it seems like it can't be that much work)

add a no-attribute test

---

sdk/tests/conformance2/extensions/ext-color-buffer-float.html

Jointly with https://github.com/KhronosGroup/WebGL/pull/1946 to cover the multisample support test for float-point color renderbuffers.

Add multsampling testcases for float-point color renderbuffers

---

sdk/tests/deqp/functional/gles3/es3fFboColorbufferTests.js
sdk/tests/deqp/functional/gles3/es3fFboDepthbufferTests.js
sdk/tests/deqp/functional/gles3/es3fFboInvalidateTests.js
sdk/tests/deqp/functional/gles3/es3fFboMultisampleTests.js
sdk/tests/deqp/functional/gles3/es3fFboStencilbufferTests.js
sdk/tests/deqp/functional/gles3/es3fFboTestCase.js
sdk/tests/deqp/functional/gles3/es3fFramebufferBlitTests.js

In https://github.com/KhronosGroup/WebGL/pull/1946, preCheck's behavior
is only changed for fbomultisample case. This breaks behavior of
preCheck for other cases. This patch makes all the appeared preChecks
return true if no exception or early return.
This also changes test status from pass to a warning for tests which
returns early.

Fix regression on preCheck

---

sdk/tests/conformance2/textures/misc/copy-texture-image-webgl-specific.html

copyTexSubImage3D should mark a specific layer/level to be cleared, but it is not.
so textures is wrongly initialized after copyTexSubImage3D by framebuffertexturelayer.

Add test case to function copyTexSubImage3D

---

specs/latest/2.0/index.html

This change was made for CopyTexSubImage2D some time ago, but the
change was never propagated to the WebGL 2.0 specification.

CopyTexSubImage3D should leave pixels outside the framebuffer untouched.

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/texture-offset-out-of-range.html
sdk/tests/conformance2/glsl3/texture-offset-uniform-texture-coordinate.html

In texture-offset-out-of-range the shader uses a uniform variable to
represent the texture coordination, which is not a common usage and will
lead to chromium WebGL2 context crash on Windows using Intel GPU on
Broadwell machines.
This patch uses attribute instead of uniform variables to work around this
issue.

Add a new test to expose issues in texture-offset-out-of-range

---

sdk/tests/conformance2/textures/misc/copy-texture-image-webgl-specific.html

copy area intersects with some part of read framebuffer should be replaced.
out-of-bounds pixels should remain unchanged.

Add test case to function copyTexSubImage to test out-of-bounds behaviors

---

sdk/tests/conformance/context/00_test_list.txt
sdk/tests/conformance/context/context-no-alpha-fbo-with-alpha.html

Add a no alpha context test.
The test makes a no alpha context, and a framebuffer/texture with an alpha channel. The test checks that working with the framebuffer/texture doesn't affect the back buffer.
The newly added test fails without https://codereview.chromium.org/2053983002/#, but succeeds with the CL.

Add a no alpha context test.

---

sdk/tests/conformance/context/context-no-alpha-fbo-with-alpha.html

These fixes make the test from #1763 pass on top of tree Chromium. In
particular it was necessary to use a tolerance of 1.

Fixes to no-alpha context test.

---

sdk/tests/conformance/context/context-attributes-alpha-depth-stencil-antialias.html

Some anti-alias algorithms may not effect on 2x2 canvas.
A postprocessing AA cannot handle 2x2 canvas because the following example cannot
be interpreted as triangle.
```
_____
|X| |
-----
| | |
¯¯¯¯¯
```
So enlarge the canvas to 3x3, because the following example can be interpreted
as triangle.
```
_______
|X|X|X|
-------
|X|X| |
-------
|X| | |
¯¯¯¯¯¯¯
```
Follow-up of PR #1730
BUG=crbug.com/634945

Some anti-alias algorithms may not effect on diagonal line pixels, but must preserve the behavior on the non-edge pixel.

---

specs/latest/2.0/index.html

These were added elsewhere in the spec after issues were resolved some
time ago, but were not added to this detail table for this method.

Add COPY_READ_BUFFER and COPY_WRITE_BUFFER to targets for bindBuffer.

---

sdk/tests/deqp/framework/common/tcuSkipList.js

It falls into the same bucket as the other missing D3D11 shadow sampling
functions but was missed on the first pass of supressions.
See KhronosGroup#1870

Skip the texture_functions.texture.sampler2darrayshadow_vertex test.

---

sdk/tests/conformance/context/context-attributes-alpha-depth-stencil-antialias.html

When drawing a square with 2 different color triangles, some AA may
affect all the pixels on diagonal, while some others, such as CMAA, may
keep the pixels on the egde intact. Given this, (1, 1) can be always a
good candidate for the check.

Check the result from AA in a general way

---

sdk/tests/conformance2/textures/misc/tex-mipmap-levels.html

To catch a bug on MacOSX. glTexStorage* don't work as expected if
the current GL_TEXTURE_BASE_LEVEL is not 0. As a result, the shader
function textureSize returns wrong size.

Add a texture mipmap case

---

sdk/tests/conformance2/misc/00_test_list.txt
sdk/tests/conformance2/misc/getextension-while-pbo-bound-stability.html

Regression test for [Chromium Issue 641643](https://bugs.chromium.org/p/chromium/issues/detail?id=641643)

Add test: getExtension while PBO is bound should not crash

---

specs/latest/2.0/index.html

&lt;code&gt; in &lt;a&gt; will make the link in tables of contents be unavailable.
Other similar usage doesn't use &lt;code&gt; tag too.
This fixes https://github.com/KhronosGroup/WebGL/issues/1998.

Fix link in table of contents

---

specs/latest/2.0/index.html

This is reported on https://github.com/KhronosGroup/WebGL/issues/1997
@kenrussell PTAL

Add missing LUMINANCE format to the tex format table in WebGL2 spec.

---

sdk/tests/conformance/rendering/00_test_list.txt
sdk/tests/conformance/rendering/clipping-wide-points.html
sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/clipping-wide-points.html
sdk/tests/deqp/framework/common/tcuSkipList.js
sdk/tests/js/tests/clipping-wide-points.js

This test is set to 2.0.1, to unblock WebGL2 release.
Move the failing test cases from clipping.html (they are covered in the newly added test)

Add a test to verify clipping works fine with wide points.

---

conformance-suites/1.0.0/conformance/object-deletion-behaviour.html
conformance-suites/1.0.0/conformance/resources/webgl-test-utils.js
conformance-suites/1.0.1/conformance/misc/object-deletion-behaviour.html
conformance-suites/1.0.1/conformance/resources/webgl-test-utils.js
conformance-suites/1.0.2/conformance/misc/object-deletion-behaviour.html
conformance-suites/1.0.2/conformance/resources/webgl-test-utils.js
conformance-suites/1.0.3/conformance/misc/object-deletion-behaviour.html

Too bad I started fixing from 1.0.0 to 1.0.3 and not in the opposite order, because otherwise I would have just copy-pasted the version of `shouldGenerateGLError` that accepts an array instead of re-implementing it myself.
If it's not too much of a churn I'd like to leave it as is, but I can also take more time to do that.
r? @kenrussell

Allow gl.NO_ERROR when attempting to bind a deleted object in old test suites.

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/blitframebuffer-test.html

If the src buffer and dst buffer are identical, generates INVALID_OPERATION.
See the gles 3.0.4 spec about this at https://www.khronos.org/registry/gles/specs/3.0/es_spec_3.0.4.pdf#nameddest=section-4.3.3. It is at the middle on page 198.
On the gles3 man page of blitFramebuffer at https://www.khronos.org/opengles/sdk/docs/man3/html/glBlitFramebuffer.xhtml. It says that this behavior is not defined. However, gles3 man page is not always updated. Moreover, to be undefined is not a good definition.

Add test cases for blitFramebuffe to cover more corner cases.

---

sdk/tests/deqp/functional/gles3/es3fShaderCommonFunctionTests.js

Mac AMD drivers do not, so this caused some cases to fail
in shadercommonfunction.html

roundEven should not distinguish -0/+0

---

sdk/tests/conformance2/rendering/blitframebuffer-test.html

Add more test cases to do a thorough test for this feature. 
PTAL. Thanks a lot.

Add more tests to blitFramebuffer for feedback loop: src buffer and dst buffer has the same image

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/blitframebuffer-filter-srgb.html

This test case will fail on MacOSX (and will fail on other platforms which is desktop OGL and the version < 4.4). But with this patch: https://codereview.chromium.org/2286593002/. It can pass!

Add test cases for blitFramebuffer to filter srgb. This means that the width/height of src region and dst region are different.

---

sdk/tests/conformance2/buffers/uniform-buffers.html
sdk/tests/js/tests/gl-object-get-calls.js

WebGL specification was revised to generate an INVALID_OPERATION error when attemping to bind a deleted object. This patch updates related tests to meet new spec.

Update tests related to binding a deleted object

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/canvas-resizing-with-pbo-bound.html

Tests rapid resizing of the canvas while a pixel unpack buffer is bound.
Regression test for Chromium bug 644572
https://bugs.chromium.org/p/chromium/issues/detail?id=644572

Add WebGL 2 conformance test canvas-resizing-with-pbo-bound

---

specs/latest/2.0/index.html

Suggested by Gregg Tavares (@greggman) in #2024 .

Simplify description of non-power-of-two texture support.

---

sdk/tests/conformance/context/methods.html
sdk/tests/conformance2/context/methods-2.html

Right now chromium is implementing WebGL's commit API, to make sure all the conformance tests will be passing, this API has to be added to ignoredMethods first.
PTAL.
@kenrussell

Add commit to ignoredMethods

---

sdk/tests/conformance2/rendering/blitframebuffer-filter-srgb.html
sdk/tests/conformance2/rendering/blitframebuffer-outside-readbuffer.html
sdk/tests/conformance2/textures/misc/tex-srgb-mipmap.html
sdk/tests/js/webgl-test-utils.js

They are common functions, move them to webgl-test-utils to reuse these functions among tests. 
@kenrussell , PTAL. Thanks a lot!

Move srgb converter related apis into wtu

---

extensions/WEBGL_compressed_texture_es3_0/extension.xml

Renamed WEBGL_compressed_texture_es3 to _etc to future-proof it.

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/unary-minus-operator-in-dynamic-loop.html

On some Intel D3D drivers, evaluating unary minus operator
on an integer variable may get wrong answer in vertex shader.
One of such situation is when attempting to read the answer
in a dynamic loop.
This patch adds test to expose this Intel D3D driver bug.

Add test to expose unary minus bug on Windows Intel

---

sdk/tests/deqp/framework/common/tcuSkipList.js

These tests are in the skip lists for the native dEQP suite. The most
immediate reason to skip them is that they are failing on macOS with
AMD GPUs, but they are skipped because they will fail on other GPU
types as well.

Add skip entries for three es3fShaderTextureFunction tests.

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/blitframebuffer-multisampled-readbuffer.html
sdk/tests/js/webgl-test-utils.js

@kenrussell , PTAL. Thanks a lot!
Per the discussion in this Chromium CL: https://codereview.chromium.org/2286593002/.  We have no tests to blit multisampled srgb to a srgb image. So this test comes, it can expose some errors in Mac (OGL 4.1).

Add test cases to test blitframebuffer against multisampled srgb image

---

sdk/tests/deqp/functional/gles3/es3fTextureFilteringTests.js

AMD is having trouble passing the quality bar for some cube and
2D array texture formats (RGB5A1, RGBA4, RGBA16F, RGB10A2, RGB5E9).
The low-quality thresholds are arbitrary in dEQP and were chosen
to make certain drivers pass - lowering the thresholds from 4 bits
to 3 (or in one case, 2) makes all tests pass.
I spoke to Pyry  (phaulos@google) from the dEQP team about this. He
told me the GL spec isn't very clear about filtering precision, and it's quite
possible that GL drivers themselves aren't perfectly conformant. They chose
these numbers by experimentation. I'd like to report this issue to AMD so
they can investigate, but it might not be possible to fix in the short time frame.

Lower quality threshold for some deqp/filtering.

---

sdk/tests/deqp/functional/gles3/es3fPixelBufferObjectTest.js

Run the webgl2 conformance test on MacOSX and fount the pixelbufferobject.html failed. It turned out to be a typo. 
@kenrussell , @zhenyao , PTAL. Thanks.

Fix the failure of pixelbufferobject.html

---

sdk/tests/deqp/framework/common/tcuSkipList.js

They were caused by a D3D compiler bug that Microsoft diagnosed. It is now worked around in ANGLE's shader translator.
See https://github.com/google/angle/commit/509e4560b3c897311a101d4d41bb27a51a6c439a

Remove tcuSkipList entries for shaderloop*

---

sdk/tests/deqp/functional/gles3/es3fMultisampleTests.js

- Fixed bug in MultisampleCase.init where it was not returning a
return value. Callers were only executing if it returned true. I'm
not sure how any of these tests were ever running since it should
have been implicitly returning "undefined" which should evaluate to
false. Fixing this bug caused several more tests to start to run.
- Eliminated unnecessary typed array allocations for rendered images.
Roughly twice the needed memory was being allocated.

Fixes to ported dEQP multisample test.

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/blitframebuffer-stencil-only.html
sdk/tests/deqp/framework/common/tcuSkipList.js

Also move the existing tests into the skip list. A bug in AMD makes
these tests hard to pass, to put them in 2.0.1 after which AMD might
be able to release a fixed driver.
We've reported this as a standalone repro to AMD, see:
https://github.com/null77/d3d11-driver-bugs/tree/master/StencilBlit
Hopefully this should be fixed soon. In the meantime working around this
issue is a bit tricky so I'd like to move it to a standalone test for 2.0.1, added
in this pull request.
@kenrussell @jdashg @zhenyao

Add a test to cover stencil-only blits.

---

sdk/tests/conformance2/rendering/blitframebuffer-test.html

@kenrussell , per our discussion about blitframebuffer from a multi-sampled srgb image to a single-sampled image, I add some tests to verify all restrictions: src/dst resource should have the same region, the same format/type, and the dst resource should not have multisampled image. 
PTAL. It can pass on both MacOSX. and Linux Desktop.

Add test cases for blitframebuffer from/to a multisampled srgb image

---

sdk/tests/js/webgl-test-utils.js

Duplicate definition line was removed.
See: https://github.com/KhronosGroup/WebGL/issues/2058

Fix duplicate definition.

---

sdk/tests/conformance2/misc/uninitialized-test-2.html

This avoids needing the ?webglVersion=2 query arg.
Thanks to jkummerow@ for pointing this out while investigating
https://bugs.chromium.org/p/v8/issues/detail?id=5386 .

Make uninitialized-test-2.html create a WebGL 2.0 context by default.

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/blitframebuffer-scissor-enabled.html

According to GLES  spec (And also OGL spec), blitFramebuffer should do scissor test per fragment operation. 
@zhenyao , @kenrussell , PTAL.

Add test cases to verify blitFramebuffer's functionality when scissor test is enabled

---

sdk/tests/conformance2/textures/misc/00_test_list.txt
sdk/tests/conformance2/textures/misc/tex-image-with-different-data-source.html

@kenrussell PTAL. More tests will be added to conformance2/textures/[canvas|video|image|image_data...] for invalid internalformat/format/type combinations.

Add test for TexImage with different data source

---

sdk/tests/conformance/extensions/webgl-depth-texture.html

The core WebGL 2.0 version of this functionality only works with the
NEAREST filter mode. While LINEAR isn't recommended, it is
historically supported, so test it, but add a comment.

Test WEBGL_depth_texture with both NEAREST and LINEAR filter modes.

---

specs/latest/2.0/index.html

@zhenyao , @kenrussell , PTAL. Thanks a lot!

update the spec for blitting pixels outside the read buffer

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/blitframebuffer-filter-outofbounds.html

@zhenyao and @kenrussell , PTAL. 
See the comments at https://bugs.chromium.org/p/chromium/issues/detail?id=644740

add tests to verify blitframebuffer when read pixels out-of-bound w/ and w/o filter

---

sdk/tests/conformance2/rendering/blitframebuffer-outside-readbuffer.html
sdk/tests/conformance2/rendering/blitframebuffer-scissor-enabled.html

Update the test cases. Any pixel lying outside of the read buffer, the corresponding dst pixel should remain untouched, instead of clamp_to_edge. 
I will merge this one with blitframebuffer-filter-outofbounds.html later (Or just remove this file if deqp has thoroughly tested the feature). This one test out-of-bounds too, but have tests to reversed src/dst, and pixels outside every edge the readbuffer, and so forth. 
PTAL. @zhenyao and @kenrussell . 
It turns out that this test can pass in Linux now, but fail in MacOSX.

Fix more bugs in blitframebuffer-outside-readbuffer.html

---

extensions/WEBGL_compressed_texture_etc/extension.xml

There are two implementations now, in Firefox and Chrome.

Rename and move WEBGL_compressed_texture_etc to community approved.

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/out-of-bounds-index-buffers-after-copying.html

index buffer and draw calls produce expected results.
(modified from conformance/rendering/out-of-bounds-index-buffers.html)

Add a test to verify that copyBufferSubData leads to out-of-bounds array

---

sdk/tests/conformance2/buffers/00_test_list.txt
sdk/tests/conformance2/buffers/one-large-uniform-buffer.html

When using a UBO with a size larger than the D3D11 maximum
constant buffer size, ANGLE would incorrectly try to memcpy
with the unclamped size.
See http://crbug.com/651493
PTAL @zhenyao @kenrussell

Add a test for an ANGLE bug with UBO sizing.

---

extensions/EXT_disjoint_timer_query/extension.xml
extensions/EXT_disjoint_timer_query_webgl2/extension.xml

It was too difficult to specialize the IDL and documentation for WebGL
2.0 and keep it in the same file. Document that the extension is still
fetched via getExtension('EXT_disjoint_timer_query').

Split WebGL 2.0 version of EXT_disjoint_timer_query into its own file.

---

sdk/tests/deqp/functional/gles3/es3fTextureFormatTests.js

The last argument of function assertMsgOptions() should be set
to false in es3fTextureFormatTests.js or this function will throw
an exception when the test fails, which will destroy the current
function stack and prevent the updates on some important
variables, such as this.m_curFace.

Fix infinite loop errors in es3fTextureFormatTests.js

---

sdk/tests/conformance2/textures/misc/tex-image-with-bad-args-from-dom-elements.html

Generate INVLID_OPERATION error for test where each separate argument
is valid but their combination is invalid.

Add test for TexImage with bad internalformat/format/type combination

---

sdk/tests/conformance2/rendering/blitframebuffer-filter-outofbounds.html

After holiday, I carefully revisited the behavior of blitting from pixels outside read framebuffer TO PIXELS OUTSIDE OF  DRAW FRAMEBUFFER, I found that I misunderstand the behavior suggested in this issue: https://cvs.khronos.org/bugzilla/show_bug.cgi?id=3576. The out-of-bounds pixels in dst region should be considered for scaling during blitting, although these outofbounds pixels in dst region will not be drew. But they should not be ignored. 
This small pr will correct the behavior.
After this revision applied, this test can pass in Linux and Windows (But still fail on MacOSX as expected). PTAL. @zhenyao and @kenrussell .

Fix bug when blitting pixels outside read framebuffer

---

sdk/tests/conformance/more/functions/texImage2D.html

Function assertOK() should be called in testTexImage2DNull, or the result
of the test will not be displayed on the webpage.

Add missing assertOK() in texImage2D.html

---

sdk/tests/deqp/modules/shared/glsSamplerObjectTest.js

Multi texture sampler test actives two texture binding points: TEXTURE0
and TEXTURE1. Reset active texture binding point to TEXTURE0 at the end
of each multi textrue sampler test. Otherwise, tests for 3d texture may
crash on Mac OSX.

Reset active texture at the end of MultiTextureSamplerTest

---

sdk/tests/conformance2/textures/misc/00_test_list.txt
sdk/tests/conformance2/textures/misc/active-3d-texture-bug.html

This will catch crash on Mac OSX 10.12 with Intel HD Graphics 515
graphics card.

Add test for active 3d texture bug on Mac OSX

---

sdk/tests/conformance2/glsl3/00_test_list.txt
sdk/tests/conformance2/glsl3/uniform-block-layouts.html
sdk/tests/deqp/data/gles3/shaders/linkage.test
sdk/tests/deqp/functional/gles3/es3fUniformBlockTests.js
specs/latest/2.0/index.html

The spec is updated to mention that std140 layout is the initial
default for uniform blocks.
The tests are updated to expect compilation to fail when uniform block
layout is shared or packed. Some deqp tests that covered shared and
packed uniform buffers are removed from the suite. One linkage test
used to assume that the default layout would be shared, that one is
also removed.

Allow only std140 layout in tests and make it the default

---

specs/latest/2.0/index.html

ETC2/EAC not supported "by default" in WebGL 2

---

specs/latest/2.0/index.html
specs/latest/2.0/webgl2.idl

Also, remove texts that indicates special handling of TIMEOUT_IGNORED,
or -1 in WebGL2, which should not be for clientWaitSync.

Change clientWaitSync to take GLuint64 for |timeout| (as vs GLint64).

---

sdk/tests/deqp/functional/gles3/es3fMultisampleTests.js

gl.getInternalformatParameter(gl.RENDERBUFFER, gl.RGBA8, gl.SAMPLES) will return
an Int32Array containing sample counts supported for internalformat in descending order.
The old way incorrectly used Int32Array.length as the max sample number.
This patch fixes it by using Int32Array[0] as the max sample number.

Fixed incorrect calculation of max sample count

---

sdk/tests/conformance/misc/views-with-offsets.html
specs/latest/2.0/index.html
specs/latest/2.0/webgl2.idl

Also update idl for compressedTex uploads to allow an optional length.
Let me know if the readPixels tests are redundant, and I can remove them.
I think the uniform upload entrypoints still need tests, but we can do this a chunk at a time.
@kenrussell @zhenyao

Add test for tex uploads with view offsets.

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/fs-color-type-mismatch-color-buffer-type.html

@kenrussell and @zhenyao , PTAL. Thanks a lot! 
One more test case for undefined behavior in GLES3 spec, but we should generate INVALID_OPERATION in WebGL 2. 
Zhenyao has landed a patch to handle this issue at https://codereview.chromium.org/2142353002. But I didn't find a conformance test to cover this feature. So I wrote this one.

Add a test to verify type mismatch

---

sdk/tests/conformance2/reading/format-r11f-g11f-b10f.html

This is a typo: gl.DRAWBUFFER0 is meant to be gl.DRAW_BUFFER0. But we should use i, instead of DRAW_BUFFERi according to the spec. If we use the latter, it will report INVALID_ENUM. 
I felt weird why the original test can pass. So I dig a little into the code. It turned out that gl.DRAWBUFFER0 was undefined. So it was 0xNaN, which was thought to be 0 too... So it can pass by chance!

Fix a small bug in call sites to clearBuffer

---

sdk/tests/conformance2/rendering/00_test_list.txt
sdk/tests/conformance2/rendering/clear-srgb-color-buffer.html

In GLES 3 spec, it explicitly says that the implementation should do srgb conversion when clear a srgb color buffer, see page 189 at section 4.2.3 <Clearing the Buffers>: https://www.khronos.org/registry/gles/specs/3.0/es_spec_3.0.4.pdf#nameddest=section-4.2.3. 
However, the OGL spec may not. For example, in OGL 4.1 spec, the srgb conversion is not included by the per-fragment operations for clear buffer. See page 276 at section 4.2.3 <Clearing the Buffers>  : https://www.opengl.org/registry/doc/glspec41.core.20100725.pdf 
This behavior is consistent to other similar behaviors in OGL spec. For example, blitFramebuffer and generateMipmap against srgb color buffer may not do srgb conversion on OGL 4.3 profile or prior to OGL 4.3 profile.
I didn't find any test case covered this feature, so …

Add tests to verify that srgb conversion is done when it clears a srgb color buffer

---

sdk/tests/conformance2/rendering/blitframebuffer-filter-outofbounds.html
sdk/tests/conformance2/rendering/blitframebuffer-filter-srgb.html
sdk/tests/conformance2/rendering/blitframebuffer-multisampled-readbuffer.html
sdk/tests/conformance2/rendering/blitframebuffer-outside-readbuffer.html
sdk/tests/conformance2/rendering/blitframebuffer-scissor-enabled.html
sdk/tests/conformance2/rendering/blitframebuffer-srgb-and-linear-drawbuffers.html
sdk/tests/conformance2/rendering/clear-srgb-color-buffer.html

@kenrussell and @zhenyao  , per your request at #2127 , this small change use function in WebGLTestUtils (wtu.checkCanvasRect) to simplify the test. 
I also go through the similar usage, and found another one. The others still use a function to do pixels comparison, but they are not solid color, so they are not suitable to be replaced by wtu.checkCanvasRect. 

Use existed function in WebGLTestUtil

---

extensions/OES_EGL_image_external/extension.xml
extensions/proposals/OES_EGL_image_external/extension.xml

Allows YUV textures to be handled without color space conversion.
This is an origin version we proposed through <public_webgl@khronos.org> at Oct.11 2016.
We are now revising this proposal to have following information:
- Time stamp of current video frame
- Texture Resolution of current video frame

Add OES_EGL_image_external extension

---

sdk/tests/deqp/framework/common/tcuSkipList.js

These failures should be fixed in MacOS driver, let's move them into skip list. Zhenyao's email also suggested to fix them in WebGL 2.0.1.
@zhenyao and @kenrussell , PTAL.

move some driver bugs into skip list

---

extensions/proposals/WEBGL_multiview/extension.xml

The extension document contains a proposal to amend the WebGL 1.0
specification to include optional stereo rendering capability. In case
the actual context parameter "stereo" is set to true, the default
framebuffer will have left and right buffers, and the user may
choose either left or right draw buffer of the default framebuffer as
a target of pixel color writes.
The intent is that the stereo default framebuffer can be used as a
VRLayer source in the WebVR API. The backing for stereo default
framebuffers should be possible to implement so that the framebuffer
may be submitted for display using a VR headset API with zero copies
in between. Since the exact layout of the framebuffer is not exposed
to the WebGL API, the WebGL implementation may choose a layout that
is suitable for the API …

Add a proposal for WEBGL_multiview extension

---

sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-data.js

(And replace the tests for obsolete entry points.)
I pretty much rewrote the whole test, sorry for the huge diff. I think it runs reasonably fast despite being pretty thorough.
Verified in Chromium: https://codereview.chromium.org/2500433003

Test 3d texture sub-source uploads from ImageData

---

sdk/tests/js/tests/tex-image-and-sub-image-3d-with-canvas.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-webgl-canvas.js

These were using an obsolete function signature.

Fixed tests uploading canvases to textures via texSubImage3D.

---

sdk/tests/js/tests/tex-image-and-sub-image-3d-with-canvas-sub-rectangle.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image-data.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-image.js
sdk/tests/js/tests/tex-image-and-sub-image-3d-with-video.js

pixel storage parameter in tests uploading HTML data sources to 3D
textures.
Added tests skipping some rows via UNPACK_IMAGE_HEIGHT for most data
sources. Left a TODO to do this for ImageData since the test was more
complex.
Tested with Chromium implementation in
https://codereview.chromium.org/2511153002 ; all tests pass.

Fixed incorrect assumptions about behavior of UNPACK_IMAGE_HEIGHT

---

sdk/tests/conformance/extensions/00_test_list.txt
sdk/tests/conformance/extensions/webgl-draw-buffers-feedback-loop.html

Copy the rendering_sampling_feedback_loop.html for drawBuffers API in WebGL 2 to WebGL_draw_buffers extension in WebGL 1, for the sake of this issue: https://bugs.chromium.org/p/angleproject/issues/detail?id=1619.
I have a fix for this issue in Chromium, but that fix need to do some optimization. I think I have time to do the optimization soon.   
PTAL when you have time, @zhenyao and @kenrussell .

add test cases for webgl-draw-buffers-ext to detect feedback loop

---

sdk/tests/webgl-conformance-tests.html

Note that this will enable several new tests, some of which are known
to not yet pass on all browsers and operating systems.

Update the WebGL 2 top-of-tree conformance version to 2.0.1 (beta).

---

conformance-suites/2.0.0/js/tests/tex-image-and-sub-image-2d-with-canvas-sub-rectangle.js
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-canvas-sub-rectangle.js

Fix a small bug. I suppose that the original code want to skip these tests. 

skip the integer cube_map texture related tests

---

conformance-suites/2.0.0/conformance/misc/bad-arguments-test.html
sdk/tests/conformance/misc/bad-arguments-test.html

Follow-on to #2099.
Also fixes #2173; race condition in this asynchronous test.

Updated bad-arguments-test for new non-nullable entry points.

---

sdk/tests/conformance2/textures/misc/00_test_list.txt
sdk/tests/conformance2/textures/misc/canvas-remains-unchanged-after-used-in-webgl-texture.html
sdk/tests/js/tests/tex-image-and-sub-image-2d-with-canvas.js

getImageData() will disable hardware acceleration for canvas2d in chrome.
So, we cannot tests GPU-to-GPU path for texImage2D taking a canvas as source.
If we need to check if pixel values in source canvas change after canvas
used as webgl texture, we can add a standalone test for it.
See GetImageDataForcesNoAcceleration flag in blink:
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/graphics/ExpensiveCanvasHeuristicParameters.h?rcl=0&l=68.

Remove checkSourceCanvasImageData for texImage2D tests

---

sdk/tests/conformance2/buffers/one-large-uniform-buffer.html

ANGLE only stores starting chunks of large UBOs because of Win7
D3D11 limitations. This was causing problems when reading back
from large UBOs in some cases.
See also http://crbug.com/660670
@zhenyao @kenrussell PTAL. Issue was a bit old but was on my action items list to make a test.

Cover ANGLE bug with large UBO readback.

---

sdk/tests/conformance2/textures/misc/00_test_list.txt
sdk/tests/conformance2/textures/misc/tex-subimage3d-pixel-buffer-bug.html

TexSubImage3D is buggy when update texture data from pixel buffer on
Linux Mesa. Add this test to track the bug.

Check TexSubImage3D works with pixel buffer
